CREATE TABLE [HKP].[AllowanceDaily] (
    [Id]                             VARCHAR (30)    NOT NULL,
    [Sequence]                       DECIMAL (18, 2) NOT NULL,
    [Code]                           VARCHAR (10)    NOT NULL,
    [ShortName]                      VARCHAR (15)    NOT NULL,
    [StandardName]                   VARCHAR (50)    NOT NULL,
    [UserName]                       VARCHAR (50)    NOT NULL,
    [Description]                    VARCHAR (250)   NULL,
    [Remarks]                        VARCHAR (250)   NULL,
    [Active]                         BIT             NOT NULL,
    [AddedBy]                        VARCHAR (30)    NOT NULL,
    [AddedDate]                      DATETIME        NOT NULL,
    [AddedFromIP]                    VARCHAR (15)    NOT NULL,
    [UpdatedBy]                      VARCHAR (30)    NULL,
    [UpdatedDate]                    DATETIME        NULL,
    [UpdatedFromIP]                  VARCHAR (15)    NULL,
    [SalaryHeadId]                   VARCHAR (30)    NOT NULL,
    [IsAllDesignation]               BIT             DEFAULT ((0)) NULL,
    [IsFixed]                        BIT             DEFAULT ((0)) NULL,
    [Rate]                           DECIMAL (18, 2) DEFAULT ((0)) NOT NULL,
    [IsAllShift]                     BIT             DEFAULT ((0)) NULL,
    [EffectiveTime]                  DATETIME        NULL,
    [IsSpecificTime]                 BIT             DEFAULT ((0)) NULL,
    [PlantId]                        VARCHAR (10)    NULL,
    [FormulaDescription]             VARCHAR (300)   NULL,
    [FormulaDesID]                   VARCHAR (300)   NULL,
    [CalculationBasics]              VARCHAR (30)    NULL,
    [Catagory]                       VARCHAR (30)    NULL,
    [FromEffectiveDate]              DATETIME        NULL,
    [ToEffectiveDate]                DATETIME        NULL,
    [IsRateBasedOnSalaryRange]       BIT             DEFAULT ((0)) NULL,
    [SalaryRangeBasedOnSalaryHeadId] VARCHAR (30)    NULL,
    [IsVoucherPayment]               BIT             DEFAULT ((0)) NULL,
    CONSTRAINT [PK_AllowanceDaily] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_AllowanceDaily_SalaryHeadId] FOREIGN KEY ([SalaryHeadId]) REFERENCES [dbo].[SalaryHead] ([SalaryHeadID])
);

