CREATE TABLE [HKP].[BankBranch] (
    [Id]              VARCHAR (10)    NOT NULL,
    [BankId]          VARCHAR (10)    NULL,
    [AddressMasterId] VARCHAR (20)    NULL,
    [ContactMasterId] VARCHAR (20)    NULL,
    [Sequence]        DECIMAL (18, 2) NOT NULL,
    [Code]            VARCHAR (10)    NOT NULL,
    [ShortName]       VARCHAR (15)    NOT NULL,
    [StandardName]    VARCHAR (50)    NOT NULL,
    [UserName]        VARCHAR (50)    NOT NULL,
    [RoutingNo]       VARCHAR (15)    NULL,
    [SWIFTCode]       VARCHAR (15)    NULL,
    [Description]     VARCHAR (250)   NULL,
    [Remarks]         VARCHAR (250)   NULL,
    [Active]          BIT             NOT NULL,
    [Archive]         BIT             NOT NULL,
    [AddedBy]         VARCHAR (30)    NOT NULL,
    [AddedDate]       DATETIME        NOT NULL,
    [AddedFromIP]     VARCHAR (15)    NOT NULL,
    [UpdatedBy]       VARCHAR (30)    NULL,
    [UpdatedDate]     DATETIME        NULL,
    [UpdatedFromIP]   VARCHAR (15)    NULL,
    [IFSCCode]        VARCHAR (30)    NULL,
    CONSTRAINT [PK_BankBranch] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_BankBranch_AddressMaster] FOREIGN KEY ([AddressMasterId]) REFERENCES [MST].[AddressMaster] ([Id]),
    CONSTRAINT [FK_BankBranch_Bank] FOREIGN KEY ([BankId]) REFERENCES [HKP].[Bank] ([Id]),
    CONSTRAINT [FK_BankBranch_ContactMaster] FOREIGN KEY ([ContactMasterId]) REFERENCES [MST].[ContactMaster] ([Id])
);

