CREATE TABLE [HKP].[CompanyParty] (
    [Id]                        VARCHAR (13)  NOT NULL,
    [PartyId]                   VARCHAR (10)  NOT NULL,
    [CompanyId]                 VARCHAR (10)  NOT NULL,
    [PlantId]                   VARCHAR (10)  NOT NULL,
    [PartyAccountGroupId]       VARCHAR (10)  NOT NULL,
    [CurrencyId]                VARCHAR (10)  NOT NULL,
    [PaymentTermId]             VARCHAR (10)  NULL,
    [PartyType]                 VARCHAR (20)  NOT NULL,
    [IsPaymentTermChangeable]   BIT           CONSTRAINT [DF__CompanyPa__IsPay__17AF0EE4] DEFAULT ((1)) NOT NULL,
    [Remarks]                   VARCHAR (250) NULL,
    [Active]                    BIT           CONSTRAINT [DF_CompanyParty_Active] DEFAULT ((0)) NOT NULL,
    [AddedBy]                   VARCHAR (30)  NOT NULL,
    [AddedDate]                 DATETIME      NOT NULL,
    [AddedFromIP]               VARCHAR (15)  NOT NULL,
    [UpdatedBy]                 VARCHAR (30)  NULL,
    [UpdatedDate]               DATETIME      NULL,
    [UpdatedFromIP]             VARCHAR (15)  NULL,
    [TaxApplicable]             VARCHAR (20)  NULL,
    [IsTaxApplicableChangeable] BIT           NOT NULL,
    [TransitDays]               INT           NULL,
    CONSTRAINT [PK_CompanyParty] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_CompanyParty_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_CompanyParty_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_CompanyParty_Party] FOREIGN KEY ([PartyId]) REFERENCES [HKP].[Party] ([Id]),
    CONSTRAINT [FK_CompanyParty_PartyAccountGroup] FOREIGN KEY ([PartyAccountGroupId]) REFERENCES [HKP].[PartyAccountGroup] ([Id]),
    CONSTRAINT [FK_CompanyParty_PaymentTerm] FOREIGN KEY ([PaymentTermId]) REFERENCES [MST].[PaymentTerm] ([Id]),
    CONSTRAINT [FK_CompanyParty_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id])
);

