CREATE TABLE [HKP].[ComplianceDocument] (
    [Id]                              VARCHAR (10)    NOT NULL,
    [CompanyGroupId]                  VARCHAR (10)    NOT NULL,
    [ComplianceDocumentCategoryId]    VARCHAR (10)    NOT NULL,
    [ComplianceDocumentSubCategoryId] VARCHAR (10)    NOT NULL,
    [QualificationLevelId]            VARCHAR (10)    NULL,
    [DocumentType]                    VARCHAR (30)    NULL,
    [Sequence]                        DECIMAL (18, 2) NULL,
    [Code]                            VARCHAR (10)    CONSTRAINT [DF__Compliance__Code__2E46C4CB] DEFAULT ('100') NOT NULL,
    [ShortName]                       VARCHAR (15)    CONSTRAINT [DF__Complianc__Short__2F3AE904] DEFAULT ('ShortName') NOT NULL,
    [StandardName]                    VARCHAR (100)   CONSTRAINT [DF__Complianc__Stand__302F0D3D] DEFAULT ('StandardName') NOT NULL,
    [UserName]                        VARCHAR (100)   NOT NULL,
    [Importance]                      VARCHAR (30)    NULL,
    [EmploymentStage]                 VARCHAR (30)    NULL,
    [OptionalOrMandatory]             VARCHAR (30)    NULL,
    [DocumentationBy]                 VARCHAR (20)    NULL,
    [ResponsiblePersonId]             VARCHAR (10)    NULL,
    [DependateDate]                   VARCHAR (100)   NULL,
    [EmpType]                         VARCHAR (30)    NULL,
    [LeadOrLagDays]                   INT             NULL,
    [IsSkillBased]                    BIT             NOT NULL,
    [IsGlobalDocument]                BIT             CONSTRAINT [DF_ComplianceDocument_IsGlobalDocument] DEFAULT ((0)) NOT NULL,
    [IsRecurring]                     BIT             CONSTRAINT [DF_ComplianceDocument_IsRecurring] DEFAULT ((0)) NOT NULL,
    [ProfileType]                     VARCHAR (30)    NULL,
    [Remarks]                         VARCHAR (250)   NULL,
    [Description]                     VARCHAR (250)   NULL,
    [Type]                            VARCHAR (20)    NULL,
    [ReNewAble]                       BIT             CONSTRAINT [DF__Complianc__ReNew__31233176] DEFAULT ((0)) NOT NULL,
    [ReNewAfterEvery]                 DECIMAL (18, 2) CONSTRAINT [DF__Complianc__ReNew__321755AF] DEFAULT ((0)) NOT NULL,
    [ReNewUOM]                        VARCHAR (10)    NULL,
    [DocumentExpirable]               VARCHAR (20)    NULL,
    [MailAlert]                       BIT             CONSTRAINT [DF__Complianc__MailA__330B79E8] DEFAULT ((0)) NOT NULL,
    [DaysBeforeExpiry]                VARCHAR (20)    NULL,
    [DocNumberRequired]               BIT             CONSTRAINT [DF__Complianc__DocNu__33FF9E21] DEFAULT ((0)) NOT NULL,
    [DocDateRequired]                 BIT             CONSTRAINT [DF__Complianc__DocDa__34F3C25A] DEFAULT ((0)) NOT NULL,
    [Expirable]                       BIT             CONSTRAINT [DF__Complianc__Expir__35E7E693] DEFAULT ((0)) NOT NULL,
    [Active]                          BIT             NOT NULL,
    [Archive]                         BIT             NOT NULL,
    [AddedBy]                         VARCHAR (30)    NOT NULL,
    [AddedFromIP]                     VARCHAR (15)    NOT NULL,
    [AddedDate]                       DATETIME        NOT NULL,
    [UpdatedBy]                       VARCHAR (30)    NULL,
    [UpdatedDate]                     DATETIME        NULL,
    [UpdatedFromIP]                   VARCHAR (15)    NULL,
    CONSTRAINT [PK_ComplianceDocument] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ComplianceDocument_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_ComplianceDocument_ComplianceDocumentCategory] FOREIGN KEY ([ComplianceDocumentCategoryId]) REFERENCES [HKP].[ComplianceDocumentCategory] ([Id]),
    CONSTRAINT [FK_ComplianceDocument_ComplianceDocumentSubCategory] FOREIGN KEY ([ComplianceDocumentSubCategoryId]) REFERENCES [HKP].[ComplianceDocumentSubCategory] ([Id]),
    CONSTRAINT [FK_ComplianceDocument_QualificationLevel] FOREIGN KEY ([QualificationLevelId]) REFERENCES [SCS].[QualificationLevel] ([Id])
);

