CREATE TABLE [HKP].[CostingItem] (
    [Id]                    VARCHAR (10)    NOT NULL,
    [Sequence]              DECIMAL (18, 2) NULL,
    [Code]                  VARCHAR (10)    NULL,
    [ShortName]             VARCHAR (15)    NULL,
    [StandardName]          VARCHAR (50)    NULL,
    [UserName]              VARCHAR (50)    NULL,
    [Description]           VARCHAR (250)   NULL,
    [Remarks]               VARCHAR (250)   NULL,
    [POIssueDeadLine]       INT             NULL,
    [Active]                BIT             CONSTRAINT [DF__CostingIt__Activ__0FF8DE83] DEFAULT ((0)) NOT NULL,
    [CostingCategoryId]     VARCHAR (10)    NULL,
    [CostingSubCategoryId]  VARCHAR (10)    NULL,
    [UnitOfMeasurementId]   VARCHAR (10)    NULL,
    [MinimumOfQuantity]     DECIMAL (18, 2) NULL,
    [Wastage]               DECIMAL (18, 2) NULL,
    [ProcessId]             VARCHAR (10)    NULL,
    [BudgetMasterId]        VARCHAR (20)    NULL,
    [ActivityId]            VARCHAR (10)    NULL,
    [PurchaseGroupId]       VARCHAR (10)    NULL,
    [CostingGroupId]        VARCHAR (10)    NULL,
    [CostingComponentId]    VARCHAR (10)    NULL,
    [AddedBy]               VARCHAR (30)    NOT NULL,
    [AddedDate]             DATETIME        NOT NULL,
    [AddedFromIP]           VARCHAR (15)    NOT NULL,
    [UpdatedBy]             VARCHAR (30)    NULL,
    [UpdatedDate]           DATETIME        NULL,
    [UpdatedFromIP]         VARCHAR (15)    NULL,
    [isSystemGenerated]     BIT             CONSTRAINT [DF_CostingItem_isSystemGenerated] DEFAULT ((0)) NULL,
    [InternalRate]          DECIMAL (18, 6) NULL,
    [ExternalRate]          DECIMAL (18, 6) NULL,
    [SubProcessId]          VARCHAR (10)    NULL,
    [ValueLossPercentage]   DECIMAL (18, 6) NULL,
    [MaterialGroupMasterId] VARCHAR (10)    NULL,
    CONSTRAINT [PK__CostingI__3214EC07C093B4A8] PRIMARY KEY CLUSTERED ([Id] ASC),
    FOREIGN KEY ([CostingComponentId]) REFERENCES [HKP].[CostingComponent] ([Id]),
    FOREIGN KEY ([MaterialGroupMasterId]) REFERENCES [MST].[MaterialGroupMaster] ([Id]),
    FOREIGN KEY ([SubProcessId]) REFERENCES [HKP].[SubProcess] ([Id]),
    CONSTRAINT [FK__CostingIt__Activ__15B1B7D9] FOREIGN KEY ([ActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK__CostingIt__Activ__3D566036] FOREIGN KEY ([ActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK__CostingIt__Budge__14BD93A0] FOREIGN KEY ([BudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK__CostingIt__Budge__3E4A846F] FOREIGN KEY ([BudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK__CostingIt__Costi__10ED02BC] FOREIGN KEY ([CostingCategoryId]) REFERENCES [HKP].[CostingCategory] ([Id]),
    CONSTRAINT [FK__CostingIt__Costi__11E126F5] FOREIGN KEY ([CostingSubCategoryId]) REFERENCES [HKP].[CostingSubCategory] ([Id]),
    CONSTRAINT [FK__CostingIt__Costi__179A004B] FOREIGN KEY ([CostingGroupId]) REFERENCES [HKP].[CostingGroup] ([Id]),
    CONSTRAINT [FK__CostingIt__Costi__3F3EA8A8] FOREIGN KEY ([CostingCategoryId]) REFERENCES [HKP].[CostingCategory] ([Id]),
    CONSTRAINT [FK__CostingIt__Costi__4032CCE1] FOREIGN KEY ([CostingSubCategoryId]) REFERENCES [HKP].[CostingSubCategory] ([Id]),
    CONSTRAINT [FK__CostingIt__Costi__4126F11A] FOREIGN KEY ([CostingGroupId]) REFERENCES [HKP].[CostingGroup] ([Id]),
    CONSTRAINT [FK__CostingIt__Proce__13C96F67] FOREIGN KEY ([ProcessId]) REFERENCES [HKP].[Process] ([Id]),
    CONSTRAINT [FK__CostingIt__Proce__421B1553] FOREIGN KEY ([ProcessId]) REFERENCES [HKP].[Process] ([Id]),
    CONSTRAINT [FK__CostingIt__Purch__16A5DC12] FOREIGN KEY ([PurchaseGroupId]) REFERENCES [ORG].[PurchaseGroup] ([Id]),
    CONSTRAINT [FK__CostingIt__Purch__430F398C] FOREIGN KEY ([PurchaseGroupId]) REFERENCES [ORG].[PurchaseGroup] ([Id]),
    CONSTRAINT [FK__CostingIt__UnitO__12D54B2E] FOREIGN KEY ([UnitOfMeasurementId]) REFERENCES [SCS].[UnitOfMeasurement] ([Id]),
    CONSTRAINT [FK__CostingIt__UnitO__44035DC5] FOREIGN KEY ([UnitOfMeasurementId]) REFERENCES [SCS].[UnitOfMeasurement] ([Id])
);

