CREATE TABLE [HKP].[FixedAssetAttributeValue] (
    [Id]                    VARCHAR (10)    NOT NULL,
    [CompanyGroupId]        VARCHAR (10)    NOT NULL,
    [FixedAssetAttributeId] VARCHAR (10)    NOT NULL,
    [Sequence]              DECIMAL (18, 2) NOT NULL,
    [Code]                  VARCHAR (15)    NOT NULL,
    [ShortName]             VARCHAR (15)    NOT NULL,
    [StandardName]          VARCHAR (50)    NOT NULL,
    [UserName]              VARCHAR (50)    NOT NULL,
    [Description]           VARCHAR (250)   NULL,
    [Remarks]               VARCHAR (250)   NULL,
    [IsDefault]             BIT             NOT NULL,
    [Active]                BIT             NOT NULL,
    [Archive]               BIT             CONSTRAINT [DF_FixedAssetAttributeValue_Archive] DEFAULT ((0)) NOT NULL,
    [AddedBy]               VARCHAR (30)    NOT NULL,
    [AddedDate]             DATETIME        NOT NULL,
    [AddedFromIP]           VARCHAR (15)    NOT NULL,
    [UpdatedBy]             VARCHAR (30)    NULL,
    [UpdatedDate]           DATETIME        NULL,
    [UpdatedFromIP]         VARCHAR (15)    NULL,
    CONSTRAINT [PK_FixedAssetAttributeValue] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_FixedAssetAttributeValue_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_FixedAssetAttributeValue_FixedAssetAttribute] FOREIGN KEY ([FixedAssetAttributeId]) REFERENCES [HKP].[FixedAssetAttribute] ([Id])
);

