CREATE TABLE [HKP].[GLGeneralInfo] (
    [Id]                     VARCHAR (10)    NOT NULL,
    [COAId]                  VARCHAR (10)    NULL,
    [COALevel1Id]            VARCHAR (1)     NULL,
    [COALevel2Id]            VARCHAR (2)     NULL,
    [COALevel3Id]            VARCHAR (3)     NULL,
    [COALevel4Id]            VARCHAR (4)     NULL,
    [COALevel5Id]            VARCHAR (4)     NULL,
    [COALevel6Id]            VARCHAR (4)     NULL,
    [AccountGroupId]         VARCHAR (10)    NOT NULL,
    [VoucherType]            VARCHAR (50)    NULL,
    [Sequence]               DECIMAL (18, 2) NOT NULL,
    [AccountCode]            VARCHAR (10)    NOT NULL,
    [RefNo]                  VARCHAR (20)    NULL,
    [IsPostingAutomaticOnly] BIT             NULL,
    [UserName]               VARCHAR (50)    NULL,
    [IsClearingAccount]      BIT             NULL,
    [IsManufacturing]        BIT             NULL,
    [IsService]              BIT             NULL,
    [IsTreding]              BIT             NULL,
    [Description]            VARCHAR (250)   NULL,
    [Active]                 BIT             NOT NULL,
    [Archive]                BIT             NOT NULL,
    [AddedBy]                VARCHAR (30)    NOT NULL,
    [AddedDate]              DATETIME        NOT NULL,
    [AddedFromIP]            VARCHAR (15)    NOT NULL,
    [UpdatedBy]              VARCHAR (30)    NULL,
    [UpdatedDate]            DATETIME        NULL,
    [UpdatedFromIP]          VARCHAR (15)    NULL,
    CONSTRAINT [PK_GLGeneralInfo] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_GLGeneralInfo_AccountGroup] FOREIGN KEY ([AccountGroupId]) REFERENCES [HKP].[AccountGroup] ([Id]),
    CONSTRAINT [FK_GLGeneralInfo_COA] FOREIGN KEY ([COAId]) REFERENCES [HKP].[COA] ([Id]),
    CONSTRAINT [FK_GLGeneralInfo_COALevel1] FOREIGN KEY ([COALevel1Id]) REFERENCES [HKP].[COALevel1] ([Id]),
    CONSTRAINT [FK_GLGeneralInfo_COALevel2] FOREIGN KEY ([COALevel2Id]) REFERENCES [HKP].[COALevel2] ([Id]),
    CONSTRAINT [FK_GLGeneralInfo_COALevel3] FOREIGN KEY ([COALevel3Id]) REFERENCES [HKP].[COALevel3] ([Id]),
    CONSTRAINT [FK_GLGeneralInfo_COALevel4] FOREIGN KEY ([COALevel4Id]) REFERENCES [HKP].[COALevel4] ([Id]),
    CONSTRAINT [FK_GLGeneralInfo_COALevel5] FOREIGN KEY ([COALevel5Id]) REFERENCES [HKP].[COALevel5] ([Id]),
    CONSTRAINT [FK_GLGeneralInfo_COALevel6] FOREIGN KEY ([COALevel6Id]) REFERENCES [HKP].[COALevel6] ([Id])
);

