CREATE TABLE [HKP].[LocalLanguage] (
    [Id]                    VARCHAR (50)   NOT NULL,
    [LanguageId]            VARCHAR (5)    NOT NULL,
    [CompanyGroupId]        VARCHAR (10)   NULL,
    [CompanyId]             VARCHAR (10)   NULL,
    [PlantId]               VARCHAR (10)   NULL,
    [UnitId]                VARCHAR (10)   NULL,
    [DivisionId]            VARCHAR (10)   NULL,
    [SubDivisionId]         VARCHAR (10)   NULL,
    [DepartmentId]          VARCHAR (10)   NULL,
    [SectionId]             VARCHAR (10)   NULL,
    [SubSectionId]          VARCHAR (10)   NULL,
    [LineId]                VARCHAR (10)   NULL,
    [DesignationId]         VARCHAR (10)   NULL,
    [Name]                  NVARCHAR (50)  NOT NULL,
    [Active]                BIT            NOT NULL,
    [Archive]               BIT            NOT NULL,
    [AddedBy]               VARCHAR (30)   NOT NULL,
    [AddedDate]             DATETIME       NOT NULL,
    [AddedFromIP]           VARCHAR (15)   NOT NULL,
    [UpdatedBy]             VARCHAR (30)   NULL,
    [UpdatedDate]           DATETIME       NULL,
    [UpdatedFromIP]         VARCHAR (15)   NULL,
    [LabelName]             VARCHAR (50)   NULL,
    [DesignationGroupId]    VARCHAR (10)   NULL,
    [LegalDesignationId]    VARCHAR (10)   NULL,
    [SalaryHeadId]          VARCHAR (30)   NULL,
    [ContinentId]           VARCHAR (10)   NULL,
    [CountryId]             VARCHAR (10)   NULL,
    [StateId]               VARCHAR (10)   NULL,
    [DistrictId]            VARCHAR (10)   NULL,
    [CityId]                VARCHAR (10)   NULL,
    [AreaId]                VARCHAR (10)   NULL,
    [PoliceStationId]       VARCHAR (10)   NULL,
    [PostOfficeId]          VARCHAR (10)   NULL,
    [CivilStatusId]         VARCHAR (10)   NULL,
    [ReligionId]            VARCHAR (10)   NULL,
    [UtilityName]           NVARCHAR (250) NULL,
    [UtilityLabelName]      NVARCHAR (50)  NULL,
    [QualificationLevelId]  VARCHAR (10)   NULL,
    [EmployeeCategoryId]    VARCHAR (10)   NULL,
    [RelationshipId]        VARCHAR (10)   NULL,
    [ProfessionId]          VARCHAR (10)   NULL,
    [LeaveTypeId]           VARCHAR (10)   NULL,
    [LegalSalaryGradeId]    VARCHAR (10)   NULL,
    [LabelId]               VARCHAR (10)   NULL,
    [EmployeeWorkTypeId]    VARCHAR (10)   NULL,
    [FinalSettlementHeadId] VARCHAR (30)   NULL,
    CONSTRAINT [PK_LocalLanguage] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_LocalLanguage_Area] FOREIGN KEY ([AreaId]) REFERENCES [SCS].[Area] ([Id]),
    CONSTRAINT [FK_LocalLanguage_City] FOREIGN KEY ([CityId]) REFERENCES [SCS].[City] ([Id]),
    CONSTRAINT [FK_LocalLanguage_CivilStatus] FOREIGN KEY ([CivilStatusId]) REFERENCES [HKP].[CivilStatus] ([Id]),
    CONSTRAINT [FK_LocalLanguage_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_LocalLanguage_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_LocalLanguage_Continent] FOREIGN KEY ([ContinentId]) REFERENCES [SCS].[Continent] ([Id]),
    CONSTRAINT [FK_LocalLanguage_Country] FOREIGN KEY ([CountryId]) REFERENCES [SCS].[Country] ([Id]),
    CONSTRAINT [FK_LocalLanguage_Department] FOREIGN KEY ([DepartmentId]) REFERENCES [ORG].[Department] ([Id]),
    CONSTRAINT [FK_LocalLanguage_DesignationGroup] FOREIGN KEY ([DesignationGroupId]) REFERENCES [HKP].[DesignationGroup] ([Id]),
    CONSTRAINT [FK_LocalLanguage_Destination] FOREIGN KEY ([DesignationId]) REFERENCES [HKP].[Designation] ([Id]),
    CONSTRAINT [FK_LocalLanguage_District] FOREIGN KEY ([DistrictId]) REFERENCES [SCS].[District] ([Id]),
    CONSTRAINT [FK_LocalLanguage_Division] FOREIGN KEY ([DivisionId]) REFERENCES [ORG].[Division] ([Id]),
    CONSTRAINT [FK_LocalLanguage_EmployeeCategory] FOREIGN KEY ([EmployeeCategoryId]) REFERENCES [HKP].[EmployeeCategory] ([Id]),
    CONSTRAINT [FK_LocalLanguage_FinalSettlementHead] FOREIGN KEY ([FinalSettlementHeadId]) REFERENCES [dbo].[FinalSettlementDeductionHead] ([Id]),
    CONSTRAINT [FK_LocalLanguage_Label] FOREIGN KEY ([LabelName]) REFERENCES [dbo].[LabelList] ([Id]),
    CONSTRAINT [FK_LocalLanguage_Language] FOREIGN KEY ([LanguageId]) REFERENCES [SCS].[Language] ([Id]),
    CONSTRAINT [FK_LocalLanguage_LeaveType] FOREIGN KEY ([LeaveTypeId]) REFERENCES [dbo].[LeaveType] ([Id]),
    CONSTRAINT [FK_LocalLanguage_LegalDesignation] FOREIGN KEY ([LegalDesignationId]) REFERENCES [HKP].[LegalDesignation] ([Id]),
    CONSTRAINT [FK_LocalLanguage_LegalSalaryGrade] FOREIGN KEY ([LegalSalaryGradeId]) REFERENCES [SCS].[LegalSalaryGrade] ([Id]),
    CONSTRAINT [FK_LocalLanguage_Line] FOREIGN KEY ([LineId]) REFERENCES [ORG].[Line] ([Id]),
    CONSTRAINT [FK_LocalLanguage_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_LocalLanguage_PoliceStation] FOREIGN KEY ([PoliceStationId]) REFERENCES [SCS].[PoliceStation] ([Id]),
    CONSTRAINT [FK_LocalLanguage_PostOffice] FOREIGN KEY ([PostOfficeId]) REFERENCES [SCS].[PostOffice] ([Id]),
    CONSTRAINT [FK_LocalLanguage_QualificationLevel] FOREIGN KEY ([QualificationLevelId]) REFERENCES [SCS].[QualificationLevel] ([Id]),
    CONSTRAINT [FK_LocalLanguage_Religion] FOREIGN KEY ([ReligionId]) REFERENCES [SCS].[Religion] ([Id]),
    CONSTRAINT [FK_LocalLanguage_SalaryHead] FOREIGN KEY ([SalaryHeadId]) REFERENCES [dbo].[SalaryHead] ([SalaryHeadID]),
    CONSTRAINT [FK_LocalLanguage_Section] FOREIGN KEY ([SectionId]) REFERENCES [ORG].[Section] ([Id]),
    CONSTRAINT [FK_LocalLanguage_State] FOREIGN KEY ([StateId]) REFERENCES [SCS].[State] ([Id]),
    CONSTRAINT [FK_LocalLanguage_SubDivision] FOREIGN KEY ([SubDivisionId]) REFERENCES [ORG].[SubDivision] ([Id]),
    CONSTRAINT [FK_LocalLanguage_SubSection] FOREIGN KEY ([SubSectionId]) REFERENCES [ORG].[SubSection] ([Id]),
    CONSTRAINT [FK_LocalLanguage_Unit] FOREIGN KEY ([UnitId]) REFERENCES [ORG].[Unit] ([Id])
);

