CREATE TABLE [HKP].[MaterialAttribute] (
    [Id]                   VARCHAR (10)    NOT NULL,
    [Sequence]             DECIMAL (18, 2) NOT NULL,
    [Code]                 VARCHAR (10)    NOT NULL,
    [ShortName]            VARCHAR (15)    NOT NULL,
    [StandardName]         VARCHAR (50)    NOT NULL,
    [UserName]             VARCHAR (50)    NOT NULL,
    [AttributeProperty]    VARCHAR (15)    NOT NULL,
    [IsFixedNoOfCharacter] BIT             NOT NULL,
    [NoOfCharacter]        INT             NOT NULL,
    [IsFreeField]          BIT             NOT NULL,
    [IsPreDefinedField]    BIT             NOT NULL,
    [IsMandatory]          BIT             NOT NULL,
    [ValueAssignmentLevel] VARCHAR (10)    NOT NULL,
    [Remarks]              VARCHAR (250)   NULL,
    [Description]          VARCHAR (250)   NULL,
    [Active]               BIT             NOT NULL,
    [Archive]              BIT             NOT NULL,
    [AddedBy]              VARCHAR (30)    NOT NULL,
    [AddedDate]            DATETIME        NOT NULL,
    [AddedFromIP]          VARCHAR (15)    NOT NULL,
    [UpdatedBy]            VARCHAR (30)    NULL,
    [UpdatedDate]          DATETIME        NULL,
    [UpdatedFromIP]        VARCHAR (15)    NULL,
    [CreationLevel]        VARCHAR (10)    NULL,
    CONSTRAINT [PK_MaterialAttribute] PRIMARY KEY CLUSTERED ([Id] ASC)
);

