CREATE TABLE [HKP].[MaterialGroupGL] (
    [Id]                            VARCHAR (10) NOT NULL,
    [COAId]                         VARCHAR (10) NULL,
    [MaterialGroupMasterId]         VARCHAR (10) NULL,
    [DownPaymentGLId]               VARCHAR (10) NULL,
    [DownPaymentBudgetMasterId]     VARCHAR (20) NULL,
    [DownPaymentActivityId]         VARCHAR (10) NULL,
    [ClearingAccountGLId]           VARCHAR (10) NULL,
    [ClearingAccountBudgetMasterId] VARCHAR (20) NULL,
    [ClearingAccountActivityId]     VARCHAR (10) NULL,
    [InventoryGLId]                 VARCHAR (10) NULL,
    [InventoryBudgetMasterId]       VARCHAR (20) NULL,
    [InventoryActivityId]           VARCHAR (10) NULL,
    [ExpenseGLId]                   VARCHAR (10) NULL,
    [ExpenseBudgetMasterId]         VARCHAR (20) NULL,
    [ExpenseActivityId]             VARCHAR (10) NULL,
    [AddedBy]                       VARCHAR (30) NOT NULL,
    [AddedDate]                     DATETIME     NOT NULL,
    [AddedFromIP]                   VARCHAR (15) NOT NULL,
    [UpdatedBy]                     VARCHAR (30) NULL,
    [UpdatedDate]                   DATETIME     NULL,
    [UpdatedFromIP]                 VARCHAR (15) NULL,
    [DebitNoteGLId]                 VARCHAR (10) NULL,
    [DebitNoteBudgetMasterId]       VARCHAR (20) NULL,
    [DebitNoteActivityId]           VARCHAR (10) NULL,
    [CreditNoteGLId]                VARCHAR (10) NULL,
    [CreditNoteBudgetMasterId]      VARCHAR (20) NULL,
    [CreditNoteActivityId]          VARCHAR (10) NULL,
    [ShortageGLId]                  VARCHAR (10) NULL,
    [ShortageBudgetMasterId]        VARCHAR (20) NULL,
    [ShortageActivityId]            VARCHAR (10) NULL,
    [RejectionGLId]                 VARCHAR (10) NULL,
    [RejectionBudgetMasterId]       VARCHAR (20) NULL,
    [RejectionActivityId]           VARCHAR (10) NULL,
    CONSTRAINT [PK_MaterialGroupGL] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_MaterialGroupGL_Activity] FOREIGN KEY ([InventoryActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_MaterialGroupGL_Activity_ClearingAccountActivityId] FOREIGN KEY ([ClearingAccountActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_MaterialGroupGL_Activity_CreditNoteGL] FOREIGN KEY ([CreditNoteActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_MaterialGroupGL_Activity_DebitNoteGL] FOREIGN KEY ([DebitNoteActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_MaterialGroupGL_Activity_DownPaymentActivityId] FOREIGN KEY ([DownPaymentActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_MaterialGroupGL_Activity_ExpenseGL] FOREIGN KEY ([ExpenseActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_MaterialGroupGL_Activity_RejectionGL] FOREIGN KEY ([RejectionActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_MaterialGroupGL_Activity_ShortageGL] FOREIGN KEY ([ShortageActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_MaterialGroupGL_BudgetMaster_CreditNoteBudgetMaster] FOREIGN KEY ([CreditNoteBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_MaterialGroupGL_BudgetMaster_DebitNoteBudgetMaster] FOREIGN KEY ([DebitNoteBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_MaterialGroupGL_BudgetMaster_RejectionBudgetMaster] FOREIGN KEY ([RejectionBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_MaterialGroupGL_BudgetMaster_ShortageBudgetMaster] FOREIGN KEY ([ShortageBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_MaterialGroupGL_ClearingAccountBudgetMaster] FOREIGN KEY ([ClearingAccountBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_MaterialGroupGL_COA] FOREIGN KEY ([COAId]) REFERENCES [HKP].[COA] ([Id]),
    CONSTRAINT [FK_MaterialGroupGL_DownPaymentBudgetMaster] FOREIGN KEY ([DownPaymentBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_MaterialGroupGL_DownPaymentGL] FOREIGN KEY ([DownPaymentGLId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_MaterialGroupGL_ExpenseBudgetMaster] FOREIGN KEY ([ExpenseBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_MaterialGroupGL_GLGeneralInfo] FOREIGN KEY ([InventoryGLId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_MaterialGroupGL_GLGeneralInfo_ClearingAccountGLId] FOREIGN KEY ([ClearingAccountGLId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_MaterialGroupGL_GLGeneralInfo_CreditNoteGL] FOREIGN KEY ([CreditNoteGLId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_MaterialGroupGL_GLGeneralInfo_DebitNoteGL] FOREIGN KEY ([DebitNoteGLId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_MaterialGroupGL_GLGeneralInfo_ExpenseGL] FOREIGN KEY ([ExpenseGLId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_MaterialGroupGL_GLGeneralInfo_RejectionGL] FOREIGN KEY ([RejectionGLId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_MaterialGroupGL_GLGeneralInfo_ShortageGL] FOREIGN KEY ([ShortageGLId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_MaterialGroupGL_InventoryBudgetMaster] FOREIGN KEY ([InventoryBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_MaterialGroupGL_MaterialGroupMaster] FOREIGN KEY ([MaterialGroupMasterId]) REFERENCES [MST].[MaterialGroupMaster] ([Id])
);

