CREATE TABLE [HKP].[MaterialAttributeValue] (
    [Id]                  VARCHAR (10)    NOT NULL,
    [CompanyGroupId]      VARCHAR (10)    NOT NULL,
    [MaterialAttributeId] VARCHAR (10)    NOT NULL,
    [Sequence]            DECIMAL (18, 2) NOT NULL,
    [Code]                VARCHAR (50)    NOT NULL,
    [ShortName]           VARCHAR (15)    NOT NULL,
    [StandardName]        VARCHAR (50)    NOT NULL,
    [UserName]            VARCHAR (50)    NOT NULL,
    [Remarks]             VARCHAR (250)   NULL,
    [Description]         VARCHAR (250)   NULL,
    [IsDefault]           BIT             NOT NULL,
    [Active]              BIT             NOT NULL,
    [Archive]             BIT             NOT NULL,
    [AddedBy]             VARCHAR (30)    NOT NULL,
    [AddedDate]           DATETIME        NOT NULL,
    [AddedFromIP]         VARCHAR (15)    NOT NULL,
    [UpdatedBy]           VARCHAR (30)    NULL,
    [UpdatedDate]         DATETIME        NULL,
    [UpdatedFromIP]       VARCHAR (15)    NULL,
    [MaterialMasterId]    VARCHAR (30)    NULL,
    [SourceType]          VARCHAR (10)    NOT NULL,
    CONSTRAINT [PK_MaterialValue] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_MaterialAttributeValue_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_MaterialAttributeValue_MaterialAttribute] FOREIGN KEY ([MaterialAttributeId]) REFERENCES [HKP].[MaterialAttribute] ([Id]),
    CONSTRAINT [FK_MaterialAttributeValue_MaterialMaster] FOREIGN KEY ([MaterialMasterId]) REFERENCES [MST].[MaterialMaster] ([Id])
);

