CREATE TABLE [HKP].[PartyGroup] (
    [Id]                      VARCHAR (10)    NOT NULL,
    [CompanyGroupId]          VARCHAR (10)    NOT NULL,
    [AddressMasterId]         VARCHAR (20)    NULL,
    [PartyGroupCategoryId]    VARCHAR (10)    NULL,
    [PartyGroupSubCategoryId] VARCHAR (10)    NULL,
    [PartyGroupClassId]       VARCHAR (10)    NULL,
    [Sequence]                DECIMAL (18, 2) NOT NULL,
    [Code]                    VARCHAR (10)    NOT NULL,
    [ShortName]               VARCHAR (15)    NOT NULL,
    [StandardName]            VARCHAR (50)    NOT NULL,
    [UserName]                VARCHAR (50)    NOT NULL,
    [RefNo]                   VARCHAR (50)    NULL,
    [GroupType]               VARCHAR (8)     NULL,
    [TransactionType]         VARCHAR (30)    NULL,
    [ExciseRange]             VARCHAR (100)   NULL,
    [CommissionRate]          DECIMAL (18, 4) NOT NULL,
    [IECNo]                   VARCHAR (50)    NULL,
    [PINCode]                 VARCHAR (50)    NULL,
    [CSTNO]                   VARCHAR (50)    NULL,
    [LSTNO]                   VARCHAR (50)    NULL,
    [TINNO]                   VARCHAR (50)    NULL,
    [VATResistrationNo]       VARCHAR (20)    NULL,
    [DebitLimit]              DECIMAL (18, 2) NULL,
    [CreditLimit]             DECIMAL (18, 2) NULL,
    [Description]             VARCHAR (250)   NULL,
    [Remarks]                 VARCHAR (250)   NULL,
    [Active]                  BIT             NOT NULL,
    [Archive]                 BIT             NOT NULL,
    [AddedBy]                 VARCHAR (30)    NOT NULL,
    [AddedDate]               DATETIME        NOT NULL,
    [AddedFromIP]             VARCHAR (15)    NOT NULL,
    [UpdatedBy]               VARCHAR (30)    NULL,
    [UpdatedDate]             DATETIME        NULL,
    [UpdatedFromIP]           VARCHAR (15)    NULL,
    CONSTRAINT [PK_PartyGroup] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_PartyGroup_AddressMaster] FOREIGN KEY ([AddressMasterId]) REFERENCES [MST].[AddressMaster] ([Id]),
    CONSTRAINT [FK_PartyGroup_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_PartyGroup_PartyGroupCategory] FOREIGN KEY ([PartyGroupCategoryId]) REFERENCES [HKP].[PartyGroupCategory] ([Id]),
    CONSTRAINT [FK_PartyGroup_PartyGroupClass] FOREIGN KEY ([PartyGroupClassId]) REFERENCES [HKP].[PartyGroupClass] ([Id]),
    CONSTRAINT [FK_PartyGroup_PartyGroupSubCategory] FOREIGN KEY ([PartyGroupSubCategoryId]) REFERENCES [HKP].[PartyGroupSubCategory] ([Id])
);

