CREATE TABLE [HKP].[PartyMapping] (
    [Id]              INT           IDENTITY (1, 1) NOT NULL,
    [CompanyGroupId]  VARCHAR (10)  NOT NULL,
    [CompanyId]       VARCHAR (10)  NOT NULL,
    [PlantId]         VARCHAR (10)  NOT NULL,
    [PartyId]         VARCHAR (10)  NULL,
    [PartyPlantId]    VARCHAR (12)  NULL,
    [OldPartyId]      VARCHAR (60)  NULL,
    [OldPartyName]    VARCHAR (200) NULL,
    [AddedBy]         VARCHAR (30)  NOT NULL,
    [AddedDate]       DATETIME      NOT NULL,
    [AddedFromIP]     VARCHAR (15)  NOT NULL,
    [UpdatedBy]       VARCHAR (30)  NULL,
    [UpdatedDate]     DATETIME      NULL,
    [UpdatedFromIP]   VARCHAR (15)  NULL,
    [PartyType]       VARCHAR (20)  NULL,
    [OldPartyGSTIN]   VARCHAR (20)  NULL,
    [OldPartyCountry] VARCHAR (60)  NULL,
    [OldPartyState]   VARCHAR (60)  NULL,
    [OldPartyCity]    VARCHAR (60)  NULL,
    [OldPartyAddress] VARCHAR (300) NULL,
    CONSTRAINT [PK_PartyMapping] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_PartyMapping_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_PartyMapping_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_PartyMapping_Party] FOREIGN KEY ([PartyId]) REFERENCES [HKP].[Party] ([Id]),
    CONSTRAINT [FK_PartyMapping_PartyPlant] FOREIGN KEY ([PartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_PartyMapping_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id])
);

