CREATE TABLE [HKP].[Party] (
    [Id]                               VARCHAR (10)    NOT NULL,
    [CompanyGroupId]                   VARCHAR (10)    NULL,
    [PartyGroupId]                     VARCHAR (10)    NULL,
    [CompanyId]                        VARCHAR (10)    NULL,
    [AddressMasterId]                  VARCHAR (20)    NULL,
    [VendorAccountGroupId]             VARCHAR (10)    NULL,
    [CustomerAccountGroupId]           VARCHAR (10)    NULL,
    [PartyType]                        VARCHAR (20)    NOT NULL,
    [Sequence]                         DECIMAL (18, 2) NOT NULL,
    [Code]                             VARCHAR (20)    NOT NULL,
    [ShortName]                        VARCHAR (15)    NULL,
    [StandardName]                     VARCHAR (100)   NULL,
    [UserName]                         VARCHAR (100)   NULL,
    [RefNo]                            VARCHAR (50)    NULL,
    [TransactionType]                  VARCHAR (30)    NULL,
    [ExciseRange]                      VARCHAR (50)    NULL,
    [CommissionRate]                   DECIMAL (18, 4) NOT NULL,
    [IECNo]                            VARCHAR (50)    NULL,
    [PINCode]                          VARCHAR (50)    NULL,
    [CSTNO]                            VARCHAR (50)    NULL,
    [BINNO]                            VARCHAR (50)    NULL,
    [TINNO]                            VARCHAR (50)    NULL,
    [LSTNO]                            VARCHAR (50)    NULL,
    [VATResistrationNo]                VARCHAR (20)    NULL,
    [TradeLicenseNo]                   VARCHAR (20)    NULL,
    [CertificationOfIncorporationNo]   VARCHAR (20)    NULL,
    [DebitLimit]                       DECIMAL (18, 4) NULL,
    [CreditLimit]                      DECIMAL (18, 4) NULL,
    [Description]                      VARCHAR (250)   NULL,
    [Remarks]                          VARCHAR (250)   NULL,
    [Active]                           BIT             NOT NULL,
    [Archive]                          BIT             NOT NULL,
    [AddedBy]                          VARCHAR (30)    NOT NULL,
    [AddedDate]                        DATETIME        NOT NULL,
    [AddedFromIP]                      VARCHAR (15)    NOT NULL,
    [UpdatedBy]                        VARCHAR (30)    NULL,
    [UpdatedDate]                      DATETIME        NULL,
    [UpdatedFromIP]                    VARCHAR (15)    NULL,
    [Latitude]                         VARCHAR (30)    NULL,
    [Longitude]                        VARCHAR (30)    NULL,
    [CertificationOfIncorporationDate] DATETIME        NULL,
    CONSTRAINT [PK_Party] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Party_AddressMaster] FOREIGN KEY ([AddressMasterId]) REFERENCES [MST].[AddressMaster] ([Id]),
    CONSTRAINT [FK_Party_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_Party_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_Party_CustomerAccountGroup] FOREIGN KEY ([CustomerAccountGroupId]) REFERENCES [HKP].[PartyAccountGroup] ([Id]),
    CONSTRAINT [FK_Party_PartyGroup] FOREIGN KEY ([PartyGroupId]) REFERENCES [HKP].[PartyGroup] ([Id]),
    CONSTRAINT [FK_Party_VendorAccountGroup] FOREIGN KEY ([VendorAccountGroupId]) REFERENCES [HKP].[PartyAccountGroup] ([Id])
);

