CREATE TABLE [HKP].[Process] (
    [Id]                  VARCHAR (10)    NOT NULL,
    [CompanyGroupId]      VARCHAR (10)    NULL,
    [MaterialTypeId]      VARCHAR (10)    NULL,
    [Sequence]            DECIMAL (18, 2) NOT NULL,
    [Code]                VARCHAR (10)    NOT NULL,
    [UserName]            VARCHAR (50)    NOT NULL,
    [StandardName]        VARCHAR (50)    NULL,
    [ShortName]           VARCHAR (15)    NULL,
    [Remarks]             VARCHAR (250)   NULL,
    [IsProductionProcess] BIT             NOT NULL,
    [IsProcessRouting]    BIT             NOT NULL,
    [IsLocked]            BIT             NOT NULL,
    [IsAppApplicable]     BIT             CONSTRAINT [DF_Process_IsAppApplicable] DEFAULT ('false') NOT NULL,
    [IsChecked]           BIT             CONSTRAINT [DF_Process_IsChecked] DEFAULT ('false') NOT NULL,
    [Active]              BIT             NOT NULL,
    [Archive]             BIT             NOT NULL,
    [AddedBy]             VARCHAR (30)    NOT NULL,
    [AddedDate]           DATETIME        NOT NULL,
    [AddedFromIP]         VARCHAR (15)    NOT NULL,
    [UpdatedBy]           VARCHAR (30)    NULL,
    [UpdatedDate]         DATETIME        NULL,
    [UpdatedFromIP]       VARCHAR (15)    NULL,
    [IsValueAdded]        BIT             DEFAULT ((0)) NOT NULL,
    [ProcessGroupId]      VARCHAR (10)    NULL,
    [IsFirst]             BIT             DEFAULT ((0)) NULL,
    [IsLast]              BIT             DEFAULT ((0)) NULL,
    CONSTRAINT [PK_aplos.Process] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Process_ProcessGroup] FOREIGN KEY ([ProcessGroupId]) REFERENCES [HKP].[ProcessGroup] ([Id]),
    CONSTRAINT [FK_Processes_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_Processes_MaterialType] FOREIGN KEY ([MaterialTypeId]) REFERENCES [HKP].[MaterialType] ([Id])
);

