CREATE TABLE [HKP].[SeparationType] (
    [Id]                         VARCHAR (10)    NOT NULL,
    [Sequence]                   DECIMAL (18, 2) NOT NULL,
    [Code]                       VARCHAR (10)    NOT NULL,
    [ShortName]                  VARCHAR (15)    NOT NULL,
    [StandardName]               VARCHAR (50)    NOT NULL,
    [UserName]                   VARCHAR (50)    NOT NULL,
    [Description]                VARCHAR (250)   NULL,
    [Remarks]                    VARCHAR (250)   NULL,
    [IsActive]                   BIT             NOT NULL,
    [IsArchive]                  BIT             NOT NULL,
    [AddedBy]                    VARCHAR (30)    NOT NULL,
    [AddedDate]                  DATETIME        NOT NULL,
    [AddedFromIP]                VARCHAR (15)    NOT NULL,
    [UpdatedBy]                  VARCHAR (30)    NULL,
    [UpdatedDate]                DATETIME        NULL,
    [UpdatedFromIP]              VARCHAR (15)    NULL,
    [FormulaDes]                 VARCHAR (1000)  NULL,
    [FormulaDesID]               VARCHAR (500)   NULL,
    [PlantID]                    VARCHAR (10)    NOT NULL,
    [IsGratuityApplicable]       BIT             DEFAULT ((0)) NOT NULL,
    [IsFixedDayAmountApplicable] BIT             DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_SeparationType] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_SeparationType_Plant] FOREIGN KEY ([PlantID]) REFERENCES [ORG].[Plant] ([Id])
);

