CREATE TABLE [HKP].[ServiceMasterCharges] (
    [Id]                      VARCHAR (10)    NOT NULL,
    [Sequence]                DECIMAL (18, 2) NULL,
    [Code]                    VARCHAR (10)    NULL,
    [ShortName]               VARCHAR (15)    NULL,
    [StandardName]            VARCHAR (50)    NULL,
    [UserName]                VARCHAR (50)    NULL,
    [Description]             VARCHAR (250)   NULL,
    [Remarks]                 VARCHAR (250)   NULL,
    [Active]                  BIT             NOT NULL,
    [Type]                    VARCHAR (20)    NULL,
    [ServiceMasterId]         VARCHAR (12)    NULL,
    [PurchaseGLGeneralInfoId] VARCHAR (10)    NULL,
    [PurchaseBudgetMasterId]  VARCHAR (20)    NULL,
    [PurchaseActivityId]      VARCHAR (10)    NULL,
    [SaleGLGeneralInfoId]     VARCHAR (10)    NULL,
    [SaleBudgetMasterId]      VARCHAR (20)    NULL,
    [SaleActivityId]          VARCHAR (10)    NULL,
    [AddedBy]                 VARCHAR (30)    NULL,
    [AddedDate]               DATETIME        NULL,
    [AddedFromIP]             VARCHAR (15)    NULL,
    [UpdatedBy]               VARCHAR (30)    NULL,
    [UpdatedDate]             DATETIME        NULL,
    [UpdatedFromIP]           VARCHAR (15)    NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    FOREIGN KEY ([SaleActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    FOREIGN KEY ([SaleActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    FOREIGN KEY ([SaleActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    FOREIGN KEY ([SaleActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    FOREIGN KEY ([SaleBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    FOREIGN KEY ([SaleBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    FOREIGN KEY ([SaleBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    FOREIGN KEY ([SaleBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    FOREIGN KEY ([SaleGLGeneralInfoId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    FOREIGN KEY ([SaleGLGeneralInfoId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    FOREIGN KEY ([SaleGLGeneralInfoId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    FOREIGN KEY ([SaleGLGeneralInfoId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_ServiceMasterCharges_PurchaseActivity] FOREIGN KEY ([PurchaseActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_ServiceMasterCharges_PurchaseBudgetMaster] FOREIGN KEY ([PurchaseBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_ServiceMasterCharges_PurchaseGLGeneralInfo] FOREIGN KEY ([PurchaseGLGeneralInfoId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_ServiceMasterCharges_SaleActivity] FOREIGN KEY ([SaleActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_ServiceMasterCharges_SaleBudgetMaster] FOREIGN KEY ([SaleBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_ServiceMasterCharges_SaleGLGeneralInfo] FOREIGN KEY ([SaleGLGeneralInfoId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_ServiceMasterCharges_ServiceMaster] FOREIGN KEY ([ServiceMasterId]) REFERENCES [HKP].[ServiceMaster] ([Id])
);

