CREATE TABLE [HKP].[ServiceGroupGL] (
    [Id]                            VARCHAR (10) NOT NULL,
    [COAId]                         VARCHAR (10) NULL,
    [ServiceGroupId]                VARCHAR (10) NULL,
    [DownPaymentGLId]               VARCHAR (10) NULL,
    [DownPaymentBudgetMasterId]     VARCHAR (20) NULL,
    [DownPaymentActivityId]         VARCHAR (10) NULL,
    [ClearingAccountGLId]           VARCHAR (10) NULL,
    [ClearingAccountBudgetMasterId] VARCHAR (20) NULL,
    [ClearingAccountActivityId]     VARCHAR (10) NULL,
    [ServiceGLId]                   VARCHAR (10) NULL,
    [ServiceBudgetMasterId]         VARCHAR (20) NULL,
    [ServiceActivityId]             VARCHAR (10) NULL,
    [ExpenseGLId]                   VARCHAR (10) NULL,
    [ExpenseBudgetMasterId]         VARCHAR (20) NULL,
    [ExpenseActivityId]             VARCHAR (10) NULL,
    [AddedBy]                       VARCHAR (30) NOT NULL,
    [AddedDate]                     DATETIME     NOT NULL,
    [AddedFromIP]                   VARCHAR (15) NOT NULL,
    [UpdatedBy]                     VARCHAR (30) NULL,
    [UpdatedDate]                   DATETIME     NULL,
    [UpdatedFromIP]                 VARCHAR (15) NULL,
    CONSTRAINT [PK_ServiceGroupGL] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ServiceGroupGL_Activity] FOREIGN KEY ([ServiceActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_ServiceGroupGL_Activity_ClearingAccountActivityId] FOREIGN KEY ([ClearingAccountActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_ServiceGroupGL_Activity_DownPaymentActivityId] FOREIGN KEY ([DownPaymentActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_ServiceGroupGL_Activity_ExpenseGL] FOREIGN KEY ([ExpenseActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_ServiceGroupGL_ClearingAccountBudgetMaster] FOREIGN KEY ([ClearingAccountBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_ServiceGroupGL_COAId] FOREIGN KEY ([COAId]) REFERENCES [HKP].[COA] ([Id]),
    CONSTRAINT [FK_ServiceGroupGL_DownPaymentBudgetMaster] FOREIGN KEY ([DownPaymentBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_ServiceGroupGL_DownPaymentGL] FOREIGN KEY ([DownPaymentGLId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_ServiceGroupGL_ExpenseBudgetMaster] FOREIGN KEY ([ExpenseBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_ServiceGroupGL_GLGeneralInfo_ClearingAccountGLId] FOREIGN KEY ([ClearingAccountGLId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_ServiceGroupGL_GLGeneralInfo_ExpenseGL] FOREIGN KEY ([ExpenseGLId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_ServiceGroupGL_GLGeneralInfo_ServiceGLId] FOREIGN KEY ([ServiceGLId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_ServiceGroupGL_ServiceBudgetMaster] FOREIGN KEY ([ServiceBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_ServiceGroupGL_ServiceGroup] FOREIGN KEY ([ServiceGroupId]) REFERENCES [HKP].[ServiceGroup] ([Id])
);

