CREATE TABLE [HKP].[SOPActivity] (
    [Id]                    VARCHAR (10)    NOT NULL,
    [SOPItemId]             VARCHAR (10)    NOT NULL,
    [PositionId]            VARCHAR (10)    NULL,
    [Name]                  VARCHAR (50)    NULL,
    [ActivityDetail]        VARCHAR (500)   NOT NULL,
    [PurposeOfTheActivity]  VARCHAR (200)   NULL,
    [ActivityCategoryId]    VARCHAR (50)    NOT NULL,
    [OtherActivityCategory] VARCHAR (200)   NULL,
    [PeriodId]              VARCHAR (50)    NOT NULL,
    [Frequency]             DECIMAL (18, 2) NOT NULL,
    [AverageTime]           INT             NULL,
    [ActivityImportanceId]  VARCHAR (50)    NOT NULL,
    [ValueInActivity]       VARCHAR (10)    NOT NULL,
    [FinancialImpact]       BIT             NULL,
    [Remarks]               VARCHAR (250)   NULL,
    [Documents]             BIT             NULL,
    [KPI]                   BIT             NULL,
    [AddedBy]               VARCHAR (30)    NOT NULL,
    [AddedDate]             DATETIME        NOT NULL,
    [AddedFromIP]           VARCHAR (15)    NOT NULL,
    [UpdatedBy]             VARCHAR (30)    NULL,
    [UpdatedDate]           DATETIME        NULL,
    [UpdatedFromIP]         VARCHAR (15)    NULL,
    CONSTRAINT [PK_SOPActivity] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_SOPActivity_Position] FOREIGN KEY ([PositionId]) REFERENCES [ORG].[Position] ([Id]),
    CONSTRAINT [FK_SOPActivity_SOPItem] FOREIGN KEY ([SOPItemId]) REFERENCES [HKP].[SOPItem] ([Id])
);

