CREATE TABLE [HKP].[SOPItem] (
    [Id]               VARCHAR (10)    NOT NULL,
    [CompanyGroupId]   VARCHAR (10)    NULL,
    [SOPCategoryId]    VARCHAR (10)    NULL,
    [SOPSubCategoryId] VARCHAR (10)    NULL,
    [Sequence]         DECIMAL (18, 2) NOT NULL,
    [Code]             VARCHAR (10)    NOT NULL,
    [ShortName]        VARCHAR (15)    NULL,
    [StandardName]     VARCHAR (50)    NULL,
    [UserName]         VARCHAR (50)    NOT NULL,
    [Description]      VARCHAR (250)   NULL,
    [Remarks]          VARCHAR (250)   NULL,
    [Active]           BIT             NOT NULL,
    [Archive]          BIT             NOT NULL,
    [AddedBy]          VARCHAR (30)    NOT NULL,
    [AddedDate]        DATETIME        NOT NULL,
    [AddedFromIP]      VARCHAR (15)    NOT NULL,
    [UpdatedBy]        VARCHAR (30)    NULL,
    [UpdatedDate]      DATETIME        NULL,
    [UpdatedFromIP]    VARCHAR (15)    NULL,
    [Objective]        VARCHAR (250)   NULL,
    [Mission]          VARCHAR (250)   NULL,
    [Vision]           VARCHAR (250)   NULL,
    CONSTRAINT [PK_aplos.SOPItem] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_SOPItems_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_SOPItems_SOPCategory] FOREIGN KEY ([SOPCategoryId]) REFERENCES [HKP].[SOPCategory] ([Id]),
    CONSTRAINT [FK_SOPItems_SOPSubCategory] FOREIGN KEY ([SOPSubCategoryId]) REFERENCES [HKP].[SOPSubCategory] ([Id])
);

