CREATE TABLE [HKP].[StitchCode] (
    [Id]             VARCHAR (10)    NOT NULL,
    [CompanyGroupId] VARCHAR (10)    NOT NULL,
    [PlantId]        VARCHAR (10)    NULL,
    [Sequence]       DECIMAL (18, 2) NOT NULL,
    [Code]           VARCHAR (10)    NOT NULL,
    [ShortName]      VARCHAR (15)    NOT NULL,
    [StandardName]   VARCHAR (50)    NOT NULL,
    [UserName]       VARCHAR (50)    NOT NULL,
    [Description]    VARCHAR (100)   NULL,
    [Remarks]        VARCHAR (150)   NULL,
    [Active]         BIT             NOT NULL,
    [Archive]        BIT             NOT NULL,
    [AddedBy]        VARCHAR (30)    NOT NULL,
    [AddedDate]      DATETIME        NOT NULL,
    [AddedFromIP]    VARCHAR (15)    NOT NULL,
    [UpdatedBy]      VARCHAR (30)    NULL,
    [UpdatedDate]    DATETIME        NULL,
    [UpdatedFromIP]  VARCHAR (15)    NULL,
    [Needle]         DECIMAL (18, 2) DEFAULT ((0)) NULL,
    [Bobbin]         DECIMAL (18, 2) DEFAULT ((0)) NULL,
    [Looper]         DECIMAL (18, 2) DEFAULT ((0)) NULL,
    CONSTRAINT [PK_StitchCode] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_StitchCode_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_StitchCode_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id])
);

