CREATE TABLE [dbo].[AttachmentDetailConsumption] (
    [Id]                           VARCHAR (30)    NOT NULL,
    [BOMAttachmentDetailId]        VARCHAR (30)    NULL,
    [RMMaterialMasterId]           VARCHAR (30)    NOT NULL,
    [RMArticleId]                  VARCHAR (10)    NULL,
    [Description]                  VARCHAR (250)   NULL,
    [CustomerSpec]                 VARCHAR (100)   NULL,
    [VendorSpec]                   VARCHAR (100)   NULL,
    [Consumption]                  DECIMAL (18, 6) NULL,
    [UoMId]                        VARCHAR (10)    NULL,
    [ProcessId]                    VARCHAR (10)    NULL,
    [VendorId]                     VARCHAR (10)    NULL,
    [WastagePer]                   DECIMAL (18, 2) NULL,
    [FirstCharacteristicsId]       VARCHAR (10)    NULL,
    [SecondCharacteristicsId]      VARCHAR (10)    NULL,
    [ThirdCharacteristicsId]       VARCHAR (10)    NULL,
    [FirstCharacteristicsValueId]  VARCHAR (10)    NULL,
    [SecondCharacteristicsValueId] VARCHAR (10)    NULL,
    [ThirdCharacteristicsValueId]  VARCHAR (10)    NULL,
    [IsSKUCommon]                  BIT             NULL,
    [Sequence]                     INT             NULL,
    [AddedBy]                      VARCHAR (30)    NOT NULL,
    [AddedDate]                    DATETIME        NOT NULL,
    [AddedFromIP]                  VARCHAR (15)    NOT NULL,
    [UpdatedBy]                    VARCHAR (30)    NULL,
    [UpdatedDate]                  DATETIME        NULL,
    [UpdatedFromIP]                VARCHAR (15)    NULL,
    CONSTRAINT [PK_AttachmentDetailConsumption] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_AttachmentDetailConsumption_BOMAttachmentDetail] FOREIGN KEY ([BOMAttachmentDetailId]) REFERENCES [dbo].[BOMAttachmentDetail] ([Id]),
    CONSTRAINT [FK_AttachmentDetailConsumption_FirstCharacteristic] FOREIGN KEY ([FirstCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_AttachmentDetailConsumption_FirstCharacteristicsValue] FOREIGN KEY ([FirstCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_AttachmentDetailConsumption_MaterialMaster] FOREIGN KEY ([RMMaterialMasterId]) REFERENCES [MST].[MaterialMaster] ([Id]),
    CONSTRAINT [FK_AttachmentDetailConsumption_MaterialMasterArticle] FOREIGN KEY ([RMArticleId]) REFERENCES [MST].[MaterialMasterArticle] ([Id]),
    CONSTRAINT [FK_AttachmentDetailConsumption_Party] FOREIGN KEY ([VendorId]) REFERENCES [HKP].[Party] ([Id]),
    CONSTRAINT [FK_AttachmentDetailConsumption_Process] FOREIGN KEY ([ProcessId]) REFERENCES [HKP].[Process] ([Id]),
    CONSTRAINT [FK_AttachmentDetailConsumption_SecondCharacteristics] FOREIGN KEY ([SecondCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_AttachmentDetailConsumption_SecondCharacteristicsValue] FOREIGN KEY ([SecondCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_AttachmentDetailConsumption_ThirdCharacteristics] FOREIGN KEY ([ThirdCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_AttachmentDetailConsumption_ThirdCharacteristicsValue] FOREIGN KEY ([ThirdCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_AttachmentDetailConsumption_UnitOfMeasurement] FOREIGN KEY ([UoMId]) REFERENCES [SCS].[UnitOfMeasurement] ([Id])
);

