CREATE TABLE [dbo].[AttachmentDetailConsumptionSKUMapping] (
    [Id]                              VARCHAR (30)  NOT NULL,
    [AttachmentDetailConsumptionId]   VARCHAR (30)  NULL,
    [RMFirstCharacteristicsId]        VARCHAR (10)  NULL,
    [RMFirstCharacteristicsValueId]   VARCHAR (10)  NULL,
    [RMSecondCharacteristicsId]       VARCHAR (10)  NULL,
    [RMSecondCharacteristicsValueId]  VARCHAR (10)  NULL,
    [RMThirdCharacteristicsId]        VARCHAR (10)  NULL,
    [RMThirdCharacteristicsValueId]   VARCHAR (10)  NULL,
    [SubFirstCharacteristicsId]       VARCHAR (10)  NULL,
    [SubFirstCharacteristicsValueId]  VARCHAR (10)  NULL,
    [SubSecondCharacteristicsId]      VARCHAR (10)  NULL,
    [SubSecondCharacteristicsValueId] VARCHAR (10)  NULL,
    [SubThirdCharacteristicsId]       VARCHAR (10)  NULL,
    [SubThirdCharacteristicsValueId]  VARCHAR (10)  NULL,
    [Description]                     VARCHAR (250) NULL,
    [IsFirstCharacteristicCommon]     BIT           NULL,
    [IsSecondCharacteristicCommon]    BIT           NULL,
    [IsThirdCharacteristicCommon]     BIT           NULL,
    [AddedBy]                         VARCHAR (30)  NOT NULL,
    [AddedDate]                       DATETIME      NOT NULL,
    [AddedFromIP]                     VARCHAR (15)  NOT NULL,
    [UpdatedBy]                       VARCHAR (30)  NULL,
    [UpdatedDate]                     DATETIME      NULL,
    [UpdatedFromIP]                   VARCHAR (15)  NULL,
    CONSTRAINT [PK_AttachmentDetailConsumptionSKUMapping] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_AttachmentDetailConsumptionSKUMapping_AttachmentDetailConsumption] FOREIGN KEY ([AttachmentDetailConsumptionId]) REFERENCES [dbo].[AttachmentDetailConsumption] ([Id]),
    CONSTRAINT [FK_AttachmentDetailConsumptionSKUMapping_RMFirstCharacteristicsId] FOREIGN KEY ([RMFirstCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_AttachmentDetailConsumptionSKUMapping_RMFirstCharacteristicsValue] FOREIGN KEY ([RMFirstCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_AttachmentDetailConsumptionSKUMapping_RMSecondCharacteristics] FOREIGN KEY ([RMSecondCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_AttachmentDetailConsumptionSKUMapping_RMSecondCharacteristicsValue] FOREIGN KEY ([RMSecondCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_AttachmentDetailConsumptionSKUMapping_RMThirdCharacteristics] FOREIGN KEY ([RMThirdCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_AttachmentDetailConsumptionSKUMapping_RMThirdCharacteristicsValue] FOREIGN KEY ([RMThirdCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_AttachmentDetailConsumptionSKUMapping_SubFirstCharacteristicsId] FOREIGN KEY ([SubFirstCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_AttachmentDetailConsumptionSKUMapping_SubFirstCharacteristicsValue] FOREIGN KEY ([SubFirstCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_AttachmentDetailConsumptionSKUMapping_SubSecondCharacteristics] FOREIGN KEY ([SubSecondCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_AttachmentDetailConsumptionSKUMapping_SubSecondCharacteristicsValue] FOREIGN KEY ([SubSecondCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_AttachmentDetailConsumptionSKUMapping_SubThirdCharacteristics] FOREIGN KEY ([SubThirdCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_AttachmentDetailConsumptionSKUMapping_SubThirdCharacteristicsValue] FOREIGN KEY ([SubThirdCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_BOMAttachmentSKUMapping_SubFirstCharacteristicsId] FOREIGN KEY ([SubFirstCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id])
);

