CREATE TABLE [dbo].[AttdnDataMonthlySummary] (
    [EmpSystemID]         VARCHAR (30)    NOT NULL,
    [MonthNo]             INT             NOT NULL,
    [YearNo]              INT             NOT NULL,
    [GroupID]             VARCHAR (10)    NOT NULL,
    [PlantID]             VARCHAR (10)    NOT NULL,
    [FromDate]            DATETIME        NOT NULL,
    [ToDate]              DATETIME        NOT NULL,
    [TotalProcDate]       INT             CONSTRAINT [DF_AttdnDataMonthlySummary_TotalProcDate] DEFAULT ((0)) NOT NULL,
    [TotalPresent]        NUMERIC (18, 2) CONSTRAINT [DF_AttdnDataMonthlySummary_TotalPresent] DEFAULT ((0)) NOT NULL,
    [TotalLate]           NUMERIC (18, 2) NOT NULL,
    [TotalAbsent]         NUMERIC (18, 2) CONSTRAINT [DF_AttdnDataMonthlySummary_TotalAbsent] DEFAULT ((0)) NOT NULL,
    [TotalLv]             NUMERIC (18, 2) CONSTRAINT [DF_AttdnDataMonthlySummary_TotalLv] DEFAULT ((0)) NOT NULL,
    [TotalMLv]            INT             CONSTRAINT [DF_AttdnDataMonthlySummary_TotalMLv] DEFAULT ((0)) NOT NULL,
    [TotalCompAssignLv]   INT             CONSTRAINT [DF_AttdnDataMonthlySummary_TotalCompAssignLv] DEFAULT ((0)) NOT NULL,
    [TotalWeekOff]        INT             CONSTRAINT [DF_AttdnDataMonthlySummary_TotalWeekOff] DEFAULT ((0)) NOT NULL,
    [TotalHoliDay]        INT             CONSTRAINT [DF_AttdnDataMonthlySummary_TotalHoliDay] DEFAULT ((0)) NOT NULL,
    [TotalWeekOffHoliDay] INT             CONSTRAINT [DF_AttdnDataMonthlySummary_TotalWeekOffHoliDay] DEFAULT ((0)) NOT NULL,
    [TotalOTHr]           NUMERIC (18, 2) CONSTRAINT [DF_AttdnDataMonthlySummary_TotalOTHr] DEFAULT ((0)) NOT NULL,
    [TotalNormalOTHr]     NUMERIC (18, 2) CONSTRAINT [DF_AttdnDataMonthlySummary_TotalNormalOTHr] DEFAULT ((0)) NOT NULL,
    [TotalExtraOTHr]      NUMERIC (18, 2) CONSTRAINT [DF_AttdnDataMonthlySummary_TotalExtraOTHr] DEFAULT ((0)) NOT NULL,
    [IsDisbusted]         BIT             CONSTRAINT [DF_AttdnDataMonthlySummary_IsDisbusted] DEFAULT ((0)) NOT NULL,
    [AddedBy]             VARCHAR (100)   NULL,
    [DateAdded]           DATETIME        NULL,
    [UpdatedBy]           VARCHAR (100)   NULL,
    [DateUpdated]         DATETIME        NULL,
    [TotalLWP]            NUMERIC (18, 2) DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_AttdnDataMonthlySummary] PRIMARY KEY CLUSTERED ([EmpSystemID] ASC, [MonthNo] ASC, [YearNo] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_AttdnDataMonthlySummary_CompanyGroup] FOREIGN KEY ([GroupID]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_AttdnDataMonthlySummary_EmployeeInformation] FOREIGN KEY ([EmpSystemID]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_AttdnDataMonthlySummary_Plant] FOREIGN KEY ([PlantID]) REFERENCES [ORG].[Plant] ([Id])
);

