CREATE TABLE [dbo].[AttdnRawDataFromApp] (
    [Id]              VARCHAR (10)    NOT NULL,
    [PlantId]         VARCHAR (10)    NOT NULL,
    [EmployeeId]      VARCHAR (30)    NOT NULL,
    [PDate]           DATE            NOT NULL,
    [InTime]          DATETIME        NULL,
    [OutTime]         DATETIME        NULL,
    [Latitude]        VARCHAR (50)    NULL,
    [Longitude]       VARCHAR (50)    NULL,
    [Remarks]         VARCHAR (250)   NULL,
    [IsProcessed]     BIT             CONSTRAINT [DF_Table_1_IsGeneral] DEFAULT ((0)) NOT NULL,
    [AddedBy]         VARCHAR (30)    NOT NULL,
    [AddedDate]       DATETIME        NOT NULL,
    [UpdatedBy]       VARCHAR (30)    NULL,
    [UpdatedDate]     DATETIME        NULL,
    [IsLocked]        BIT             DEFAULT ((0)) NOT NULL,
    [SourceFlag]      VARCHAR (30)    NULL,
    [LocationDesc]    NVARCHAR (1024) NULL,
    [isApprovedIN]    BIT             DEFAULT ((0)) NULL,
    [ApprovedByIN]    VARCHAR (30)    NULL,
    [ApprovalDateIN]  DATETIME        NULL,
    [isApprovedOUT]   BIT             DEFAULT ((0)) NULL,
    [ApprovedByOUT]   VARCHAR (30)    NULL,
    [ApprovalDateOUT] DATETIME        NULL,
    [LatitudeOUT]     VARCHAR (50)    NULL,
    [LongitudeOUT]    VARCHAR (50)    NULL,
    [RemarksOUT]      VARCHAR (250)   NULL,
    [OutLocationDesc] NVARCHAR (1024) NULL,
    [INLocationDesc]  NVARCHAR (1024) NULL,
    [AttndType]       VARCHAR (50)    NULL,
    CONSTRAINT [PK_AttdnRawDataFromApp] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_AttdnRawDataFromApp_EmployeeInformation] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_AttdnRawDataFromApp_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id])
);

