CREATE TABLE [dbo].[AttdnProcessData] (
    [EmpSystemID]            VARCHAR (30)    NOT NULL,
    [WorkDate]               DATETIME        NOT NULL,
    [GroupID]                VARCHAR (10)    NULL,
    [PlantID]                VARCHAR (10)    NULL,
    [ShiftSystemID]          VARCHAR (30)    NULL,
    [InTime]                 DATETIME        NULL,
    [IsManualInTime]         BIT             CONSTRAINT [DF_AttdnProcessData_IsManualInTime] DEFAULT ((0)) NOT NULL,
    [OutTime]                DATETIME        NULL,
    [IsManualOutTime]        BIT             CONSTRAINT [DF_AttdnProcessData_IsManualOutTime] DEFAULT ((0)) NOT NULL,
    [DayStatus]              VARCHAR (10)    NULL,
    [IsManualDayStatus]      BIT             CONSTRAINT [DF_AttdnProcessData_IsManualDayStatus] DEFAULT ((0)) NOT NULL,
    [OTHr]                   NUMERIC (18, 2) CONSTRAINT [DF_AttdnProcessData_OTHr] DEFAULT ((0)) NOT NULL,
    [IsOTComfirm]            BIT             CONSTRAINT [DF_AttdnProcessData_IsOTComfirm] DEFAULT ((0)) NOT NULL,
    [OTComfirmBy]            VARCHAR (100)   NULL,
    [DateOTComfirm]          DATETIME        NULL,
    [LTSystemID]             VARCHAR (30)    NULL,
    [IsLock]                 BIT             CONSTRAINT [DF_AttdnProcessData_IsLock] DEFAULT ((0)) NOT NULL,
    [ToReprocess]            VARCHAR (5)     CONSTRAINT [DF_AttdnProcessData_ToReprocess] DEFAULT ('No') NOT NULL,
    [InTimeRowID]            INT             NULL,
    [OutTimeRowID]           INT             NULL,
    [AddedBy]                VARCHAR (100)   NULL,
    [DateAdded]              DATETIME        NULL,
    [UpdatedBy]              VARCHAR (100)   NULL,
    [DateUpdated]            DATETIME        NULL,
    [IsShortLeave]           BIT             CONSTRAINT [DF__AttdnProc__IsSho__4401C717] DEFAULT ((0)) NOT NULL,
    [DayStatusInTimeOnly]    VARCHAR (10)    NULL,
    [OTIntime]               NUMERIC (18, 2) CONSTRAINT [DF__AttdnProc__OTInt__7B51FC01] DEFAULT ((0)) NOT NULL,
    [OTOuttime]              NUMERIC (18, 2) CONSTRAINT [DF__AttdnProc__OTOut__7C46203A] DEFAULT ((0)) NOT NULL,
    [CountedShortLeave]      INT             NULL,
    [IsHalfDayLeave]         BIT             CONSTRAINT [DF__AttdnProc__IsHal__012AD0E8] DEFAULT ((0)) NOT NULL,
    [AttendanceRestDetailId] VARCHAR (50)    NULL,
    [IsOD]                   BIT             DEFAULT ((0)) NOT NULL,
    [IsLWP]                  BIT             DEFAULT ((0)) NOT NULL,
    [IsOTEntitled]           BIT             DEFAULT ((0)) NOT NULL,
    [PunchInTime]            DATETIME        NULL,
    [PunchOutTime]           DATETIME        NULL,
    [MaternityStatus]        VARCHAR (50)    NULL,
    [LockedBy]               VARCHAR (30)    NULL,
    [LockedDate]             DATETIME        NULL,
    [LeaveDuration]          NUMERIC (18, 2) DEFAULT ((0)) NOT NULL,
    [ManualShiftID]          VARCHAR (30)    NULL,
    [RosterShiftID]          VARCHAR (30)    NULL,
    [ProfileShiftID]         VARCHAR (30)    NULL,
    [BudgetedShiftID]        VARCHAR (30)    NULL,
    [ShiftInTime]            DATETIME        NULL,
    [ShiftOutTime]           DATETIME        NULL,
    [ShiftDuration]          NUMERIC (18, 2) NULL,
    [ManualInTime]           DATETIME        NULL,
    [ManualOutTime]          DATETIME        NULL,
    [InStatus]               VARCHAR (10)    NULL,
    [ManualDayStatus]        VARCHAR (10)    NULL,
    [Duration]               NUMERIC (18, 2) NULL,
    [EarlyIn]                NUMERIC (18, 2) NULL,
    [LateIn]                 NUMERIC (18, 2) NULL,
    [LateOut]                NUMERIC (18, 2) NULL,
    [EarlyOut]               NUMERIC (18, 2) NULL,
    [WrongShift]             BIT             DEFAULT ((0)) NULL,
    [BudgetId]               VARCHAR (10)    NULL,
    [RosterId]               VARCHAR (30)    NULL,
    [PlantInPunchStartTime]  DATETIME        NULL,
    [OutPunchLimit]          DATETIME        NULL,
    [WeeklyStatus]           VARCHAR (10)    NULL,
    [HolidayStatus]          VARCHAR (10)    NULL,
    [OverStay]               DECIMAL (18, 2) DEFAULT ((0)) NULL,
    [UnderStay]              DECIMAL (18, 2) DEFAULT ((0)) NULL,
    [LeaveStatus]            VARCHAR (10)    NULL,
    [DurationStatus]         VARCHAR (10)    NULL,
    [EarlyLateIn]            VARCHAR (10)    NULL,
    [EarlyLateOut]           VARCHAR (10)    NULL,
    [DayStatusCode]          VARCHAR (20)    NULL,
    CONSTRAINT [PK_AttdnProcessDate] PRIMARY KEY CLUSTERED ([EmpSystemID] ASC, [WorkDate] ASC),
    CONSTRAINT [FK_AttdnProcessData_AttendanceRestDetailId] FOREIGN KEY ([AttendanceRestDetailId]) REFERENCES [dbo].[AttendanceRestDetail] ([Id]),
    CONSTRAINT [FK_AttdnProcessData_BudgetedShiftID] FOREIGN KEY ([BudgetedShiftID]) REFERENCES [dbo].[ShiftDefination] ([SystemID]),
    CONSTRAINT [FK_AttdnProcessData_BudgetId] FOREIGN KEY ([BudgetId]) REFERENCES [MST].[ManpowerBudget] ([Id]),
    CONSTRAINT [FK_AttdnProcessData_CompanyGroup] FOREIGN KEY ([GroupID]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_AttdnProcessData_EmployeeInformation] FOREIGN KEY ([EmpSystemID]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_AttdnProcessData_ManualShiftID] FOREIGN KEY ([ManualShiftID]) REFERENCES [dbo].[ShiftDefination] ([SystemID]),
    CONSTRAINT [FK_AttdnProcessData_Plant] FOREIGN KEY ([PlantID]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_AttdnProcessData_ProfileShiftID] FOREIGN KEY ([ProfileShiftID]) REFERENCES [dbo].[ShiftDefination] ([SystemID]),
    CONSTRAINT [FK_AttdnProcessData_RosterId] FOREIGN KEY ([RosterId]) REFERENCES [dbo].[RosterPatternHeader] ([Id]),
    CONSTRAINT [FK_AttdnProcessData_RosterShiftID] FOREIGN KEY ([RosterShiftID]) REFERENCES [dbo].[ShiftDefination] ([SystemID]),
    CONSTRAINT [FK_AttdnProcessData_ShiftDefination] FOREIGN KEY ([ShiftSystemID]) REFERENCES [dbo].[ShiftDefination] ([SystemID])
);


GO
CREATE NONCLUSTERED INDEX [Ind_AttdnProcessData]
    ON [dbo].[AttdnProcessData]([EmpSystemID] ASC, [WorkDate] ASC, [ShiftSystemID] ASC);

