CREATE TABLE [dbo].[AttdnBonusPmtPolicyDetails] (
    [ID]                          VARCHAR (20)    NOT NULL,
    [AttdnBonusPmtPolicyID]       VARCHAR (20)    NOT NULL,
    [IsFixed]                     BIT             NULL,
    [FixedValue]                  NUMERIC (18, 2) NULL,
    [IsFormula]                   BIT             NULL,
    [FormulaDes]                  VARCHAR (1000)  NULL,
    [FormulaDesID]                VARCHAR (500)   NULL,
    [IsEarlyOutApplicable]        BIT             DEFAULT ((0)) NOT NULL,
    [FixedOrFormula]              VARCHAR (30)    DEFAULT ('Fixed') NOT NULL,
    [IsLateInApplicable]          BIT             NULL,
    [IsLunchOutApplicable]        BIT             DEFAULT ((0)) NULL,
    [IsAbsentApplicable]          BIT             DEFAULT ((0)) NULL,
    [IsLateApplicable]            BIT             DEFAULT ((0)) NULL,
    [IsLeaveApplicable]           BIT             DEFAULT ((0)) NULL,
    [IsLeaveWithOutPayApplicable] BIT             DEFAULT ((0)) NULL,
    [IsRouteApplicableForLate]    BIT             DEFAULT ((0)) NULL,
    [EOLIFromValue]               VARCHAR (30)    DEFAULT ((0)) NOT NULL,
    [EOLIToValue]                 VARCHAR (30)    DEFAULT ((0)) NOT NULL,
    [LunchOutFromValue]           VARCHAR (30)    DEFAULT ((0)) NOT NULL,
    [LunchOutToValue]             VARCHAR (30)    DEFAULT ((0)) NOT NULL,
    [AbsentFromValue]             VARCHAR (30)    DEFAULT ((0)) NOT NULL,
    [AbsentToValue]               VARCHAR (30)    DEFAULT ((0)) NOT NULL,
    [LateFromValue]               VARCHAR (30)    DEFAULT ((0)) NOT NULL,
    [LateToValue]                 VARCHAR (30)    DEFAULT ((0)) NOT NULL,
    [LeaveFromValue]              VARCHAR (30)    DEFAULT ((0)) NOT NULL,
    [LeaveToValue]                VARCHAR (30)    DEFAULT ((0)) NOT NULL,
    [LeaveWithOutPayFromValue]    VARCHAR (30)    DEFAULT ((0)) NOT NULL,
    [LeaveWithOutPayToValue]      VARCHAR (30)    DEFAULT ((0)) NOT NULL,
    [SalaryHeadID]                VARCHAR (10)    NULL,
    CONSTRAINT [PK_AttdnBonusPmtPolicyDetails] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_AttdnBonusPmtPolicyDetails_AttdnBonusPmtPolicyMaster] FOREIGN KEY ([AttdnBonusPmtPolicyID]) REFERENCES [dbo].[AttdnBonusPmtPolicyMaster] ([ID])
);

