CREATE TABLE [dbo].[AttdnManualDataBackUp] (
    [ID]                   INT            IDENTITY (1, 1) NOT NULL,
    [EmpSystemID]          VARCHAR (30)   NOT NULL,
    [WorkDate]             DATETIME       NOT NULL,
    [GroupID]              VARCHAR (10)   NULL,
    [PlantID]              VARCHAR (10)   NULL,
    [IsOutDuty]            BIT            CONSTRAINT [DF_AttdnManualDataBackUp_OutDuity] DEFAULT ((0)) NOT NULL,
    [DayStatus]            VARCHAR (10)   NULL,
    [InTime]               DATETIME       NULL,
    [OutTime]              DATETIME       NULL,
    [PrvIsOutDuty]         BIT            CONSTRAINT [DF_AttdnManualDataBackUp_IsOutDuty1] DEFAULT ((0)) NOT NULL,
    [PrvDayStatus]         VARCHAR (10)   NULL,
    [PrvIsManualDayStatus] BIT            CONSTRAINT [DF_AttdnManualDataBackUp_IsManualInTime] DEFAULT ((0)) NULL,
    [PrvInTime]            DATETIME       NULL,
    [PrvIsManualInTime]    BIT            CONSTRAINT [DF_AttdnManualDataBackUp_IsManualInTime1] DEFAULT ((0)) NULL,
    [PrvOutTime]           DATETIME       NULL,
    [PrvIsManualOutTime]   BIT            NULL,
    [AddedBy]              NVARCHAR (100) NULL,
    [DateAdded]            DATETIME       NULL,
    [UpdatedBy]            VARCHAR (100)  NULL,
    [DateUpdated]          DATETIME       NULL,
    [AddedPCIP]            VARCHAR (100)  NULL,
    [AddedPCMAC]           VARCHAR (100)  NULL,
    [UpdatedPCIP]          VARCHAR (100)  NULL,
    [UpdatedPCMAC]         VARCHAR (100)  NULL,
    CONSTRAINT [PK_AttdnManualDataBackUp] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_AttdnManualDataBackUp_AttdnManualData] FOREIGN KEY ([EmpSystemID]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_AttdnManualDataBackUp_CompanyGroup] FOREIGN KEY ([GroupID]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_AttdnManualDataBackUp_Plant] FOREIGN KEY ([PlantID]) REFERENCES [ORG].[Plant] ([Id])
);

