CREATE TABLE [dbo].[BOMDetail] (
    [Id]                           VARCHAR (20)    NOT NULL,
    [BOMMasterId]                  VARCHAR (20)    NOT NULL,
    [RMMaterialMasterId]           VARCHAR (30)    NOT NULL,
    [RMArticleId]                  VARCHAR (10)    NULL,
    [Description]                  VARCHAR (250)   NULL,
    [CustomerSpec]                 VARCHAR (100)   NULL,
    [VendorSpec]                   VARCHAR (100)   NULL,
    [Consumption]                  DECIMAL (18, 6) NULL,
    [UoMId]                        VARCHAR (10)    NULL,
    [ProcessId]                    VARCHAR (10)    NULL,
    [VendorId]                     VARCHAR (10)    NULL,
    [WastagePer]                   DECIMAL (18, 2) NULL,
    [FirstCharacteristicsId]       VARCHAR (10)    NULL,
    [SecondCharacteristicsId]      VARCHAR (10)    NULL,
    [ThirdCharacteristicsId]       VARCHAR (10)    NULL,
    [FirstCharacteristicsValueId]  VARCHAR (10)    NULL,
    [SecondCharacteristicsValueId] VARCHAR (10)    NULL,
    [ThirdCharacteristicsValueId]  VARCHAR (10)    NULL,
    [IsSKUCommon]                  BIT             NULL,
    [AddedBy]                      VARCHAR (30)    NOT NULL,
    [AddedDate]                    DATETIME        NOT NULL,
    [AddedFromIP]                  VARCHAR (15)    NOT NULL,
    [UpdatedBy]                    VARCHAR (30)    NULL,
    [UpdatedDate]                  DATETIME        NULL,
    [UpdatedFromIP]                VARCHAR (15)    NULL,
    [IsConsumptionDetail]          BIT             CONSTRAINT [DF__BOMDetail__IsCon__6D270597] DEFAULT ((0)) NOT NULL,
    [Sequence]                     DECIMAL (18, 2) CONSTRAINT [DF__BOMDetail__Seque__7F45B5D2] DEFAULT ((0)) NOT NULL,
    [IsDestinationSpecific]        BIT             DEFAULT ((0)) NOT NULL,
    [IsPOSpecific]                 BIT             DEFAULT ((0)) NOT NULL,
    [ConsumptionSpecificToSKU1]    BIT             DEFAULT ((0)) NOT NULL,
    [ConsumptionSpecificToSKU2]    BIT             DEFAULT ((0)) NOT NULL,
    [ConsumptionSpecificToSKU3]    BIT             DEFAULT ((0)) NOT NULL,
    [SalesOrderSpecificMaterial]   BIT             DEFAULT ((1)) NULL,
    CONSTRAINT [PK_BOMDetails] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_BOMDetail_BOMMaster] FOREIGN KEY ([BOMMasterId]) REFERENCES [dbo].[BOMMaster] ([Id]),
    CONSTRAINT [FK_BOMDetails_FirstCharacteristic] FOREIGN KEY ([FirstCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_BOMDetails_FirstCharacteristicsValue] FOREIGN KEY ([FirstCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_BOMDetails_MaterialMaster] FOREIGN KEY ([RMMaterialMasterId]) REFERENCES [MST].[MaterialMaster] ([Id]),
    CONSTRAINT [FK_BOMDetails_MaterialMasterArticle] FOREIGN KEY ([RMArticleId]) REFERENCES [MST].[MaterialMasterArticle] ([Id]),
    CONSTRAINT [FK_BOMDetails_Party] FOREIGN KEY ([VendorId]) REFERENCES [HKP].[Party] ([Id]),
    CONSTRAINT [FK_BOMDetails_Process] FOREIGN KEY ([ProcessId]) REFERENCES [HKP].[Process] ([Id]),
    CONSTRAINT [FK_BOMDetails_SecondCharacteristics] FOREIGN KEY ([SecondCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_BOMDetails_SecondCharacteristicsValue] FOREIGN KEY ([SecondCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_BOMDetails_ThirdCharacteristics] FOREIGN KEY ([ThirdCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_BOMDetails_ThirdCharacteristicsValue] FOREIGN KEY ([ThirdCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_BOMDetails_UnitOfMeasurement] FOREIGN KEY ([UoMId]) REFERENCES [SCS].[UnitOfMeasurement] ([Id])
);

