CREATE TABLE [dbo].[BonusPolicyMonthlyRetainDetails] (
    [ID]                     VARCHAR (20)    NOT NULL,
    [BnsPlcMthRetainID]      VARCHAR (20)    NULL,
    [FormulaDesEarning]      VARCHAR (1000)  NULL,
    [FormulaDesIDEarning]    VARCHAR (500)   NULL,
    [SalaryHeadIDEarning]    VARCHAR (500)   NULL,
    [EarningValueRangeFrom]  INT             NULL,
    [EarningValueRangeTo]    INT             NULL,
    [IsMandatory]            BIT             CONSTRAINT [DF_BonusPolicyMonthlyRetainDetails_IsMandatory] DEFAULT ((0)) NULL,
    [IsFixed]                BIT             NULL,
    [FixedValue]             NUMERIC (18, 2) NULL,
    [IsFormula]              BIT             CONSTRAINT [DF_BonusPolicyMonthlyRetainDetails_IsFormula] DEFAULT ((0)) NOT NULL,
    [IsDependOnEarning]      BIT             CONSTRAINT [DF_BonusPolicyMonthlyRetainDetails_IsDependOnEarning] DEFAULT ((0)) NOT NULL,
    [IsMinWages]             BIT             CONSTRAINT [DF_BonusPolicyMonthlyRetainDetails_IsMinWages] DEFAULT ((0)) NOT NULL,
    [CompMinWagesAndOrginal] VARCHAR (100)   NULL,
    [FormulaDes]             VARCHAR (1000)  NULL,
    [FormulaDesID]           VARCHAR (500)   NULL,
    [SalaryHeadID]           VARCHAR (500)   NULL,
    [GroupID]                VARCHAR (10)    NULL,
    [PlantID]                VARCHAR (10)    NULL,
    [AddedBy]                VARCHAR (30)    NOT NULL,
    [AddedDate]              DATETIME        NOT NULL,
    [AddedFromIP]            VARCHAR (15)    NOT NULL,
    [UpdatedBy]              VARCHAR (30)    NULL,
    [UpdatedDate]            DATETIME        NULL,
    [UpdatedFromIP]          VARCHAR (15)    NULL,
    CONSTRAINT [PK_BonusPolicyMonthlyRetainDetails] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_BonusPolicyMonthlyRetainDetails_BonusPolicyMonthlyRetainMaster] FOREIGN KEY ([BnsPlcMthRetainID]) REFERENCES [dbo].[BonusPolicyMonthlyRetainMaster] ([ID]),
    CONSTRAINT [FK_BonusPolicyMonthlyRetainDetails_CompanyGroup] FOREIGN KEY ([GroupID]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_BonusPolicyMonthlyRetainDetails_Plant] FOREIGN KEY ([PlantID]) REFERENCES [ORG].[Plant] ([Id])
);

