CREATE TABLE [dbo].[BOQRequisition] (
    [Id]                 INT             IDENTITY (1, 1) NOT NULL,
    [CostingBOQMasterId] VARCHAR (30)    NULL,
    [SalesOrderId]       VARCHAR (20)    NULL,
    [CostingItemId]      VARCHAR (10)    NULL,
    [DestinationId]      VARCHAR (10)    NULL,
    [MaterialMasterId]   VARCHAR (30)    NULL,
    [ArticleId]          VARCHAR (10)    NULL,
    [ItemRefNo]          VARCHAR (20)    NULL,
    [BOQCriteria]        VARCHAR (30)    NULL,
    [IncompleteMaterial] BIT             NULL,
    [UoMId]              VARCHAR (10)    NULL,
    [CurrencyId]         VARCHAR (10)    NULL,
    [VendorId]           VARCHAR (10)    NULL,
    [SKU1]               VARCHAR (10)    NULL,
    [SKU2]               VARCHAR (10)    NULL,
    [SKU3]               VARCHAR (10)    NULL,
    [OrderQty]           DECIMAL (18, 4) NULL,
    [BOMQty]             DECIMAL (18, 4) NULL,
    [RequiredQty]        DECIMAL (18, 4) NULL,
    [BOMAmount]          DECIMAL (18, 8) NULL,
    [Sequence]           DECIMAL (8, 2)  NULL,
    [AddedBy]            VARCHAR (30)    NULL,
    [AddedDate]          DATETIME        NULL,
    [AddedFromIP]        VARCHAR (15)    NULL,
    [UpdatedBy]          VARCHAR (30)    NULL,
    [UpdatedDate]        DATETIME        NULL,
    [UpdatedFromIP]      VARCHAR (15)    NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    FOREIGN KEY ([ArticleId]) REFERENCES [MST].[MaterialMasterArticle] ([Id]),
    FOREIGN KEY ([CostingBOQMasterId]) REFERENCES [dbo].[CostingBOQMaster] ([Id]),
    FOREIGN KEY ([CostingItemId]) REFERENCES [HKP].[CostingItem] ([Id]),
    FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    FOREIGN KEY ([DestinationId]) REFERENCES [MST].[Destination] ([Id]),
    FOREIGN KEY ([MaterialMasterId]) REFERENCES [MST].[MaterialMaster] ([Id]),
    FOREIGN KEY ([SalesOrderId]) REFERENCES [TRN].[SalesOrder] ([Id]),
    FOREIGN KEY ([SKU1]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    FOREIGN KEY ([SKU2]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    FOREIGN KEY ([SKU3]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    FOREIGN KEY ([UoMId]) REFERENCES [SCS].[UnitOfMeasurement] ([Id]),
    FOREIGN KEY ([VendorId]) REFERENCES [HKP].[Party] ([Id])
);

