CREATE TABLE [dbo].[Contract] (
    [Id]                                     VARCHAR (10)    NOT NULL,
    [CustomerId]                             VARCHAR (10)    NOT NULL,
    [IsLC]                                   BIT             CONSTRAINT [DF_Contract_IsLC] DEFAULT ((0)) NOT NULL,
    [AddedBy]                                VARCHAR (30)    NOT NULL,
    [AddedDate]                              DATETIME        NOT NULL,
    [AddedFromIP]                            VARCHAR (15)    NOT NULL,
    [UpdatedBy]                              VARCHAR (30)    NULL,
    [UpdatedDate]                            DATETIME        NULL,
    [UpdatedFromIP]                          VARCHAR (15)    NULL,
    [MasterLCId]                             VARCHAR (10)    NULL,
    [ContractNo]                             VARCHAR (50)    NULL,
    [TotalQty]                               DECIMAL (18, 2) NULL,
    [SOQty]                                  DECIMAL (18, 2) NULL,
    [Amount]                                 DECIMAL (18, 2) NULL,
    [Description]                            VARCHAR (250)   NULL,
    [UDNo]                                   VARCHAR (50)    NULL,
    [UDDate]                                 DATETIME        NULL,
    [ContractDate]                           DATETIME        NULL,
    [IsPrint]                                BIT             DEFAULT ((0)) NOT NULL,
    [IsMarketingCommisssionApplicable]       BIT             DEFAULT ((0)) NOT NULL,
    [MarketingCommisssionId]                 VARCHAR (10)    NULL,
    [IsBusinessDevelopmentChargesApplicable] BIT             DEFAULT ((0)) NOT NULL,
    [BusinessDevelopmentCharge]              VARCHAR (10)    NULL,
    [BusinessDevelopmentChargeValue]         DECIMAL (18, 4) NULL,
    [InvoicingPartyPlantId]                  VARCHAR (12)    NULL,
    [DeliveryPartyPlantId]                   VARCHAR (12)    NULL,
    [InvoicingByAddress]                     VARCHAR (200)   NULL,
    [DeliveryByAddress]                      VARCHAR (200)   NULL,
    [CompanyId]                              VARCHAR (10)    NULL,
    [MarketingCommisssionCharge]             VARCHAR (10)    NULL,
    [MarketingCommisssionValue]              DECIMAL (18, 4) NULL,
    [MasterOrderId]                          VARCHAR (10)    NULL,
    [Remarks]                                VARCHAR (250)   NULL,
    CONSTRAINT [PK_Contract] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [Contarct_MasterOrder] FOREIGN KEY ([MasterOrderId]) REFERENCES [TRN].[MasterOrder] ([Id]),
    CONSTRAINT [FK_Contract_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_Contract_Customer] FOREIGN KEY ([CustomerId]) REFERENCES [HKP].[Party] ([Id]),
    CONSTRAINT [FK_Contract_MasterLC] FOREIGN KEY ([MasterLCId]) REFERENCES [dbo].[MasterLC] ([Id])
);

