CREATE TABLE [dbo].[CostingBOQ] (
    [Id]                                      VARCHAR (30)    NOT NULL,
    [CostingBOQMasterId]                      VARCHAR (30)    NULL,
    [SalesOrderId]                            VARCHAR (20)    NULL,
    [CostingItemId]                           VARCHAR (10)    NULL,
    [DestinationId]                           VARCHAR (10)    NULL,
    [MaterialMasterId]                        VARCHAR (30)    NULL,
    [ArticleId]                               VARCHAR (10)    NULL,
    [OrderProcurementCostingDirectMaterialId] VARCHAR (10)    NULL,
    [ItemRefNo]                               VARCHAR (20)    NULL,
    [BOQCriteria]                             VARCHAR (30)    NULL,
    [UoMId]                                   VARCHAR (10)    NULL,
    [UoMIdBase]                               VARCHAR (10)    NULL,
    [CurrencyId]                              VARCHAR (10)    NULL,
    [CurrencyIdBase]                          VARCHAR (10)    NULL,
    [VendorId]                                VARCHAR (10)    NULL,
    [FirstCharacteristicsValueId]             VARCHAR (10)    NULL,
    [SecondCharacteristicsValueId]            VARCHAR (10)    NULL,
    [ThirdCharacteristicsValueId]             VARCHAR (10)    NULL,
    [OrderQty]                                DECIMAL (18, 4) NULL,
    [BOMQty]                                  DECIMAL (18, 4) NULL,
    [RequiredQty]                             DECIMAL (18, 4) NULL,
    [BOMAmount]                               DECIMAL (18, 8) NULL,
    [Sequence]                                DECIMAL (8, 2)  NULL,
    [AddedBy]                                 VARCHAR (30)    NULL,
    [AddedDate]                               DATETIME        NULL,
    [AddedFromIP]                             VARCHAR (15)    NULL,
    [UpdatedBy]                               VARCHAR (30)    NULL,
    [UpdatedDate]                             DATETIME        NULL,
    [UpdatedFromIP]                           VARCHAR (15)    NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    FOREIGN KEY ([ArticleId]) REFERENCES [MST].[MaterialMasterArticle] ([Id]),
    FOREIGN KEY ([CostingBOQMasterId]) REFERENCES [dbo].[CostingBOQMaster] ([Id]),
    FOREIGN KEY ([CostingItemId]) REFERENCES [HKP].[CostingItem] ([Id]),
    FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    FOREIGN KEY ([CurrencyIdBase]) REFERENCES [SCS].[Currency] ([Id]),
    FOREIGN KEY ([DestinationId]) REFERENCES [MST].[Destination] ([Id]),
    FOREIGN KEY ([FirstCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    FOREIGN KEY ([MaterialMasterId]) REFERENCES [MST].[MaterialMaster] ([Id]),
    FOREIGN KEY ([OrderProcurementCostingDirectMaterialId]) REFERENCES [dbo].[OrderProcurementCostingDirectMaterial] ([Id]),
    FOREIGN KEY ([SalesOrderId]) REFERENCES [TRN].[SalesOrder] ([Id]),
    FOREIGN KEY ([SecondCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    FOREIGN KEY ([ThirdCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    FOREIGN KEY ([UoMId]) REFERENCES [SCS].[UnitOfMeasurement] ([Id]),
    FOREIGN KEY ([UoMIdBase]) REFERENCES [SCS].[UnitOfMeasurement] ([Id]),
    FOREIGN KEY ([VendorId]) REFERENCES [HKP].[Party] ([Id])
);

