CREATE TABLE [dbo].[CostingMasterTemplate] (
    [Id]                               VARCHAR (10)    NOT NULL,
    [ProductMasterId]                  VARCHAR (10)    NULL,
    [CustomerId]                       VARCHAR (10)    NULL,
    [Code]                             VARCHAR (10)    NOT NULL,
    [SpecifyTo]                        VARCHAR (20)    NOT NULL,
    [ShortName]                        VARCHAR (15)    NOT NULL,
    [StandardName]                     VARCHAR (50)    NOT NULL,
    [UserName]                         VARCHAR (50)    NOT NULL,
    [OrderSize]                        DECIMAL (18, 2) NULL,
    [ProductionAvailableDays]          INT             NULL,
    [MKTTargetPerHour]                 DECIMAL (18, 2) NULL,
    [TargetSellingPrice]               DECIMAL (18, 2) NULL,
    [PaymentDays]                      DECIMAL (18, 2) NULL,
    [PackingType]                      VARCHAR (20)    NULL,
    [EstNoOfPackingList]               INT             NULL,
    [FileName]                         VARCHAR (50)    NULL,
    [Description]                      VARCHAR (250)   NULL,
    [Remarks]                          VARCHAR (250)   NULL,
    [Active]                           BIT             NOT NULL,
    [AddedBy]                          VARCHAR (30)    NOT NULL,
    [AddedDate]                        DATETIME        NOT NULL,
    [AddedFromIP]                      VARCHAR (15)    NOT NULL,
    [UpdatedBy]                        VARCHAR (30)    NULL,
    [UpdatedDate]                      DATETIME        NULL,
    [UpdatedFromIP]                    VARCHAR (15)    NULL,
    [ExcessShipmentPer]                DECIMAL (18, 2) NULL,
    [TargetProfit]                     DECIMAL (18, 2) DEFAULT ((0)) NOT NULL,
    [TargetCM]                         DECIMAL (18, 2) DEFAULT ((0)) NOT NULL,
    [IsPercentage]                     BIT             NULL,
    [CurrencyId]                       VARCHAR (10)    NULL,
    [UOM]                              VARCHAR (10)    NULL,
    [TargetOrSPT]                      VARCHAR (10)    NULL,
    [CriticalLevel]                    VARCHAR (20)    NULL,
    [SPT]                              DECIMAL (18, 4) NULL,
    [NoOfWorkstation]                  INT             NULL,
    [EfficiencyPercentage]             DECIMAL (18, 4) NULL,
    [StandardWorkingHours]             DECIMAL (18, 4) NULL,
    [WorkCenterTargetPerDay]           DECIMAL (18, 4) NULL,
    [StandardWorkingHourCost]          DECIMAL (18, 4) NULL,
    [AdditionalWorkingHourCostPerHour] DECIMAL (18, 4) NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    FOREIGN KEY ([UOM]) REFERENCES [SCS].[UnitOfMeasurement] ([Id])
);

