CREATE TABLE [dbo].[DayStatusMaster] (
    [Id]                        VARCHAR (30)    NOT NULL,
    [ShortName]                 VARCHAR (15)    NOT NULL,
    [StandardName]              VARCHAR (50)    NOT NULL,
    [UserName]                  VARCHAR (50)    NOT NULL,
    [Remarks]                   VARCHAR (250)   NULL,
    [Sequence]                  DECIMAL (18, 2) NOT NULL,
    [DayStatusCategory]         VARCHAR (30)    NOT NULL,
    [StandardDayStatus]         VARCHAR (30)    NOT NULL,
    [FirstSource]               BIT             NOT NULL,
    [DefaultDayStatusId]        VARCHAR (20)    NOT NULL,
    [DayStatusSubCategory]      VARCHAR (30)    NOT NULL,
    [UserDayStatus]             VARCHAR (20)    NOT NULL,
    [ManualAuto]                BIT             NOT NULL,
    [InStatusApplicable]        BIT             NOT NULL,
    [OutStatusApplicable]       BIT             NOT NULL,
    [DurationApplicable]        BIT             NOT NULL,
    [TotalWorkingDay]           DECIMAL (18, 2) NOT NULL,
    [ActualWorkingDay]          DECIMAL (18, 2) NOT NULL,
    [PayDay]                    DECIMAL (18, 2) NULL,
    [NonPayDay]                 DECIMAL (18, 2) NULL,
    [PresentValuePD]            DECIMAL (18, 2) NULL,
    [LeaveValueLP]              DECIMAL (18, 2) NULL,
    [LeaveValueLWP]             DECIMAL (18, 2) NULL,
    [AbsentValueAB]             DECIMAL (18, 2) NULL,
    [WeeklyOffWO]               DECIMAL (18, 2) NULL,
    [HolidayH]                  DECIMAL (18, 2) NULL,
    [Other]                     DECIMAL (18, 2) NULL,
    [AttendanceBonus]           DECIMAL (18, 2) NULL,
    [WorkingDayOTApplicable]    BIT             NOT NULL,
    [CompensatoryApplicable]    BIT             NOT NULL,
    [GoodWorkApplicable]        BIT             NOT NULL,
    [ToCheck]                   BIT             NOT NULL,
    [AddedBy]                   VARCHAR (30)    NOT NULL,
    [AddedDate]                 DATETIME        NOT NULL,
    [AddedFromIP]               VARCHAR (15)    NOT NULL,
    [UpdatedBy]                 VARCHAR (30)    NULL,
    [UpdatedDate]               DATETIME        NULL,
    [UpdatedFromIP]             VARCHAR (15)    NULL,
    [Active]                    BIT             NULL,
    [NonWorkingDayOTApplicable] BIT             NULL,
    [CurrentDayStatus]          VARCHAR (5)     NULL,
    CONSTRAINT [PK_DayStatusMaster] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_DayStatusMaster_CurrentDayStatus] FOREIGN KEY ([CurrentDayStatus]) REFERENCES [dbo].[DayType] ([DayType]),
    CONSTRAINT [FK_DayStatusMaster_DefaultDayStatusId] FOREIGN KEY ([DefaultDayStatusId]) REFERENCES [HKP].[DefaultDayStatus] ([Id])
);

