CREATE TABLE [dbo].[DetailConsumptionSKUMapping] (
    [Id]                              VARCHAR (30)  NOT NULL,
    [DetailConsumptionId]             VARCHAR (30)  NULL,
    [RMFirstCharacteristicsId]        VARCHAR (10)  NULL,
    [RMFirstCharacteristicsValueId]   VARCHAR (10)  NULL,
    [RMSecondCharacteristicsId]       VARCHAR (10)  NULL,
    [RMSecondCharacteristicsValueId]  VARCHAR (10)  NULL,
    [RMThirdCharacteristicsId]        VARCHAR (10)  NULL,
    [RMThirdCharacteristicsValueId]   VARCHAR (10)  NULL,
    [SubFirstCharacteristicsId]       VARCHAR (10)  NULL,
    [SubFirstCharacteristicsValueId]  VARCHAR (10)  NULL,
    [SubSecondCharacteristicsId]      VARCHAR (10)  NULL,
    [SubSecondCharacteristicsValueId] VARCHAR (10)  NULL,
    [SubThirdCharacteristicsId]       VARCHAR (10)  NULL,
    [SubThirdCharacteristicsValueId]  VARCHAR (10)  NULL,
    [Description]                     VARCHAR (250) NULL,
    [AddedBy]                         VARCHAR (30)  NOT NULL,
    [AddedDate]                       DATETIME      NOT NULL,
    [AddedFromIP]                     VARCHAR (15)  NOT NULL,
    [UpdatedBy]                       VARCHAR (30)  NULL,
    [UpdatedDate]                     DATETIME      NULL,
    [UpdatedFromIP]                   VARCHAR (15)  NULL,
    [IsFirstCharacteristicCommon]     BIT           DEFAULT ((0)) NOT NULL,
    [IsSecondCharacteristicCommon]    BIT           DEFAULT ((0)) NOT NULL,
    [IsThirdCharacteristicCommon]     BIT           DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_DetailConsumtionSKUMapping] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_DetailConsumptionSKUMapping_DetailConsumption] FOREIGN KEY ([DetailConsumptionId]) REFERENCES [dbo].[DetailConsumption] ([Id]),
    CONSTRAINT [FK_DetailConsumptionSKUMapping_RMFirstCharacteristicsId] FOREIGN KEY ([RMFirstCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_DetailConsumptionSKUMapping_RMFirstCharacteristicsValue] FOREIGN KEY ([RMFirstCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_DetailConsumptionSKUMapping_RMSecondCharacteristics] FOREIGN KEY ([RMSecondCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_DetailConsumptionSKUMapping_RMSecondCharacteristicsValue] FOREIGN KEY ([RMSecondCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_DetailConsumptionSKUMapping_RMThirdCharacteristics] FOREIGN KEY ([RMThirdCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_DetailConsumptionSKUMapping_RMThirdCharacteristicsValue] FOREIGN KEY ([RMThirdCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_DetailConsumptionSKUMapping_SubFirstCharacteristicsId] FOREIGN KEY ([SubFirstCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_DetailConsumptionSKUMapping_SubFirstCharacteristicsValue] FOREIGN KEY ([SubFirstCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_DetailConsumptionSKUMapping_SubSecondCharacteristics] FOREIGN KEY ([SubSecondCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_DetailConsumptionSKUMapping_SubSecondCharacteristicsValue] FOREIGN KEY ([SubSecondCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_DetailConsumptionSKUMapping_SubThirdCharacteristics] FOREIGN KEY ([SubThirdCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_DetailConsumptionSKUMapping_SubThirdCharacteristicsValue] FOREIGN KEY ([SubThirdCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id])
);

