CREATE TABLE [dbo].[EmpExperienceInformation] (
    [SystemID]             VARCHAR (30)  NOT NULL,
    [EmpSystemID]          VARCHAR (30)  NOT NULL,
    [Employer]             VARCHAR (100) NOT NULL,
    [Designation]          VARCHAR (100) NOT NULL,
    [StartDate]            DATE          NULL,
    [EndDate]              DATE          NULL,
    [JobDescription]       VARCHAR (200) NULL,
    [Achievement]          VARCHAR (100) NULL,
    [IsCurrentJob]         BIT           NULL,
    [IsPartTime]           BIT           NULL,
    [DurationYear]         INT           NULL,
    [DurationMonth]        INT           NULL,
    [AddedBy]              VARCHAR (100) NOT NULL,
    [DateAdded]            DATETIME      NOT NULL,
    [UpdatedBy]            VARCHAR (100) NULL,
    [DateUpdated]          DATETIME      NULL,
    [FileId]               VARCHAR (50)  NULL,
    [FileName]             VARCHAR (50)  NULL,
    [IsExperienceApproved] BIT           DEFAULT ((0)) NOT NULL,
    [ApprovedBy]           VARCHAR (50)  NULL,
    [ApprovedFromIP]       VARCHAR (50)  NULL,
    [ApprovedDateTime]     DATETIME      NULL,
    [ComplianceDocumentId] VARCHAR (10)  NULL,
    CONSTRAINT [PK_EmpExperienceInformation] PRIMARY KEY CLUSTERED ([SystemID] ASC),
    CONSTRAINT [FK_EmpExperienceInformation_ComplianceDocument] FOREIGN KEY ([ComplianceDocumentId]) REFERENCES [HKP].[ComplianceDocument] ([Id]),
    CONSTRAINT [FK_EmpExperienceInformation_EmployeeInformation] FOREIGN KEY ([EmpSystemID]) REFERENCES [dbo].[EmployeeInformation] ([SystemId])
);

