CREATE TABLE [dbo].[EmployeeInformation] (
    [SystemId]                           VARCHAR (30)    NOT NULL,
    [EmployeeId]                         VARCHAR (30)    NULL,
    [PreRecruitmentEmployeeId]           VARCHAR (10)    NULL,
    [EmployeeCode]                       VARCHAR (30)    NULL,
    [GroupID]                            VARCHAR (10)    NULL,
    [CompanyId]                          VARCHAR (10)    NULL,
    [PlantId]                            VARCHAR (10)    NULL,
    [UnitId]                             VARCHAR (10)    NULL,
    [DivisionId]                         VARCHAR (10)    NULL,
    [DepartmentId]                       VARCHAR (10)    NULL,
    [SectionId]                          VARCHAR (10)    NULL,
    [SubSectionId]                       VARCHAR (10)    NULL,
    [SubdivisionID]                      VARCHAR (10)    NULL,
    [LineId]                             VARCHAR (10)    NULL,
    [DesignationGroupId]                 VARCHAR (10)    NULL,
    [DesignationSystemID]                VARCHAR (10)    NULL,
    [BudgetCode]                         VARCHAR (10)    NULL,
    [PositionID]                         VARCHAR (10)    NULL,
    [IsDirect]                           BIT             CONSTRAINT [DF_EmployeeInformation_IsDirect] DEFAULT ((0)) NOT NULL,
    [SalaryPercentage]                   DECIMAL (18, 2) CONSTRAINT [DF_EmployeeInformation_SalaryPercentage] DEFAULT ((0)) NOT NULL,
    [CardNumber]                         VARCHAR (50)    NULL,
    [Salutation]                         VARCHAR (10)    NULL,
    [FirstName]                          VARCHAR (100)   NULL,
    [MiddleName]                         VARCHAR (100)   NULL,
    [LastName]                           VARCHAR (100)   NULL,
    [EmployeeName]                       VARCHAR (200)   NULL,
    [NickName]                           VARCHAR (100)   NULL,
    [EmpPicPath]                         VARCHAR (200)   NULL,
    [EmpType]                            VARCHAR (50)    NULL,
    [EmploymentType]                     VARCHAR (50)    NULL,
    [EmployeeGroupSystemID]              VARCHAR (10)    NULL,
    [JobLocationID]                      VARCHAR (30)    NULL,
    [DOB]                                DATETIME        NULL,
    [DOJ]                                DATETIME        NULL,
    [DOCIsDay]                           BIT             CONSTRAINT [DF_EmployeeInformation_DOCIsDay] DEFAULT ((0)) NOT NULL,
    [DOCDay]                             INT             CONSTRAINT [DF_EmployeeInformation_DOCDay] DEFAULT ((0)) NOT NULL,
    [DOCIsMonth]                         BIT             CONSTRAINT [DF_EmployeeInformation_DOCIsMonth] DEFAULT ((0)) NOT NULL,
    [DOCMonth]                           INT             CONSTRAINT [DF_EmployeeInformation_DOCMonth] DEFAULT ((0)) NOT NULL,
    [DOC]                                DATETIME        NULL,
    [DOS]                                DATETIME        NULL,
    [IsConfirmed]                        BIT             CONSTRAINT [DF_EmployeeInformation_DOCIsMonth1] DEFAULT ((0)) NULL,
    [ReActiveDate]                       DATETIME        NULL,
    [EmployeeStatus]                     VARCHAR (30)    NULL,
    [NationalID]                         VARCHAR (30)    NULL,
    [TIN]                                VARCHAR (30)    NULL,
    [CitizenID]                          VARCHAR (10)    NULL,
    [FatherName]                         VARCHAR (100)   NULL,
    [MotherName]                         VARCHAR (100)   NULL,
    [ReligionID]                         VARCHAR (10)    NULL,
    [CivilStatusID]                      VARCHAR (10)    NULL,
    [BloodGroupID]                       VARCHAR (10)    NULL,
    [GenderID]                           VARCHAR (30)    NULL,
    [SpouseName]                         VARCHAR (100)   NULL,
    [SpouseNationalID]                   VARCHAR (50)    NULL,
    [SpouseOccupation]                   VARCHAR (100)   NULL,
    [NoOfChildren]                       INT             NULL,
    [PresentAddress1]                    VARCHAR (200)   NULL,
    [PresentAddress2]                    VARCHAR (200)   NULL,
    [ParmanentAddress1]                  VARCHAR (200)   NULL,
    [ParmanentAddress2]                  VARCHAR (200)   NULL,
    [PresThanaID]                        VARCHAR (10)    NULL,
    [ParmThanaID]                        VARCHAR (10)    NULL,
    [PresPostOfficeID]                   VARCHAR (10)    NULL,
    [ParmPostOfficeID]                   VARCHAR (10)    NULL,
    [PresZipCode]                        VARCHAR (10)    NULL,
    [ParmZipCode]                        VARCHAR (10)    NULL,
    [PresDistrictID]                     VARCHAR (10)    NULL,
    [ParmDistrictID]                     VARCHAR (10)    NULL,
    [PresCountryID]                      VARCHAR (10)    NULL,
    [ParmCountryID]                      VARCHAR (10)    NULL,
    [PresCityID]                         VARCHAR (10)    NULL,
    [ParmCityID]                         VARCHAR (10)    NULL,
    [PresAreaID]                         VARCHAR (10)    NULL,
    [ParmAreaID]                         VARCHAR (10)    NULL,
    [TelePhnNo]                          VARCHAR (50)    NULL,
    [CellPhnNo]                          VARCHAR (25)    NULL,
    [EmailId]                            VARCHAR (80)    NULL,
    [BudgetCategoryID]                   VARCHAR (10)    NULL,
    [EmployeeCategorySystemID]           VARCHAR (10)    NULL,
    [LVPolicyMasterSystemID]             VARCHAR (30)    NULL,
    [SalaryRuleMasterSystemID]           VARCHAR (30)    NULL,
    [BankSystemID]                       VARCHAR (10)    NULL,
    [BankName]                           VARCHAR (150)   NULL,
    [BankAccNo]                          VARCHAR (50)    NULL,
    [BankAddedBy]                        VARCHAR (100)   NULL,
    [BankDateAdded]                      VARCHAR (50)    NULL,
    [BankUpdatedBy]                      VARCHAR (100)   NULL,
    [BankDateUpdated]                    VARCHAR (50)    NULL,
    [RegisterFP]                         BIT             CONSTRAINT [DF_EmployeeInformation_RegisterFP] DEFAULT ((0)) NOT NULL,
    [RegisterProximate]                  BIT             CONSTRAINT [DF_EmployeeInformation_RegisterProximate] DEFAULT ((0)) NOT NULL,
    [IsSlvDevReg]                        VARCHAR (3)     CONSTRAINT [DF_EmployeeInformation_IsSlvDevReg] DEFAULT ('No') NULL,
    [IsAttdnProcBaseOnDeviceData]        BIT             CONSTRAINT [DF_EmployeeInformation_IsAttdnRequire] DEFAULT ((0)) NOT NULL,
    [SubSecStrucSystemID]                VARCHAR (30)    NULL,
    [AddedBy]                            VARCHAR (100)   NULL,
    [DateAdded]                          DATETIME        NULL,
    [UpdatedBy]                          VARCHAR (100)   NULL,
    [DateUpdated]                        DATETIME        NULL,
    [EmrCntPer1Name]                     VARCHAR (100)   NULL,
    [EmrCntPer1CellNo]                   VARCHAR (20)    NULL,
    [EmrCntPer2Name]                     VARCHAR (100)   NULL,
    [EmrCntPer2CellNo]                   VARCHAR (20)    NULL,
    [GivenDesignationId]                 VARCHAR (10)    NULL,
    [LegalDesignationId]                 VARCHAR (10)    NULL,
    [AgreedDOJ]                          DATETIME        NULL,
    [TotalSalary]                        DECIMAL (18, 2) NULL,
    [SpecialReviewDuration]              INT             NULL,
    [SpecialReviewAmount]                DECIMAL (18, 2) NULL,
    [EmrCntPer1CellNo2]                  VARCHAR (20)    NULL,
    [EmrCntPer1CellNo3]                  VARCHAR (20)    NULL,
    [EmrCntPer2CellNo2]                  VARCHAR (20)    NULL,
    [EmrCntPer2CellNo3]                  VARCHAR (20)    NULL,
    [IsApproved]                         BIT             CONSTRAINT [DF__EmployeeI__IsApp__035C66C6] DEFAULT ((0)) NOT NULL,
    [ApprovedBy]                         VARCHAR (50)    NULL,
    [ApprovedDateTime]                   DATETIME        NULL,
    [ApprovedFromIP]                     VARCHAR (50)    NULL,
    [ParmStateId]                        VARCHAR (10)    NULL,
    [PresStateId]                        VARCHAR (10)    NULL,
    [IsImage]                            BIT             CONSTRAINT [DF__EmployeeI__IsIma__04508AFF] DEFAULT ((0)) NOT NULL,
    [ApplyingAsFresher]                  BIT             CONSTRAINT [DF__EmployeeI__Apply__0544AF38] DEFAULT ((0)) NOT NULL,
    [DOCBy]                              VARCHAR (50)    NULL,
    [ProbationConfirmEntryDate]          DATETIME        NULL,
    [DOSBy]                              VARCHAR (50)    NULL,
    [DOSDate]                            DATETIME        NULL,
    [ProximityAddedBy]                   VARCHAR (100)   NULL,
    [ProximityAddedDate]                 DATETIME        NULL,
    [ProximityUpdatedBy]                 VARCHAR (100)   NULL,
    [ProximityUpdatedDate]               DATETIME        NULL,
    [BirthdayCelebrationDate]            DATETIME        NULL,
    [MarriagedayCelebrationDate]         DATETIME        NULL,
    [ParmanentArea]                      VARCHAR (50)    NULL,
    [PresentArea]                        VARCHAR (50)    NULL,
    [IsAccessible]                       BIT             CONSTRAINT [DF__EmployeeI__IsAcc__0638D371] DEFAULT ((0)) NOT NULL,
    [ExtensionNo]                        VARCHAR (20)    NULL,
    [IsKnownPerson]                      BIT             CONSTRAINT [DF__EmployeeI__IsKno__072CF7AA] DEFAULT ((0)) NOT NULL,
    [NumberOfKnownPerson]                INT             CONSTRAINT [DF__EmployeeI__Numbe__08211BE3] DEFAULT ((0)) NOT NULL,
    [EmpSignature]                       VARCHAR (30)    NULL,
    [IdentificationMark]                 VARCHAR (30)    NULL,
    [LocalIdentificationMark]            NVARCHAR (50)   NULL,
    [Height]                             DECIMAL (18, 2) NULL,
    [Weight]                             DECIMAL (18, 2) NULL,
    [PreviouslyWorkedHere]               BIT             CONSTRAINT [DF__EmployeeI__Previ__75841412] DEFAULT ((0)) NOT NULL,
    [PreviousEmployeeCode]               VARCHAR (30)    NULL,
    [PreviousDesignation]                VARCHAR (50)    NULL,
    [PreviousSalary]                     DECIMAL (18, 2) NULL,
    [PreviousServicePeriod]              DECIMAL (18, 2) NULL,
    [ExitReason]                         VARCHAR (250)   NULL,
    [AnyRelativeWorkedHere]              BIT             CONSTRAINT [DF__EmployeeI__AnyRe__7678384B] DEFAULT ((0)) NOT NULL,
    [RelativeSystemId]                   VARCHAR (30)    NULL,
    [PaymentModeEffectiveDate]           DATETIME        NULL,
    [PaymentMode]                        VARCHAR (30)    NULL,
    [EmployeeNameLocal]                  NVARCHAR (100)  NULL,
    [FatherNameLocal]                    NVARCHAR (100)  NULL,
    [MotherNameLocal]                    NVARCHAR (100)  NULL,
    [PresentAddress1Local]               NVARCHAR (200)  NULL,
    [PresentAddress2Local]               NVARCHAR (200)  NULL,
    [ParmanentAddress1Local]             NVARCHAR (200)  NULL,
    [ParmanentAddress2Local]             NVARCHAR (200)  NULL,
    [SpouseNameLocal]                    NVARCHAR (100)  NULL,
    [RelationShip]                       VARCHAR (100)   NULL,
    [RelativeCellNo]                     VARCHAR (20)    NULL,
    [ExitReasonLocal]                    NVARCHAR (250)  NULL,
    [PreviousDesignationLocal]           NVARCHAR (50)   NULL,
    [OperationMasterID]                  VARCHAR (10)    NULL,
    [AppliedDate]                        DATETIME        NULL,
    [EmployeeCurrentStatus]              VARCHAR (50)    NULL,
    [EmployeeCurrentStatusEffectiveDate] DATETIME        NULL,
    [IssueDate]                          DATETIME        NULL,
    [OperationVariationId]               VARCHAR (10)    NULL,
    [EmployeeCodePreFix]                 VARCHAR (20)    NULL,
    [EmployeeCodeNumeric]                INT             CONSTRAINT [DF__EmployeeI__Emplo__32ED1505] DEFAULT ((0)) NULL,
    [TentativeExpiryDate]                DATETIME        NULL,
    [EmployeeDisciplinaryActionIdForLA]  VARCHAR (10)    NULL,
    [UnApprovedBy]                       VARCHAR (50)    NULL,
    [UnApprovedDateTime]                 DATETIME        NULL,
    [UnApprovedFromIP]                   VARCHAR (50)    NULL,
    [VendorId]                           VARCHAR (10)    NULL,
    [IsEntryComplete]                    BIT             DEFAULT ((0)) NOT NULL,
    [FirstTimeLock]                      BIT             DEFAULT ((0)) NOT NULL,
    [ProfileShiftId]                     VARCHAR (30)    NULL,
    [WeekOffHeaderId]                    VARCHAR (30)    NULL,
    CONSTRAINT [PK_EmpInformation] PRIMARY KEY CLUSTERED ([SystemId] ASC),
    CONSTRAINT [FK_EmployeeInformation_BloodGroup] FOREIGN KEY ([BloodGroupID]) REFERENCES [HKP].[BloodGroup] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_CitizenID] FOREIGN KEY ([CitizenID]) REFERENCES [SCS].[Country] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_CivilStatus] FOREIGN KEY ([CivilStatusID]) REFERENCES [HKP].[CivilStatus] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_CompanyGroup] FOREIGN KEY ([GroupID]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_Department] FOREIGN KEY ([DepartmentId]) REFERENCES [ORG].[Department] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_Designation] FOREIGN KEY ([DesignationSystemID]) REFERENCES [HKP].[Designation] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_DesignationGroup] FOREIGN KEY ([DesignationGroupId]) REFERENCES [HKP].[DesignationGroup] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_Division] FOREIGN KEY ([DivisionId]) REFERENCES [ORG].[Division] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_GivenDesignation] FOREIGN KEY ([GivenDesignationId]) REFERENCES [HKP].[Designation] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_JobLocation] FOREIGN KEY ([JobLocationID]) REFERENCES [dbo].[JobLocation] ([SystemID]),
    CONSTRAINT [FK_EmployeeInformation_LegalDesignation] FOREIGN KEY ([LegalDesignationId]) REFERENCES [HKP].[LegalDesignation] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_Line] FOREIGN KEY ([LineId]) REFERENCES [ORG].[Line] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_LVPolicyMaster] FOREIGN KEY ([LVPolicyMasterSystemID]) REFERENCES [dbo].[LeavePolicyMaster] ([SystemID]),
    CONSTRAINT [FK_EmployeeInformation_OperationMaster] FOREIGN KEY ([OperationMasterID]) REFERENCES [MST].[OperationMaster] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_OperationVariation] FOREIGN KEY ([OperationVariationId]) REFERENCES [MST].[OperationVariation] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_ParmArea] FOREIGN KEY ([ParmAreaID]) REFERENCES [SCS].[Area] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_ParmCity] FOREIGN KEY ([ParmCityID]) REFERENCES [SCS].[City] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_ParmCountry] FOREIGN KEY ([ParmCountryID]) REFERENCES [SCS].[Country] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_ParmDistrict] FOREIGN KEY ([ParmDistrictID]) REFERENCES [SCS].[District] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_ParmPostOffice] FOREIGN KEY ([ParmPostOfficeID]) REFERENCES [SCS].[PostOffice] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_ParmStateId] FOREIGN KEY ([ParmStateId]) REFERENCES [SCS].[State] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_ParmThana] FOREIGN KEY ([ParmThanaID]) REFERENCES [SCS].[PoliceStation] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_Party] FOREIGN KEY ([VendorId]) REFERENCES [HKP].[Party] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_PositionID] FOREIGN KEY ([PositionID]) REFERENCES [ORG].[Position] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_PositionManpowerBudget] FOREIGN KEY ([BudgetCode]) REFERENCES [MST].[ManpowerBudget] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_PreRecruitmentEmployee] FOREIGN KEY ([PreRecruitmentEmployeeId]) REFERENCES [dbo].[PreRecruitmentEmployee] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_PresArea] FOREIGN KEY ([PresAreaID]) REFERENCES [SCS].[Area] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_PresCity] FOREIGN KEY ([PresCityID]) REFERENCES [SCS].[City] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_PresCountry] FOREIGN KEY ([PresCountryID]) REFERENCES [SCS].[Country] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_PresDistrict] FOREIGN KEY ([PresDistrictID]) REFERENCES [SCS].[District] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_PresPostOffice] FOREIGN KEY ([PresPostOfficeID]) REFERENCES [SCS].[PostOffice] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_PresStateId] FOREIGN KEY ([PresStateId]) REFERENCES [SCS].[State] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_PresThana] FOREIGN KEY ([PresThanaID]) REFERENCES [SCS].[PoliceStation] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_ReligionID] FOREIGN KEY ([ReligionID]) REFERENCES [SCS].[Religion] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_SalaryInfoDefine] FOREIGN KEY ([SalaryRuleMasterSystemID]) REFERENCES [dbo].[SalaryRuleMaster] ([SystemID]),
    CONSTRAINT [FK_EmployeeInformation_Salutation] FOREIGN KEY ([Salutation]) REFERENCES [HKP].[Salutation] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_Section] FOREIGN KEY ([SectionId]) REFERENCES [ORG].[Section] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_Shiftp] FOREIGN KEY ([ProfileShiftId]) REFERENCES [dbo].[ShiftDefination] ([SystemID]),
    CONSTRAINT [FK_EmployeeInformation_SubSection] FOREIGN KEY ([SubSectionId]) REFERENCES [ORG].[SubSection] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_Unit] FOREIGN KEY ([UnitId]) REFERENCES [ORG].[Unit] ([Id]),
    CONSTRAINT [FK_EmployeeInformation_WeekOffHeaderId] FOREIGN KEY ([WeekOffHeaderId]) REFERENCES [dbo].[WeekOffHeader] ([Id])
);

