CREATE TABLE [dbo].[EmployeeFinalSettlement] (
    [Id]                         VARCHAR (30)    NOT NULL,
    [PlantId]                    VARCHAR (10)    NOT NULL,
    [EmpSystemId]                VARCHAR (30)    NOT NULL,
    [SeparationTypeId]           VARCHAR (10)    NOT NULL,
    [FinalSettlementDate]        DATETIME        NOT NULL,
    [FormulaDes]                 VARCHAR (500)   NULL,
    [PolicyYearNo]               INT             NULL,
    [PolicyDayNo]                INT             NULL,
    [SeparationTypeAmount]       DECIMAL (18, 2) NULL,
    [GratuityAmount]             DECIMAL (18, 2) NULL,
    [LvEncashmentAmount]         DECIMAL (18, 2) NULL,
    [EarningAmount]              DECIMAL (18, 2) NULL,
    [DeductionAmount]            DECIMAL (18, 2) NULL,
    [GrossAmount]                DECIMAL (18, 2) NULL,
    [BasicAmount]                DECIMAL (18, 2) NULL,
    [OTRate]                     DECIMAL (18, 2) NULL,
    [SalaryRate]                 DECIMAL (18, 2) NULL,
    [TenureDayNo]                INT             NULL,
    [TenureMonthNo]              INT             NULL,
    [TenureYearNo]               INT             NULL,
    [Remarks]                    VARCHAR (500)   NULL,
    [AddedBy]                    VARCHAR (30)    NOT NULL,
    [AddedDate]                  DATETIME        NOT NULL,
    [AddedFromIP]                VARCHAR (15)    NOT NULL,
    [UpdatedBy]                  VARCHAR (30)    NULL,
    [UpdatedDate]                DATETIME        NULL,
    [UpdatedFromIP]              VARCHAR (15)    NULL,
    [PolicyFixedDayNo]           DECIMAL (18, 2) NULL,
    [FixedDayAmount]             DECIMAL (18, 2) NULL,
    [LvEncashmentDayNo]          DECIMAL (18, 2) NULL,
    [LvEncashmentRateAmount]     DECIMAL (18, 2) NULL,
    [LastMonthProcDay]           DECIMAL (18, 2) NULL,
    [LastMonthNetPayAmount]      DECIMAL (18, 2) NULL,
    [LastMonthAbsentDay]         DECIMAL (18, 2) NULL,
    [LastMonthOTHour]            DECIMAL (18, 2) NULL,
    [StampAmount]                DECIMAL (18, 2) NULL,
    [LastMonthGrossAmount]       DECIMAL (18, 2) NULL,
    [LastMonthAbsenteeismAmount] DECIMAL (18, 2) NULL,
    [LastMonthOTAmount]          DECIMAL (18, 2) NULL,
    [TotalPayableAmount]         DECIMAL (18, 2) NULL,
    [TotalDeductionAmount]       DECIMAL (18, 2) NULL,
    [NetPayAmount]               DECIMAL (18, 2) NULL,
    [EarnLvDeductionDayNo]       DECIMAL (18, 2) NULL,
    [EarnLvDeductionAmount]      DECIMAL (18, 2) NULL,
    [TotalRetainedAmount]        DECIMAL (18, 2) NULL,
    [NoticePeriodDayNo]          DECIMAL (18, 2) NULL,
    [NoticePeriodAmount]         DECIMAL (18, 2) NULL,
    [NoticePeriodRate]           DECIMAL (18, 2) NULL,
    [NoticePeriodType]           VARCHAR (30)    NULL,
    CONSTRAINT [PK_EmployeeFinalSettlement] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_EmployeeFinalSettlement_EmployeeInformation] FOREIGN KEY ([EmpSystemId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_EmployeeFinalSettlement_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_EmployeeFinalSettlement_SeparationType] FOREIGN KEY ([SeparationTypeId]) REFERENCES [HKP].[SeparationType] ([Id])
);

