CREATE TABLE [dbo].[HourlyOffDuty] (
    [Id]                  VARCHAR (30)    NOT NULL,
    [EmpSystemId]         VARCHAR (30)    NULL,
    [FromDate]            DATETIME        NOT NULL,
    [ToDate]              DATETIME        NOT NULL,
    [DurationInMin]       INT             NOT NULL,
    [PlantId]             VARCHAR (10)    NULL,
    [AddedBy]             VARCHAR (30)    NOT NULL,
    [AddedDate]           DATETIME        NOT NULL,
    [AddedFromIP]         VARCHAR (15)    NOT NULL,
    [UpdatedBy]           VARCHAR (30)    NULL,
    [UpdatedDate]         DATETIME        NULL,
    [UpdatedFromIP]       VARCHAR (15)    NULL,
    [IsApprove]           BIT             DEFAULT ((0)) NOT NULL,
    [ApproveType]         VARCHAR (30)    NULL,
    [WorkDate]            DATETIME        NOT NULL,
    [HourlyLeaveReasonId] VARCHAR (10)    NULL,
    [DurationInHours]     DECIMAL (18, 2) NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    FOREIGN KEY ([EmpSystemId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    FOREIGN KEY ([EmpSystemId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    FOREIGN KEY ([EmpSystemId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    FOREIGN KEY ([EmpSystemId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    FOREIGN KEY ([EmpSystemId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    FOREIGN KEY ([EmpSystemId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_HourlyOffDuty_HourlyLeaveReasonId] FOREIGN KEY ([HourlyLeaveReasonId]) REFERENCES [HKP].[HourlyLeaveReason] ([Id])
);

