CREATE TABLE [dbo].[InvoiceBudgetChargesSetting] (
    [Id]                       VARCHAR (20)    NOT NULL,
    [CompanyId]                VARCHAR (10)    NOT NULL,
    [Process]                  VARCHAR (20)    NULL,
    [Type]                     VARCHAR (10)    NULL,
    [ExpenseTypeId]            VARCHAR (10)    NULL,
    [DrGLGeneralInfoId]        VARCHAR (10)    NULL,
    [DrActivityId]             VARCHAR (10)    NULL,
    [DrBudgetMasterId]         VARCHAR (20)    NULL,
    [CrGLGeneralInfoId]        VARCHAR (10)    NULL,
    [CrActivityId]             VARCHAR (10)    NULL,
    [CrBudgetMasterId]         VARCHAR (20)    NULL,
    [Days]                     INT             NULL,
    [PaymentTerms]             INT             NULL,
    [EstimatedPercentageValue] DECIMAL (18, 2) NULL,
    [EstimatedMaxValue]        DECIMAL (18, 2) NULL,
    [AddedBy]                  VARCHAR (30)    NOT NULL,
    [AddedDate]                DATETIME        NOT NULL,
    [AddedFromIP]              VARCHAR (15)    NOT NULL,
    [UpdatedBy]                VARCHAR (30)    NULL,
    [UpdatedDate]              DATETIME        NULL,
    [UpdatedFromIP]            VARCHAR (15)    NULL,
    CONSTRAINT [PK_InvoiceBudgetChargesSetting] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_InvoiceBudgetChargesSetting_Activity] FOREIGN KEY ([DrActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_InvoiceBudgetChargesSetting_Activity1] FOREIGN KEY ([CrActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_InvoiceBudgetChargesSetting_BudgetMaster] FOREIGN KEY ([CrBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_InvoiceBudgetChargesSetting_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_InvoiceBudgetChargesSetting_GLGeneralInfo] FOREIGN KEY ([DrGLGeneralInfoId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_InvoiceBudgetChargesSetting_GLGeneralInfo1] FOREIGN KEY ([CrGLGeneralInfoId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_InvoiceBudgetChargesSetting_InvoiceBudgetChargesSetting] FOREIGN KEY ([DrBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_InvoiceBudgetChargesSetting_OverHeadType] FOREIGN KEY ([ExpenseTypeId]) REFERENCES [HKP].[OverHeadType] ([Id])
);

