CREATE TABLE [dbo].[IssueTransaction] (
    [Id]                                 VARCHAR (10)    NOT NULL,
    [Issue]                              VARCHAR (120)   NULL,
    [IssueDetail]                        VARCHAR (250)   NOT NULL,
    [Remarks]                            VARCHAR (250)   NULL,
    [IssueImportanceId]                  VARCHAR (10)    NULL,
    [OverdueDays]                        INT             NOT NULL,
    [IssueDate]                          DATETIME        NOT NULL,
    [IssueType]                          VARCHAR (20)    NULL,
    [ObservedBy]                         VARCHAR (30)    NULL,
    [AssignToId]                         VARCHAR (30)    NULL,
    [RequiredDate]                       DATETIME        NOT NULL,
    [AssignById]                         VARCHAR (30)    NULL,
    [AddedBy]                            VARCHAR (30)    NOT NULL,
    [AddedDate]                          DATETIME        NOT NULL,
    [AddedFromIP]                        VARCHAR (15)    NOT NULL,
    [UpdatedBy]                          VARCHAR (30)    NULL,
    [UpdatedDate]                        DATETIME        NULL,
    [UpdatedFromIP]                      VARCHAR (15)    NULL,
    [CloseDate]                          DATETIME        NULL,
    [IssueStandardId]                    VARCHAR (10)    NULL,
    [MentorId]                           VARCHAR (30)    NULL,
    [IsUpdateApplicable]                 BIT             NULL,
    [IsUpdateRecurring]                  BIT             NULL,
    [UpdateOneTimeDateTime]              DATETIME        NULL,
    [IsFollowUpApplicable]               BIT             NULL,
    [IsFollowUpRecurring]                BIT             NULL,
    [FollowUpOneTimeDateTime]            DATETIME        NULL,
    [IsInternalApplicable]               BIT             NULL,
    [IsInternalRecurring]                BIT             NULL,
    [InternalOneTimeDateTime]            DATETIME        NULL,
    [IsExternalApplicable]               BIT             NULL,
    [IsExternalRecurring]                BIT             NULL,
    [ExternalOneTimeDateTime]            DATETIME        NULL,
    [UpdateResponsiblePersonId]          VARCHAR (30)    NULL,
    [FollowUpResponsiblePersonId]        VARCHAR (30)    NULL,
    [InternalResponsiblePersonId]        VARCHAR (30)    NULL,
    [ExternalResponsiblePersonId]        VARCHAR (30)    NULL,
    [FinalStatus]                        VARCHAR (20)    NULL,
    [ExternalResponsiblePerson]          VARCHAR (50)    NULL,
    [ExternalRespPersonEmail]            VARCHAR (100)   NULL,
    [ExternalRespPersonDesignation]      VARCHAR (50)    NULL,
    [CloseBy]                            VARCHAR (30)    NULL,
    [TargetDate]                         DATETIME        NULL,
    [IsReleased]                         BIT             NULL,
    [CommitmentDate]                     DATETIME        NULL,
    [RevisedCommitmentDate]              DATETIME        NULL,
    [Priority]                           DECIMAL (5, 2)  NULL,
    [UpdateAuditTaskSchedulerMasterId]   VARCHAR (30)    NULL,
    [FollowUpAuditTaskSchedulerMasterId] VARCHAR (30)    NULL,
    [InternalAuditTaskSchedulerMasterId] VARCHAR (30)    NULL,
    [ExternalAuditTaskSchedulerMasterId] VARCHAR (30)    NULL,
    [IssueGroupId]                       VARCHAR (30)    NULL,
    [TaskCategoryId]                     VARCHAR (10)    NULL,
    [TaskSubCategoryId]                  VARCHAR (10)    NULL,
    [StoryPoint]                         DECIMAL (18, 2) NULL,
    [CustomerId]                         VARCHAR (10)    NULL,
    [IsExpiry]                           BIT             DEFAULT ((0)) NULL,
    [ExpiryDate]                         DATETIME        NULL,
    [CostIfAny]                          DECIMAL (18, 2) DEFAULT ((0)) NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    FOREIGN KEY ([ExternalAuditTaskSchedulerMasterId]) REFERENCES [dbo].[TaskSchedulerMaster] ([Id]),
    FOREIGN KEY ([ExternalAuditTaskSchedulerMasterId]) REFERENCES [dbo].[TaskSchedulerMaster] ([Id]),
    FOREIGN KEY ([ExternalAuditTaskSchedulerMasterId]) REFERENCES [dbo].[TaskSchedulerMaster] ([Id]),
    FOREIGN KEY ([FollowUpAuditTaskSchedulerMasterId]) REFERENCES [dbo].[TaskSchedulerMaster] ([Id]),
    FOREIGN KEY ([FollowUpAuditTaskSchedulerMasterId]) REFERENCES [dbo].[TaskSchedulerMaster] ([Id]),
    FOREIGN KEY ([FollowUpAuditTaskSchedulerMasterId]) REFERENCES [dbo].[TaskSchedulerMaster] ([Id]),
    FOREIGN KEY ([InternalAuditTaskSchedulerMasterId]) REFERENCES [dbo].[TaskSchedulerMaster] ([Id]),
    FOREIGN KEY ([InternalAuditTaskSchedulerMasterId]) REFERENCES [dbo].[TaskSchedulerMaster] ([Id]),
    FOREIGN KEY ([InternalAuditTaskSchedulerMasterId]) REFERENCES [dbo].[TaskSchedulerMaster] ([Id]),
    FOREIGN KEY ([IssueGroupId]) REFERENCES [dbo].[IssueGroup] ([Id]),
    FOREIGN KEY ([IssueGroupId]) REFERENCES [dbo].[IssueGroup] ([Id]),
    FOREIGN KEY ([IssueGroupId]) REFERENCES [dbo].[IssueGroup] ([Id]),
    FOREIGN KEY ([IssueImportanceId]) REFERENCES [dbo].[IssueImportance] ([Id]),
    FOREIGN KEY ([IssueImportanceId]) REFERENCES [dbo].[IssueImportance] ([Id]),
    FOREIGN KEY ([IssueImportanceId]) REFERENCES [dbo].[IssueImportance] ([Id]),
    FOREIGN KEY ([IssueStandardId]) REFERENCES [dbo].[IssueStandard] ([Id]),
    FOREIGN KEY ([IssueStandardId]) REFERENCES [dbo].[IssueStandard] ([Id]),
    FOREIGN KEY ([IssueStandardId]) REFERENCES [dbo].[IssueStandard] ([Id]),
    FOREIGN KEY ([TaskCategoryId]) REFERENCES [HKP].[TaskCategory] ([Id]),
    FOREIGN KEY ([TaskCategoryId]) REFERENCES [HKP].[TaskCategory] ([Id]),
    FOREIGN KEY ([TaskCategoryId]) REFERENCES [HKP].[TaskCategory] ([Id]),
    FOREIGN KEY ([TaskSubCategoryId]) REFERENCES [HKP].[TaskSubCategory] ([Id]),
    FOREIGN KEY ([TaskSubCategoryId]) REFERENCES [HKP].[TaskSubCategory] ([Id]),
    FOREIGN KEY ([TaskSubCategoryId]) REFERENCES [HKP].[TaskSubCategory] ([Id]),
    FOREIGN KEY ([UpdateAuditTaskSchedulerMasterId]) REFERENCES [dbo].[TaskSchedulerMaster] ([Id]),
    FOREIGN KEY ([UpdateAuditTaskSchedulerMasterId]) REFERENCES [dbo].[TaskSchedulerMaster] ([Id]),
    FOREIGN KEY ([UpdateAuditTaskSchedulerMasterId]) REFERENCES [dbo].[TaskSchedulerMaster] ([Id]),
    CONSTRAINT [FK__IssueTran__Assig__2A02C949] FOREIGN KEY ([AssignToId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK__IssueTran__Assig__2AF6ED82] FOREIGN KEY ([AssignById]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK__IssueTran__Assig__4E7533E9] FOREIGN KEY ([AssignToId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK__IssueTran__Assig__4F695822] FOREIGN KEY ([AssignById]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK__IssueTran__Assig__73DBC2C2] FOREIGN KEY ([AssignToId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK__IssueTran__Assig__74CFE6FB] FOREIGN KEY ([AssignById]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK__IssueTran__Exter__2BEB11BB] FOREIGN KEY ([ExternalResponsiblePersonId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK__IssueTran__Exter__505D7C5B] FOREIGN KEY ([ExternalResponsiblePersonId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK__IssueTran__Exter__75C40B34] FOREIGN KEY ([ExternalResponsiblePersonId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK__IssueTran__Follo__2DD35A2D] FOREIGN KEY ([FollowUpResponsiblePersonId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK__IssueTran__Follo__5245C4CD] FOREIGN KEY ([FollowUpResponsiblePersonId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK__IssueTran__Follo__77AC53A6] FOREIGN KEY ([FollowUpResponsiblePersonId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK__IssueTran__Inter__2FBBA29F] FOREIGN KEY ([InternalResponsiblePersonId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK__IssueTran__Inter__542E0D3F] FOREIGN KEY ([InternalResponsiblePersonId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK__IssueTran__Inter__79949C18] FOREIGN KEY ([InternalResponsiblePersonId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK__IssueTran__Updat__004199A7] FOREIGN KEY ([UpdateResponsiblePersonId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK__IssueTran__Updat__3668A02E] FOREIGN KEY ([UpdateResponsiblePersonId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK__IssueTran__Updat__5ADB0ACE] FOREIGN KEY ([UpdateResponsiblePersonId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_IssueTransaction_Party] FOREIGN KEY ([CustomerId]) REFERENCES [HKP].[Party] ([Id])
);

