CREATE TABLE [dbo].[IssueStandard] (
    [Id]                VARCHAR (10)  NOT NULL,
    [Issue]             VARCHAR (250) NOT NULL,
    [IssueDetail]       VARCHAR (250) NOT NULL,
    [Remarks]           VARCHAR (250) NULL,
    [IssueImportanceId] VARCHAR (10)  NULL,
    [AddedBy]           VARCHAR (30)  NOT NULL,
    [AddedDate]         DATETIME      NOT NULL,
    [AddedFromIP]       VARCHAR (15)  NOT NULL,
    [UpdatedBy]         VARCHAR (30)  NULL,
    [UpdatedDate]       DATETIME      NULL,
    [UpdatedFromIP]     VARCHAR (15)  NULL,
    [ArchiveDate]       DATETIME      NULL,
    [CloseBy]           VARCHAR (30)  NULL,
    [CloseDate]         DATETIME      NULL,
    [Code]              VARCHAR (10)  NOT NULL,
    [SortName]          VARCHAR (15)  NOT NULL,
    [StandardName]      VARCHAR (50)  NOT NULL,
    [UserName]          VARCHAR (50)  NOT NULL,
    [TaskCategoryId]    VARCHAR (10)  NULL,
    [TaskSubCategoryId] VARCHAR (10)  NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    FOREIGN KEY ([IssueImportanceId]) REFERENCES [dbo].[IssueImportance] ([Id]),
    FOREIGN KEY ([IssueImportanceId]) REFERENCES [dbo].[IssueImportance] ([Id]),
    FOREIGN KEY ([IssueImportanceId]) REFERENCES [dbo].[IssueImportance] ([Id]),
    FOREIGN KEY ([TaskCategoryId]) REFERENCES [HKP].[TaskCategory] ([Id]),
    FOREIGN KEY ([TaskCategoryId]) REFERENCES [HKP].[TaskCategory] ([Id]),
    FOREIGN KEY ([TaskCategoryId]) REFERENCES [HKP].[TaskCategory] ([Id]),
    FOREIGN KEY ([TaskSubCategoryId]) REFERENCES [HKP].[TaskSubCategory] ([Id]),
    FOREIGN KEY ([TaskSubCategoryId]) REFERENCES [HKP].[TaskSubCategory] ([Id]),
    FOREIGN KEY ([TaskSubCategoryId]) REFERENCES [HKP].[TaskSubCategory] ([Id])
);

