CREATE TABLE [dbo].[LeaveTransaction] (
    [SystemID]                VARCHAR (30)    NOT NULL,
    [EmpSystemID]             VARCHAR (30)    NOT NULL,
    [LTSystemID]              VARCHAR (10)    NOT NULL,
    [ComAssignLvSystemID]     VARCHAR (30)    NULL,
    [OffDayMstSystemID]       VARCHAR (30)    NULL,
    [GroupID]                 VARCHAR (10)    NOT NULL,
    [PlantID]                 VARCHAR (10)    NOT NULL,
    [FromDate]                DATETIME        NULL,
    [ToDate]                  DATETIME        NULL,
    [LeaveDays]               DECIMAL (18, 2) NULL,
    [IsApproved]              BIT             CONSTRAINT [DF_LeaveTransaction_IsApproved] DEFAULT ((0)) NOT NULL,
    [LvReason]                VARCHAR (200)   NULL,
    [AddedBy]                 VARCHAR (100)   NOT NULL,
    [DateAdded]               DATETIME        NOT NULL,
    [UpdatedBy]               VARCHAR (100)   NULL,
    [DateUpdated]             DATETIME        NULL,
    [AppliedDate]             DATETIME        NULL,
    [ApprovedBy]              VARCHAR (30)    NULL,
    [ApprovedDate]            DATETIME        NULL,
    [IsPostApplied]           BIT             DEFAULT ((0)) NOT NULL,
    [CompanyId]               VARCHAR (10)    NULL,
    [IsAdminApproved]         BIT             DEFAULT ((0)) NOT NULL,
    [Cancelby]                VARCHAR (10)    NULL,
    [CancelationDate]         DATETIME        NULL,
    [CancelationReason]       VARCHAR (250)   NULL,
    [AppliedBy]               VARCHAR (10)    NULL,
    [LeaveDay]                VARCHAR (10)    NULL,
    [LeaveStatus]             VARCHAR (20)    NULL,
    [BabyNo]                  INT             CONSTRAINT [LeaveTransaction_BabyNo] DEFAULT ((0)) NOT NULL,
    [ExpectedDelivaryDate]    DATETIME        NULL,
    [IsCancel]                BIT             CONSTRAINT [LeaveTransaction_IsCancel] DEFAULT ((0)) NOT NULL,
    [LeaveDayType]            VARCHAR (20)    NULL,
    [ExceptionLeave]          VARCHAR (30)    NULL,
    [ApprovalPerson]          VARCHAR (30)    NULL,
    [MaternityLeavePolicyId]  VARCHAR (10)    NULL,
    [FirstApprovingDate]      DATE            NULL,
    [FirstApprovingAuthority] VARCHAR (30)    NULL,
    [FirstApprovingStatus]    BIT             DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_LeaveTransaction] PRIMARY KEY CLUSTERED ([SystemID] ASC),
    FOREIGN KEY ([FirstApprovingAuthority]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_LeaveTransaction_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_LeaveTransaction_CompanyGroup] FOREIGN KEY ([GroupID]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_LeaveTransaction_EmployeeInformation] FOREIGN KEY ([EmpSystemID]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_LeaveTransaction_LeaveTransactionCompanyAssign] FOREIGN KEY ([ComAssignLvSystemID]) REFERENCES [dbo].[LeaveTransactionCompanyAssign] ([SystemID]),
    CONSTRAINT [FK_LeaveTransaction_LeaveType] FOREIGN KEY ([LTSystemID]) REFERENCES [dbo].[LeaveType] ([Id]),
    CONSTRAINT [FK_LeaveTransaction_MaternityLeavePolicyId] FOREIGN KEY ([MaternityLeavePolicyId]) REFERENCES [MST].[MaternityLeavePolicy] ([Id]),
    CONSTRAINT [FK_LeaveTransaction_OffDayMaster] FOREIGN KEY ([OffDayMstSystemID]) REFERENCES [SCS].[OffDayMaster] ([Id]),
    CONSTRAINT [FK_LeaveTransaction_Plant] FOREIGN KEY ([PlantID]) REFERENCES [ORG].[Plant] ([Id])
);

