CREATE TABLE [dbo].[LeavePolicyDetail] (
    [SystemID]                               VARCHAR (30)    NOT NULL,
    [LPMSystemID]                            VARCHAR (30)    NULL,
    [LTSystemID]                             VARCHAR (10)    NULL,
    [StartDate]                              DATETIME        NULL,
    [EndDate]                                DATETIME        NULL,
    [IsWithoutPay]                           BIT             CONSTRAINT [DF_LeavePolicyDetail_IsWithoutPay] DEFAULT ((0)) NOT NULL,
    [LeaveDays]                              INT             NULL,
    [IsCarryForward]                         BIT             CONSTRAINT [DF_LeavePolicyDetail_IsCarryForward] DEFAULT ((0)) NOT NULL,
    [CarryForwardDay]                        INT             NULL,
    [IsMaxAllocation]                        BIT             CONSTRAINT [DF_LeavePolicyDetail_IsMaxAllocation] DEFAULT ((0)) NOT NULL,
    [MaxAllocationLimit]                     INT             NULL,
    [CalculationBasis]                       VARCHAR (50)    NULL,
    [LeaveCredit]                            VARCHAR (100)   NULL,
    [IsExcessAllow]                          BIT             CONSTRAINT [DF_LeavePolicyDetail_IsExcessAllow] DEFAULT ((0)) NOT NULL,
    [IsPrecedingWeekoff]                     BIT             CONSTRAINT [DF_LeavePolicyDetail_IsPrecedingWeekoff] DEFAULT ((0)) NOT NULL,
    [IsPrecedingHoliday]                     BIT             CONSTRAINT [DF_LeavePolicyDetail_IsPrecedingHoliday] DEFAULT ((0)) NOT NULL,
    [IsSucceedignWeekoff]                    BIT             CONSTRAINT [DF_LeavePolicyDetail_IsSucceedignWeekoff_1] DEFAULT ((0)) NOT NULL,
    [IsSucceedignHoliday]                    BIT             CONSTRAINT [DF_LeavePolicyDetail_IsSucceedignHoliday_1] DEFAULT ((0)) NOT NULL,
    [InBetweenWeekoff]                       BIT             CONSTRAINT [DF_LeavePolicyDetail_InBetweenWeekoff_1] DEFAULT ((0)) NOT NULL,
    [InBetweenHoliday]                       BIT             CONSTRAINT [DF_LeavePolicyDetail_InBetweenHoliday] DEFAULT ((0)) NOT NULL,
    [LeaveInHourDaily]                       INT             NULL,
    [IsActive]                               BIT             CONSTRAINT [DF_LeavePolicyDetail_IsActive] DEFAULT ((1)) NOT NULL,
    [GroupID]                                VARCHAR (30)    NULL,
    [PlantID]                                VARCHAR (30)    NULL,
    [AddedBy]                                VARCHAR (100)   NOT NULL,
    [DateAdded]                              DATETIME        NOT NULL,
    [UpdatedBy]                              VARCHAR (100)   NULL,
    [DateUpdated]                            DATETIME        NULL,
    [IsMaxEncashment]                        BIT             DEFAULT ((0)) NOT NULL,
    [MaxEncashment]                          INT             DEFAULT ((0)) NOT NULL,
    [IsMaxEncashmentLapse]                   BIT             DEFAULT ((0)) NOT NULL,
    [MaxEncashmentLapse]                     INT             DEFAULT ((0)) NOT NULL,
    [IsAllowed]                              BIT             DEFAULT ((0)) NULL,
    [IsAllowedonspecialappeal]               BIT             DEFAULT ((0)) NULL,
    [IsProratacurrentyear]                   BIT             DEFAULT ((0)) NOT NULL,
    [IsNewlyJoined]                          BIT             DEFAULT ((0)) NULL,
    [NewlyJoined]                            INT             DEFAULT ((0)) NULL,
    [EncashWorkingDaysQty]                   INT             DEFAULT ((0)) NULL,
    [EncashEarnLeaveQty]                     INT             DEFAULT ((0)) NULL,
    [IsSubmittoApproval]                     BIT             DEFAULT ((0)) NULL,
    [IsAvailPreviousYearProRata]             BIT             NULL,
    [IsAvailCurrentYearProRata]              BIT             NULL,
    [IsAvailExceptionAllowedOnSpecialAppeal] BIT             NULL,
    [AllowedAfterDays]                       INT             DEFAULT ((0)) NULL,
    [IsPostApplicationAllowed]               BIT             DEFAULT ((0)) NOT NULL,
    [IsExceptionAllowed]                     BIT             DEFAULT ((0)) NOT NULL,
    [IsSubjectToApproval]                    BIT             DEFAULT ((0)) NOT NULL,
    [IsProofDocRequired]                     BIT             DEFAULT ((0)) NOT NULL,
    [ProofDocReqAfterDays]                   INT             DEFAULT ((0)) NOT NULL,
    [LvCalculationOnDOJ]                     BIT             DEFAULT ((0)) NOT NULL,
    [LvCalculationOnDOC]                     BIT             DEFAULT ((0)) NOT NULL,
    [LvAvailedOnDOJ]                         BIT             DEFAULT ((0)) NOT NULL,
    [LvAvailedOnDOC]                         BIT             DEFAULT ((0)) NOT NULL,
    [LvCanAvailAfter]                        INT             DEFAULT ((0)) NOT NULL,
    [CanAvailUOM]                            VARCHAR (15)    NULL,
    [IsCFFixed]                              BIT             DEFAULT ((0)) NOT NULL,
    [IsCFRestFixed]                          BIT             DEFAULT ((0)) NOT NULL,
    [IsCFCRestFixed]                         BIT             DEFAULT ((0)) NOT NULL,
    [IsCFRestEncash]                         BIT             DEFAULT ((0)) NOT NULL,
    [IsCFCRestEncash]                        BIT             DEFAULT ((0)) NOT NULL,
    [IsProrataMonthly]                       BIT             DEFAULT ((0)) NOT NULL,
    [EncasementEndDate]                      VARCHAR (30)    NULL,
    [LvEncashmentFormulaDesID]               VARCHAR (100)   NULL,
    [FormulaDescription]                     VARCHAR (100)   NULL,
    [CarryForwardRoundupOption]              VARCHAR (30)    NULL,
    [EncashmentSpecificDay]                  VARCHAR (30)    NULL,
    [EncashmentSpecificMonth]                VARCHAR (30)    NULL,
    [EncashmentBasis]                        VARCHAR (30)    DEFAULT ('CalanderYear') NOT NULL,
    [LeaveCalculationRoundOption]            VARCHAR (30)    DEFAULT ('Round') NOT NULL,
    [LvCanAvailQuantity]                     NUMERIC (18, 2) DEFAULT ((100)) NOT NULL,
    [LvAvailedOnFixedOrPercentage]           VARCHAR (15)    DEFAULT ('Percentage') NULL,
    [IsAsperEntryOnW]                        BIT             DEFAULT ((1)) NOT NULL,
    [IsNoLeaveOnW]                           BIT             DEFAULT ((0)) NOT NULL,
    [IsAsperEntryOnH]                        BIT             DEFAULT ((1)) NOT NULL,
    [IsNoLeaveOnH]                           BIT             DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_LeavePolicyDetail] PRIMARY KEY CLUSTERED ([SystemID] ASC),
    CONSTRAINT [FK_LeavePolicyDetail_LeavePolicyDetail] FOREIGN KEY ([LTSystemID]) REFERENCES [dbo].[LeaveType] ([Id]),
    CONSTRAINT [FK_LeavePolicyDetail_LeavePolicyMaster] FOREIGN KEY ([LPMSystemID]) REFERENCES [dbo].[LeavePolicyMaster] ([SystemID])
);

