CREATE TABLE [dbo].[LeaveEncashmentTransaction] (
    [Id]                  VARCHAR (15)    NOT NULL,
    [PlantId]             VARCHAR (10)    NULL,
    [YearlyCalendarId]    VARCHAR (30)    NULL,
    [EncashmentDate]      DATE            NULL,
    [LeaveEncashmentType] VARCHAR (30)    NULL,
    [EmpSystemId]         VARCHAR (30)    NULL,
    [Days]                DECIMAL (18, 2) NULL,
    [Isdisburse]          BIT             NULL,
    [Rate]                DECIMAL (18, 2) NULL,
    [AddedBy]             VARCHAR (30)    NOT NULL,
    [AddedDate]           DATETIME        NOT NULL,
    [AddedFromIP]         VARCHAR (15)    NOT NULL,
    [UpdatedBy]           VARCHAR (30)    NULL,
    [UpdatedDate]         DATETIME        NULL,
    [UpdatedFromIP]       VARCHAR (15)    NULL,
    [LeaveTypeSystemId]   VARCHAR (10)    NULL,
    [BasicAmmount]        DECIMAL (18, 2) NULL,
    [GrossAmmount]        DECIMAL (18, 2) NULL,
    [BankAccNo]           VARCHAR (50)    NULL,
    [LegalDesignationId]  VARCHAR (10)    NULL,
    [BankSystemID]        VARCHAR (10)    NULL,
    [BankBranchId]        VARCHAR (10)    NULL,
    [BroughtForward]      DECIMAL (18, 2) NULL,
    [DaysCanBeSanctioned] DECIMAL (18, 2) NULL,
    [AvailedLeave]        DECIMAL (18, 2) NULL,
    [YearEndLapse]        DECIMAL (18, 2) NULL,
    [CarryForward]        DECIMAL (18, 2) NULL,
    [PaymentMode]         VARCHAR (30)    NULL,
    CONSTRAINT [PK_LeaveEncashmentTransaction] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_LeaveEncashmentTransaction_EmployeeId] FOREIGN KEY ([EmpSystemId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_LeaveEncashmentTransaction_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_LeaveEncashmentTransaction_YearlyCalendar] FOREIGN KEY ([YearlyCalendarId]) REFERENCES [dbo].[YearlyCalendar] ([Id])
);

