CREATE TABLE [dbo].[MasterOrderTaskTemplate] (
    [Id]                        VARCHAR (30)    NOT NULL,
    [MasterOrderId]             VARCHAR (10)    NULL,
    [TaskMasterId]              VARCHAR (30)    NULL,
    [TaskDescription]           NVARCHAR (1024) NULL,
    [Active]                    BIT             NULL,
    [Sequence]                  DECIMAL (10, 2) NULL,
    [Duration]                  DECIMAL (10, 4) NULL,
    [predecessor]               VARCHAR (100)   NULL,
    [startDate]                 DATETIME        NULL,
    [endDate]                   DATETIME        NULL,
    [EmployeeId]                VARCHAR (30)    NULL,
    [ForNewOrder]               BIT             NULL,
    [IsMandatory]               BIT             DEFAULT ((0)) NULL,
    [TaskType]                  VARCHAR (30)    NULL,
    [IsTaskMilestone]           BIT             DEFAULT ((0)) NULL,
    [TaskDependentDatesId]      VARCHAR (10)    NULL,
    [TaskAppliedOnId]           VARCHAR (10)    NULL,
    [Remarks]                   NVARCHAR (255)  NULL,
    [WillSendEmail]             BIT             DEFAULT ((0)) NULL,
    [WillSendSMS]               BIT             DEFAULT ((0)) NULL,
    [ResponsiblePersonCategory] VARCHAR (20)    NULL,
    [IsFirstTask]               BIT             DEFAULT ((0)) NULL,
    [IsLastTask]                BIT             DEFAULT ((0)) NULL,
    [AddedBy]                   VARCHAR (30)    NOT NULL,
    [AddedDate]                 DATETIME        NOT NULL,
    [AddedFromIP]               VARCHAR (15)    NOT NULL,
    [UpdatedBy]                 VARCHAR (30)    NULL,
    [UpdatedDate]               DATETIME        NULL,
    [UpdatedFromIP]             VARCHAR (15)    NULL,
    [RefTaskTemplateId]         VARCHAR (30)    NULL,
    [StoryPoint]                DECIMAL (18, 2) NULL,
    [LagDays]                   DECIMAL (10, 4) NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK__MasterOrd__Emplo__0E05A919] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK__MasterOrd__Emplo__1A6B7FFE] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK__MasterOrd__Emplo__23F4EA38] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK__MasterOrd__Emplo__2D7E5472] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK__MasterOrd__Emplo__3707BEAC] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK__MasterOrd__Emplo__409128E6] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK__MasterOrd__Maste__0EF9CD52] FOREIGN KEY ([MasterOrderId]) REFERENCES [TRN].[MasterOrder] ([Id]),
    CONSTRAINT [FK__MasterOrd__Maste__1B5FA437] FOREIGN KEY ([MasterOrderId]) REFERENCES [TRN].[MasterOrder] ([Id]),
    CONSTRAINT [FK__MasterOrd__Maste__24E90E71] FOREIGN KEY ([MasterOrderId]) REFERENCES [TRN].[MasterOrder] ([Id]),
    CONSTRAINT [FK__MasterOrd__Maste__2E7278AB] FOREIGN KEY ([MasterOrderId]) REFERENCES [TRN].[MasterOrder] ([Id]),
    CONSTRAINT [FK__MasterOrd__Maste__37FBE2E5] FOREIGN KEY ([MasterOrderId]) REFERENCES [TRN].[MasterOrder] ([Id]),
    CONSTRAINT [FK__MasterOrd__Maste__41854D1F] FOREIGN KEY ([MasterOrderId]) REFERENCES [TRN].[MasterOrder] ([Id])
);

