CREATE TABLE [dbo].[MasterLC] (
    [Id]                 VARCHAR (10)    NOT NULL,
    [BenificiaryBankId]  VARCHAR (10)    NULL,
    [OpeningBank]        VARCHAR (50)    NULL,
    [OpeningDescription] VARCHAR (250)   NULL,
    [LeinBank]           VARCHAR (50)    NULL,
    [LeinDescription]    VARCHAR (250)   NULL,
    [LCRef]              VARCHAR (50)    NULL,
    [LCDate]             DATETIME        NULL,
    [ExpiryDate]         DATETIME        NULL,
    [Amount]             DECIMAL (18, 2) NULL,
    [Type]               VARCHAR (20)    NULL,
    [Tenure]             INT             NULL,
    [FinalDestinationId] VARCHAR (10)    NULL,
    [PortOfLandingId]    VARCHAR (10)    NULL,
    [AddedBy]            VARCHAR (30)    NOT NULL,
    [AddedDate]          DATETIME        NOT NULL,
    [AddedFromIP]        VARCHAR (15)    NOT NULL,
    [UpdatedBy]          VARCHAR (30)    NULL,
    [UpdatedDate]        DATETIME        NULL,
    [UpdatedFromIP]      VARCHAR (15)    NULL,
    [CurrencyId]         VARCHAR (10)    NULL,
    [IsClose]            BIT             DEFAULT ((0)) NOT NULL,
    [CustomerId]         VARCHAR (10)    NULL,
    CONSTRAINT [PK_MasterLC] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_MasterLC_BankMaster] FOREIGN KEY ([BenificiaryBankId]) REFERENCES [MST].[BankMaster] ([Id]),
    CONSTRAINT [FK_MasterLC_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_MasterLC_Destination] FOREIGN KEY ([FinalDestinationId]) REFERENCES [MST].[Destination] ([Id]),
    CONSTRAINT [FK_MasterLC_Port] FOREIGN KEY ([PortOfLandingId]) REFERENCES [MST].[Port] ([Id])
);

