CREATE TABLE [dbo].[MaternityBenefitMaster] (
    [Id]                     VARCHAR (50)    NOT NULL,
    [LeaveTransactionId]     VARCHAR (30)    NULL,
    [PlantId]                VARCHAR (10)    NULL,
    [EmpSystemId]            VARCHAR (30)    NOT NULL,
    [WageRate]               DECIMAL (18, 2) NOT NULL,
    [LeaveDays]              DECIMAL (18, 2) NOT NULL,
    [BeforeAmount]           DECIMAL (18, 2) NOT NULL,
    [BeforePaymentDate]      DATETIME        NULL,
    [IsPaidBefore]           BIT             NULL,
    [AfterAmount]            DECIMAL (18, 2) NULL,
    [AfterPaymentDate]       DATETIME        NULL,
    [IsPaidAfter]            BIT             NULL,
    [AdditionalAmount]       DECIMAL (18, 2) NULL,
    [AdditionalAmountBefore] DECIMAL (18, 2) NULL,
    [AdditionalAmountAfter]  DECIMAL (18, 2) NULL,
    [Deduction]              DECIMAL (18, 2) NULL,
    [Remark]                 VARCHAR (200)   NULL,
    [AddedBy]                VARCHAR (30)    NOT NULL,
    [AddedDate]              DATETIME        NOT NULL,
    [AddedFromIP]            VARCHAR (15)    NOT NULL,
    [UpdatedBy]              VARCHAR (30)    NULL,
    [UpdatedDate]            DATETIME        NULL,
    [UpdatedFromIP]          VARCHAR (15)    NULL,
    [TotalWorkingDays]       DECIMAL (18, 2) DEFAULT ((0)) NOT NULL,
    [TotalPayable]           DECIMAL (18, 2) DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_MaternityBenefitMaster] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_MaternityBenefitMaster_EmployeeInformation] FOREIGN KEY ([EmpSystemId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_MaternityBenefitMaster_LeaveTransaction] FOREIGN KEY ([LeaveTransactionId]) REFERENCES [dbo].[LeaveTransaction] ([SystemID]),
    CONSTRAINT [FK_MaternityBenefitMaster_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id])
);

