CREATE TABLE [dbo].[PFPolicyDetails] (
    [ID]                                         VARCHAR (20)    NOT NULL,
    [PFPolicyMasterID]                           VARCHAR (20)    NOT NULL,
    [FormulaDesEarning]                          VARCHAR (1000)  NULL,
    [FormulaDesIDEarning]                        VARCHAR (500)   NULL,
    [SalaryHeadIDEarning]                        VARCHAR (500)   NULL,
    [EarningValueRangeFrom]                      INT             NULL,
    [EarningValueRangeTo]                        INT             NULL,
    [IsMandatory]                                BIT             NULL,
    [IsFixedEmp]                                 BIT             NULL,
    [FixedValueEmp]                              NUMERIC (18, 2) NULL,
    [IsFormulaEmp]                               BIT             NULL,
    [IsContributionSlrHDdependOnEarningEmp]      BIT             CONSTRAINT [DF_PFPolicyDetails_IsContributionSlrHDdependOnEarningEmp] DEFAULT ((0)) NOT NULL,
    [FormulaDesEmp]                              VARCHAR (1000)  NULL,
    [FormulaDesIDEmp]                            VARCHAR (500)   NULL,
    [SalaryHeadIDEmp]                            VARCHAR (500)   NULL,
    [IsDistributionEmp]                          BIT             CONSTRAINT [DF_PFPolicyDetails_IsDistributionEmp] DEFAULT ((0)) NOT NULL,
    [IsFixedEmployer]                            BIT             NULL,
    [FixedValueEmployer]                         NUMERIC (18, 2) NULL,
    [IsFormulaEmployer]                          BIT             NULL,
    [IsContributionSlrHDdependOnEarningEmployer] BIT             NULL,
    [FormulaDesEmployer]                         VARCHAR (1000)  NULL,
    [FormulaDesIDEmployer]                       VARCHAR (500)   NULL,
    [SalaryHeadIDEmployer]                       VARCHAR (500)   NULL,
    [IsDistributionEmployer]                     BIT             CONSTRAINT [DF_PFPolicyDetails_IsDistributionEmployer] DEFAULT ((0)) NOT NULL,
    [EmpCntValPer]                               NUMERIC (18, 2) NULL,
    [EmployerCntValPer]                          NUMERIC (18, 2) NULL,
    [EmpVolunValPer]                             NUMERIC (18, 2) NULL,
    [FormulaDesIDEmployerDis]                    VARCHAR (500)   NULL,
    [FormulaDesIDEmpDis]                         VARCHAR (1000)  NULL,
    [IsVoluntaryPF]                              BIT             NULL,
    [IsNotEntGetEmplrAlwn]                       BIT             CONSTRAINT [DF_PFPolicyDetails_IsNotEntGetEmplrAlwn] DEFAULT ((0)) NOT NULL,
    [IsIndividualAlwn]                           BIT             CONSTRAINT [DF_PFPolicyDetails_IsIndividualAlwn] DEFAULT ((0)) NOT NULL,
    [AlwnSlrHd]                                  VARCHAR (30)    NULL,
    [IsAgeLimit]                                 BIT             DEFAULT ((0)) NOT NULL,
    [AgeLimit]                                   INT             DEFAULT ((0)) NULL,
    CONSTRAINT [PK_PFPolicyDetails] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PFPolicyDetails_PFPolicyMaster] FOREIGN KEY ([PFPolicyMasterID]) REFERENCES [dbo].[PFPolicyMaster] ([ID]),
    CONSTRAINT [FK_PFPolicyDetails_SalaryHead] FOREIGN KEY ([AlwnSlrHd]) REFERENCES [dbo].[SalaryHead] ([SalaryHeadID])
);

