CREATE TABLE [dbo].[PreRecruitmentEmployee] (
    [Id]                           VARCHAR (10)    NOT NULL,
    [GroupID]                      VARCHAR (10)    NOT NULL,
    [CompanyId]                    VARCHAR (10)    NOT NULL,
    [Image]                        VARCHAR (50)    NULL,
    [InterviewRankingId]           VARCHAR (10)    NULL,
    [PlantId]                      VARCHAR (10)    NOT NULL,
    [PositionID]                   VARCHAR (10)    NULL,
    [BudgetId]                     VARCHAR (10)    NOT NULL,
    [FullName]                     VARCHAR (100)   NULL,
    [Salutation]                   VARCHAR (10)    NULL,
    [FirstName]                    VARCHAR (100)   NULL,
    [MiddleName]                   VARCHAR (100)   NULL,
    [LastName]                     VARCHAR (100)   NULL,
    [NickName]                     VARCHAR (100)   NULL,
    [EmployeeName]                 VARCHAR (200)   NULL,
    [FatherName]                   VARCHAR (100)   NULL,
    [MotherName]                   VARCHAR (100)   NULL,
    [Gender]                       VARCHAR (30)    NOT NULL,
    [NationalID]                   VARCHAR (30)    NULL,
    [DOJ]                          DATETIME        NULL,
    [DOB]                          DATETIME        NULL,
    [Phone]                        VARCHAR (50)    NULL,
    [Email]                        VARCHAR (80)    NULL,
    [EmpType]                      VARCHAR (50)    NULL,
    [TIN]                          VARCHAR (30)    NULL,
    [CitizenID]                    VARCHAR (30)    NULL,
    [ReligionID]                   VARCHAR (10)    NULL,
    [BloodGroupID]                 VARCHAR (10)    NULL,
    [SpouseName]                   VARCHAR (100)   NULL,
    [SpouseNationalID]             VARCHAR (50)    NULL,
    [SpouseOccupation]             VARCHAR (100)   NULL,
    [NoOfChildren]                 INT             NULL,
    [PresentAddress1]              VARCHAR (200)   NULL,
    [PresentAddress2]              VARCHAR (200)   NULL,
    [ParmanentAddress1]            VARCHAR (200)   NULL,
    [ParmanentAddress2]            VARCHAR (200)   NULL,
    [PresThanaID]                  VARCHAR (10)    NULL,
    [ParmThanaID]                  VARCHAR (10)    NULL,
    [PresPostOfficeID]             VARCHAR (10)    NULL,
    [ParmPostOfficeID]             VARCHAR (10)    NULL,
    [PresAreaID]                   VARCHAR (10)    NULL,
    [ParmAreaID]                   VARCHAR (10)    NULL,
    [PresZipCode]                  VARCHAR (10)    NULL,
    [ParmZipCode]                  VARCHAR (10)    NULL,
    [PresCityID]                   VARCHAR (10)    NULL,
    [ParmCityID]                   VARCHAR (10)    NULL,
    [PresDistrictID]               VARCHAR (10)    NULL,
    [ParmDistrictID]               VARCHAR (10)    NULL,
    [PresCountryID]                VARCHAR (10)    NULL,
    [ParmCountryID]                VARCHAR (10)    NULL,
    [EmrCntPer1Name]               VARCHAR (100)   NULL,
    [EmrCntPer2Name]               VARCHAR (100)   NULL,
    [EmrCntPer1CellNo]             VARCHAR (20)    NULL,
    [EmrCntPer2CellNo]             VARCHAR (20)    NULL,
    [CivilStatusID]                VARCHAR (10)    NULL,
    [GivenDesignationId]           VARCHAR (10)    NULL,
    [LegalDesignationId]           VARCHAR (10)    NULL,
    [BirthdayCelebrationDate]      DATETIME        NULL,
    [MarriagedayCelebrationDate]   DATETIME        NULL,
    [AgreedDOJ]                    DATETIME        NULL,
    [TotalSalary]                  DECIMAL (18, 2) NULL,
    [SpecialReviewDuration]        INT             NULL,
    [SpecialReviewAmount]          DECIMAL (18, 2) NULL,
    [IsFirstlogin]                 BIT             CONSTRAINT [DF_PreRecruitmentEmployee_IsFirstlogin] DEFAULT ((0)) NOT NULL,
    [InitialPIN]                   VARCHAR (10)    NULL,
    [NewPIN]                       VARCHAR (10)    NULL,
    [LastLoginTime]                DATETIME        NULL,
    [Status]                       VARCHAR (30)    NULL,
    [AppAddedDateTime]             DATETIME        NULL,
    [AppAddedBy]                   VARCHAR (50)    NULL,
    [AppUpdatedBy]                 VARCHAR (50)    NULL,
    [AppUpdatedDateTime]           DATETIME        NULL,
    [Submitted]                    BIT             CONSTRAINT [DF_PreRecruitmentEmployee_Submitted] DEFAULT ((0)) NOT NULL,
    [SubmitDateTime]               DATETIME        NULL,
    [SelectionDateTime]            DATETIME        NULL,
    [SelectedBy]                   VARCHAR (30)    NULL,
    [SelectionStatus]              VARCHAR (30)    NULL,
    [ReadyForCandidateAccess]      BIT             CONSTRAINT [DF_PreRecruitmentEmployee_ReadyForCandidateAccess] DEFAULT ((0)) NOT NULL,
    [ExpiredDays]                  INT             CONSTRAINT [DF_PreRecruitmentEmployee_ExpiredDays] DEFAULT ((0)) NOT NULL,
    [ConfirmationStatus]           VARCHAR (10)    NULL,
    [ConfirmationDate]             DATETIME        NULL,
    [ConfirmationBy]               VARCHAR (30)    NULL,
    [Completed]                    BIT             CONSTRAINT [DF_PreRecruitmentEmployee_Completed] DEFAULT ((0)) NOT NULL,
    [AddedBy]                      VARCHAR (30)    NOT NULL,
    [AddedDate]                    DATETIME        NOT NULL,
    [AddedFromIP]                  VARCHAR (15)    NOT NULL,
    [UpdatedBy]                    VARCHAR (30)    NULL,
    [UpdatedDate]                  DATETIME        NULL,
    [UpdatedFromIP]                VARCHAR (15)    NULL,
    [ParmanentArea]                VARCHAR (50)    NULL,
    [PresentArea]                  VARCHAR (50)    NULL,
    [IsKnownPerson]                BIT             CONSTRAINT [DF__PreRecrui__IsKno__27AFA12C] DEFAULT ((0)) NOT NULL,
    [NumberOfKnownPerson]          INT             CONSTRAINT [DF__PreRecrui__Numbe__28A3C565] DEFAULT ((0)) NOT NULL,
    [IsExceptionalDesigApplicable] INT             CONSTRAINT [DF__PreRecrui__IsExc__2997E99E] DEFAULT ((0)) NOT NULL,
    [PresStateId]                  VARCHAR (10)    NULL,
    [ParmStateId]                  VARCHAR (10)    NULL,
    [IsImage]                      BIT             CONSTRAINT [DF__PreRecrui__IsIma__47B25C6A] DEFAULT ((0)) NOT NULL,
    [IsApproved]                   BIT             CONSTRAINT [DF__PreRecrui__IsApp__48A680A3] DEFAULT ((0)) NOT NULL,
    [ApprovedBy]                   VARCHAR (50)    NULL,
    [ApprovedFromIP]               VARCHAR (50)    NULL,
    [ApprovedDateTime]             DATETIME        NULL,
    [EmrCntPer1CellNo2]            VARCHAR (20)    NULL,
    [EmrCntPer1CellNo3]            VARCHAR (20)    NULL,
    [EmrCntPer2CellNo2]            VARCHAR (20)    NULL,
    [EmrCntPer2CellNo3]            VARCHAR (20)    NULL,
    [ConfirmAfterDays]             INT             CONSTRAINT [DF_PreRecruitmentEmployee_ConfirmAfterDays] DEFAULT ((0)) NOT NULL,
    [IsDepartmentSubmit]           BIT             CONSTRAINT [DF__PreRecrui__IsDep__668BE945] DEFAULT ((0)) NOT NULL,
    [DeptDocumentBy]               VARCHAR (50)    NULL,
    [DeptDocumentDateTime]         DATETIME        NULL,
    [ApplyingAsFresher]            BIT             CONSTRAINT [DF_PreRecruitmentEmployee_ApplyingAsFresher] DEFAULT ((0)) NOT NULL,
    [EmployeeCode]                 VARCHAR (30)    NULL,
    [IsSalaryFixationAccepted]     BIT             DEFAULT ((0)) NOT NULL,
    [OperationMasterID]            VARCHAR (10)    NULL,
    CONSTRAINT [PK_PreRecruitmentEmployee] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_PreRecruitmentEmployee_BloodGroupID] FOREIGN KEY ([BloodGroupID]) REFERENCES [HKP].[BloodGroup] ([Id]),
    CONSTRAINT [FK_PreRecruitmentEmployee_BudgetId] FOREIGN KEY ([BudgetId]) REFERENCES [MST].[ManpowerBudget] ([Id]),
    CONSTRAINT [FK_PreRecruitmentEmployee_CivilStatusID] FOREIGN KEY ([CivilStatusID]) REFERENCES [HKP].[CivilStatus] ([Id]),
    CONSTRAINT [FK_PreRecruitmentEmployee_CompanyId] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_PreRecruitmentEmployee_GivenDesignationId] FOREIGN KEY ([GivenDesignationId]) REFERENCES [HKP].[Designation] ([Id]),
    CONSTRAINT [FK_PreRecruitmentEmployee_LegalDesignation] FOREIGN KEY ([LegalDesignationId]) REFERENCES [HKP].[LegalDesignation] ([Id]),
    CONSTRAINT [FK_PreRecruitmentEmployee_ParmAreaID] FOREIGN KEY ([ParmAreaID]) REFERENCES [SCS].[Area] ([Id]),
    CONSTRAINT [FK_PreRecruitmentEmployee_ParmCityID] FOREIGN KEY ([ParmCityID]) REFERENCES [SCS].[City] ([Id]),
    CONSTRAINT [FK_PreRecruitmentEmployee_ParmCountryID] FOREIGN KEY ([ParmCountryID]) REFERENCES [SCS].[Country] ([Id]),
    CONSTRAINT [FK_PreRecruitmentEmployee_ParmDistrictID] FOREIGN KEY ([ParmDistrictID]) REFERENCES [SCS].[District] ([Id]),
    CONSTRAINT [FK_PreRecruitmentEmployee_ParmPostOfficeID] FOREIGN KEY ([ParmPostOfficeID]) REFERENCES [SCS].[PostOffice] ([Id]),
    CONSTRAINT [FK_PreRecruitmentEmployee_ParmState] FOREIGN KEY ([ParmStateId]) REFERENCES [SCS].[State] ([Id]),
    CONSTRAINT [FK_PreRecruitmentEmployee_PlantId] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_PreRecruitmentEmployee_PositionID] FOREIGN KEY ([PositionID]) REFERENCES [ORG].[Position] ([Id]),
    CONSTRAINT [FK_PreRecruitmentEmployee_PresAreaID] FOREIGN KEY ([PresAreaID]) REFERENCES [SCS].[Area] ([Id]),
    CONSTRAINT [FK_PreRecruitmentEmployee_PresCityID] FOREIGN KEY ([PresCityID]) REFERENCES [SCS].[City] ([Id]),
    CONSTRAINT [FK_PreRecruitmentEmployee_PresCountryID] FOREIGN KEY ([PresCountryID]) REFERENCES [SCS].[Country] ([Id]),
    CONSTRAINT [FK_PreRecruitmentEmployee_PresDistrictID] FOREIGN KEY ([PresDistrictID]) REFERENCES [SCS].[District] ([Id]),
    CONSTRAINT [FK_PreRecruitmentEmployee_PresPostOfficeID] FOREIGN KEY ([PresPostOfficeID]) REFERENCES [SCS].[PostOffice] ([Id]),
    CONSTRAINT [FK_PreRecruitmentEmployee_PresState] FOREIGN KEY ([PresStateId]) REFERENCES [SCS].[State] ([Id]),
    CONSTRAINT [FK_PreRecruitmentEmployee_ReligionID] FOREIGN KEY ([ReligionID]) REFERENCES [SCS].[Religion] ([Id])
);

