CREATE TABLE [dbo].[PreRecruitmentEmpQualification] (
    [SystemID]                 VARCHAR (30)    NOT NULL,
    [PreRecruitmentEmployeeId] VARCHAR (10)    NULL,
    [EductLevelSystemID]       VARCHAR (10)    NULL,
    [StreamId]                 VARCHAR (10)    NULL,
    [CountryId]                VARCHAR (10)    NULL,
    [HasDistinction]           BIT             NULL,
    [TypeIsAcademic]           BIT             NULL,
    [Session]                  VARCHAR (30)    NULL,
    [IsGeneral]                BIT             CONSTRAINT [DF_PreRecruitmentEmpQualification_IsGeneral] DEFAULT ((0)) NULL,
    [IsEnglishMedium]          BIT             CONSTRAINT [DF_PreRecruitmentEmpQualification_IsEnglishMedium] DEFAULT ((0)) NULL,
    [IsMadrasah]               BIT             CONSTRAINT [DF_PreRecruitmentEmpQualification_IsMadrasah] DEFAULT ((0)) NULL,
    [IsVocational]             BIT             CONSTRAINT [DF_PreRecruitmentEmpQualification_IsVocational] DEFAULT ((0)) NULL,
    [IsOther]                  BIT             CONSTRAINT [DF_PreRecruitmentEmpQualification_IsOther] DEFAULT ((0)) NULL,
    [OtherEductType]           VARCHAR (150)   NULL,
    [ExamDegreeType]           VARCHAR (100)   NULL,
    [ConcMajor]                VARCHAR (100)   NULL,
    [InstituteName]            VARCHAR (150)   NULL,
    [IsForeignInstitute]       BIT             CONSTRAINT [DF_PreRecruitmentEmpQualification_IsForeignInstitute] DEFAULT ((0)) NULL,
    [ResultSystemID]           VARCHAR (30)    NULL,
    [Marks]                    NUMERIC (18, 2) NULL,
    [CGPA]                     NUMERIC (18, 2) NULL,
    [Scale]                    NUMERIC (18, 2) NULL,
    [YearOfPass]               INT             NULL,
    [Duration]                 INT             NULL,
    [Achievement]              VARCHAR (100)   NULL,
    [AddedBy]                  VARCHAR (30)    NULL,
    [AddedDate]                DATETIME        NULL,
    [AddedFromIP]              VARCHAR (15)    NULL,
    [UpdatedBy]                VARCHAR (30)    NULL,
    [UpdatedDate]              DATETIME        NULL,
    [UpdatedFromIP]            VARCHAR (15)    NULL,
    [FileId]                   VARCHAR (50)    NULL,
    [FileName]                 VARCHAR (50)    NULL,
    [IsQualificationApproved]  BIT             CONSTRAINT [DF__PreRecrui__IsQua__4B82ED4E] DEFAULT ((0)) NOT NULL,
    [ApprovedBy]               VARCHAR (50)    NULL,
    [ApprovedFromIP]           VARCHAR (50)    NULL,
    [ApprovedDateTime]         DATETIME        NULL,
    [ComplianceDocumentId]     VARCHAR (10)    NULL,
    CONSTRAINT [PK_PreRecruitmentEmpQualification] PRIMARY KEY CLUSTERED ([SystemID] ASC),
    CONSTRAINT [FK_PreRecruitmentEmpQualification_ComplianceDocument] FOREIGN KEY ([ComplianceDocumentId]) REFERENCES [HKP].[ComplianceDocument] ([Id]),
    CONSTRAINT [FK_PreRecruitmentEmpQualification_Country] FOREIGN KEY ([CountryId]) REFERENCES [SCS].[Country] ([Id]),
    CONSTRAINT [FK_PreRecruitmentEmpQualification_PreRecruitmentEmployee] FOREIGN KEY ([PreRecruitmentEmployeeId]) REFERENCES [dbo].[PreRecruitmentEmployee] ([Id]),
    CONSTRAINT [FK_PreRecruitmentEmpQualification_QualificationLevel] FOREIGN KEY ([EductLevelSystemID]) REFERENCES [SCS].[QualificationLevel] ([Id]),
    CONSTRAINT [FK_PreRecruitmentEmpQualification_StreamId] FOREIGN KEY ([StreamId]) REFERENCES [SCS].[QualificationStream] ([Id])
);

