CREATE TABLE [dbo].[PreRecruitmentEmpExperience] (
    [SystemID]                 VARCHAR (30)  NOT NULL,
    [PreRecruitmentEmployeeId] VARCHAR (10)  NULL,
    [Employer]                 VARCHAR (100) NULL,
    [Designation]              VARCHAR (100) NULL,
    [StartDate]                DATE          NULL,
    [EndDate]                  DATE          NULL,
    [JobDescription]           VARCHAR (200) NULL,
    [Achievement]              VARCHAR (100) NULL,
    [IsCurrentJob]             BIT           NULL,
    [IsPartTime]               BIT           NULL,
    [DurationYear]             INT           NULL,
    [DurationMonth]            INT           NULL,
    [AddedBy]                  VARCHAR (30)  NULL,
    [AddedDate]                DATETIME      NULL,
    [AddedFromIP]              VARCHAR (15)  NULL,
    [UpdatedBy]                VARCHAR (30)  NULL,
    [UpdatedDate]              DATETIME      NULL,
    [UpdatedFromIP]            VARCHAR (15)  NULL,
    [FileId]                   VARCHAR (50)  NULL,
    [FileName]                 VARCHAR (50)  NULL,
    [IsExperienceApproved]     BIT           CONSTRAINT [DF__PreRecrui__IsExp__4A8EC915] DEFAULT ((0)) NOT NULL,
    [ApprovedBy]               VARCHAR (50)  NULL,
    [ApprovedFromIP]           VARCHAR (50)  NULL,
    [ApprovedDateTime]         DATETIME      NULL,
    [ComplianceDocumentId]     VARCHAR (10)  NULL,
    CONSTRAINT [PK_PreRecruitmentEmpExperience] PRIMARY KEY CLUSTERED ([SystemID] ASC),
    CONSTRAINT [FK_PreRecruitmentEmpExperience_ComplianceDocument] FOREIGN KEY ([ComplianceDocumentId]) REFERENCES [HKP].[ComplianceDocument] ([Id]),
    CONSTRAINT [FK_PreRecruitmentEmpExperience_PreRecruitmentEmployee] FOREIGN KEY ([PreRecruitmentEmployeeId]) REFERENCES [dbo].[PreRecruitmentEmployee] ([Id])
);

