CREATE TABLE [dbo].[PreRecruitmentDocument] (
    [Id]                       VARCHAR (20) NOT NULL,
    [ComplianceDocumentId]     VARCHAR (10) NULL,
    [PreRecruitmentEmployeeId] VARCHAR (10) NULL,
    [FileId]                   VARCHAR (50) NULL,
    [FileName]                 VARCHAR (50) NULL,
    [AddedBy]                  VARCHAR (30) NULL,
    [AddedDate]                DATETIME     NULL,
    [UpdatedBy]                VARCHAR (30) NULL,
    [UpdatedDate]              DATETIME     NULL,
    [IsDocumentApproved]       BIT          DEFAULT ((0)) NULL,
    [ApprovedBy]               VARCHAR (50) NULL,
    [ApprovedFromIP]           VARCHAR (50) NULL,
    [ApprovedDateTime]         DATETIME     NULL,
    [DueDate]                  DATETIME     NULL,
    [DueProcessDateTime]       DATETIME     NULL,
    [IsMailSend]               BIT          DEFAULT ((0)) NOT NULL,
    [DocNumber]                VARCHAR (30) NULL,
    [DocDate]                  DATETIME     NULL,
    [ComplianceDocumentSetId]  VARCHAR (10) NULL,
    [IsCopied]                 BIT          DEFAULT ((0)) NOT NULL,
    [OptionalOrMandatory]      VARCHAR (30) NULL,
    [ResponsiblePersonId]      VARCHAR (30) NULL,
    [Number]                   VARCHAR (30) NULL,
    [IssueDate]                DATETIME     NULL,
    CONSTRAINT [PK_PreRecruitmentDocument] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_PreRecruitmentDocument_ComplianceDocumentId] FOREIGN KEY ([ComplianceDocumentId]) REFERENCES [HKP].[ComplianceDocument] ([Id]),
    CONSTRAINT [FK_PreRecruitmentDocument_ComplianceDocumentSetId] FOREIGN KEY ([ComplianceDocumentSetId]) REFERENCES [HKP].[ComplianceDocumentSet] ([Id]),
    CONSTRAINT [FK_PreRecruitmentDocument_PreRecruitmentEmployee] FOREIGN KEY ([PreRecruitmentEmployeeId]) REFERENCES [dbo].[PreRecruitmentEmployee] ([Id]),
    CONSTRAINT [FK_PreRecruitmentDocument_ResponsiblePersonId] FOREIGN KEY ([ResponsiblePersonId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId])
);

