CREATE TABLE [dbo].[ProductionOrderSchedulingParametersType1] (
    [ID]                                 INT             IDENTITY (1, 1) NOT NULL,
    [ProductionOrderID]                  VARCHAR (30)    NULL,
    [NoOfWorkStation]                    INT             NULL,
    [Efficiency]                         DECIMAL (10, 4) NULL,
    [SPT]                                DECIMAL (10, 4) NULL,
    [PlanWorkingHoursPerDay]             DECIMAL (18, 4) NULL,
    [FirstDayOutPut]                     DECIMAL (18, 4) NULL,
    [PlanTargetPerHour]                  DECIMAL (18, 4) NULL,
    [IncrementValue]                     DECIMAL (18, 4) NULL,
    [IncrementType]                      VARCHAR (30)    NULL,
    [DayToReachTheTarget]                DECIMAL (18, 4) NULL,
    [LSD]                                DATE            NULL,
    [CommitmentDate]                     DATE            NULL,
    [ProductionPriority]                 DECIMAL (10, 4) NULL,
    [TargetPerHour]                      DECIMAL (10, 4) NULL,
    [TargetPerDay]                       DECIMAL (10, 4) NULL,
    [MinimumLineDays]                    DECIMAL (18, 4) NULL,
    [RequiredLineDays]                   DECIMAL (18, 4) NULL,
    [RequiredNoOfLines]                  DECIMAL (18, 4) NULL,
    [AllocatedLines]                     DECIMAL (18, 4) NULL,
    [Color]                              VARCHAR (10)    NULL,
    [Qty]                                DECIMAL (18, 4) NULL,
    [AddedBy]                            VARCHAR (30)    NULL,
    [AddedDate]                          DATETIME        NULL,
    [AddedFromIP]                        VARCHAR (15)    NULL,
    [UpdatedBy]                          VARCHAR (30)    NULL,
    [UpdatedDate]                        DATETIME        NULL,
    [UpdatedFromIP]                      VARCHAR (15)    NULL,
    [MainRawMaterialInhouseDate]         DATETIME        NULL,
    [OtherRawMaterialInhouseDate]        DATETIME        NULL,
    [WCPreferenceType]                   VARCHAR (20)    NULL,
    [PlanningStatus]                     VARCHAR (10)    DEFAULT ('TOSTART') NULL,
    [RunningOrderBlockSize]              INT             DEFAULT ((1)) NULL,
    [ConsiderHourFromWorkCenter]         BIT             NULL,
    [ConsiderWorkStationsFromWorkCenter] BIT             NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    FOREIGN KEY ([ProductionOrderID]) REFERENCES [TRN].[ProductionOrder] ([Id])
);

