CREATE TABLE [dbo].[ProductLibrary] (
    [Id]                      VARCHAR (30)    NOT NULL,
    [CompanyGroupId]          VARCHAR (10)    NOT NULL,
    [RecipeId]                VARCHAR (30)    NULL,
    [MaterialMasterId]        VARCHAR (30)    NULL,
    [Sequence]                DECIMAL (18, 2) NOT NULL,
    [Code]                    VARCHAR (10)    NULL,
    [ShortName]               VARCHAR (15)    NULL,
    [StandardName]            VARCHAR (50)    NULL,
    [UserName]                VARCHAR (50)    NULL,
    [ProductionGroup]         VARCHAR (50)    NULL,
    [RecipeOrProductionGroup] VARCHAR (15)    NULL,
    [Description]             VARCHAR (250)   NULL,
    [Remarks]                 VARCHAR (250)   NULL,
    [AddedBy]                 VARCHAR (30)    NOT NULL,
    [AddedDate]               DATETIME        NOT NULL,
    [AddedFromIP]             VARCHAR (15)    NOT NULL,
    [UpdatedBy]               VARCHAR (30)    NULL,
    [UpdatedDate]             DATETIME        NULL,
    [UpdatedFromIP]           VARCHAR (15)    NULL,
    [ArticleId]               VARCHAR (10)    NULL,
    [Active]                  BIT             DEFAULT ((0)) NULL,
    CONSTRAINT [PK_ProductLibrary] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ProductLibrary_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_ProductLibrary_MaterialMaster] FOREIGN KEY ([MaterialMasterId]) REFERENCES [MST].[MaterialMaster] ([Id]),
    CONSTRAINT [FK_ProductLibrary_MaterialMasterArticle] FOREIGN KEY ([ArticleId]) REFERENCES [MST].[MaterialMasterArticle] ([Id]),
    CONSTRAINT [FK_ProductLibrary_Recipe] FOREIGN KEY ([RecipeId]) REFERENCES [TRN].[RecipeGlobalMaster] ([Id])
);

