CREATE TABLE [dbo].[ProductLibraryAttribute] (
    [Id]               VARCHAR (10)    NOT NULL,
    [ProductLibraryId] VARCHAR (30)    NOT NULL,
    [Sequence]         DECIMAL (18, 2) NOT NULL,
    [Code]             VARCHAR (10)    NOT NULL,
    [ShortName]        VARCHAR (15)    NOT NULL,
    [StandardName]     VARCHAR (50)    NOT NULL,
    [UserName]         VARCHAR (50)    NOT NULL,
    [ScanItemId]       VARCHAR (10)    NULL,
    [UoMId]            VARCHAR (10)    NULL,
    [AttributeValue]   VARCHAR (100)   NULL,
    [Remarks]          VARCHAR (250)   NULL,
    [Description]      VARCHAR (250)   NULL,
    [Active]           BIT             NOT NULL,
    [AddedBy]          VARCHAR (30)    NOT NULL,
    [AddedDate]        DATETIME        NOT NULL,
    [AddedFromIP]      VARCHAR (15)    NOT NULL,
    [UpdatedBy]        VARCHAR (30)    NULL,
    [UpdatedDate]      DATETIME        NULL,
    [UpdatedFromIP]    VARCHAR (15)    NULL,
    CONSTRAINT [PK_ProductLibraryAttribute] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ProductLibraryAttribute_ProductLibrary] FOREIGN KEY ([ProductLibraryId]) REFERENCES [dbo].[ProductLibrary] ([Id]),
    CONSTRAINT [FK_ProductLibraryAttribute_ScanItem] FOREIGN KEY ([ScanItemId]) REFERENCES [dbo].[ScanItem] ([Id]),
    CONSTRAINT [FK_ProductLibraryAttributes_UnitOfMeasurement] FOREIGN KEY ([UoMId]) REFERENCES [SCS].[UnitOfMeasurement] ([Id])
);

