CREATE TABLE [dbo].[ProductionPlanningSnapshotType1] (
    [ID]                                    INT             IDENTITY (1, 1) NOT NULL,
    [ProductionPlanningSnapshotMasterType1] VARCHAR (30)    NULL,
    [ProductionOrderID]                     VARCHAR (30)    NULL,
    [WorkCenterMasterId]                    VARCHAR (30)    NULL,
    [MaterialMasterId]                      VARCHAR (30)    NULL,
    [EntityID]                              VARCHAR (10)    NULL,
    [ProcessID]                             VARCHAR (10)    NULL,
    [ProductionDate]                        DATETIME        NULL,
    [Quantity]                              DECIMAL (18, 4) NULL,
    [ProductionHours]                       DECIMAL (18, 4) NULL,
    [isBuildUp]                             BIT             DEFAULT ((0)) NULL,
    [isStyleChange]                         BIT             DEFAULT ((0)) NULL,
    [BlockNo]                               INT             DEFAULT ((0)) NULL,
    [ActualTarget]                          DECIMAL (18, 4) NULL,
    [ActualProduction]                      DECIMAL (18, 4) NULL,
    [isProductionConfirmed]                 BIT             DEFAULT ((0)) NULL,
    [AddedBy]                               VARCHAR (30)    NULL,
    [AddedDate]                             DATETIME        NULL,
    [AddedFromIP]                           VARCHAR (15)    NULL,
    [UpdatedBy]                             VARCHAR (30)    NULL,
    [UpdatedDate]                           DATETIME        NULL,
    [UpdatedFromIP]                         VARCHAR (15)    NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    FOREIGN KEY ([EntityID]) REFERENCES [ORG].[Entity] ([Id]),
    FOREIGN KEY ([MaterialMasterId]) REFERENCES [MST].[MaterialMaster] ([Id]),
    FOREIGN KEY ([ProcessID]) REFERENCES [HKP].[Process] ([Id]),
    FOREIGN KEY ([ProductionOrderID]) REFERENCES [TRN].[ProductionOrder] ([Id]),
    FOREIGN KEY ([ProductionPlanningSnapshotMasterType1]) REFERENCES [dbo].[ProductionPlanningSnapshotMasterType1] ([ID]),
    CONSTRAINT [FK__Productio__WorkC__78A20E8D] FOREIGN KEY ([WorkCenterMasterId]) REFERENCES [SCS].[WorkCenterMaster] ([Id])
);

