CREATE TABLE [dbo].[PurchaseLC] (
    [Id]                         VARCHAR (10)    NOT NULL,
    [Version]                    DECIMAL (18, 2) NULL,
    [ContractId]                 VARCHAR (10)    NULL,
    [VendorId]                   VARCHAR (10)    NULL,
    [BenificiaryBank]            VARCHAR (50)    NULL,
    [OpeningBankMasterId]        VARCHAR (10)    NULL,
    [BenificiaryBankDescription] VARCHAR (250)   NULL,
    [LeinBank]                   VARCHAR (50)    NULL,
    [LeinBankDescription]        VARCHAR (250)   NULL,
    [OrderSpecific]              VARCHAR (10)    NULL,
    [LCRef]                      VARCHAR (50)    NULL,
    [AmendmentDate]              DATETIME        NULL,
    [LCDate]                     DATETIME        NULL,
    [ExpiryDate]                 DATETIME        NULL,
    [Amount]                     DECIMAL (18, 2) NULL,
    [Type]                       VARCHAR (20)    NULL,
    [Tenure]                     INT             NULL,
    [CurrencyId]                 VARCHAR (10)    NULL,
    [Rate]                       DECIMAL (18, 2) NULL,
    [FinalDestination]           VARCHAR (50)    NULL,
    [PortOfLandingId]            VARCHAR (10)    NULL,
    [Status]                     VARCHAR (50)    NULL,
    [AddedBy]                    VARCHAR (30)    NOT NULL,
    [AddedDate]                  DATETIME        NOT NULL,
    [AddedFromIP]                VARCHAR (15)    NOT NULL,
    [UpdatedBy]                  VARCHAR (30)    NULL,
    [UpdatedDate]                DATETIME        NULL,
    [UpdatedFromIP]              VARCHAR (15)    NULL,
    [LCANo]                      VARCHAR (20)    NULL,
    [LIBOUR]                     DECIMAL (18, 2) DEFAULT ((0)) NOT NULL,
    [InsuranceCoverNoteNo]       VARCHAR (20)    NULL,
    [InsuranceAttachment]        VARCHAR (100)   NULL,
    [PaymentBasedOn]             VARCHAR (15)    NULL,
    [PortOfLoading]              VARCHAR (50)    NULL,
    [PlantId]                    VARCHAR (10)    NULL,
    [InsuranceValue]             VARCHAR (50)    NULL,
    [IsAccepptanceFirst]         BIT             NULL,
    [ShipmentDate]               DATETIME        NULL,
    [PINo]                       VARCHAR (50)    NULL,
    CONSTRAINT [PK_PurchaseLC] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_PurchaseLC_BankMaster] FOREIGN KEY ([OpeningBankMasterId]) REFERENCES [MST].[BankMaster] ([Id]),
    CONSTRAINT [FK_PurchaseLC_Contract] FOREIGN KEY ([ContractId]) REFERENCES [dbo].[Contract] ([Id]),
    CONSTRAINT [FK_PurchaseLC_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_PurchaseLC_Party] FOREIGN KEY ([VendorId]) REFERENCES [HKP].[Party] ([Id]),
    CONSTRAINT [FK_PurchaseLC_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_PurchaseLC_Port] FOREIGN KEY ([PortOfLandingId]) REFERENCES [MST].[Port] ([Id])
);

