CREATE TABLE [dbo].[QuickCostingMaster] (
    [Id]                      VARCHAR (10)    NOT NULL,
    [ProductMasterId]         VARCHAR (10)    NULL,
    [CustomerId]              VARCHAR (10)    NULL,
    [Sequence]                DECIMAL (18, 2) NOT NULL,
    [Code]                    VARCHAR (10)    NOT NULL,
    [SpecifyTo]               VARCHAR (20)    NOT NULL,
    [ShortName]               VARCHAR (15)    NOT NULL,
    [StandardName]            VARCHAR (50)    NOT NULL,
    [UserName]                VARCHAR (50)    NOT NULL,
    [OrderSize]               DECIMAL (18, 2) NULL,
    [ProductionAvailableDays] INT             NULL,
    [MKTTargetPerHour]        DECIMAL (18, 2) NULL,
    [TargetFOB]               DECIMAL (18, 2) NULL,
    [PaymentDays]             DECIMAL (18, 2) NULL,
    [AccessShipmentPer]       DECIMAL (18, 2) NULL,
    [PackingType]             VARCHAR (20)    NULL,
    [EstNoOfPackingList]      INT             NULL,
    [FileName]                VARCHAR (50)    NULL,
    [Description]             VARCHAR (250)   NULL,
    [Remarks]                 VARCHAR (250)   NULL,
    [Active]                  BIT             NOT NULL,
    [AddedBy]                 VARCHAR (30)    NOT NULL,
    [AddedDate]               DATETIME        NOT NULL,
    [AddedFromIP]             VARCHAR (15)    NOT NULL,
    [UpdatedBy]               VARCHAR (30)    NULL,
    [UpdatedDate]             DATETIME        NULL,
    [UpdatedFromIP]           VARCHAR (15)    NULL,
    CONSTRAINT [PK_QuickCostingMaster] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_QuickCostingMaster_Party] FOREIGN KEY ([CustomerId]) REFERENCES [HKP].[Party] ([Id]),
    CONSTRAINT [FK_QuickCostingMaster_ProductMaster] FOREIGN KEY ([ProductMasterId]) REFERENCES [MST].[ProductMaster] ([Id])
);

