CREATE TABLE [dbo].[ResourcesConstraint] (
    [Id]                   VARCHAR (20)    NOT NULL,
    [EffectiveDateFrom]    DATETIME        NOT NULL,
    [EffectiveDateTo]      DATETIME        NOT NULL,
    [ProcessNameId]        VARCHAR (10)    NOT NULL,
    [ResourcesName]        VARCHAR (50)    NULL,
    [EntityName]           VARCHAR (50)    NULL,
    [WorkCenterName]       VARCHAR (50)    NULL,
    [WorkingHoursPerDay]   DECIMAL (18, 2) NULL,
    [WorkingDaysPerWeek]   DECIMAL (18, 2) NULL,
    [WorkingHoursPerWeek]  DECIMAL (18, 2) NULL,
    [WorkingDaysPerMonth]  DECIMAL (18, 2) NULL,
    [WorkingHoursPerMonth] DECIMAL (18, 2) NULL,
    [CapacityUOMId]        VARCHAR (10)    NULL,
    [CapacityPerDay]       DECIMAL (18, 2) NULL,
    [CapacityPerWeek]      DECIMAL (18, 2) NULL,
    [CapacityPerMonth]     DECIMAL (18, 2) NULL,
    [ResponsiblePersonId]  VARCHAR (30)    NULL,
    [Remarks]              VARCHAR (250)   NULL,
    [AddedBy]              VARCHAR (30)    NOT NULL,
    [AddedDate]            DATETIME        NOT NULL,
    [AddedFromIP]          VARCHAR (15)    NOT NULL,
    [UpdatedBy]            VARCHAR (30)    NULL,
    [UpdatedDate]          DATETIME        NULL,
    [UpdatedFromIP]        VARCHAR (15)    NULL,
    CONSTRAINT [PK_ResourcesConstraint] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ResourcesConstraint_CapacityUOM] FOREIGN KEY ([CapacityUOMId]) REFERENCES [SCS].[UnitOfMeasurement] ([Id]),
    CONSTRAINT [FK_ResourcesConstraint_ProcessName] FOREIGN KEY ([ProcessNameId]) REFERENCES [HKP].[Process] ([Id]),
    CONSTRAINT [FK_ResourcesConstraint_ResponsiblePerson] FOREIGN KEY ([ResponsiblePersonId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId])
);

