CREATE TABLE [dbo].[SalaryIncrementInfoDefine] (
    [SystemID]                    VARCHAR (30)    NOT NULL,
    [IncMstSystemID]              VARCHAR (30)    NULL,
    [SalaryHeadID]                VARCHAR (30)    NULL,
    [PrevEntryCurrencyID]         VARCHAR (10)    NULL,
    [PrevEntryAmount]             NUMERIC (18, 4) NOT NULL,
    [PrevDefineCurrencyID]        VARCHAR (10)    NULL,
    [PrevDefineAmount]            NUMERIC (18, 4) NULL,
    [PrevAmtDefinationCurrencyID] VARCHAR (10)    NULL,
    [PrevAmtDefinationRate]       NUMERIC (18, 4) NULL,
    [EntryCurrencyID]             VARCHAR (10)    NULL,
    [EntryAmount]                 NUMERIC (18, 4) NULL,
    [DefineCurrencyID]            VARCHAR (10)    NULL,
    [DefineAmount]                NUMERIC (18, 4) NULL,
    [AmtDefinationCurrencyID]     VARCHAR (10)    NULL,
    [AmtDefinationRate]           NUMERIC (18, 4) NULL,
    [AddedBy]                     VARCHAR (100)   NOT NULL,
    [DateAdded]                   DATETIME        NOT NULL,
    [UpdatedBy]                   VARCHAR (100)   NULL,
    [DateUpdated]                 DATETIME        NULL,
    CONSTRAINT [PK_SalaryIncrementInfoDefine] PRIMARY KEY CLUSTERED ([SystemID] ASC),
    CONSTRAINT [FK_SalaryIncrementInfoDefine_Currency] FOREIGN KEY ([PrevEntryCurrencyID]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_SalaryIncrementInfoDefine_Currency1] FOREIGN KEY ([PrevDefineCurrencyID]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_SalaryIncrementInfoDefine_Currency2] FOREIGN KEY ([PrevAmtDefinationCurrencyID]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_SalaryIncrementInfoDefine_Currency3] FOREIGN KEY ([EntryCurrencyID]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_SalaryIncrementInfoDefine_Currency4] FOREIGN KEY ([DefineCurrencyID]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_SalaryIncrementInfoDefine_Currency5] FOREIGN KEY ([AmtDefinationCurrencyID]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_SalaryIncrementInfoDefine_SalaryHead] FOREIGN KEY ([SalaryHeadID]) REFERENCES [dbo].[SalaryHead] ([SalaryHeadID]),
    CONSTRAINT [FK_SalaryIncrementInfoDefine_SalaryIncrementInfoDefineMaster] FOREIGN KEY ([IncMstSystemID]) REFERENCES [dbo].[SalaryIncrementInfoDefineMaster] ([SystemID])
);

