CREATE TABLE [dbo].[SalaryRuleAbsenteeism] (
    [SalaryRuleAbsenteeismSystemID] VARCHAR (30)    NOT NULL,
    [SalaryRuleMasterSystemID]      VARCHAR (30)    NOT NULL,
    [SalaryHeadID]                  VARCHAR (30)    NULL,
    [IsAbsNetPayEffect]             BIT             CONSTRAINT [DF_SalaryRuleAbsenteeism_IsAbsNetPayEffect] DEFAULT ((0)) NOT NULL,
    [IsAbsTagAndUnTag]              BIT             CONSTRAINT [DF_SalaryRuleAbsenteeism_IsAbsNetPayEffect1] DEFAULT ((0)) NOT NULL,
    [IsFixed]                       BIT             NULL,
    [FixedValue]                    NUMERIC (18, 2) NULL,
    [IsFormula]                     BIT             NULL,
    [FormulaDes]                    VARCHAR (8000)  NULL,
    [FormulaDesID]                  VARCHAR (500)   NULL,
    [IsFixedMonthDay]               BIT             NULL,
    [FixedMonthDayValue]            NUMERIC (18, 2) NULL,
    [IsMonthDay]                    BIT             NULL,
    [IsMonthWorkDay]                BIT             NULL,
    [IsFixedDisbus]                 BIT             NULL,
    [SequenceNo]                    INT             NULL,
    [IsDisbusted]                   BIT             CONSTRAINT [DF_SalaryRuleAbsenteeism_IsDisbusted] DEFAULT ((0)) NOT NULL,
    [AddedBy]                       VARCHAR (100)   NOT NULL,
    [DateAdded]                     DATETIME        NOT NULL,
    [UpdatedBy]                     VARCHAR (100)   NULL,
    [DateUpdated]                   DATETIME        NULL,
    [BaseOnNetPay]                  BIT             CONSTRAINT [DF_SalaryRuleAbsenteeism_BaseOnNetPay] DEFAULT ((0)) NOT NULL,
    [FormulaDesID_NewJoin]          VARCHAR (100)   NULL,
    [IsDeductionOnGross]            BIT             DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_SalaryRuleAbsenteeism] PRIMARY KEY CLUSTERED ([SalaryRuleAbsenteeismSystemID] ASC),
    CONSTRAINT [FK_SalaryRuleAbsenteeism_SalaryHead] FOREIGN KEY ([SalaryHeadID]) REFERENCES [dbo].[SalaryHead] ([SalaryHeadID]),
    CONSTRAINT [FK_SalaryRuleAbsenteeism_SalaryRuleMaster] FOREIGN KEY ([SalaryRuleMasterSystemID]) REFERENCES [dbo].[SalaryRuleMaster] ([SystemID])
);

