CREATE TABLE [dbo].[SalaryRuleGeneral] (
    [SalaryRuleGeneralSystemID]      VARCHAR (30)    NOT NULL,
    [SalaryRuleMasterSystemID]       VARCHAR (30)    NOT NULL,
    [SalaryHeadID]                   VARCHAR (30)    NULL,
    [IsGNRNetPayEffect]              BIT             CONSTRAINT [DF_SalaryRuleGeneral_IsGNRNetPayEffect] DEFAULT ((0)) NOT NULL,
    [IsGNRTagAndUnTag]               BIT             CONSTRAINT [DF_SalaryRuleGeneral_IsGNRNetPayEffect1] DEFAULT ((0)) NOT NULL,
    [IsOpen]                         BIT             CONSTRAINT [DF_SalaryRuleGeneral_IsOpen] DEFAULT ((0)) NOT NULL,
    [IsFixed]                        BIT             NOT NULL,
    [IsNA]                           BIT             NULL,
    [FixedValue]                     NUMERIC (18, 2) NOT NULL,
    [IsFormula]                      BIT             NOT NULL,
    [FormulaDes]                     VARCHAR (1000)  NULL,
    [FormulaDesID]                   VARCHAR (500)   NULL,
    [IsFixedMonthDay]                BIT             NOT NULL,
    [FixedMonthDayValue]             NUMERIC (18, 2) NULL,
    [IsMonthDay]                     BIT             NOT NULL,
    [IsMonthWorkDay]                 BIT             NOT NULL,
    [IsFixedDisbus]                  BIT             NOT NULL,
    [SequenceNo]                     INT             NOT NULL,
    [IsDisbusted]                    BIT             CONSTRAINT [DF_SalaryRuleGeneral_IsDisbusted] DEFAULT ((0)) NOT NULL,
    [IsBankPayment]                  BIT             CONSTRAINT [DF_SalaryRuleGeneral_IsBankPayment] DEFAULT ((1)) NOT NULL,
    [IsCashPayment]                  BIT             CONSTRAINT [DF_SalaryRuleGeneral_IsCashPayment1] DEFAULT ((1)) NOT NULL,
    [BaseOnNetPay]                   BIT             CONSTRAINT [DF_SalaryRuleGeneral_BaseOnNetPay] DEFAULT ((0)) NOT NULL,
    [RefAbsentism]                   BIT             CONSTRAINT [DF_SalaryRuleGeneral_RefAbsentism] DEFAULT ((0)) NOT NULL,
    [IsCTCComponent]                 BIT             CONSTRAINT [DF_SalaryRuleGeneral_IsGNRNetPayEffect1_1] DEFAULT ((0)) NOT NULL,
    [IsGrossComponent]               BIT             CONSTRAINT [DF_SalaryRuleGeneral_IsCTCComponent1] DEFAULT ((0)) NOT NULL,
    [AddedBy]                        VARCHAR (100)   NOT NULL,
    [DateAdded]                      DATETIME        NOT NULL,
    [UpdatedBy]                      VARCHAR (100)   NULL,
    [DateUpdated]                    DATETIME        NULL,
    [GNRBaseOthSlrHDFormula]         VARCHAR (100)   NULL,
    [GNRApplicableMonthNo]           VARCHAR (100)   NULL,
    [IsGNRBaseOthSlrHD]              BIT             CONSTRAINT [DF_SalaryRuleGeneral_IsGNRBaseOthSlrHD] DEFAULT ((0)) NOT NULL,
    [IsRetain]                       BIT             CONSTRAINT [DF_SalaryRuleGeneral_IsRetain] DEFAULT ((0)) NOT NULL,
    [IsMinWages]                     BIT             CONSTRAINT [DF_SalaryRuleGeneral_IsMinWages] DEFAULT ((0)) NOT NULL,
    [IsGNRWhichEverLess]             BIT             CONSTRAINT [DF_SalaryRuleGeneral_IsGNRWhichEverLess] DEFAULT ((0)) NOT NULL,
    [IsWorkDaysInAMonthIncHold]      BIT             DEFAULT ((0)) NOT NULL,
    [HasMaxLimit]                    BIT             DEFAULT ((0)) NOT NULL,
    [FixedMaxLimit]                  BIT             DEFAULT ((0)) NOT NULL,
    [MaxLimitValue]                  INT             DEFAULT ((0)) NOT NULL,
    [PercentageMaxLimit]             BIT             DEFAULT ((0)) NOT NULL,
    [PercentageMaxLimitSalaryHeadId] VARCHAR (30)    NULL,
    [HasMinLimit]                    BIT             DEFAULT ((0)) NOT NULL,
    [FixedMinLimit]                  BIT             DEFAULT ((0)) NOT NULL,
    [MinLimitValue]                  INT             DEFAULT ((0)) NOT NULL,
    [PercentageMinLimit]             BIT             DEFAULT ((0)) NOT NULL,
    [PercentageMinLimitSalaryHeadId] VARCHAR (30)    NULL,
    [IsPolicyDerived]                BIT             DEFAULT ((0)) NOT NULL,
    [IsSlabBased]                    BIT             DEFAULT ((0)) NOT NULL,
    [IsPayOnWeekoffForFixedMonthDay] BIT             DEFAULT ((0)) NOT NULL,
    [IsPayOnHolidayForFixedMonthDay] BIT             DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_SalaryRuleGeneral] PRIMARY KEY CLUSTERED ([SalaryRuleGeneralSystemID] ASC),
    CONSTRAINT [FK_SalaryRuleGeneral_SalaryHead] FOREIGN KEY ([SalaryHeadID]) REFERENCES [dbo].[SalaryHead] ([SalaryHeadID]),
    CONSTRAINT [FK_SalaryRuleGeneral_SalaryRuleMaster] FOREIGN KEY ([SalaryRuleMasterSystemID]) REFERENCES [dbo].[SalaryRuleMaster] ([SystemID])
);

