CREATE TABLE [dbo].[SalaryProceAttdnData] (
    [EmpSystemID]         VARCHAR (30)    NOT NULL,
    [SlrProcMstSystemID]  VARCHAR (30)    NOT NULL,
    [MonthNo]             INT             NOT NULL,
    [YearNo]              INT             NOT NULL,
    [GroupID]             VARCHAR (10)    NOT NULL,
    [PlantID]             VARCHAR (10)    NOT NULL,
    [FromDate]            DATETIME        NOT NULL,
    [ToDate]              DATETIME        NOT NULL,
    [TotalProcDate]       DECIMAL (18, 2) CONSTRAINT [DF_SalaryProceAttdnData_TotalProcDate] DEFAULT ((0)) NOT NULL,
    [TotalPresent]        DECIMAL (18, 2) CONSTRAINT [DF_SalaryProceAttdnData_TotalPresent] DEFAULT ((0)) NOT NULL,
    [TotalLate]           DECIMAL (18, 2) CONSTRAINT [DF_SalaryProceAttdnData_TotalLate] DEFAULT ((0)) NOT NULL,
    [TotalAbsent]         DECIMAL (18, 2) CONSTRAINT [DF_SalaryProceAttdnData_TotalAbsent] DEFAULT ((0)) NOT NULL,
    [TotalLv]             DECIMAL (18, 2) CONSTRAINT [DF_SalaryProceAttdnData_TotalLv] DEFAULT ((0)) NOT NULL,
    [TotalMLv]            INT             CONSTRAINT [DF_SalaryProceAttdnData_TotalMLv] DEFAULT ((0)) NOT NULL,
    [TotalCompAssignLv]   INT             CONSTRAINT [DF_SalaryProceAttdnData_TotalCompAssignLv] DEFAULT ((0)) NOT NULL,
    [TotalWeekOff]        INT             CONSTRAINT [DF_SalaryProceAttdnData_TotalWeekOff] DEFAULT ((0)) NOT NULL,
    [TotalHoliDay]        INT             CONSTRAINT [DF_SalaryProceAttdnData_TotalHoliDay] DEFAULT ((0)) NOT NULL,
    [TotalWeekOffHoliDay] INT             CONSTRAINT [DF_SalaryProceAttdnData_TotalWeekOffHoliDay] DEFAULT ((0)) NOT NULL,
    [TotalOTHr]           NUMERIC (18, 2) CONSTRAINT [DF_SalaryProceAttdnData_TotalOTHr] DEFAULT ((0)) NOT NULL,
    [TotalNormalOTHr]     NUMERIC (18, 2) CONSTRAINT [DF_SalaryProceAttdnData_TotalNormalOTHr] DEFAULT ((0)) NOT NULL,
    [TotalExtraOTHr]      NUMERIC (18, 2) CONSTRAINT [DF_SalaryProceAttdnData_TotalExtraOTHr] DEFAULT ((0)) NOT NULL,
    [AddedBy]             VARCHAR (100)   NULL,
    [DateAdded]           DATETIME        NULL,
    [UpdatedBy]           VARCHAR (100)   NULL,
    [DateUpdated]         DATETIME        NULL,
    [WeekOffOTHr]         NUMERIC (18, 2) NULL,
    [HoliDayOTHr]         NUMERIC (18, 2) NULL,
    [TotalLWP]            NUMERIC (18, 2) CONSTRAINT [DF__SalaryPro__Total__448B0BA5] DEFAULT ((0)) NOT NULL,
    [IsOTEntitled]        BIT             CONSTRAINT [DF__SalaryPro__IsOTE__298DC7FD] DEFAULT ((0)) NOT NULL,
    [OTRate]              NUMERIC (18, 2) CONSTRAINT [DF__SalaryPro__OTRat__56606E74] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_SalaryProceAttdnData] PRIMARY KEY CLUSTERED ([EmpSystemID] ASC, [SlrProcMstSystemID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_SalaryProceAttdnData_CompanyGroup] FOREIGN KEY ([GroupID]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_SalaryProceAttdnData_EmployeeInformation] FOREIGN KEY ([EmpSystemID]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_SalaryProceAttdnData_Plant] FOREIGN KEY ([PlantID]) REFERENCES [ORG].[Plant] ([Id])
);

