CREATE TABLE [dbo].[ShiftDefination] (
    [SystemID]                   VARCHAR (30)    NOT NULL,
    [GroupID]                    VARCHAR (10)    NULL,
    [PlantID]                    VARCHAR (10)    NULL,
    [ShiftDefinationName]        VARCHAR (50)    NULL,
    [ShiftDefinationDescription] VARCHAR (150)   NULL,
    [UserName]                   VARCHAR (50)    NULL,
    [SequenceNo]                 INT             NULL,
    [IsActive]                   BIT             CONSTRAINT [DF_ShiftDefination_IsActive] DEFAULT ((1)) NOT NULL,
    [DefaultShift]               BIT             CONSTRAINT [DF_ShiftDefination_DefaultShift] DEFAULT ((0)) NOT NULL,
    [ShiftType]                  VARCHAR (20)    NULL,
    [InTime]                     DATETIME        NULL,
    [InTimeStartMargin]          INT             NULL,
    [LateMargin]                 INT             NULL,
    [AbsentEndMargin]            INT             NULL,
    [OutTime]                    DATETIME        NULL,
    [OutTimeEndMargin]           INT             NULL,
    [OTStartTime]                INT             NULL,
    [IsGapInclude]               BIT             CONSTRAINT [DF_ShiftDefination_IsGapInclude] DEFAULT ((0)) NOT NULL,
    [BreakStratTime]             DATETIME        NULL,
    [BreakEndTime]               DATETIME        NULL,
    [BreakPeriod]                INT             NULL,
    [WorkingHour]                FLOAT (53)      NULL,
    [AddedBy]                    VARCHAR (100)   NOT NULL,
    [DateAdded]                  DATETIME        NOT NULL,
    [UpdatedBy]                  VARCHAR (100)   NULL,
    [DateUpdated]                DATETIME        NULL,
    [EarlyIn]                    BIT             DEFAULT ((0)) NOT NULL,
    [LateIn]                     BIT             DEFAULT ((0)) NOT NULL,
    [LateInMargin]               INT             DEFAULT ((0)) NOT NULL,
    [EarlyOut]                   BIT             DEFAULT ((0)) NOT NULL,
    [EarlyOutMargin]             INT             DEFAULT ((0)) NOT NULL,
    [EarlyInMargin]              INT             DEFAULT ((0)) NOT NULL,
    [LateOutMargin]              INT             DEFAULT ((0)) NOT NULL,
    [LateOut]                    BIT             DEFAULT ((0)) NOT NULL,
    [LateOutRoundMargin]         INT             DEFAULT ((0)) NOT NULL,
    [LateInRoundMargin]          INT             DEFAULT ((0)) NOT NULL,
    [EarlyOutRoundMargin]        INT             DEFAULT ((0)) NOT NULL,
    [EarlyInRoundMargin]         INT             DEFAULT ((0)) NOT NULL,
    [LateOutRoundMarginType]     VARCHAR (10)    NULL,
    [LateInRoundMarginType]      VARCHAR (10)    NULL,
    [EarlyOutRoundMarginType]    VARCHAR (10)    NULL,
    [EarlyInRoundMarginType]     VARCHAR (10)    NULL,
    [IncludeBreakTimeInOT]       BIT             DEFAULT ((0)) NOT NULL,
    [HalfDayAbsentMaxLimit]      NUMERIC (18, 2) DEFAULT ((0)) NOT NULL,
    [LateInMaxLimit]             INT             DEFAULT ((0)) NOT NULL,
    [IsLateInApplicable]         BIT             DEFAULT ((0)) NOT NULL,
    [RawINDefinitionFrom]        INT             DEFAULT ((0)) NOT NULL,
    [RawINDefinitionTo]          INT             DEFAULT ((0)) NOT NULL,
    [RawOUTDefinitionFrom]       INT             DEFAULT ((0)) NOT NULL,
    [RawOUTDefinitionTo]         INT             DEFAULT ((0)) NOT NULL,
    [EarlyOutMaxLimit]           INT             DEFAULT ((0)) NOT NULL,
    [IsLunchOutApplicable]       BIT             DEFAULT ((0)) NULL,
    [IsEarlyOutApplicable]       BIT             DEFAULT ((0)) NULL,
    [LateInToleranceMargin]      INT             DEFAULT ((0)) NOT NULL,
    [EarlyOutToleranceMargin]    INT             DEFAULT ((0)) NOT NULL,
    [LateMarginSeconds]          INT             DEFAULT ((0)) NOT NULL,
    [INAfterOUTAsOTStart]        BIT             DEFAULT ((0)) NOT NULL,
    [ShiftDuration]              NUMERIC (18, 2) DEFAULT ((0)) NULL,
    [HalfDayDuration]            NUMERIC (18, 2) DEFAULT ((0)) NULL,
    [FullDayDuration]            NUMERIC (18, 2) DEFAULT ((0)) NULL,
    [ShortDuration]              NUMERIC (18, 2) DEFAULT ((0)) NULL,
    [MaxOutDuration]             NUMERIC (18, 2) DEFAULT ((0)) NULL,
    [ShiftEarlyInMargin]         NUMERIC (18, 2) DEFAULT ((0)) NULL,
    [ShiftEarlyOutMargin]        NUMERIC (18, 2) DEFAULT ((0)) NULL,
    [ShiftLateInMargin]          NUMERIC (18, 2) DEFAULT ((0)) NULL,
    [ShiftLateOutMargin]         NUMERIC (18, 2) DEFAULT ((0)) NULL,
    [HoursWithoutOT]             NUMERIC (18, 2) DEFAULT ((0)) NULL,
    CONSTRAINT [PK_ShiftDefination] PRIMARY KEY CLUSTERED ([SystemID] ASC),
    CONSTRAINT [FK_ShiftDefination_CompanyGroup] FOREIGN KEY ([GroupID]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_ShiftDefination_Plant] FOREIGN KEY ([PlantID]) REFERENCES [ORG].[Plant] ([Id])
);

