CREATE TABLE [dbo].[TaskMaster] (
    [Id]                        VARCHAR (30)    NOT NULL,
    [Sequence]                  INT             DEFAULT ((0)) NULL,
    [TaskDescription]           NVARCHAR (1024) NULL,
    [UserDefineTask]            NVARCHAR (1024) NULL,
    [StandardName]              VARCHAR (255)   NULL,
    [Code]                      VARCHAR (50)    NULL,
    [Active]                    BIT             NULL,
    [ForNewOrder]               BIT             NULL,
    [HasSubTaskList]            BIT             DEFAULT ((0)) NULL,
    [TaskCategoryId]            VARCHAR (10)    NULL,
    [ProcessId]                 VARCHAR (10)    NULL,
    [DepartmentId]              VARCHAR (10)    NULL,
    [IsMandatory]               BIT             DEFAULT ((0)) NULL,
    [TaskType]                  VARCHAR (30)    NULL,
    [IsTaskMilestone]           BIT             DEFAULT ((0)) NULL,
    [TaskDependentDatesId]      VARCHAR (10)    NULL,
    [TaskAppliedOnId]           VARCHAR (10)    NULL,
    [Remarks]                   NVARCHAR (255)  NULL,
    [LagDays]                   DECIMAL (10, 4) NULL,
    [StandardDays]              DECIMAL (10, 4) NULL,
    [WillSendEmail]             BIT             DEFAULT ((0)) NULL,
    [WillSendSMS]               BIT             DEFAULT ((0)) NULL,
    [ResponsiblePersonCategory] VARCHAR (20)    NULL,
    [AddedBy]                   VARCHAR (30)    NOT NULL,
    [AddedDate]                 DATETIME        NOT NULL,
    [AddedFromIP]               VARCHAR (15)    NOT NULL,
    [UpdatedBy]                 VARCHAR (30)    NULL,
    [UpdatedDate]               DATETIME        NULL,
    [UpdatedFromIP]             VARCHAR (15)    NULL,
    [RepeatTask]                BIT             DEFAULT ((0)) NULL,
    [ConsiderOffDays]           BIT             NULL,
    [TaskSubCategoryId]         VARCHAR (10)    NULL,
    [StoryPoint]                DECIMAL (18, 2) NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    FOREIGN KEY ([DepartmentId]) REFERENCES [ORG].[Department] ([Id]),
    FOREIGN KEY ([DepartmentId]) REFERENCES [ORG].[Department] ([Id]),
    FOREIGN KEY ([DepartmentId]) REFERENCES [ORG].[Department] ([Id]),
    FOREIGN KEY ([ProcessId]) REFERENCES [HKP].[Process] ([Id]),
    FOREIGN KEY ([ProcessId]) REFERENCES [HKP].[Process] ([Id]),
    FOREIGN KEY ([ProcessId]) REFERENCES [HKP].[Process] ([Id]),
    FOREIGN KEY ([TaskAppliedOnId]) REFERENCES [HKP].[TaskAppliedOn] ([Id]),
    FOREIGN KEY ([TaskAppliedOnId]) REFERENCES [HKP].[TaskAppliedOn] ([Id]),
    FOREIGN KEY ([TaskAppliedOnId]) REFERENCES [HKP].[TaskAppliedOn] ([Id]),
    FOREIGN KEY ([TaskCategoryId]) REFERENCES [HKP].[TaskCategory] ([Id]),
    FOREIGN KEY ([TaskCategoryId]) REFERENCES [HKP].[TaskCategory] ([Id]),
    FOREIGN KEY ([TaskCategoryId]) REFERENCES [HKP].[TaskCategory] ([Id]),
    FOREIGN KEY ([TaskDependentDatesId]) REFERENCES [HKP].[TaskDependentDates] ([Id]),
    FOREIGN KEY ([TaskDependentDatesId]) REFERENCES [HKP].[TaskDependentDates] ([Id]),
    FOREIGN KEY ([TaskDependentDatesId]) REFERENCES [HKP].[TaskDependentDates] ([Id]),
    FOREIGN KEY ([TaskSubCategoryId]) REFERENCES [HKP].[TaskSubCategory] ([Id])
);

