CREATE TABLE [dbo].[TaskTemplate] (
    [Id]                        VARCHAR (30)    NOT NULL,
    [TaskTemplateMasterId]      VARCHAR (30)    NULL,
    [TaskMasterId]              VARCHAR (30)    NULL,
    [TaskDescription]           NVARCHAR (1024) NULL,
    [Active]                    BIT             NULL,
    [Sequence]                  DECIMAL (10, 2) NULL,
    [Duration]                  DECIMAL (10, 4) NULL,
    [predecessor]               VARCHAR (100)   NULL,
    [startDate]                 DATETIME        NULL,
    [endDate]                   DATETIME        NULL,
    [EmployeeId]                VARCHAR (30)    NULL,
    [ForNewOrder]               BIT             NULL,
    [IsMandatory]               BIT             DEFAULT ((0)) NULL,
    [TaskType]                  VARCHAR (30)    NULL,
    [IsTaskMilestone]           BIT             DEFAULT ((0)) NULL,
    [TaskDependentDatesId]      VARCHAR (10)    NULL,
    [TaskAppliedOnId]           VARCHAR (10)    NULL,
    [Remarks]                   NVARCHAR (255)  NULL,
    [WillSendEmail]             BIT             DEFAULT ((0)) NULL,
    [WillSendSMS]               BIT             DEFAULT ((0)) NULL,
    [ResponsiblePersonCategory] VARCHAR (20)    NULL,
    [IsFirstTask]               BIT             DEFAULT ((0)) NULL,
    [IsLastTask]                BIT             DEFAULT ((0)) NULL,
    [AddedBy]                   VARCHAR (30)    NOT NULL,
    [AddedDate]                 DATETIME        NOT NULL,
    [AddedFromIP]               VARCHAR (15)    NOT NULL,
    [UpdatedBy]                 VARCHAR (30)    NULL,
    [UpdatedDate]               DATETIME        NULL,
    [UpdatedFromIP]             VARCHAR (15)    NULL,
    [StoryPoint]                DECIMAL (18, 2) NULL,
    [LagDays]                   DECIMAL (10, 4) NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    FOREIGN KEY ([TaskAppliedOnId]) REFERENCES [HKP].[TaskAppliedOn] ([Id]),
    FOREIGN KEY ([TaskAppliedOnId]) REFERENCES [HKP].[TaskAppliedOn] ([Id]),
    FOREIGN KEY ([TaskAppliedOnId]) REFERENCES [HKP].[TaskAppliedOn] ([Id]),
    FOREIGN KEY ([TaskDependentDatesId]) REFERENCES [HKP].[TaskDependentDates] ([Id]),
    FOREIGN KEY ([TaskDependentDatesId]) REFERENCES [HKP].[TaskDependentDates] ([Id]),
    FOREIGN KEY ([TaskDependentDatesId]) REFERENCES [HKP].[TaskDependentDates] ([Id]),
    FOREIGN KEY ([TaskMasterId]) REFERENCES [dbo].[TaskMaster] ([Id]),
    FOREIGN KEY ([TaskMasterId]) REFERENCES [dbo].[TaskMaster] ([Id]),
    FOREIGN KEY ([TaskMasterId]) REFERENCES [dbo].[TaskMaster] ([Id]),
    FOREIGN KEY ([TaskTemplateMasterId]) REFERENCES [dbo].[TaskTemplateMaster] ([Id]),
    FOREIGN KEY ([TaskTemplateMasterId]) REFERENCES [dbo].[TaskTemplateMaster] ([Id]),
    FOREIGN KEY ([TaskTemplateMasterId]) REFERENCES [dbo].[TaskTemplateMaster] ([Id]),
    CONSTRAINT [FK__TaskTempl__Emplo__1BE9B41C] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK__TaskTempl__Emplo__5210BAA3] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK__TaskTempl__Emplo__76832543] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId])
);

