CREATE TABLE [dbo].[TaskSchedulerMaster] (
    [Id]                                 VARCHAR (30)  NOT NULL,
    [RepeatType]                         VARCHAR (20)  NULL,
    [EveryInterval]                      INT           NULL,
    [StartDate]                          DATETIME      NULL,
    [EndDate]                            DATETIME      NULL,
    [IsNever]                            BIT           NULL,
    [AfterNoOfAccurence]                 INT           NULL,
    [WeeklyRepeatationBycommaSepDayName] VARCHAR (100) NULL,
    [RepeatByDayNumber]                  INT           NULL,
    [RepeatbyNthWeek]                    VARCHAR (20)  NULL,
    [RepeatByMonth]                      VARCHAR (10)  NULL,
    [RepeatbyOfEarly]                    VARCHAR (10)  NULL,
    [RepeatByWeek]                       VARCHAR (10)  NULL,
    [AddedBy]                            VARCHAR (30)  NULL,
    [AddedDate]                          DATETIME      NULL,
    [AddedFromIP]                        VARCHAR (15)  NULL,
    [UpdatedBy]                          VARCHAR (30)  NULL,
    [UpdatedDate]                        DATETIME      NULL,
    [UpdatedFromIP]                      VARCHAR (15)  NULL,
    [Details]                            VARCHAR (250) NULL,
    [IsAfter]                            BIT           NULL,
    [IsOn]                               BIT           NULL,
    [isRepeatByDay]                      BIT           NULL,
    [isRepeatByTheNthWeekForMonthly]     BIT           NULL,
    [isRepeatByTheNthWeek]               BIT           NULL,
    [isRepeatByTheMonth]                 BIT           NULL,
    [isRepeatByTheNthWeekForYearly]      BIT           NULL,
    [OnPreviousAccomplishment]           BIT           DEFAULT ((1)) NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

