CREATE TABLE [dbo].[TaxableIncomeSalaryHeadWise] (
    [SystemID]                VARCHAR (30)    NOT NULL,
    [EmpInfoSystemID]         VARCHAR (30)    NOT NULL,
    [TaxDefineMasterSystemID] VARCHAR (30)    NULL,
    [TaxPolicyMstID]          VARCHAR (30)    NULL,
    [TaxGroupID]              VARCHAR (30)    NULL,
    [TaxYearID]               VARCHAR (30)    NULL,
    [SalaryHeadID]            VARCHAR (30)    NOT NULL,
    [GroupID]                 VARCHAR (10)    NOT NULL,
    [PlantID]                 VARCHAR (10)    NOT NULL,
    [EntryIncomeCurrencyID]   VARCHAR (10)    NULL,
    [EntryIncome]             NUMERIC (18, 4) NOT NULL,
    [DefinitionCurrencyID]    VARCHAR (10)    NULL,
    [DefinitionAmount]        NUMERIC (18, 4) NULL,
    [DefinitionCurrencyRate]  NUMERIC (18, 4) NULL,
    [TaxPayablePeriod]        NUMERIC (18, 2) NULL,
    [LocalCurrencyID]         VARCHAR (10)    NULL,
    [ConvertionRate]          NUMERIC (18, 4) NULL,
    [YearlyIncome]            NUMERIC (18, 4) NULL,
    [AddedBy]                 VARCHAR (100)   NOT NULL,
    [DateAdded]               DATETIME        NOT NULL,
    [UpdatedBy]               VARCHAR (100)   NULL,
    [DateUpdated]             DATETIME        NULL,
    CONSTRAINT [PK_TaxableIncomeSalaryHeadWise] PRIMARY KEY CLUSTERED ([SystemID] ASC),
    CONSTRAINT [FK_TaxableIncomeSalaryHeadWise_EmployeeInformation] FOREIGN KEY ([EmpInfoSystemID]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_TaxableIncomeSalaryHeadWise_SalaryHead] FOREIGN KEY ([SalaryHeadID]) REFERENCES [dbo].[SalaryHead] ([SalaryHeadID]),
    CONSTRAINT [FK_TaxableIncomeSalaryHeadWise_TaxDefineMaster] FOREIGN KEY ([TaxDefineMasterSystemID]) REFERENCES [dbo].[TaxDefineMaster] ([SystemID]),
    CONSTRAINT [FK_TaxableIncomeSalaryHeadWise_TaxGroup] FOREIGN KEY ([TaxGroupID]) REFERENCES [dbo].[TaxGroup] ([SystemID]),
    CONSTRAINT [FK_TaxableIncomeSalaryHeadWise_TaxPolicyMaster] FOREIGN KEY ([TaxPolicyMstID]) REFERENCES [dbo].[TaxPolicyMaster] ([SystemID])
);

