CREATE TABLE [dbo].[TaxDefineMaster] (
    [SystemID]                VARCHAR (30)    NOT NULL,
    [EmpInfoSystemID]         VARCHAR (30)    NOT NULL,
    [TaxPolicyMstID]          VARCHAR (30)    NULL,
    [TaxGroupID]              VARCHAR (30)    NULL,
    [TaxYearID]               VARCHAR (10)    NULL,
    [SalaryID]                VARCHAR (30)    NULL,
    [EffectiveDate]           DATETIME        NULL,
    [TaxStartFromYear]        INT             NOT NULL,
    [TaxStartFromMonth]       INT             NOT NULL,
    [TaxableIncome]           NUMERIC (18, 4) NOT NULL,
    [InvestmentAmount]        NUMERIC (18, 4) NOT NULL,
    [RebateAmount]            NUMERIC (18, 4) NOT NULL,
    [TaxableAmount]           NUMERIC (18, 4) NOT NULL,
    [PaidTaxAmount]           NUMERIC (18, 4) NOT NULL,
    [TaxPaidUptoYear]         INT             NOT NULL,
    [TaxPaidUptoMonth]        INT             NOT NULL,
    [TaxToBePay]              NUMERIC (18, 4) NULL,
    [ActualTaxAmountPerMonth] NUMERIC (18, 4) NULL,
    [MonthlyTaxSystemID]      VARCHAR (30)    NULL,
    [AddedBy]                 VARCHAR (100)   NOT NULL,
    [DateAdded]               DATETIME        NOT NULL,
    [UpdatedBy]               VARCHAR (100)   NULL,
    [DateUpdated]             DATETIME        NULL,
    CONSTRAINT [PK_TaxDefineMaster] PRIMARY KEY CLUSTERED ([SystemID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_TaxDefineMaster_EmployeeInformation] FOREIGN KEY ([EmpInfoSystemID]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_TaxDefineMaster_TaxYear] FOREIGN KEY ([TaxYearID]) REFERENCES [SCS].[TaxYear] ([Id])
);

