CREATE TABLE [dbo].[TaxExemptedAmtSalaryHeadWise] (
    [SystemID]               VARCHAR (30)    NOT NULL,
    [EmpInfoSystemID]        VARCHAR (30)    NOT NULL,
    [TaxPolicyMstID]         VARCHAR (30)    NULL,
    [TaxGroupID]             VARCHAR (30)    NULL,
    [TaxYearID]              VARCHAR (30)    NULL,
    [SalaryHeadID]           VARCHAR (30)    NOT NULL,
    [GroupID]                VARCHAR (10)    NOT NULL,
    [PlantID]                VARCHAR (10)    NOT NULL,
    [EntryIncomeCurrencyID]  VARCHAR (10)    NULL,
    [EntryIncome]            NUMERIC (18, 4) NOT NULL,
    [DefinationCurrencyID]   VARCHAR (10)    NULL,
    [DefinationAmount]       NUMERIC (18, 4) NULL,
    [DefinationCurrencyRate] NUMERIC (18, 4) NULL,
    [LocalCurrencyID]        VARCHAR (10)    NULL,
    [ConvertionRate]         NUMERIC (18, 4) NULL,
    [TaxExemptedAmt]         NUMERIC (18, 4) NULL,
    [AddedBy]                VARCHAR (100)   NOT NULL,
    [DateAdded]              DATETIME        NOT NULL,
    [UpdatedBy]              VARCHAR (100)   NULL,
    [DateUpdated]            DATETIME        NULL,
    CONSTRAINT [PK_TaxExemptedAmtSalaryHeadWise] PRIMARY KEY CLUSTERED ([SystemID] ASC),
    CONSTRAINT [FK_TaxExemptedAmtSalaryHeadWise_CompanyGroup] FOREIGN KEY ([GroupID]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_TaxExemptedAmtSalaryHeadWise_Currency] FOREIGN KEY ([EntryIncomeCurrencyID]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_TaxExemptedAmtSalaryHeadWise_Currency1] FOREIGN KEY ([DefinationCurrencyID]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_TaxExemptedAmtSalaryHeadWise_Currency2] FOREIGN KEY ([LocalCurrencyID]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_TaxExemptedAmtSalaryHeadWise_EmployeeInformation] FOREIGN KEY ([EmpInfoSystemID]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_TaxExemptedAmtSalaryHeadWise_Plant] FOREIGN KEY ([PlantID]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_TaxExemptedAmtSalaryHeadWise_SalaryHead] FOREIGN KEY ([SalaryHeadID]) REFERENCES [dbo].[SalaryHead] ([SalaryHeadID]),
    CONSTRAINT [FK_TaxExemptedAmtSalaryHeadWise_TaxGroup] FOREIGN KEY ([TaxGroupID]) REFERENCES [dbo].[TaxGroup] ([SystemID]),
    CONSTRAINT [FK_TaxExemptedAmtSalaryHeadWise_TaxPolicyMaster] FOREIGN KEY ([TaxPolicyMstID]) REFERENCES [dbo].[TaxPolicyMaster] ([SystemID])
);

