CREATE TABLE [dbo].[TaxPolicyMaster] (
    [SystemID]                     VARCHAR (30)    NOT NULL,
    [TaxPolicyName]                VARCHAR (50)    NULL,
    [Description]                  VARCHAR (250)   NULL,
    [TaxYearID]                    VARCHAR (10)    NULL,
    [GroupID]                      VARCHAR (10)    NULL,
    [PlantID]                      VARCHAR (10)    NULL,
    [LocalCurrencyCode]            VARCHAR (20)    NULL,
    [MinSalaryHeadID]              VARCHAR (30)    NULL,
    [MinSalaryAmount]              NUMERIC (18, 2) CONSTRAINT [DF_TaxPolicyMaster_MinSalaryAmount] DEFAULT ((0)) NULL,
    [MinimumTaxableAmount]         NUMERIC (18, 2) CONSTRAINT [DF_TaxPolicyMaster_MinimumTaxableAmount] DEFAULT ((0)) NULL,
    [IsFixedTaxInvestAll]          BIT             CONSTRAINT [DF_TaxPolicyMaster_IsFixedTaxInvestAll] DEFAULT ((0)) NOT NULL,
    [TaxFixedTaxInvestAll]         NUMERIC (18, 2) CONSTRAINT [DF_TaxPolicyMaster_TaxFixedTaxInvestAll] DEFAULT ((0)) NOT NULL,
    [IsPercentageTaxInvestAll]     BIT             CONSTRAINT [DF_TaxPolicyMaster_IsPercentageTaxInvestAll] DEFAULT ((0)) NOT NULL,
    [TaxPercentageInvestAll]       INT             CONSTRAINT [DF_TaxPolicyMaster_TaxPercentageInvestAll] DEFAULT ((0)) NOT NULL,
    [IsLimitInvestAll]             BIT             CONSTRAINT [DF_TaxPolicyMaster_IsLimitInvestAll] DEFAULT ((0)) NOT NULL,
    [TaxLimitInvestAll]            INT             CONSTRAINT [DF_TaxPolicyMaster_TaxLimitInvestAll] DEFAULT ((0)) NOT NULL,
    [IsFixedTaxRebate]             BIT             CONSTRAINT [DF_TaxPolicyMaster_IsFixedTaxRebate] DEFAULT ((0)) NOT NULL,
    [TaxFixedTaxRebate]            NUMERIC (18, 2) CONSTRAINT [DF_TaxPolicyMaster_TaxFixedTaxRebate] DEFAULT ((0)) NOT NULL,
    [IsPercentageTaxRebate]        BIT             CONSTRAINT [DF_TaxPolicyMaster_IsPercentageTaxRebate] DEFAULT ((0)) NOT NULL,
    [TaxPercentageRebate]          INT             CONSTRAINT [DF_TaxPolicyMaster_TaxPercentageRebate] DEFAULT ((0)) NOT NULL,
    [BaseOnIncomeTaxRebate]        BIT             CONSTRAINT [DF_TaxPolicyMaster_BaseOnIncomeTaxRebate] DEFAULT ((0)) NOT NULL,
    [IsBaseOnActEntAmt]            BIT             CONSTRAINT [DF_TaxPolicyMaster_IsBaseOnActEntAmt] DEFAULT ((0)) NOT NULL,
    [IsFixedTaxBonusDefine]        BIT             CONSTRAINT [DF_TaxPolicyMaster_IsFixedTaxBonusDefine] DEFAULT ((0)) NOT NULL,
    [TaxFixedBonusDefine]          INT             CONSTRAINT [DF_TaxPolicyMaster_TaxFixedBonusDefine] DEFAULT ((0)) NOT NULL,
    [IsTaxAsPerActual]             BIT             CONSTRAINT [DF_TaxPolicyMaster_IsTaxAsPerActual] DEFAULT ((0)) NOT NULL,
    [IsTaxAsPerProjection]         BIT             CONSTRAINT [DF_TaxPolicyMaster_IsTaxAsPerProjection] DEFAULT ((0)) NOT NULL,
    [IsFixedTaxLvEncash]           BIT             CONSTRAINT [DF_TaxPolicyMaster_IsFixedTaxLvEncash] DEFAULT ((0)) NOT NULL,
    [TaxFixedLvEncash]             INT             CONSTRAINT [DF_TaxPolicyMaster_TaxFixedLvEncash] DEFAULT ((0)) NOT NULL,
    [IsTaxAsPerActualLvEncash]     BIT             CONSTRAINT [DF_TaxPolicyMaster_IsTaxAsPerActualLvEncash] DEFAULT ((0)) NOT NULL,
    [IsTaxAsPerProjectionLvEncash] BIT             CONSTRAINT [DF_TaxPolicyMaster_IsTaxAsPerProjectionLvEncash] DEFAULT ((0)) NOT NULL,
    [IsCumulativeTaxSlabDefine]    BIT             CONSTRAINT [DF_TaxPolicyMaster_IsCumulativeTaxSlabDefine] DEFAULT ((0)) NOT NULL,
    [IsBrakeTaxSlabDefine]         BIT             CONSTRAINT [DF_TaxPolicyMaster_IsBrakeTaxSlabDefine] DEFAULT ((0)) NOT NULL,
    [AddedBy]                      VARCHAR (100)   NOT NULL,
    [DateAdded]                    DATETIME        NOT NULL,
    [UpdatedBy]                    VARCHAR (100)   NULL,
    [DateUpdated]                  DATETIME        NULL,
    [IsGenderSpecific]             BIT             CONSTRAINT [DF_TaxPolicyMaster_IsGenderSpecific] DEFAULT ((0)) NULL,
    [GenderID]                     VARCHAR (10)    NULL,
    [TaxTypeId]                    VARCHAR (30)    NULL,
    [CalculationBasis]             VARCHAR (50)    NULL,
    CONSTRAINT [PK_TaxPolicyMaster] PRIMARY KEY CLUSTERED ([SystemID] ASC),
    CONSTRAINT [FK_TaxPolicyMaster_CompanyGroup] FOREIGN KEY ([GroupID]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_TaxPolicyMaster_Plant] FOREIGN KEY ([PlantID]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_TaxPolicyMaster_SalaryHead] FOREIGN KEY ([MinSalaryHeadID]) REFERENCES [dbo].[SalaryHead] ([SalaryHeadID]),
    CONSTRAINT [FK_TaxPolicyMaster_TaxType] FOREIGN KEY ([TaxTypeId]) REFERENCES [dbo].[TaxType] ([Id]),
    CONSTRAINT [FK_TaxPolicyMaster_TaxYear] FOREIGN KEY ([TaxYearID]) REFERENCES [SCS].[TaxYear] ([Id])
);

