CREATE TABLE [dbo].[TNATasks] (
    [Id]                          VARCHAR (30) NOT NULL,
    [TNAMasterId]                 VARCHAR (30) NULL,
    [TaskTemplateId]              VARCHAR (30) NULL,
    [HasActualDate]               BIT          NULL,
    [HasPredecessorActualDate]    BIT          NULL,
    [ACTIVE]                      BIT          NULL,
    [TempStartDate]               DATETIME     NULL,
    [TempEndDate]                 DATETIME     NULL,
    [ActualStartDate]             DATETIME     NULL,
    [ActualEndDate]               DATETIME     NULL,
    [SequentialStartDate]         DATETIME     NULL,
    [SequentialEndDate]           DATETIME     NULL,
    [EmployeeId]                  VARCHAR (30) NULL,
    [AddedBy]                     VARCHAR (30) NOT NULL,
    [AddedDate]                   DATETIME     NOT NULL,
    [AddedFromIP]                 VARCHAR (15) NOT NULL,
    [UpdatedBy]                   VARCHAR (30) NULL,
    [UpdatedDate]                 DATETIME     NULL,
    [UpdatedFromIP]               VARCHAR (15) NULL,
    [OriginalSequentialStartDate] DATETIME     NULL,
    [OriginalSequentialEndDate]   DATETIME     NULL,
    [DependentDate]               DATETIME     NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    FOREIGN KEY ([TaskTemplateId]) REFERENCES [dbo].[MasterOrderTaskTemplate] ([Id]),
    FOREIGN KEY ([TaskTemplateId]) REFERENCES [dbo].[MasterOrderTaskTemplate] ([Id]),
    FOREIGN KEY ([TaskTemplateId]) REFERENCES [dbo].[MasterOrderTaskTemplate] ([Id]),
    FOREIGN KEY ([TaskTemplateId]) REFERENCES [dbo].[MasterOrderTaskTemplate] ([Id]),
    FOREIGN KEY ([TNAMasterId]) REFERENCES [dbo].[TNAMaster] ([Id]),
    FOREIGN KEY ([TNAMasterId]) REFERENCES [dbo].[TNAMaster] ([Id]),
    FOREIGN KEY ([TNAMasterId]) REFERENCES [dbo].[TNAMaster] ([Id]),
    FOREIGN KEY ([TNAMasterId]) REFERENCES [dbo].[TNAMaster] ([Id]),
    CONSTRAINT [FK__TNATasks__Employ__03DD2061] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK__TNATasks__Employ__1EFB2AF1] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK__TNATasks__Employ__2943AF3A] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK__TNATasks__Employ__5F6AB5C1] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId])
);

