CREATE TABLE [dbo].[VisitorEntry] (
    [SystemID]          VARCHAR (30)   NOT NULL,
    [VisitorID]         INT            DEFAULT ((0)) NOT NULL,
    [GroupID]           VARCHAR (10)   NOT NULL,
    [CompanyID]         VARCHAR (10)   NOT NULL,
    [PlantID]           VARCHAR (10)   NOT NULL,
    [VisCatSystemID]    VARCHAR (30)   NULL,
    [VisitorName]       VARCHAR (100)  NULL,
    [VisitorStatue]     VARCHAR (50)   CONSTRAINT [DF_VisitorEntry_EmployeeStatue] DEFAULT ('Active') NOT NULL,
    [RegisterFP]        BIT            DEFAULT ((0)) NOT NULL,
    [RegisterProximate] BIT            DEFAULT ((0)) NOT NULL,
    [CardNumber]        VARCHAR (50)   NULL,
    [LeftFPID]          VARCHAR (50)   NULL,
    [LeftFPTemplate]    NVARCHAR (MAX) NULL,
    [LeftFPImage]       IMAGE          NULL,
    [LeftAddedBy]       VARCHAR (100)  NULL,
    [LeftDateAdded]     DATETIME       NULL,
    [LeftUpdatedBy]     VARCHAR (100)  NULL,
    [LeftDateUpdated]   DATETIME       NULL,
    [RightFPID]         VARCHAR (50)   NULL,
    [RightFPTemplate]   NVARCHAR (MAX) NULL,
    [RightFPImage]      IMAGE          NULL,
    [RightAddedBy]      VARCHAR (100)  NULL,
    [RightDateAdded]    DATETIME       NULL,
    [RightUpdatedBy]    VARCHAR (100)  NULL,
    [RightDateUpdated]  DATETIME       NULL,
    [AddedBy]           VARCHAR (100)  NULL,
    [DateAdded]         DATETIME       NULL,
    [UpdatedBy]         VARCHAR (100)  NULL,
    [DateUpdated]       DATETIME       NULL,
    CONSTRAINT [PK_VisitorEntry] PRIMARY KEY CLUSTERED ([SystemID] ASC),
    CONSTRAINT [FK_VisitorEntry_Company] FOREIGN KEY ([CompanyID]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_VisitorEntry_GroupCreation] FOREIGN KEY ([GroupID]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_VisitorEntry_Plant] FOREIGN KEY ([PlantID]) REFERENCES [ORG].[Plant] ([Id])
);

