CREATE TABLE [SCS].[Country] (
    [Id]            VARCHAR (10)    NOT NULL,
    [ContinentId]   VARCHAR (10)    NOT NULL,
    [CurrencyId]    VARCHAR (10)    NOT NULL,
    [Sequence]      DECIMAL (18, 2) NOT NULL,
    [ICC]           VARCHAR (10)    NULL,
    [Code]          VARCHAR (15)    NOT NULL,
    [ShortName]     VARCHAR (15)    NOT NULL,
    [StandardName]  VARCHAR (50)    NOT NULL,
    [UserName]      VARCHAR (50)    NOT NULL,
    [Nationality]   VARCHAR (50)    CONSTRAINT [DF_Country_Nationality_1] DEFAULT ('BD') NOT NULL,
    [GMTMinute]     INT             CONSTRAINT [DF_Country_GMTMinute] DEFAULT ((0)) NOT NULL,
    [GMTHour]       INT             CONSTRAINT [DF_Country_GMTHour] DEFAULT ((0)) NOT NULL,
    [TINCaption]    VARCHAR (30)    NULL,
    [NIDCaption]    VARCHAR (30)    NULL,
    [PhoneLength]   INT             CONSTRAINT [DF_Country_PhoneLength_1] DEFAULT ((0)) NOT NULL,
    [NIDLength]     INT             CONSTRAINT [DF_Country_NIDLength] DEFAULT ((0)) NOT NULL,
    [TINLength]     INT             CONSTRAINT [DF_Country_TINLength] DEFAULT ((0)) NOT NULL,
    [Description]   VARCHAR (250)   NULL,
    [Remarks]       VARCHAR (250)   NULL,
    [Active]        BIT             NOT NULL,
    [Archive]       BIT             NOT NULL,
    [AddedBy]       VARCHAR (30)    NOT NULL,
    [AddedDate]     DATETIME        NOT NULL,
    [AddedFromIP]   VARCHAR (15)    NOT NULL,
    [UpdatedBy]     VARCHAR (30)    NULL,
    [UpdatedDate]   DATETIME        NULL,
    [UpdatedFromIP] VARCHAR (15)    NULL,
    CONSTRAINT [PK_Country] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Country_Continent] FOREIGN KEY ([ContinentId]) REFERENCES [SCS].[Continent] ([Id]),
    CONSTRAINT [FK_Country_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id])
);

