CREATE TABLE [SCS].[ExchangeGainLossGL] (
    [Id]                                 VARCHAR (10) NOT NULL,
    [COAId]                              VARCHAR (10) NOT NULL,
    [CompanyCurrencyGLId]                VARCHAR (10) NOT NULL,
    [CompanyCurrencyBudgetMasterId]      VARCHAR (20) NULL,
    [CompanyCurrencyActivityId]          VARCHAR (10) NULL,
    [CompanyGroupCurrencyGLId]           VARCHAR (10) NULL,
    [CompanyGroupCurrencyBudgetMasterId] VARCHAR (20) NULL,
    [CompanyGroupCurrencyActivityId]     VARCHAR (10) NULL,
    [HardCurrencyGLId]                   VARCHAR (10) NULL,
    [HardCurrencyBudgetMasterId]         VARCHAR (20) NULL,
    [HardCurrencyActivityId]             VARCHAR (10) NULL,
    [ExchangeStatus]                     VARCHAR (25) NOT NULL,
    [Active]                             BIT          NOT NULL,
    [AddedBy]                            VARCHAR (30) NOT NULL,
    [AddedDate]                          DATETIME     NOT NULL,
    [AddedFromIP]                        VARCHAR (15) NOT NULL,
    [UpdatedBy]                          VARCHAR (30) NULL,
    [UpdatedDate]                        DATETIME     NULL,
    [UpdatedFromIP]                      VARCHAR (15) NULL,
    [SourceType]                         VARCHAR (20) NULL,
    CONSTRAINT [PK_ExchangeGainLossGL] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ExchangeGainLossGL_COA] FOREIGN KEY ([COAId]) REFERENCES [HKP].[COA] ([Id]),
    CONSTRAINT [FK_ExchangeGainLossGL_CompanyCurrencyActivity] FOREIGN KEY ([CompanyCurrencyActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_ExchangeGainLossGL_CompanyCurrencyBudgetMaster] FOREIGN KEY ([CompanyCurrencyBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_ExchangeGainLossGL_CompanyCurrencyGL] FOREIGN KEY ([CompanyCurrencyGLId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_ExchangeGainLossGL_CompanyGroupCurrencyActivity] FOREIGN KEY ([CompanyGroupCurrencyActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_ExchangeGainLossGL_CompanyGroupCurrencyBudgetMaster] FOREIGN KEY ([CompanyGroupCurrencyBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_ExchangeGainLossGL_CompanyGroupCurrencyGL] FOREIGN KEY ([CompanyGroupCurrencyGLId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_ExchangeGainLossGL_HardCurrencyActivity] FOREIGN KEY ([HardCurrencyActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_ExchangeGainLossGL_HardCurrencyBudgetMaster] FOREIGN KEY ([HardCurrencyBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_ExchangeGainLossGL_HardCurrencyGL] FOREIGN KEY ([HardCurrencyGLId]) REFERENCES [HKP].[GLGeneralInfo] ([Id])
);

