CREATE TABLE [SCS].[LegalSalaryGrade] (
    [Id]                   VARCHAR (10)    NOT NULL,
    [CompanyGroupId]       VARCHAR (10)    NOT NULL,
    [CurrencyRuleMasterId] VARCHAR (30)    NOT NULL,
    [Sequence]             DECIMAL (18, 2) NOT NULL,
    [Code]                 VARCHAR (10)    NOT NULL,
    [ShortName]            VARCHAR (15)    NOT NULL,
    [StandardName]         VARCHAR (50)    NOT NULL,
    [UserName]             VARCHAR (50)    NOT NULL,
    [Description]          VARCHAR (250)   NULL,
    [Remarks]              VARCHAR (250)   NULL,
    [Active]               BIT             NOT NULL,
    [Archive]              BIT             CONSTRAINT [DF_LegalSalaryGrade_Archive] DEFAULT ((0)) NOT NULL,
    [AddedBy]              VARCHAR (30)    NOT NULL,
    [AddedDate]            DATETIME        NOT NULL,
    [AddedFromIP]          VARCHAR (15)    NOT NULL,
    [UpdatedBy]            VARCHAR (30)    NULL,
    [UpdatedDate]          DATETIME        NULL,
    [UpdatedFromIP]        VARCHAR (15)    NULL,
    [PlantId]              VARCHAR (10)    NULL,
    CONSTRAINT [PK_LegalSalaryGrade] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_LegalSalaryGrade_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_LegalSalaryGrade_CurrencyRuleMaster] FOREIGN KEY ([CurrencyRuleMasterId]) REFERENCES [dbo].[CurrencyRuleMaster] ([SystemID]),
    CONSTRAINT [FK_LegalSalaryGrade_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id])
);

