CREATE TABLE [SCS].[RecipeConfig] (
    [Id]                                      VARCHAR (10) NOT NULL,
    [CompanyGroupId]                          VARCHAR (10) NOT NULL,
    [CompanyId]                               VARCHAR (10) NOT NULL,
    [PlantId]                                 VARCHAR (10) NOT NULL,
    [ProcessId]                               VARCHAR (10) NULL,
    [OutputDependAttributeId]                 VARCHAR (10) NULL,
    [OutputDependCharacteristicsId]           VARCHAR (10) NULL,
    [OutputDependSubprocessId]                VARCHAR (10) NULL,
    [OutPutUoMId]                             VARCHAR (10) NULL,
    [OutputLevel]                             VARCHAR (2)  NOT NULL,
    [RawMaterialConsumptionAattributeId]      VARCHAR (10) NULL,
    [RawMaterialConsumptionCharacteristicsId] VARCHAR (10) NULL,
    [RmConsumptionUoMId]                      VARCHAR (10) NULL,
    [ConsumptionLevel]                        VARCHAR (2)  NOT NULL,
    [RecipeDependAttributeId]                 VARCHAR (10) NULL,
    [RecipeDependCharacteristicsId]           VARCHAR (10) NULL,
    [RecipeDependonSubprocessId]              VARCHAR (10) NULL,
    [RecipeLevel]                             VARCHAR (2)  NOT NULL,
    [AddedBy]                                 VARCHAR (30) NOT NULL,
    [AddedDate]                               DATETIME     NOT NULL,
    [AddedFromIP]                             VARCHAR (15) NOT NULL,
    [UpdatedBy]                               VARCHAR (30) NULL,
    [UpdatedDate]                             DATETIME     NULL,
    [UpdatedFromIP]                           VARCHAR (15) NULL,
    [SpecificationLevel1]                     VARCHAR (2)  NULL,
    [SpecificationLevel2]                     VARCHAR (2)  NULL,
    [SpecificationCharacteristicId1]          VARCHAR (10) NULL,
    [SpecificationCharacteristicId2]          VARCHAR (10) NULL,
    [SpecificationAttributeId1]               VARCHAR (10) NULL,
    [SpecificationAttributeId2]               VARCHAR (10) NULL,
    CONSTRAINT [PK_ButtonRecipeConfig] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ButtonConfig_OutputDependCharacteristics] FOREIGN KEY ([OutputDependCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_ButtonConfig_RawMaterialConsumptionCharacteristics] FOREIGN KEY ([RawMaterialConsumptionCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_ButtonConfig_RecipeDependCharacteristics] FOREIGN KEY ([RecipeDependCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_ButtonRecipeConfig_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_ButtonRecipeConfig_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_ButtonRecipeConfig_MaterialAttribute_OutputDependAttribute] FOREIGN KEY ([OutputDependAttributeId]) REFERENCES [HKP].[MaterialAttribute] ([Id]),
    CONSTRAINT [FK_ButtonRecipeConfig_MaterialAttribute_RawMaterialConsumptionAattribute] FOREIGN KEY ([RawMaterialConsumptionAattributeId]) REFERENCES [HKP].[MaterialAttribute] ([Id]),
    CONSTRAINT [FK_ButtonRecipeConfig_MaterialAttribute_RecipeDependAttribute] FOREIGN KEY ([RecipeDependAttributeId]) REFERENCES [HKP].[MaterialAttribute] ([Id]),
    CONSTRAINT [FK_ButtonRecipeConfig_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_ButtonRecipeConfig_Process] FOREIGN KEY ([ProcessId]) REFERENCES [HKP].[Process] ([Id]),
    CONSTRAINT [FK_ButtonRecipeConfig_SubProcess_OutputDependSubprocess] FOREIGN KEY ([OutputDependSubprocessId]) REFERENCES [HKP].[SubProcess] ([Id]),
    CONSTRAINT [FK_ButtonRecipeConfig_SubProcess_RecipeDependonSubprocess] FOREIGN KEY ([RecipeDependonSubprocessId]) REFERENCES [HKP].[SubProcess] ([Id]),
    CONSTRAINT [FK_ButtonRecipeConfig_UnitOfMeasurement_OutPutUoM] FOREIGN KEY ([OutPutUoMId]) REFERENCES [SCS].[UnitOfMeasurement] ([Id]),
    CONSTRAINT [FK_ButtonRecipeConfig_UnitOfMeasurement_RmConsumptionUoM] FOREIGN KEY ([RmConsumptionUoMId]) REFERENCES [SCS].[UnitOfMeasurement] ([Id])
);

