CREATE TABLE [SCS].[SalaryFixation] (
    [Id]                       VARCHAR (10)  NOT NULL,
    [PreRecruitmentEmployeeID] VARCHAR (10)  NULL,
    [SalaryRuleID]             VARCHAR (30)  NULL,
    [SalaryHeadID]             VARCHAR (30)  NULL,
    [LeaveTypeID]              VARCHAR (10)  NULL,
    [AnnualNonCashId]          VARCHAR (10)  NULL,
    [IsMonthly]                BIT           NOT NULL,
    [IsAnnualCash]             BIT           NOT NULL,
    [IsAnnualNonCash]          BIT           NOT NULL,
    [IsLeave]                  BIT           NOT NULL,
    [CurrentStatus]            BIT           CONSTRAINT [DF_SalaryFixation_CurrentStatus] DEFAULT ((0)) NOT NULL,
    [ExpectedStatus]           BIT           CONSTRAINT [DF_SalaryFixation_ExpectedStatus] DEFAULT ((0)) NOT NULL,
    [FixationStatus]           BIT           CONSTRAINT [DF_SalaryFixation_FixationStatus] DEFAULT ((0)) NOT NULL,
    [ExpectedAmount]           DECIMAL (18)  CONSTRAINT [DF_SalaryFixation_ExpectedAmount] DEFAULT ((0)) NOT NULL,
    [CurrentAmount]            DECIMAL (18)  CONSTRAINT [DF_SalaryFixation_CurrentAmount] DEFAULT ((0)) NOT NULL,
    [FixationAmount]           DECIMAL (18)  NOT NULL,
    [IsCalculated]             BIT           CONSTRAINT [DF_SalaryFixation_IsCalculated] DEFAULT ((0)) NOT NULL,
    [PlantId]                  VARCHAR (10)  NULL,
    [CompanyGroupID]           VARCHAR (10)  NULL,
    [AddedBy]                  VARCHAR (100) NOT NULL,
    [AddedDate]                DATETIME      NOT NULL,
    [AddedFromIP]              VARCHAR (15)  NULL,
    [UpdatedBy]                VARCHAR (100) NULL,
    [UpdatedDate]              DATETIME      NULL,
    [UpdatedFromIP]            VARCHAR (15)  NULL,
    CONSTRAINT [PK__SalaryFixation] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_SalaryFixation_AnnualNonCashId] FOREIGN KEY ([AnnualNonCashId]) REFERENCES [SCS].[AnnualNonCash] ([Id]),
    CONSTRAINT [FK_SalaryFixation_CompanyGroupID] FOREIGN KEY ([CompanyGroupID]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_SalaryFixation_LeaveTypeID] FOREIGN KEY ([LeaveTypeID]) REFERENCES [dbo].[LeaveType] ([Id]),
    CONSTRAINT [FK_SalaryFixation_PlantId] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_SalaryFixation_PreRecruitmentEmployeeID] FOREIGN KEY ([PreRecruitmentEmployeeID]) REFERENCES [dbo].[PreRecruitmentEmployee] ([Id]),
    CONSTRAINT [FK_SalaryFixation_SalaryHeadID] FOREIGN KEY ([SalaryHeadID]) REFERENCES [dbo].[SalaryHead] ([SalaryHeadID]),
    CONSTRAINT [FK_SalaryFixation_SalaryRuleID] FOREIGN KEY ([SalaryRuleID]) REFERENCES [dbo].[SalaryRuleMaster] ([SystemID])
);

