CREATE TABLE [SCS].[SkillGrouping] (
    [Id]                  VARCHAR (10)    NOT NULL,
    [CompanyGroupId]      VARCHAR (10)    NOT NULL,
    [Sequence]            DECIMAL (18, 2) NOT NULL,
    [Code]                VARCHAR (10)    NOT NULL,
    [ShortName]           VARCHAR (15)    NOT NULL,
    [StandardName]        VARCHAR (50)    NOT NULL,
    [UserName]            VARCHAR (50)    NOT NULL,
    [Description]         VARCHAR (250)   NULL,
    [Remarks]             VARCHAR (250)   NULL,
    [LegalSalaryGradeId]  VARCHAR (10)    NOT NULL,
    [Grouping]            VARCHAR (50)    NOT NULL,
    [DesignationCategory] VARCHAR (50)    NOT NULL,
    [StandardSalary]      NUMERIC (18, 4) NOT NULL,
    [Active]              BIT             CONSTRAINT [DF_SkillGrouping_Active] DEFAULT ('false') NOT NULL,
    [AddedBy]             VARCHAR (30)    NOT NULL,
    [AddedDate]           DATETIME        NOT NULL,
    [AddedFromIP]         VARCHAR (15)    NOT NULL,
    [UpdatedBy]           VARCHAR (30)    NULL,
    [UpdatedDate]         DATETIME        NULL,
    [UpdatedFromIP]       VARCHAR (15)    NULL,
    CONSTRAINT [PK_SkillGrouping] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_SkillGrouping_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_SkillGrouping_LegalSalaryGrade] FOREIGN KEY ([LegalSalaryGradeId]) REFERENCES [SCS].[LegalSalaryGrade] ([Id])
);

