CREATE TABLE [SCS].[WorkCenterMaster] (
    [Id]                       VARCHAR (30)    NOT NULL,
    [CompanyId]                VARCHAR (10)    NOT NULL,
    [PlantId]                  VARCHAR (10)    NOT NULL,
    [EntityId]                 VARCHAR (10)    NULL,
    [WorkCenterCategoryId]     VARCHAR (10)    NULL,
    [WorkCenterSubcategoryId]  VARCHAR (10)    NULL,
    [ProcessId]                VARCHAR (10)    NULL,
    [Code]                     VARCHAR (10)    NULL,
    [UserName]                 VARCHAR (50)    NULL,
    [StandardName]             VARCHAR (50)    NULL,
    [Description]              VARCHAR (100)   NULL,
    [CapacityProcessUoMId]     VARCHAR (10)    NOT NULL,
    [UoMId]                    VARCHAR (10)    NOT NULL,
    [LineId]                   VARCHAR (10)    NULL,
    [Capacity]                 DECIMAL (18, 3) NULL,
    [PlanEfficiency]           INT             NOT NULL,
    [MaxTimePerDay]            INT             NOT NULL,
    [StandardTimePerDay]       INT             NOT NULL,
    [PlanBudgetCapacityPerDay] DECIMAL (18, 2) NOT NULL,
    [DailyFixedCost]           DECIMAL (18, 2) NOT NULL,
    [VariableCost]             DECIMAL (18, 2) NOT NULL,
    [CurrencyId]               VARCHAR (10)    NOT NULL,
    [AddedBy]                  VARCHAR (30)    NOT NULL,
    [AddedDate]                DATETIME        NOT NULL,
    [AddedFromIP]              VARCHAR (15)    NOT NULL,
    [UpdatedBy]                VARCHAR (30)    NULL,
    [UpdatedDate]              DATETIME        NULL,
    [UpdatedFromIP]            VARCHAR (15)    NULL,
    [SPT]                      DECIMAL (18, 2) CONSTRAINT [DF__WorkCenterM__SPT__34DEB3C1] DEFAULT ((0)) NOT NULL,
    [CM]                       DECIMAL (18, 2) CONSTRAINT [DF__WorkCenterMa__CM__35D2D7FA] DEFAULT ((0)) NOT NULL,
    [NoOfWorkStation]          INT             CONSTRAINT [DF__WorkCente__NoOfW__36C6FC33] DEFAULT ((0)) NOT NULL,
    [MonthlyNoOfDays]          INT             CONSTRAINT [DF__WorkCente__Month__37BB206C] DEFAULT ((0)) NOT NULL,
    [ResponsiblePersonId]      VARCHAR (30)    NULL,
    [MentorId]                 VARCHAR (30)    NULL,
    [BuyerId]                  VARCHAR (10)    NULL,
    [Sequence]                 DECIMAL (18, 2) CONSTRAINT [DF__WorkCente__Seque__08EBEE41] DEFAULT ((0)) NOT NULL,
    [AccountHolder]            VARCHAR (30)    NULL,
    [AccountInCharge]          VARCHAR (30)    NULL,
    [GroupingData]             VARCHAR (20)    NULL,
    CONSTRAINT [PK_WorkCenterMaster] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_WorkCenterMaster_AccountHolder] FOREIGN KEY ([AccountHolder]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_WorkCenterMaster_AccountInCharge] FOREIGN KEY ([AccountInCharge]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_WorkCenterMaster_Buyer] FOREIGN KEY ([BuyerId]) REFERENCES [HKP].[Buyer] ([Id]),
    CONSTRAINT [FK_WorkCenterMaster_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_WorkCenterMaster_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_WorkCenterMaster_Entity] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_WorkCenterMaster_Line] FOREIGN KEY ([LineId]) REFERENCES [ORG].[Line] ([Id]),
    CONSTRAINT [FK_WorkCenterMaster_Mentor_EmployeeInformation] FOREIGN KEY ([MentorId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_WorkCenterMaster_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_WorkCenterMaster_Process] FOREIGN KEY ([ProcessId]) REFERENCES [HKP].[Process] ([Id]),
    CONSTRAINT [FK_WorkCenterMaster_ProcessUoM] FOREIGN KEY ([CapacityProcessUoMId]) REFERENCES [SCS].[ProcessUoM] ([Id]),
    CONSTRAINT [FK_WorkCenterMaster_ResponsiblePerson_EmployeeInformation] FOREIGN KEY ([ResponsiblePersonId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_WorkCenterMaster_UoM] FOREIGN KEY ([UoMId]) REFERENCES [SCS].[UnitOfMeasurement] ([Id]),
    CONSTRAINT [FK_WorkCenterMaster_WorkCenterCategory] FOREIGN KEY ([WorkCenterCategoryId]) REFERENCES [HKP].[WorkCenterCategory] ([Id]),
    CONSTRAINT [FK_WorkCenterMaster_WorkCenterSubCategory] FOREIGN KEY ([WorkCenterSubcategoryId]) REFERENCES [HKP].[WorkCenterSubCategory] ([Id])
);

