CREATE TABLE [ORG].[CompanyGroup] (
    [Id]                       VARCHAR (10)    NOT NULL,
    [AddressMasterId]          VARCHAR (20)    NULL,
    [ContactMasterId]          VARCHAR (20)    NULL,
    [ConsolidateCurrencyId]    VARCHAR (10)    NOT NULL,
    [Sequence]                 DECIMAL (18, 2) NOT NULL,
    [Code]                     VARCHAR (15)    NOT NULL,
    [ShortName]                VARCHAR (15)    NOT NULL,
    [StandardName]             VARCHAR (30)    NOT NULL,
    [UserName]                 VARCHAR (50)    NOT NULL,
    [LegalName]                VARCHAR (50)    NOT NULL,
    [Description]              VARCHAR (250)   NULL,
    [Remarks]                  VARCHAR (250)   NULL,
    [PKPrefixField]            CHAR (2)        NOT NULL,
    [Image]                    VARCHAR (40)    NULL,
    [IsUserAccessFromEmployee] BIT             NOT NULL,
    [Active]                   BIT             NOT NULL,
    [Archive]                  BIT             CONSTRAINT [DF_CompanyGroup_ARCHIVE] DEFAULT ((0)) NOT NULL,
    [AddedBy]                  VARCHAR (30)    NOT NULL,
    [AddedDate]                DATETIME        NOT NULL,
    [AddedFromIP]              VARCHAR (15)    NOT NULL,
    [UpdatedBy]                VARCHAR (30)    NULL,
    [UpdatedDate]              DATETIME        NULL,
    [UpdatedFromIP]            VARCHAR (15)    NULL,
    [LanguageId]               VARCHAR (5)     NULL,
    [AplosId]                  VARCHAR (30)    NULL,
    [ApopURL]                  VARCHAR (350)   NULL,
    [MyAppURL]                 VARCHAR (350)   NULL,
    CONSTRAINT [PK_CompanyGroup] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_CompanyGroup_AddressMaster] FOREIGN KEY ([AddressMasterId]) REFERENCES [MST].[AddressMaster] ([Id]),
    CONSTRAINT [FK_CompanyGroup_ContactMaster] FOREIGN KEY ([ContactMasterId]) REFERENCES [MST].[ContactMaster] ([Id]),
    CONSTRAINT [FK_CompanyGroup_Currency] FOREIGN KEY ([ConsolidateCurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_CompanyGroup_Language] FOREIGN KEY ([LanguageId]) REFERENCES [SCS].[Language] ([Id])
);

