CREATE TABLE [ORG].[Company] (
    [Id]                          VARCHAR (10)    NOT NULL,
    [AddressMasterId]             VARCHAR (20)    NULL,
    [ContactMasterId]             VARCHAR (20)    NULL,
    [CompanyGroupId]              VARCHAR (10)    NOT NULL,
    [OrganizationCategoryId]      VARCHAR (10)    NULL,
    [OrganizationClassId]         VARCHAR (10)    NULL,
    [BaseCurrencyId]              VARCHAR (10)    NOT NULL,
    [COAId]                       VARCHAR (10)    NULL,
    [AlternativeCOAId]            VARCHAR (10)    NULL,
    [EntityType]                  VARCHAR (20)    NOT NULL,
    [Sequence]                    DECIMAL (18, 2) NOT NULL,
    [Code]                        VARCHAR (15)    NOT NULL,
    [ShortName]                   VARCHAR (20)    NOT NULL,
    [StandardName]                VARCHAR (50)    NOT NULL,
    [LegalName]                   VARCHAR (50)    NOT NULL,
    [UserName]                    VARCHAR (50)    NOT NULL,
    [TINNo]                       VARCHAR (20)    NULL,
    [VATResistrationNo]           VARCHAR (20)    NULL,
    [BINNo]                       VARCHAR (25)    NULL,
    [FYSDate]                     DATETIME        NULL,
    [LPSDate]                     DATETIME        NULL,
    [PPSDate]                     DATETIME        NULL,
    [EstedDate]                   DATETIME        NULL,
    [PKPrefixField]               CHAR (2)        NULL,
    [Image]                       VARCHAR (40)    NULL,
    [WebDomain]                   VARCHAR (100)   NULL,
    [ManagementGroup]             VARCHAR (50)    NULL,
    [Description]                 VARCHAR (250)   NULL,
    [Remarks]                     VARCHAR (250)   NULL,
    [IsBuyingSellingApplicable]   BIT             NOT NULL,
    [IsCostCenterApplicable]      BIT             NOT NULL,
    [IsProfitCenterApplicable]    BIT             NOT NULL,
    [IsVoucherFromBudget]         BIT             NOT NULL,
    [IsBudgetPeriod]              BIT             NOT NULL,
    [IsQualificationDoc]          BIT             NOT NULL,
    [IsTrainingDoc]               BIT             NOT NULL,
    [IsExperienceDoc]             BIT             NOT NULL,
    [IsTINRequiredForSalaryAbove] BIT             CONSTRAINT [DF__Company__IsTINRe__7E62A77F] DEFAULT ((0)) NOT NULL,
    [TINRequiredForSalaryAbove]   INT             CONSTRAINT [DF__Company__TINRequ__7D6E8346] DEFAULT ((0)) NOT NULL,
    [Active]                      BIT             NOT NULL,
    [Archive]                     BIT             CONSTRAINT [DF_Company_ARCHIVE] DEFAULT ((0)) NOT NULL,
    [AddedBy]                     VARCHAR (30)    NOT NULL,
    [AddedDate]                   DATETIME        NOT NULL,
    [AddedFromIP]                 VARCHAR (15)    NOT NULL,
    [UpdatedBy]                   VARCHAR (30)    NULL,
    [UpdatedDate]                 DATETIME        NULL,
    [UpdatedFromIP]               VARCHAR (15)    NULL,
    [IsAccountModuleRunning]      BIT             NULL,
    [IsInventorySalesBook]        BIT             DEFAULT ((0)) NULL,
    [IsFixedAssetSalesBook]       BIT             NULL,
    CONSTRAINT [PK_Company] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Company_AddressMaster] FOREIGN KEY ([AddressMasterId]) REFERENCES [MST].[AddressMaster] ([Id]),
    CONSTRAINT [FK_Company_AlternativeCOA] FOREIGN KEY ([AlternativeCOAId]) REFERENCES [HKP].[AlternativeCOA] ([Id]),
    CONSTRAINT [FK_Company_COA] FOREIGN KEY ([COAId]) REFERENCES [HKP].[COA] ([Id]),
    CONSTRAINT [FK_Company_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_Company_ContactMaster] FOREIGN KEY ([ContactMasterId]) REFERENCES [MST].[ContactMaster] ([Id]),
    CONSTRAINT [FK_Company_Currency] FOREIGN KEY ([BaseCurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_Company_OrganizationCategory] FOREIGN KEY ([OrganizationCategoryId]) REFERENCES [ORG].[OrganizationCategory] ([Id]),
    CONSTRAINT [FK_Company_OrganizationClass] FOREIGN KEY ([OrganizationClassId]) REFERENCES [ORG].[OrganizationClass] ([Id])
);

