CREATE TABLE [ORG].[Entity] (
    [Id]                     VARCHAR (10)  NOT NULL,
    [CompanyGroupId]         VARCHAR (10)  NULL,
    [CompanyId]              VARCHAR (10)  NOT NULL,
    [PlantId]                VARCHAR (10)  NULL,
    [DivisionId]             VARCHAR (10)  NULL,
    [SubDivisionId]          VARCHAR (10)  NULL,
    [DepartmentId]           VARCHAR (10)  NULL,
    [SectionId]              VARCHAR (10)  NULL,
    [SubSectionId]           VARCHAR (10)  NULL,
    [LineId]                 VARCHAR (10)  NULL,
    [UnitId]                 VARCHAR (10)  NULL,
    [EmployeeGroupId]        VARCHAR (10)  NULL,
    [ShiftDefinationId]      VARCHAR (30)  NULL,
    [EmployeeId]             VARCHAR (30)  NULL,
    [EntityType]             VARCHAR (20)  NOT NULL,
    [UserName]               VARCHAR (30)  NOT NULL,
    [Code]                   VARCHAR (20)  NULL,
    [OldRefCode]             VARCHAR (10)  NULL,
    [EffectiveDate]          DATETIME      NULL,
    [EffectiveDateUpTo]      DATETIME      NULL,
    [Description]            VARCHAR (250) NULL,
    [Remarks]                VARCHAR (250) NULL,
    [FilePrefix]             VARCHAR (10)  NULL,
    [IsExceptionForPlanning] BIT           NOT NULL,
    [IsProduction]           BIT           NOT NULL,
    [Active]                 BIT           NOT NULL,
    [Archive]                BIT           NOT NULL,
    [AddedBy]                VARCHAR (30)  NOT NULL,
    [AddedDate]              DATETIME      NOT NULL,
    [AddedFromIP]            VARCHAR (15)  NOT NULL,
    [UpdatedBy]              VARCHAR (30)  NULL,
    [UpdatedDate]            DATETIME      NULL,
    [UpdatedFromIP]          VARCHAR (15)  NULL,
    CONSTRAINT [PK_Entity] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Entity_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_Entity_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_Entity_Department] FOREIGN KEY ([DepartmentId]) REFERENCES [ORG].[Department] ([Id]),
    CONSTRAINT [FK_Entity_Division] FOREIGN KEY ([DivisionId]) REFERENCES [ORG].[Division] ([Id]),
    CONSTRAINT [FK_Entity_Employee] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_Entity_EmployeeGroup] FOREIGN KEY ([EmployeeGroupId]) REFERENCES [HKP].[EmployeeGroup] ([Id]),
    CONSTRAINT [FK_Entity_Line] FOREIGN KEY ([LineId]) REFERENCES [ORG].[Line] ([Id]),
    CONSTRAINT [FK_Entity_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_Entity_Section] FOREIGN KEY ([SectionId]) REFERENCES [ORG].[Section] ([Id]),
    CONSTRAINT [FK_Entity_ShiftDefination] FOREIGN KEY ([ShiftDefinationId]) REFERENCES [dbo].[ShiftDefination] ([SystemID]),
    CONSTRAINT [FK_Entity_SubDivision] FOREIGN KEY ([SubDivisionId]) REFERENCES [ORG].[SubDivision] ([Id]),
    CONSTRAINT [FK_Entity_SubSection] FOREIGN KEY ([SubSectionId]) REFERENCES [ORG].[SubSection] ([Id]),
    CONSTRAINT [FK_Entity_Unit] FOREIGN KEY ([UnitId]) REFERENCES [ORG].[Unit] ([Id])
);

