CREATE TABLE [ORG].[Plant] (
    [Id]                VARCHAR (10)    NOT NULL,
    [CompanyGroupId]    VARCHAR (10)    NOT NULL,
    [CompanyId]         VARCHAR (10)    NOT NULL,
    [LanguageId]        VARCHAR (5)     NULL,
    [AddressMasterId]   VARCHAR (20)    NULL,
    [Sequence]          DECIMAL (18, 2) NOT NULL,
    [Code]              VARCHAR (10)    NOT NULL,
    [ShortName]         VARCHAR (15)    NOT NULL,
    [StandardName]      VARCHAR (50)    NOT NULL,
    [UserName]          VARCHAR (50)    NOT NULL,
    [VATResistrationNo] VARCHAR (20)    NULL,
    [GSTIN]             VARCHAR (20)    NULL,
    [Description]       VARCHAR (250)   NULL,
    [Remarks]           VARCHAR (250)   NULL,
    [FilePrefix]        VARCHAR (3)     NULL,
    [Active]            BIT             NOT NULL,
    [Archive]           BIT             CONSTRAINT [DF_Plant_ARCHIVE] DEFAULT ((0)) NOT NULL,
    [AddedBy]           VARCHAR (30)    NOT NULL,
    [AddedDate]         DATETIME        NOT NULL,
    [AddedFromIP]       VARCHAR (15)    NOT NULL,
    [UpdatedBy]         VARCHAR (30)    NULL,
    [UpdatedDate]       DATETIME        NULL,
    [UpdatedFromIP]     VARCHAR (15)    NULL,
    [IsShowFCInWord]    BIT             NOT NULL,
    CONSTRAINT [PK_Plant] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Plant_AddressMaster] FOREIGN KEY ([AddressMasterId]) REFERENCES [MST].[AddressMaster] ([Id]),
    CONSTRAINT [FK_Plant_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_Plant_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_Plant_Language] FOREIGN KEY ([LanguageId]) REFERENCES [SCS].[Language] ([Id])
);

