CREATE TABLE [ORG].[SalesOrganisation] (
    [Id]                VARCHAR (10)    NOT NULL,
    [CompanyGroupId]    VARCHAR (10)    NOT NULL,
    [AddressMasterId]   VARCHAR (20)    NULL,
    [Sequence]          DECIMAL (18, 2) NOT NULL,
    [Code]              VARCHAR (10)    NOT NULL,
    [ShortName]         VARCHAR (15)    NOT NULL,
    [StandardName]      VARCHAR (50)    NOT NULL,
    [UserName]          VARCHAR (50)    NOT NULL,
    [VATResistrationNo] VARCHAR (20)    NULL,
    [Description]       VARCHAR (250)   NULL,
    [Remarks]           VARCHAR (250)   NULL,
    [Active]            BIT             NOT NULL,
    [Archive]           BIT             NOT NULL,
    [AddedBy]           VARCHAR (30)    NOT NULL,
    [AddedDate]         DATETIME        NOT NULL,
    [AddedFromIP]       VARCHAR (15)    NOT NULL,
    [UpdatedBy]         VARCHAR (30)    NULL,
    [UpdatedDate]       DATETIME        NULL,
    [UpdatedFromIP]     VARCHAR (15)    NULL,
    CONSTRAINT [PK_SalesOrganisation] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_SalesOrganisation_AddressMaster] FOREIGN KEY ([AddressMasterId]) REFERENCES [MST].[AddressMaster] ([Id]),
    CONSTRAINT [FK_SalesOrganisation_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id])
);

