CREATE TYPE [MMS].[MenuDetail_BulkType] AS TABLE (
    [Id]                         VARCHAR (40)    NOT NULL,
    [MenuId]                     VARCHAR (10)    NULL,
    [Sequence]                   DECIMAL (18, 2) NULL,
    [FieldCode]                  VARCHAR (50)    NULL,
    [StandardCaption]            VARCHAR (100)   NULL,
    [UserCaption]                VARCHAR (100)   NULL,
    [Mandatory]                  BIT             NULL,
    [Applicable]                 BIT             NULL,
    [Description]                VARCHAR (250)   NULL,
    [Remarks]                    VARCHAR (250)   NULL,
    [Active]                     BIT             NULL,
    [Archive]                    BIT             NULL,
    [AddedBy]                    VARCHAR (30)    NULL,
    [AddedDate]                  DATETIME        NULL,
    [AddedFromIP]                VARCHAR (15)    NULL,
    [UpdatedBy]                  VARCHAR (30)    NULL,
    [UpdatedDate]                DATETIME        NULL,
    [UpdatedFromIP]              VARCHAR (15)    NULL,
    [sync_update_peer_timestamp] BIGINT          NULL,
    [sync_update_peer_key]       INT             NULL,
    [sync_create_peer_timestamp] BIGINT          NULL,
    [sync_create_peer_key]       INT             NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC));

