CREATE TABLE [ACS].[AccessLog] (
    [Id]                    VARCHAR (36)  NOT NULL,
    [CompanyGroupId]        VARCHAR (10)  NULL,
    [UserId]                VARCHAR (30)  NULL,
    [AccessTime]            DATETIME      NOT NULL,
    [AccessTimeWithCountry] VARCHAR (100) NULL,
    [WorkStationIP]         VARCHAR (15)  NULL,
    [WorkStationName]       VARCHAR (100) NULL,
    [OS]                    VARCHAR (30)  NULL,
    [Browser]               VARCHAR (30)  NULL,
    [Panel]                 VARCHAR (10)  NOT NULL,
    [Status]                BIT           NOT NULL,
    [Resistered]            BIT           NOT NULL,
    [CountryCode]           VARCHAR (10)  NULL,
    [CountryName]           VARCHAR (30)  NULL,
    [RegionCode]            VARCHAR (10)  NULL,
    [RegionName]            VARCHAR (30)  NULL,
    [City]                  VARCHAR (30)  NULL,
    [ZipCode]               VARCHAR (10)  NULL,
    [Latitude]              VARCHAR (30)  NULL,
    [Longitude]             VARCHAR (30)  NULL,
    [TimeZone]              VARCHAR (20)  NULL,
    [Gmtoffset]             VARCHAR (10)  NULL,
    [Dstoffset]             VARCHAR (10)  NULL,
    [DaylightName]          VARCHAR (30)  NULL,
    [DeviceType]            VARCHAR (20)  NULL,
    [UserAgent]             VARCHAR (400) NULL,
    [ScreenSize]            VARCHAR (50)  NULL,
    [IsCookieEnable]        BIT           NULL,
    [IsJavascriptEnable]    BIT           NULL,
    [EmployeeId]            VARCHAR (30)  NULL,
    CONSTRAINT [PK_AccessLog] PRIMARY KEY CLUSTERED ([Id] ASC)
);

