CREATE TABLE [ACS].[MailLog] (
    [Id]                     BIGINT        IDENTITY (1, 1) NOT NULL,
    [CompanyGroupId]         VARCHAR (10)  NULL,
    [CompanyId]              VARCHAR (10)  NULL,
    [PlantId]                VARCHAR (10)  NULL,
    [MailReceiverId]         VARCHAR (10)  NULL,
    [UserId]                 VARCHAR (10)  NULL,
    [MailGenerator]          VARCHAR (40)  NOT NULL,
    [SenderEmail]            VARCHAR (40)  NULL,
    [SenderName]             VARCHAR (50)  NULL,
    [Subject]                VARCHAR (50)  NULL,
    [ServiceName]            VARCHAR (50)  NULL,
    [AttachmentName]         VARCHAR (200) NULL,
    [RecordTime]             DATETIME      NOT NULL,
    [AppVersion]             VARCHAR (20)  NOT NULL,
    [IsSuccess]              BIT           NOT NULL,
    [IsServiceActive]        BIT           NULL,
    [IsReciepientListActive] BIT           NULL,
    [HasAttachment]          BIT           NULL,
    [InactiveUsers]          VARCHAR (500) NULL,
    [MissingEMails]          VARCHAR (500) NULL,
    [ToAddressProblem]       VARCHAR (500) NULL,
    [ToList]                 VARCHAR (500) NULL,
    [CcList]                 VARCHAR (500) NULL,
    [BccList]                VARCHAR (500) NULL,
    [AddedBy]                VARCHAR (30)  NOT NULL,
    [AddedDate]              DATETIME      NOT NULL,
    [AddedFromIP]            VARCHAR (15)  NOT NULL,
    [Remarks]                VARCHAR (MAX) NULL,
    CONSTRAINT [PK_MailLog] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_MailLog_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_MailLog_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_MailLog_MailReceiver] FOREIGN KEY ([MailReceiverId]) REFERENCES [SCS].[MailReceiver] ([Id]),
    CONSTRAINT [FK_MailLog_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_MailLog_User] FOREIGN KEY ([UserId]) REFERENCES [SEC].[User] ([Id])
);

