CREATE TABLE [TRN].[AdditionalTax] (
    [Id]                             VARCHAR (50)     NOT NULL,
    [InvoiceId]                      VARCHAR (50)     NULL,
    [VoucherId]                      VARCHAR (50)     NULL,
    [InventoryReceiveId]             VARCHAR (10)     NULL,
    [SourceType]                     VARCHAR (30)     NULL,
    [TaxAutoAmount]                  DECIMAL (18, 10) NOT NULL,
    [TaxAmount]                      DECIMAL (18, 10) NOT NULL,
    [Archive]                        BIT              NOT NULL,
    [AddedBy]                        VARCHAR (30)     NOT NULL,
    [AddedDate]                      DATETIME         NOT NULL,
    [AddedFromIP]                    VARCHAR (15)     NOT NULL,
    [UpdatedBy]                      VARCHAR (30)     NULL,
    [UpdatedDate]                    DATETIME         NULL,
    [UpdatedFromIP]                  VARCHAR (15)     NULL,
    [WrittenOffAmount]               DECIMAL (18, 10) NOT NULL,
    [IsWrittenOff]                   BIT              NOT NULL,
    [PartyId]                        VARCHAR (10)     NULL,
    [TaxYearId]                      VARCHAR (10)     NOT NULL,
    [TaxYearPeriodId]                VARCHAR (10)     NOT NULL,
    [PartyPlantId]                   VARCHAR (12)     NULL,
    [EmployeePayableId]              VARCHAR (100)    NULL,
    [InvoiceWriteOffId]              VARCHAR (50)     NULL,
    [ServiceAcknowledgementMasterId] VARCHAR (30)     NULL,
    CONSTRAINT [PK_AdditionalTax] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_AdditionalTax_EmployeePayable] FOREIGN KEY ([EmployeePayableId]) REFERENCES [TRN].[EmployeePayable] ([Id]),
    CONSTRAINT [FK_AdditionalTax_InventoryReceive] FOREIGN KEY ([InventoryReceiveId]) REFERENCES [TRN].[InventoryReceive] ([Id]),
    CONSTRAINT [FK_AdditionalTax_Invoice] FOREIGN KEY ([InvoiceId]) REFERENCES [TRN].[Invoice] ([Id]),
    CONSTRAINT [FK_AdditionalTax_InvoiceWriteOff] FOREIGN KEY ([InvoiceWriteOffId]) REFERENCES [TRN].[InvoiceWriteOff] ([Id]),
    CONSTRAINT [FK_AdditionalTax_Party] FOREIGN KEY ([PartyId]) REFERENCES [HKP].[Party] ([Id]),
    CONSTRAINT [FK_AdditionalTax_PartyPlant] FOREIGN KEY ([PartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_AdditionalTax_ServiceAcknowledgementMasterId] FOREIGN KEY ([ServiceAcknowledgementMasterId]) REFERENCES [TRN].[ServiceAcknowledgementMaster] ([Id]),
    CONSTRAINT [FK_AdditionalTax_TaxYear] FOREIGN KEY ([TaxYearId]) REFERENCES [SCS].[TaxYear] ([Id]),
    CONSTRAINT [FK_AdditionalTax_TaxYearPeriod] FOREIGN KEY ([TaxYearPeriodId]) REFERENCES [SCS].[TaxYearPeriod] ([Id]),
    CONSTRAINT [FK_AdditionalTax_Voucher] FOREIGN KEY ([VoucherId]) REFERENCES [TRN].[Voucher] ([Id])
);

