CREATE TABLE [TRN].[AdjustmentNoteDetail] (
    [Id]                       VARCHAR (80)     NOT NULL,
    [AdjustmentNoteId]         VARCHAR (50)     NOT NULL,
    [InvoiceId]                VARCHAR (50)     NULL,
    [InvoiceDetailId]          VARCHAR (80)     NULL,
    [GLGeneralInfoId]          VARCHAR (10)     NOT NULL,
    [BudgetMasterId]           VARCHAR (20)     NULL,
    [ActivityId]               VARCHAR (10)     NULL,
    [Amount]                   DECIMAL (18, 4)  NOT NULL,
    [Archive]                  BIT              NOT NULL,
    [AddedBy]                  VARCHAR (30)     NOT NULL,
    [AddedDate]                DATETIME         NOT NULL,
    [AddedFromIP]              VARCHAR (15)     NOT NULL,
    [UpdatedBy]                VARCHAR (30)     NULL,
    [UpdatedDate]              DATETIME         NULL,
    [UpdatedFromIP]            VARCHAR (15)     NULL,
    [WrittenOffAmount]         DECIMAL (18, 10) NULL,
    [IsWrittenOff]             BIT              DEFAULT ((0)) NOT NULL,
    [InventoryReceiveId]       VARCHAR (10)     NULL,
    [InventoryReceiveDetailId] VARCHAR (50)     NULL,
    CONSTRAINT [PK_AdjustmentNoteDetail] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_AdjustmentNoteDetail_Activity] FOREIGN KEY ([ActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_AdjustmentNoteDetail_AdjustmentNote] FOREIGN KEY ([AdjustmentNoteId]) REFERENCES [TRN].[AdjustmentNote] ([Id]),
    CONSTRAINT [FK_AdjustmentNoteDetail_BudgetMaster] FOREIGN KEY ([BudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_AdjustmentNoteDetail_GLGeneralInfo] FOREIGN KEY ([GLGeneralInfoId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [Fk_AdjustmentNoteDetail_InventoryReceiveDetail] FOREIGN KEY ([InventoryReceiveDetailId]) REFERENCES [TRN].[InventoryReceiveDetail] ([Id]),
    CONSTRAINT [FK_AdjustmentNoteDetail_Invoice] FOREIGN KEY ([InvoiceId]) REFERENCES [TRN].[Invoice] ([Id]),
    CONSTRAINT [FK_AdjustmentNoteDetail_InvoiceDetail] FOREIGN KEY ([InvoiceDetailId]) REFERENCES [TRN].[InvoiceDetail] ([Id])
);

