CREATE TABLE [TRN].[AdjustmentNote] (
    [Id]                 VARCHAR (50)     NOT NULL,
    [CompanyGroupId]     VARCHAR (10)     NOT NULL,
    [CompanyId]          VARCHAR (10)     NOT NULL,
    [PlantId]            VARCHAR (10)     NOT NULL,
    [EntityId]           VARCHAR (10)     NULL,
    [VoucherId]          VARCHAR (50)     NULL,
    [NoteType]           VARCHAR (30)     NOT NULL,
    [SourceType]         VARCHAR (30)     NOT NULL,
    [PostingDate]        DATETIME         NOT NULL,
    [DocDate]            DATETIME         NOT NULL,
    [DocRefNo]           VARCHAR (50)     NOT NULL,
    [Narration]          VARCHAR (250)    NULL,
    [IsPark]             BIT              NOT NULL,
    [Archive]            BIT              NOT NULL,
    [AddedBy]            VARCHAR (30)     NOT NULL,
    [AddedDate]          DATETIME         NOT NULL,
    [AddedFromIP]        VARCHAR (15)     NOT NULL,
    [UpdatedBy]          VARCHAR (30)     NULL,
    [UpdatedDate]        DATETIME         NULL,
    [UpdatedFromIP]      VARCHAR (15)     NULL,
    [FiscalYearId]       VARCHAR (10)     NULL,
    [FiscalYearPeriodId] VARCHAR (10)     NULL,
    [TaxYearId]          VARCHAR (10)     NULL,
    [TaxYearPeriodId]    VARCHAR (10)     NULL,
    [VoucherTypeId]      VARCHAR (10)     NULL,
    [VoucherDate]        DATETIME         NOT NULL,
    [PartyType]          VARCHAR (10)     NOT NULL,
    [PartyId]            VARCHAR (10)     NULL,
    [PartyPlantId]       VARCHAR (12)     NULL,
    [CurrencyId]         VARCHAR (10)     NOT NULL,
    [Amount]             DECIMAL (18, 10) NOT NULL,
    [InvoiceId]          VARCHAR (50)     NULL,
    [SettlementType]     VARCHAR (30)     NULL,
    [WrittenOffAmount]   DECIMAL (18, 10) NULL,
    [IsWrittenOff]       BIT              DEFAULT ((0)) NOT NULL,
    [InventoryReceiveId] VARCHAR (10)     NULL,
    CONSTRAINT [PK_AdjustmentNote] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_AdjustmentNote_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_AdjustmentNote_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_AdjustmentNote_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_AdjustmentNote_Entity] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_AdjustmentNote_FiscalYear] FOREIGN KEY ([FiscalYearId]) REFERENCES [SCS].[FiscalYear] ([Id]),
    CONSTRAINT [FK_AdjustmentNote_FiscalYearPeriod] FOREIGN KEY ([FiscalYearPeriodId]) REFERENCES [SCS].[FiscalYearPeriod] ([Id]),
    CONSTRAINT [FK_AdjustmentNote_Invoice] FOREIGN KEY ([InvoiceId]) REFERENCES [TRN].[Invoice] ([Id]),
    CONSTRAINT [FK_AdjustmentNote_Party] FOREIGN KEY ([PartyId]) REFERENCES [HKP].[Party] ([Id]),
    CONSTRAINT [FK_AdjustmentNote_PartyPlant] FOREIGN KEY ([PartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_AdjustmentNote_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_AdjustmentNote_TaxYear] FOREIGN KEY ([TaxYearId]) REFERENCES [SCS].[TaxYear] ([Id]),
    CONSTRAINT [FK_AdjustmentNote_TaxYearPeriod] FOREIGN KEY ([TaxYearPeriodId]) REFERENCES [SCS].[TaxYearPeriod] ([Id]),
    CONSTRAINT [FK_AdjustmentNote_Voucher] FOREIGN KEY ([VoucherId]) REFERENCES [TRN].[Voucher] ([Id]),
    CONSTRAINT [FK_AdjustmentNote_VoucherType] FOREIGN KEY ([VoucherTypeId]) REFERENCES [SCS].[VoucherType] ([Id])
);

