CREATE TABLE [TRN].[AdvanceDetail] (
    [Id]               VARCHAR (100)    NOT NULL,
    [AdvanceId]        VARCHAR (10)     NOT NULL,
    [GLGeneralInfoId]  VARCHAR (10)     NOT NULL,
    [BudgetMasterId]   VARCHAR (20)     NULL,
    [ActivityId]       VARCHAR (10)     NULL,
    [Amount]           DECIMAL (18, 10) NOT NULL,
    [WrittenOffAmount] DECIMAL (18, 10) NOT NULL,
    [IsWrittenOff]     BIT              NOT NULL,
    [Archive]          BIT              NOT NULL,
    [AddedBy]          VARCHAR (30)     NOT NULL,
    [AddedDate]        DATETIME         NOT NULL,
    [AddedFromIP]      VARCHAR (15)     NOT NULL,
    [UpdatedBy]        VARCHAR (30)     NULL,
    [UpdatedDate]      DATETIME         NULL,
    [UpdatedFromIP]    VARCHAR (15)     NULL,
    [PartyId]          VARCHAR (10)     NULL,
    [PartyPlantId]     VARCHAR (12)     NULL,
    [Narration]        VARCHAR (250)    NOT NULL,
    [PartyType]        VARCHAR (10)     NULL,
    [TaxAmount]        DECIMAL (18, 10) NOT NULL,
    [NetAmount]        DECIMAL (18, 10) NOT NULL,
    [CompanyId]        VARCHAR (10)     NOT NULL,
    [PlantId]          VARCHAR (10)     NOT NULL,
    [RefId]            VARCHAR (12)     NULL,
    [EmployeeId]       VARCHAR (30)     NULL,
    [PaymentType]      VARCHAR (15)     NULL,
    CONSTRAINT [PK_AdvanceDetail] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_AdvanceDetail_Activity] FOREIGN KEY ([ActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_AdvanceDetail_Advance] FOREIGN KEY ([AdvanceId]) REFERENCES [TRN].[Advance] ([Id]),
    CONSTRAINT [FK_AdvanceDetail_BudgetMaster] FOREIGN KEY ([BudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_AdvanceDetail_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_AdvanceDetail_EmployeeInformation] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_AdvanceDetail_GLGeneralInfo] FOREIGN KEY ([GLGeneralInfoId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_AdvanceDetail_Party] FOREIGN KEY ([PartyId]) REFERENCES [HKP].[Party] ([Id]),
    CONSTRAINT [FK_AdvanceDetail_PartyPlant] FOREIGN KEY ([PartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_AdvanceDetail_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id])
);

