CREATE TABLE [TRN].[Advance] (
    [Id]                        VARCHAR (10)     NOT NULL,
    [CompanyGroupId]            VARCHAR (10)     NOT NULL,
    [CompanyId]                 VARCHAR (10)     NOT NULL,
    [PlantId]                   VARCHAR (10)     NOT NULL,
    [EntityId]                  VARCHAR (10)     NULL,
    [VoucherId]                 VARCHAR (50)     NOT NULL,
    [CurrencyId]                VARCHAR (10)     NOT NULL,
    [OpeningBalanceId]          VARCHAR (30)     NULL,
    [EmployeeTransactionTypeId] VARCHAR (10)     NULL,
    [ResponsiblePersonId]       VARCHAR (30)     NULL,
    [EmployeeId]                VARCHAR (30)     NULL,
    [PartyId]                   VARCHAR (10)     NULL,
    [PartyType]                 VARCHAR (10)     NULL,
    [SourceType]                VARCHAR (30)     NOT NULL,
    [PaymentSource]             VARCHAR (20)     NULL,
    [PostingDate]               DATETIME         NOT NULL,
    [DocDate]                   DATETIME         NOT NULL,
    [DocRefNo]                  VARCHAR (50)     NOT NULL,
    [ReviewDate]                DATETIME         NULL,
    [Narration]                 VARCHAR (250)    NOT NULL,
    [Amount]                    DECIMAL (18, 10) NOT NULL,
    [WrittenOffAmount]          DECIMAL (18, 10) NOT NULL,
    [IsWrittenOff]              BIT              NOT NULL,
    [IsPark]                    BIT              NOT NULL,
    [Archive]                   BIT              NOT NULL,
    [AddedBy]                   VARCHAR (30)     NOT NULL,
    [AddedDate]                 DATETIME         NOT NULL,
    [AddedFromIP]               VARCHAR (15)     NOT NULL,
    [UpdatedBy]                 VARCHAR (30)     NULL,
    [UpdatedDate]               DATETIME         NULL,
    [UpdatedFromIP]             VARCHAR (15)     NULL,
    [PartyPlantId]              VARCHAR (12)     NULL,
    [AdvanceNo]                 VARCHAR (30)     NULL,
    [FiscalYearId]              VARCHAR (10)     NULL,
    [FiscalYearPeriodId]        VARCHAR (10)     NULL,
    [TaxYearId]                 VARCHAR (10)     NULL,
    [TaxYearPeriodId]           VARCHAR (10)     NULL,
    [VoucherTypeId]             VARCHAR (10)     NOT NULL,
    [BankMasterId]              VARCHAR (10)     NULL,
    [CashMasterId]              VARCHAR (10)     NULL,
    [BankAmount]                DECIMAL (18, 10) NULL,
    [VoucherDate]               DATETIME         NOT NULL,
    [FinancingTypeId]           VARCHAR (10)     NULL,
    [IsInterTransaction]        BIT              NOT NULL,
    [JournalId]                 VARCHAR (10)     NULL,
    [IsPosted]                  BIT              NOT NULL,
    [JournalType]               VARCHAR (30)     NULL,
    [SettlementType]            VARCHAR (25)     NULL,
    [RequisitionId]             VARCHAR (10)     NULL,
    [CompanyCurrencyRate]       DECIMAL (18, 10) NULL,
    CONSTRAINT [PK_Advance] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Advance_BankMaster] FOREIGN KEY ([BankMasterId]) REFERENCES [MST].[BankMaster] ([Id]),
    CONSTRAINT [FK_Advance_CashMaster] FOREIGN KEY ([CashMasterId]) REFERENCES [MST].[CashMaster] ([Id]),
    CONSTRAINT [FK_Advance_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_Advance_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_Advance_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_Advance_EmployeeInformation] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_Advance_EmployeeInformation_ResponsiblePersonId] FOREIGN KEY ([ResponsiblePersonId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_Advance_EmployeeTransactionType] FOREIGN KEY ([EmployeeTransactionTypeId]) REFERENCES [HKP].[EmployeeTransactionType] ([Id]),
    CONSTRAINT [FK_Advance_Entity] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_Advance_FinancingType] FOREIGN KEY ([FinancingTypeId]) REFERENCES [HKP].[FinancingType] ([Id]),
    CONSTRAINT [FK_Advance_FiscalYear] FOREIGN KEY ([FiscalYearId]) REFERENCES [SCS].[FiscalYear] ([Id]),
    CONSTRAINT [FK_Advance_FiscalYearPeriod] FOREIGN KEY ([FiscalYearPeriodId]) REFERENCES [SCS].[FiscalYearPeriod] ([Id]),
    CONSTRAINT [FK_Advance_OpeningBalance] FOREIGN KEY ([OpeningBalanceId]) REFERENCES [TRN].[OpeningBalance] ([Id]),
    CONSTRAINT [FK_Advance_Party] FOREIGN KEY ([PartyId]) REFERENCES [HKP].[Party] ([Id]),
    CONSTRAINT [FK_Advance_PartyPlant] FOREIGN KEY ([PartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_Advance_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_Advance_Requisition] FOREIGN KEY ([RequisitionId]) REFERENCES [TRN].[EmployeeAdvanceRequisition] ([SystemId]),
    CONSTRAINT [FK_Advance_TaxYear] FOREIGN KEY ([TaxYearId]) REFERENCES [SCS].[TaxYear] ([Id]),
    CONSTRAINT [FK_Advance_TaxYearPeriod] FOREIGN KEY ([TaxYearPeriodId]) REFERENCES [SCS].[TaxYearPeriod] ([Id]),
    CONSTRAINT [FK_Advance_Voucher] FOREIGN KEY ([VoucherId]) REFERENCES [TRN].[Voucher] ([Id]),
    CONSTRAINT [FK_Advance_VoucherType] FOREIGN KEY ([VoucherTypeId]) REFERENCES [SCS].[VoucherType] ([Id])
);

