CREATE TABLE [TRN].[AdvanceWriteOffDetail] (
    [Id]                VARCHAR (100)    NOT NULL,
    [AdvanceId]         VARCHAR (10)     NOT NULL,
    [AdvanceDetailId]   VARCHAR (100)    NOT NULL,
    [AdvanceWriteOffId] VARCHAR (80)     NOT NULL,
    [GLGeneralInfoId]   VARCHAR (10)     NOT NULL,
    [BudgetMasterId]    VARCHAR (20)     NULL,
    [ActivityId]        VARCHAR (10)     NULL,
    [CurrencyId]        VARCHAR (10)     NOT NULL,
    [Amount]            DECIMAL (18, 10) NOT NULL,
    [Archive]           BIT              NOT NULL,
    [AddedBy]           VARCHAR (30)     NOT NULL,
    [AddedDate]         DATETIME         NOT NULL,
    [AddedFromIP]       VARCHAR (15)     NOT NULL,
    [UpdatedBy]         VARCHAR (30)     NULL,
    [UpdatedDate]       DATETIME         NULL,
    [UpdatedFromIP]     VARCHAR (15)     NULL,
    [PartyType]         VARCHAR (10)     NOT NULL,
    [CompanyId]         VARCHAR (10)     NOT NULL,
    [PlantId]           VARCHAR (10)     NOT NULL,
    [PartyId]           VARCHAR (10)     NULL,
    [PartyPlantId]      VARCHAR (12)     NULL,
    CONSTRAINT [PK_AdvanceWriteOffDetail] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_AdvanceWriteOffDetail_Activity] FOREIGN KEY ([ActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_AdvanceWriteOffDetail_Advance] FOREIGN KEY ([AdvanceId]) REFERENCES [TRN].[Advance] ([Id]),
    CONSTRAINT [FK_AdvanceWriteOffDetail_AdvanceDetail] FOREIGN KEY ([AdvanceDetailId]) REFERENCES [TRN].[AdvanceDetail] ([Id]),
    CONSTRAINT [FK_AdvanceWriteOffDetail_AdvanceWriteOff] FOREIGN KEY ([AdvanceWriteOffId]) REFERENCES [TRN].[AdvanceWriteOff] ([Id]),
    CONSTRAINT [FK_AdvanceWriteOffDetail_BudgetMaster] FOREIGN KEY ([BudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_AdvanceWriteOffDetail_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_AdvanceWriteOffDetail_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_AdvanceWriteOffDetail_GLGeneralInfo] FOREIGN KEY ([GLGeneralInfoId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_AdvanceWriteOffDetail_Party] FOREIGN KEY ([PartyId]) REFERENCES [HKP].[Party] ([Id]),
    CONSTRAINT [FK_AdvanceWriteOffDetail_PartyPlant] FOREIGN KEY ([PartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_AdvanceWriteOffDetail_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id])
);

