CREATE TABLE [TRN].[Commitment] (
    [Id]                VARCHAR (10)    NOT NULL,
    [EntityId]          VARCHAR (10)    NOT NULL,
    [BuyerDepartmentId] VARCHAR (10)    NULL,
    [BuyerDivisionId]   VARCHAR (10)    NULL,
    [BuyerBrandId]      VARCHAR (10)    NULL,
    [ProcessId]         VARCHAR (10)    NULL,
    [SubProcessId]      VARCHAR (10)    NULL,
    [CurrencyId]        VARCHAR (10)    NOT NULL,
    [FOB]               DECIMAL (18, 2) NOT NULL,
    [CM]                DECIMAL (18, 2) NOT NULL,
    [SPT]               DECIMAL (18, 2) NOT NULL,
    [Efficiency]        INT             NOT NULL,
    [Target]            INT             NOT NULL,
    [LSD]               DATE            NOT NULL,
    [AddedBy]           VARCHAR (30)    NOT NULL,
    [AddedDate]         DATETIME        NOT NULL,
    [AddedFromIP]       VARCHAR (15)    NOT NULL,
    [UpdatedBy]         VARCHAR (30)    NULL,
    [UpdatedDate]       DATETIME        NULL,
    [UpdatedFromIP]     VARCHAR (15)    NULL,
    [Buyer]             VARCHAR (50)    NULL,
    [SeasonId]          VARCHAR (10)    NULL,
    [BuyerProgramId]    VARCHAR (10)    NULL,
    [BuyerMasterId]     VARCHAR (10)    NOT NULL,
    [Year]              INT             NULL,
    [ClosingDate]       DATETIME        NOT NULL,
    [Remarks]           VARCHAR (250)   NULL,
    [ProductMasterId]   VARCHAR (10)    NULL,
    CONSTRAINT [PK_Commitment] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_BuyerMaster_BuyerMaster] FOREIGN KEY ([BuyerMasterId]) REFERENCES [MST].[BuyerMaster] ([Id]),
    CONSTRAINT [FK_Commitment_BuyerBrand] FOREIGN KEY ([BuyerBrandId]) REFERENCES [HKP].[BuyerBrand] ([Id]),
    CONSTRAINT [FK_Commitment_BuyerDepartment] FOREIGN KEY ([BuyerDepartmentId]) REFERENCES [HKP].[BuyerDepartment] ([Id]),
    CONSTRAINT [FK_Commitment_BuyerDivision] FOREIGN KEY ([BuyerDivisionId]) REFERENCES [HKP].[BuyerDivision] ([Id]),
    CONSTRAINT [FK_Commitment_BuyerProgram] FOREIGN KEY ([BuyerProgramId]) REFERENCES [HKP].[BuyerProgram] ([Id]),
    CONSTRAINT [FK_Commitment_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_Commitment_Entity] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_Commitment_Process] FOREIGN KEY ([ProcessId]) REFERENCES [HKP].[Process] ([Id]),
    CONSTRAINT [FK_Commitment_ProductMaster] FOREIGN KEY ([ProductMasterId]) REFERENCES [MST].[ProductMaster] ([Id]),
    CONSTRAINT [FK_Commitment_Season] FOREIGN KEY ([SeasonId]) REFERENCES [HKP].[Season] ([Id]),
    CONSTRAINT [FK_Commitment_SubProcess] FOREIGN KEY ([SubProcessId]) REFERENCES [HKP].[SubProcess] ([Id])
);

