CREATE TABLE [TRN].[DailyProductionTarget] (
    [ID]                              VARCHAR (30)    NOT NULL,
    [PlantID]                         VARCHAR (10)    NULL,
    [ProductionOrderId]               VARCHAR (30)    NULL,
    [ProductionOrderIdPlanning]       VARCHAR (30)    NULL,
    [MaterialMasterId]                VARCHAR (30)    NULL,
    [MaterialMasterIdPlanning]        VARCHAR (30)    NULL,
    [MaterialMasterArticleId]         VARCHAR (10)    NULL,
    [MaterialMasterArticleIdPlanning] VARCHAR (10)    NULL,
    [isBuildUp]                       BIT             NULL,
    [isBuildUpPlanning]               BIT             NULL,
    [WorkCenterMasterID]              VARCHAR (30)    NULL,
    [WorkCenterMasterIDPlanning]      VARCHAR (30)    NULL,
    [TargetDate]                      DATETIME        NULL,
    [Quantity]                        DECIMAL (18, 4) NULL,
    [QuantityPlanning]                DECIMAL (18, 4) NULL,
    [SMV]                             DECIMAL (18, 4) NULL,
    [SMVPlanning]                     DECIMAL (18, 4) NULL,
    [Manpower]                        DECIMAL (18, 4) NULL,
    [ManpowerPlanning]                DECIMAL (18, 4) NULL,
    [TotalHour]                       DECIMAL (18, 4) NULL,
    [TotalHourPlanning]               DECIMAL (18, 4) NULL,
    [TotalQuantityOnHundredPercent]   DECIMAL (18, 4) NULL,
    [TotalHourOnHundredPercent]       DECIMAL (18, 4) NULL,
    [AddedBy]                         VARCHAR (100)   NULL,
    [AddedDate]                       DATETIME        NULL,
    [UpdatedBy]                       VARCHAR (100)   NULL,
    [UpdatedDate]                     DATETIME        NULL,
    [SalesOrderMasterID]              VARCHAR (20)    NULL,
    [QuantityBulletin]                DECIMAL (18, 4) NULL,
    [SMVBulletin]                     DECIMAL (18, 4) NULL,
    [ManpowerBulletin]                DECIMAL (18, 4) NULL,
    [TotalHourBulletin]               DECIMAL (18, 4) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    FOREIGN KEY ([MaterialMasterArticleId]) REFERENCES [MST].[MaterialMasterArticle] ([Id]),
    FOREIGN KEY ([MaterialMasterArticleIdPlanning]) REFERENCES [MST].[MaterialMasterArticle] ([Id]),
    FOREIGN KEY ([MaterialMasterId]) REFERENCES [MST].[MaterialMaster] ([Id]),
    FOREIGN KEY ([MaterialMasterIdPlanning]) REFERENCES [MST].[MaterialMaster] ([Id]),
    FOREIGN KEY ([PlantID]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK__DailyProd__Produ__1F460F0B] FOREIGN KEY ([ProductionOrderId]) REFERENCES [TRN].[ProductionOrder] ([Id]),
    CONSTRAINT [FK__DailyProd__Produ__203A3344] FOREIGN KEY ([ProductionOrderIdPlanning]) REFERENCES [TRN].[ProductionOrder] ([Id]),
    CONSTRAINT [FK__DailyProd__WorkC__24FEE861] FOREIGN KEY ([WorkCenterMasterID]) REFERENCES [SCS].[WorkCenterMaster] ([Id]),
    CONSTRAINT [FK__DailyProd__WorkC__25F30C9A] FOREIGN KEY ([WorkCenterMasterIDPlanning]) REFERENCES [SCS].[WorkCenterMaster] ([Id])
);

