CREATE TABLE [TRN].[DailyProduction] (
    [ID]                          VARCHAR (30)    NOT NULL,
    [PlantID]                     VARCHAR (10)    NULL,
    [EntityId]                    VARCHAR (10)    NULL,
    [ShiftId]                     VARCHAR (10)    NULL,
    [ProcessID]                   VARCHAR (10)    NULL,
    [WorkCenterMasterID]          VARCHAR (30)    NULL,
    [SalesOrderMasterID]          VARCHAR (20)    NULL,
    [ProductionOrderId]           VARCHAR (30)    NULL,
    [OperationVariationId]        VARCHAR (10)    NULL,
    [EmployeeInformationSystemID] VARCHAR (30)    NULL,
    [ResponsiblePersonID]         VARCHAR (30)    NULL,
    [ProductionBookingPeriodId]   VARCHAR (10)    NULL,
    [ProductionDate]              DATETIME        NULL,
    [Quantity]                    DECIMAL (18, 4) NULL,
    [RefNo]                       VARCHAR (30)    NULL,
    [Grade]                       VARCHAR (30)    NULL,
    [Remarks]                     VARCHAR (30)    NULL,
    [AddedBy]                     VARCHAR (100)   NULL,
    [AddedDate]                   DATETIME        NULL,
    [UpdatedBy]                   VARCHAR (100)   NULL,
    [UpdatedDate]                 DATETIME        NULL,
    [MaterialMasterId]            VARCHAR (30)    NULL,
    [MaterialMasterArticleId]     VARCHAR (10)    NULL,
    [WorkStationDailyID]          VARCHAR (10)    NULL,
    [FLAG]                        VARCHAR (10)    NULL,
    CONSTRAINT [PK__DailyPro__3214EC275CFEBBFB] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK__DailyProd__Emplo__01217A9E] FOREIGN KEY ([EmployeeInformationSystemID]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK__DailyProd__Mater__6387C16D] FOREIGN KEY ([MaterialMasterArticleId]) REFERENCES [MST].[MaterialMasterArticle] ([Id]),
    CONSTRAINT [FK__DailyProd__Mater__647BE5A6] FOREIGN KEY ([MaterialMasterId]) REFERENCES [MST].[MaterialMaster] ([Id]),
    CONSTRAINT [FK__DailyProd__Opera__2CF6A692] FOREIGN KEY ([OperationVariationId]) REFERENCES [MST].[OperationVariation] ([Id]),
    CONSTRAINT [FK__DailyProd__Plant__0309C310] FOREIGN KEY ([PlantID]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK__DailyProd__Plant__2400A287] FOREIGN KEY ([PlantID]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK__DailyProd__Proce__6A34BEFC] FOREIGN KEY ([ProcessID]) REFERENCES [HKP].[Process] ([Id]),
    CONSTRAINT [FK__DailyProd__Produ__6B28E335] FOREIGN KEY ([ProductionOrderId]) REFERENCES [TRN].[ProductionOrder] ([Id]),
    CONSTRAINT [FK__DailyProd__Produ__6C1D076E] FOREIGN KEY ([ProductionBookingPeriodId]) REFERENCES [HKP].[ProductionBookingPeriod] ([Id]),
    CONSTRAINT [FK__DailyProd__Respo__04F20B82] FOREIGN KEY ([ResponsiblePersonID]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK__DailyProd__WorkC__409CE135] FOREIGN KEY ([WorkCenterMasterID]) REFERENCES [SCS].[WorkCenterMaster] ([Id]),
    CONSTRAINT [FK__DailyProd__WorkS__07CE782D] FOREIGN KEY ([WorkStationDailyID]) REFERENCES [TRN].[WorkStationDaily] ([Id]),
    CONSTRAINT [FK_DailyProduction_CompliedShiftGrouping] FOREIGN KEY ([ShiftId]) REFERENCES [MST].[CompliedShiftGrouping] ([Id]),
    CONSTRAINT [FK_DailyProduction_Entity] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_DailyProduction_SalesOrder] FOREIGN KEY ([SalesOrderMasterID]) REFERENCES [TRN].[SalesOrder] ([Id])
);

