CREATE TABLE [TRN].[EmployeePayableWriteOffDetail] (
    [Id]                        VARCHAR (150)    NOT NULL,
    [EmployeePayableId]         VARCHAR (100)    NOT NULL,
    [EmployeePayableDetailId]   VARCHAR (150)    NOT NULL,
    [EmployeePayableWriteOffId] VARCHAR (100)    NOT NULL,
    [CurrencyId]                VARCHAR (10)     NOT NULL,
    [GLGeneralInfoId]           VARCHAR (10)     NOT NULL,
    [BudgetMasterId]            VARCHAR (20)     NULL,
    [ActivityId]                VARCHAR (10)     NULL,
    [DocDate]                   DATETIME         NOT NULL,
    [DocRefNo]                  VARCHAR (50)     NOT NULL,
    [Narration]                 VARCHAR (250)    NULL,
    [Amount]                    DECIMAL (18, 10) NOT NULL,
    [Archive]                   BIT              NOT NULL,
    [AddedBy]                   VARCHAR (30)     NOT NULL,
    [AddedDate]                 DATETIME         NOT NULL,
    [AddedFromIP]               VARCHAR (15)     NOT NULL,
    [UpdatedBy]                 VARCHAR (30)     NULL,
    [UpdatedDate]               DATETIME         NULL,
    [UpdatedFromIP]             VARCHAR (15)     NULL,
    CONSTRAINT [PK_EmployeePayableWriteOffDetail] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_EmployeePayableWriteOffDetail_Activity] FOREIGN KEY ([ActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_EmployeePayableWriteOffDetail_BudgetMaster] FOREIGN KEY ([BudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_EmployeePayableWriteOffDetail_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_EmployeePayableWriteOffDetail_EmployeePayable] FOREIGN KEY ([EmployeePayableId]) REFERENCES [TRN].[EmployeePayable] ([Id]),
    CONSTRAINT [FK_EmployeePayableWriteOffDetail_EmployeePayableDetail] FOREIGN KEY ([EmployeePayableDetailId]) REFERENCES [TRN].[EmployeePayableDetail] ([Id]),
    CONSTRAINT [FK_EmployeePayableWriteOffDetail_EmployeePayableWriteOff] FOREIGN KEY ([EmployeePayableWriteOffId]) REFERENCES [TRN].[EmployeePayableWriteOff] ([Id]),
    CONSTRAINT [FK_EmployeePayableWriteOffDetail_GLGeneralInfo] FOREIGN KEY ([GLGeneralInfoId]) REFERENCES [HKP].[GLGeneralInfo] ([Id])
);

