CREATE TABLE [TRN].[EmployeePayableWriteOff] (
    [Id]                        VARCHAR (100)    NOT NULL,
    [CompanyGroupId]            VARCHAR (10)     NOT NULL,
    [CompanyId]                 VARCHAR (10)     NOT NULL,
    [PlantId]                   VARCHAR (10)     NOT NULL,
    [EntityId]                  VARCHAR (10)     NULL,
    [CurrencyId]                VARCHAR (10)     NOT NULL,
    [VoucherId]                 VARCHAR (50)     NOT NULL,
    [EmployeeId]                VARCHAR (30)     NULL,
    [PartyType]                 VARCHAR (10)     NOT NULL,
    [SourceType]                VARCHAR (30)     NULL,
    [SourceFrom]                VARCHAR (20)     NULL,
    [PostingDate]               DATETIME         NOT NULL,
    [DocDate]                   DATETIME         NOT NULL,
    [DocRefNo]                  VARCHAR (50)     NOT NULL,
    [Narration]                 VARCHAR (250)    NOT NULL,
    [Amount]                    DECIMAL (18, 10) NOT NULL,
    [Archive]                   BIT              NOT NULL,
    [AddedBy]                   VARCHAR (30)     NOT NULL,
    [AddedDate]                 DATETIME         NOT NULL,
    [AddedFromIP]               VARCHAR (15)     NOT NULL,
    [UpdatedBy]                 VARCHAR (30)     NULL,
    [UpdatedDate]               DATETIME         NULL,
    [UpdatedFromIP]             VARCHAR (15)     NULL,
    [FiscalYearId]              VARCHAR (10)     NULL,
    [FiscalYearPeriodId]        VARCHAR (10)     NULL,
    [TaxYearId]                 VARCHAR (10)     NULL,
    [TaxYearPeriodId]           VARCHAR (10)     NULL,
    [VoucherTypeId]             VARCHAR (10)     NULL,
    [VoucherDate]               DATETIME         NOT NULL,
    [EmployeePayableWriteOffNo] VARCHAR (30)     NULL,
    [RoundingType]              VARCHAR (20)     NULL,
    [RoundingAmount]            DECIMAL (18, 10) NULL,
    CONSTRAINT [PK_EmployeePayableWriteOff] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_EmployeePayableWriteOff_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_EmployeePayableWriteOff_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_EmployeePayableWriteOff_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_EmployeePayableWriteOff_EmployeeInformation] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_EmployeePayableWriteOff_Entity] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_EmployeePayableWriteOff_FiscalYear] FOREIGN KEY ([FiscalYearId]) REFERENCES [SCS].[FiscalYear] ([Id]),
    CONSTRAINT [FK_EmployeePayableWriteOff_FiscalYearPeriod] FOREIGN KEY ([FiscalYearPeriodId]) REFERENCES [SCS].[FiscalYearPeriod] ([Id]),
    CONSTRAINT [FK_EmployeePayableWriteOff_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_EmployeePayableWriteOff_TaxYear] FOREIGN KEY ([TaxYearId]) REFERENCES [SCS].[TaxYear] ([Id]),
    CONSTRAINT [FK_EmployeePayableWriteOff_TaxYearPeriod] FOREIGN KEY ([TaxYearPeriodId]) REFERENCES [SCS].[TaxYearPeriod] ([Id]),
    CONSTRAINT [FK_EmployeePayableWriteOff_Voucher] FOREIGN KEY ([VoucherId]) REFERENCES [TRN].[Voucher] ([Id]),
    CONSTRAINT [FK_EmployeePayableWriteOff_VoucherType] FOREIGN KEY ([VoucherTypeId]) REFERENCES [SCS].[VoucherType] ([Id])
);

