CREATE TABLE [TRN].[EmployeeLeaveSummary] (
    [Id]                                  VARCHAR (50)    NOT NULL,
    [EmployeeId]                          VARCHAR (30)    NOT NULL,
    [CalanderYearId]                      VARCHAR (30)    NULL,
    [LeaveTypeId]                         VARCHAR (10)    NULL,
    [CarryForward]                        DECIMAL (18, 2) NULL,
    [CurrentYearAllocation]               DECIMAL (18, 2) NULL,
    [DaysCanBeSanctioned]                 DECIMAL (18, 2) NULL,
    [CurrentYearAvailedOpeningBalance]    DECIMAL (18, 2) NULL,
    [AppliedDays]                         DECIMAL (18, 2) NULL,
    [AvailedDays]                         DECIMAL (18, 2) NULL,
    [AddedBy]                             VARCHAR (30)    NOT NULL,
    [AddedDate]                           DATETIME        NOT NULL,
    [AddedFromIP]                         VARCHAR (15)    NOT NULL,
    [UpdatedBy]                           VARCHAR (30)    NULL,
    [UpdatedDate]                         DATETIME        NULL,
    [UpdatedFromIP]                       VARCHAR (15)    NULL,
    [PreviousYearCarryForward]            DECIMAL (18, 2) NULL,
    [CompanyGroupId]                      VARCHAR (10)    NULL,
    [PlantId]                             VARCHAR (10)    NULL,
    [CurrentYearEarnedDaysOpeningBalance] DECIMAL (18, 2) NULL,
    [CarryForwardOpeningBalance]          DECIMAL (18, 2) CONSTRAINT [DF__EmployeeL__Carry__6B509E62] DEFAULT ((0.00)) NOT NULL,
    [YearEndEncash]                       DECIMAL (18, 2) NULL,
    [YearEndLapse]                        DECIMAL (18, 2) NULL,
    [YearEndEncashCumulative]             DECIMAL (18, 2) NULL,
    [YearEndLapseCumulative]              DECIMAL (18, 2) NULL,
    [BroughtForward]                      DECIMAL (18, 2) NULL,
    [IsYearlyProcessed]                   BIT             CONSTRAINT [DF__EmployeeL__IsYea__71346041] DEFAULT ((0)) NOT NULL,
    [CalculatedEarningDays]               DECIMAL (18, 2) NULL,
    [CurrentYearAllocationAsPerPolicy]    DECIMAL (18, 2) DEFAULT ((0)) NOT NULL,
    [EncashedInbetween]                   NUMERIC (18, 2) DEFAULT ((0)) NOT NULL,
    [IsEncashed]                          BIT             DEFAULT ((0)) NOT NULL,
    [NotEncashedButYearEnded]             BIT             DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_EmployeeLeaveSummary] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_EmployeeLeaveSummary_EmployeeInformation] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_EmployeeLeaveSummary_LeaveType] FOREIGN KEY ([LeaveTypeId]) REFERENCES [dbo].[LeaveType] ([Id]),
    CONSTRAINT [FK_EmployeeLeaveSummary_YearlyCalendar] FOREIGN KEY ([CalanderYearId]) REFERENCES [dbo].[YearlyCalendar] ([Id])
);

