CREATE TABLE [TRN].[EmployeePayable] (
    [Id]                        VARCHAR (100)    NOT NULL,
    [CompanyGroupId]            VARCHAR (10)     NOT NULL,
    [CompanyId]                 VARCHAR (10)     NOT NULL,
    [PlantId]                   VARCHAR (10)     NOT NULL,
    [EntityId]                  VARCHAR (10)     NULL,
    [CurrencyId]                VARCHAR (10)     NOT NULL,
    [VoucherId]                 VARCHAR (50)     NULL,
    [OpeningBalanceId]          VARCHAR (30)     NULL,
    [ExpenseBookingId]          VARCHAR (100)    NULL,
    [EmployeeId]                VARCHAR (30)     NOT NULL,
    [PartyType]                 VARCHAR (10)     NOT NULL,
    [SourceType]                VARCHAR (30)     NULL,
    [PostingDate]               DATETIME         NULL,
    [DocDate]                   DATETIME         NOT NULL,
    [DocRefNo]                  VARCHAR (50)     NOT NULL,
    [Narration]                 VARCHAR (250)    NULL,
    [Amount]                    DECIMAL (18, 10) NOT NULL,
    [WrittenOffAmount]          DECIMAL (18, 10) NOT NULL,
    [IsWrittenOff]              BIT              NOT NULL,
    [IsPark]                    BIT              NOT NULL,
    [Archive]                   BIT              NOT NULL,
    [AddedBy]                   VARCHAR (30)     NOT NULL,
    [AddedDate]                 DATETIME         NOT NULL,
    [AddedFromIP]               VARCHAR (15)     NOT NULL,
    [UpdatedBy]                 VARCHAR (30)     NULL,
    [UpdatedDate]               DATETIME         NULL,
    [UpdatedFromIP]             VARCHAR (15)     NULL,
    [EmployeePayableNo]         VARCHAR (30)     NULL,
    [FiscalYearId]              VARCHAR (10)     NULL,
    [FiscalYearPeriodId]        VARCHAR (10)     NULL,
    [TaxYearId]                 VARCHAR (10)     NULL,
    [TaxYearPeriodId]           VARCHAR (10)     NULL,
    [VoucherTypeId]             VARCHAR (10)     NULL,
    [EmployeeTransactionTypeId] VARCHAR (10)     NULL,
    [NetAmount]                 DECIMAL (18, 10) NULL,
    [VoucherDate]               DATETIME         NOT NULL,
    [CompanyCurrencyRate]       DECIMAL (18, 10) NOT NULL,
    [InventoryReceiveId]        VARCHAR (10)     NULL,
    [PartyId]                   VARCHAR (10)     NULL,
    [PartyPlantId]              VARCHAR (12)     NULL,
    [PaymentTermId]             VARCHAR (10)     NULL,
    [BaseOnDueDate]             DATETIME         NULL,
    [RevisedDueDate]            DATETIME         NULL,
    [ActualDueDate]             DATETIME         NULL,
    [BaseNoOfDays]              INT              NULL,
    CONSTRAINT [PK_EmployeePayable] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_EmployeePayable_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_EmployeePayable_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_EmployeePayable_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_EmployeePayable_EmployeeInformation] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_EmployeePayable_EmployeeTransactionType] FOREIGN KEY ([EmployeeTransactionTypeId]) REFERENCES [HKP].[EmployeeTransactionType] ([Id]),
    CONSTRAINT [FK_EmployeePayable_Entity] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_EmployeePayable_ExpenseBooking] FOREIGN KEY ([ExpenseBookingId]) REFERENCES [TRN].[ExpenseBooking] ([Id]),
    CONSTRAINT [FK_EmployeePayable_FiscalYear] FOREIGN KEY ([FiscalYearId]) REFERENCES [SCS].[FiscalYear] ([Id]),
    CONSTRAINT [FK_EmployeePayable_FiscalYearPeriod] FOREIGN KEY ([FiscalYearPeriodId]) REFERENCES [SCS].[FiscalYearPeriod] ([Id]),
    CONSTRAINT [FK_EmployeePayable_InventoryReceive] FOREIGN KEY ([InventoryReceiveId]) REFERENCES [TRN].[InventoryReceive] ([Id]),
    CONSTRAINT [FK_EmployeePayable_OpeningBalance] FOREIGN KEY ([OpeningBalanceId]) REFERENCES [TRN].[OpeningBalance] ([Id]),
    CONSTRAINT [FK_EmployeePayable_Party] FOREIGN KEY ([PartyId]) REFERENCES [HKP].[Party] ([Id]),
    CONSTRAINT [FK_EmployeePayable_PartyPlant] FOREIGN KEY ([PartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_EmployeePayable_PaymentTerm] FOREIGN KEY ([PaymentTermId]) REFERENCES [MST].[PaymentTerm] ([Id]),
    CONSTRAINT [FK_EmployeePayable_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_EmployeePayable_TaxYear] FOREIGN KEY ([TaxYearId]) REFERENCES [SCS].[TaxYear] ([Id]),
    CONSTRAINT [FK_EmployeePayable_TaxYearPeriod] FOREIGN KEY ([TaxYearPeriodId]) REFERENCES [SCS].[TaxYearPeriod] ([Id]),
    CONSTRAINT [FK_EmployeePayable_Voucher] FOREIGN KEY ([VoucherId]) REFERENCES [TRN].[Voucher] ([Id]),
    CONSTRAINT [FK_EmployeePayable_VoucherType] FOREIGN KEY ([VoucherTypeId]) REFERENCES [SCS].[VoucherType] ([Id])
);

