CREATE TABLE [TRN].[EmployeePayableDetail] (
    [Id]                    VARCHAR (150)    NOT NULL,
    [EmployeePayableId]     VARCHAR (100)    NOT NULL,
    [GLGeneralInfoId]       VARCHAR (10)     NOT NULL,
    [BudgetMasterId]        VARCHAR (20)     NULL,
    [ActivityId]            VARCHAR (10)     NULL,
    [Amount]                DECIMAL (18, 10) NOT NULL,
    [TaxAmount]             DECIMAL (18, 10) NOT NULL,
    [NetAmount]             DECIMAL (18, 4)  NOT NULL,
    [WrittenOffAmount]      DECIMAL (18, 10) NOT NULL,
    [IsWrittenOff]          BIT              NOT NULL,
    [IsBlock]               BIT              NOT NULL,
    [BlockReason]           VARCHAR (250)    NULL,
    [BlockDate]             DATETIME         NULL,
    [Archive]               BIT              NOT NULL,
    [AddedBy]               VARCHAR (30)     NOT NULL,
    [AddedDate]             DATETIME         NOT NULL,
    [AddedFromIP]           VARCHAR (15)     NOT NULL,
    [UpdatedBy]             VARCHAR (30)     NULL,
    [UpdatedDate]           DATETIME         NULL,
    [UpdatedFromIP]         VARCHAR (15)     NULL,
    [MaterialGroupMasterId] VARCHAR (10)     NULL,
    CONSTRAINT [PK_EmployeePayableDetail] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_EmployeePayableDetail_Activity] FOREIGN KEY ([ActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_EmployeePayableDetail_BudgetMaster] FOREIGN KEY ([BudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_EmployeePayableDetail_EmployeePayable] FOREIGN KEY ([EmployeePayableId]) REFERENCES [TRN].[EmployeePayable] ([Id]),
    CONSTRAINT [FK_EmployeePayableDetail_GLGeneralInfo] FOREIGN KEY ([GLGeneralInfoId]) REFERENCES [HKP].[GLGeneralInfo] ([Id])
);

