CREATE TABLE [TRN].[ExpenseBooking] (
    [Id]                   VARCHAR (100) NOT NULL,
    [CompanyGroupId]       VARCHAR (10)  NOT NULL,
    [PlantId]              VARCHAR (10)  NULL,
    [EntityId]             VARCHAR (10)  NULL,
    [EmployeeId]           VARCHAR (30)  NOT NULL,
    [CurrencyId]           VARCHAR (10)  NOT NULL,
    [InvoiceNumber]        VARCHAR (20)  NOT NULL,
    [InvoiceDate]          DATETIME      NOT NULL,
    [ApprovalStatus]       VARCHAR (20)  NOT NULL,
    [Remarks]              VARCHAR (250) NULL,
    [Archive]              BIT           NOT NULL,
    [AddedBy]              VARCHAR (30)  NOT NULL,
    [AddedDate]            DATETIME      NOT NULL,
    [AddedFromIP]          VARCHAR (15)  NOT NULL,
    [UpdatedBy]            VARCHAR (30)  NULL,
    [UpdatedDate]          DATETIME      NULL,
    [UpdatedFromIP]        VARCHAR (15)  NULL,
    [CompanyId]            VARCHAR (10)  NOT NULL,
    [IsPosted]             BIT           NULL,
    [ResponsiblePersonId]  VARCHAR (30)  NULL,
    [PartyId]              VARCHAR (10)  NULL,
    [BeneficiaryType]      VARCHAR (20)  NULL,
    [VoucherId]            VARCHAR (50)  NULL,
    [AppliedBy]            VARCHAR (20)  NULL,
    [PartyPlantId]         VARCHAR (12)  NULL,
    [CashMasterId]         VARCHAR (10)  NULL,
    [FileName]             VARCHAR (100) NULL,
    [ToBeCheckedRetrieve]  BIT           NULL,
    [ToBeApporvedRetrieve] BIT           NULL,
    CONSTRAINT [PK_ExpenseBooking] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ExpenseBooking_CashMaster] FOREIGN KEY ([CashMasterId]) REFERENCES [MST].[CashMaster] ([Id]),
    CONSTRAINT [FK_ExpenseBooking_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_ExpenseBooking_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_ExpenseBooking_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_ExpenseBooking_EmployeeInformation] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_ExpenseBooking_EmployeeInformation_ResponsiblePerson] FOREIGN KEY ([ResponsiblePersonId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_ExpenseBooking_Entity] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_ExpenseBooking_Party] FOREIGN KEY ([PartyId]) REFERENCES [HKP].[Party] ([Id]),
    CONSTRAINT [FK_ExpenseBooking_PartyPlant] FOREIGN KEY ([PartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_ExpenseBooking_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_ExpenseBooking_Voucher] FOREIGN KEY ([VoucherId]) REFERENCES [TRN].[Voucher] ([Id])
);

