CREATE TABLE [TRN].[ExpenseBookingDetail] (
    [Id]                   VARCHAR (150)   NOT NULL,
    [ExpenseBookingId]     VARCHAR (100)   NOT NULL,
    [PartyId]              VARCHAR (10)    NULL,
    [FixedAssetRegisterId] VARCHAR (30)    NULL,
    [GLGeneralInfoId]      VARCHAR (10)    NOT NULL,
    [BudgetMasterId]       VARCHAR (20)    NULL,
    [ActivityId]           VARCHAR (10)    NULL,
    [ActivityPhoneId]      VARCHAR (20)    NULL,
    [DocDate]              DATETIME        NOT NULL,
    [DocRefNo]             VARCHAR (50)    NOT NULL,
    [Amount]               DECIMAL (18, 4) NOT NULL,
    [ApprovalStatus]       VARCHAR (20)    NULL,
    [ApprovalStatusDate]   DATETIME        NULL,
    [AddedBy]              VARCHAR (30)    NOT NULL,
    [AddedDate]            DATETIME        NOT NULL,
    [AddedFromIP]          VARCHAR (15)    NOT NULL,
    [UpdatedBy]            VARCHAR (30)    NULL,
    [UpdatedDate]          DATETIME        NULL,
    [UpdatedFromIP]        VARCHAR (15)    NULL,
    [IsPosted]             BIT             NULL,
    [MaterialMasterId]     VARCHAR (30)    NULL,
    [ActivityType]         VARCHAR (25)    NULL,
    CONSTRAINT [PK_ExpenseBookingDetail] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ExpenseBookingDetail_Activity] FOREIGN KEY ([ActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_ExpenseBookingDetail_ActivityPhone] FOREIGN KEY ([ActivityPhoneId]) REFERENCES [HKP].[ActivityPhone] ([Id]),
    CONSTRAINT [FK_ExpenseBookingDetail_BudgetMaster] FOREIGN KEY ([BudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_ExpenseBookingDetail_ExpenseBooking] FOREIGN KEY ([ExpenseBookingId]) REFERENCES [TRN].[ExpenseBooking] ([Id]),
    CONSTRAINT [FK_ExpenseBookingDetail_FixedAssetRegister] FOREIGN KEY ([FixedAssetRegisterId]) REFERENCES [TRN].[FixedAssetRegister] ([Id]),
    CONSTRAINT [FK_ExpenseBookingDetail_GLGeneralInfo] FOREIGN KEY ([GLGeneralInfoId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_ExpenseBookingDetail_MaterialMaster] FOREIGN KEY ([MaterialMasterId]) REFERENCES [MST].[MaterialMaster] ([Id]),
    CONSTRAINT [FK_ExpenseBookingDetail_Party] FOREIGN KEY ([PartyId]) REFERENCES [HKP].[Party] ([Id])
);

