CREATE TABLE [TRN].[ExpenseBookingApprovalHistory] (
    [Id]                     VARCHAR (50)  NOT NULL,
    [ExpenseBookingId]       VARCHAR (100) NULL,
    [ExpenseBookingDetailId] VARCHAR (150) NULL,
    [PositionId]             VARCHAR (10)  NULL,
    [ManpowerBudgetId]       VARCHAR (10)  NULL,
    [EmployeeId]             VARCHAR (30)  NULL,
    [ApprovalStatus]         VARCHAR (20)  NULL,
    [ApprovalStatusDate]     DATETIME      NULL,
    [ApprovalLevel]          VARCHAR (20)  NULL,
    [Remarks]                VARCHAR (250) NULL,
    [AddedBy]                VARCHAR (30)  NOT NULL,
    [AddedDate]              DATETIME      NOT NULL,
    [AddedFromIP]            VARCHAR (15)  NOT NULL,
    [UpdatedBy]              VARCHAR (30)  NULL,
    [UpdatedDate]            DATETIME      NULL,
    [UpdatedFromIP]          VARCHAR (15)  NULL,
    [CheckedStatus]          VARCHAR (20)  NULL,
    [CheckedStatusDate]      DATETIME      NULL,
    [CheckedPersonId]        VARCHAR (30)  NULL,
    CONSTRAINT [PK_ExpenseBookingApprovalHistory] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ExpenseBookingApprovalHistory_CheckedPerson] FOREIGN KEY ([CheckedPersonId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_ExpenseBookingApprovalHistory_Employee] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_ExpenseBookingApprovalHistory_ExpenseBooking] FOREIGN KEY ([ExpenseBookingId]) REFERENCES [TRN].[ExpenseBooking] ([Id]),
    CONSTRAINT [FK_ExpenseBookingApprovalHistory_ExpenseBookingDetail] FOREIGN KEY ([ExpenseBookingDetailId]) REFERENCES [TRN].[ExpenseBookingDetail] ([Id]),
    CONSTRAINT [FK_ExpenseBookingApprovalHistory_ManpowerBudget] FOREIGN KEY ([ManpowerBudgetId]) REFERENCES [MST].[ManpowerBudget] ([Id]),
    CONSTRAINT [FK_ExpenseBookingApprovalHistory_Position] FOREIGN KEY ([PositionId]) REFERENCES [ORG].[Position] ([Id])
);

