CREATE TABLE [TRN].[FabricRollMaster] (
    [Id]                        VARCHAR (10)    NOT NULL,
    [RollNo]                    VARCHAR (30)    NULL,
    [MaterialMasterId]          VARCHAR (30)    NOT NULL,
    [ArticleId]                 VARCHAR (10)    NULL,
    [SKUId]                     VARCHAR (10)    NULL,
    [Width]                     DECIMAL (18)    NULL,
    [VendorWidth]               DECIMAL (18)    NULL,
    [VendorRollNo]              VARCHAR (50)    NULL,
    [VendorLotNo]               VARCHAR (50)    NULL,
    [VendorQty]                 INT             NOT NULL,
    [IsBlanketCutApplicable]    BIT             CONSTRAINT [DF_FabricRollMaster_IsBlanketCutApplicable] DEFAULT ((0)) NOT NULL,
    [BlanketLengthBeforeWash]   DECIMAL (18, 2) NULL,
    [BlanketWidthBeforeWash]    DECIMAL (10, 2) NULL,
    [BlanketLengthAfterWash]    DECIMAL (18, 2) NULL,
    [BlanketWidthAfterWash]     DECIMAL (18, 2) NULL,
    [ShrinkagePercentageLength] DECIMAL (18, 2) NULL,
    [ShrinkagePercentageWidth]  DECIMAL (18, 2) NULL,
    [HasDefectShade]            BIT             NULL,
    [SpecialShadeType]          VARCHAR (10)    NULL,
    [QtyInspected]              DECIMAL (18, 2) NULL,
    [IsInspectionPassed]        BIT             NULL,
    [[QualityPass]]]            BIT             NULL,
    [Shade]                     VARCHAR (50)    NULL,
    [Remark]                    VARCHAR (250)   NULL,
    [PlantId]                   VARCHAR (10)    NOT NULL,
    [AddedBy]                   VARCHAR (30)    NULL,
    [AddedDate]                 DATETIME        NULL,
    [AddedFromIP]               VARCHAR (15)    NULL,
    [UpdatedBy]                 VARCHAR (30)    NULL,
    [UpdatedDate]               DATETIME        NULL,
    [UpdatedFromIP]             VARCHAR (15)    NULL,
    [IAddedBy]                  VARCHAR (30)    NULL,
    [IAddedDate]                DATETIME        NULL,
    [IAddedFromIP]              VARCHAR (15)    NULL,
    [IUpdatedBy]                VARCHAR (30)    NULL,
    [IUpdatedDate]              DATETIME        NULL,
    [IUpdatedFromIP]            VARCHAR (15)    NULL,
    [QAddedBy]                  VARCHAR (30)    NULL,
    [QAddedDate]                DATETIME        NULL,
    [QAddedFromIP]              VARCHAR (15)    NULL,
    [QUpdatedBy]                VARCHAR (30)    NULL,
    [QUpdatedDate]              DATETIME        NULL,
    [QUpdatedFromIP]            VARCHAR (15)    NULL,
    [InsAddedBy]                VARCHAR (30)    NULL,
    [InsAddedDate]              DATETIME        NULL,
    [InsAddedFromIP]            VARCHAR (15)    NULL,
    [InsUpdatedBy]              VARCHAR (30)    NULL,
    [InsUpdatedDate]            DATETIME        NULL,
    [InsUpdatedFromIP]          VARCHAR (15)    NULL,
    [InventoryReceiveDetailId]  VARCHAR (50)    NOT NULL,
    [SKUValueId]                VARCHAR (10)    NULL,
    CONSTRAINT [PK_FabricRollMaster] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_FabricRollMaster_CharacteristicsValue] FOREIGN KEY ([SKUValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_FabricRollMaster_InventoryReceiveDetail] FOREIGN KEY ([InventoryReceiveDetailId]) REFERENCES [TRN].[InventoryReceiveDetail] ([Id])
);

