CREATE TABLE [TRN].[FGInventoryReceive] (
    [Id]                           VARCHAR (30)     NOT NULL,
    [CompanyGroupId]               VARCHAR (10)     NOT NULL,
    [PlantId]                      VARCHAR (10)     NOT NULL,
    [EntityId]                     VARCHAR (10)     NULL,
    [ProductionOrderDetailId]      VARCHAR (30)     NULL,
    [ProductionSummaryDetailId]    VARCHAR (30)     NULL,
    [ChallanId]                    VARCHAR (10)     NULL,
    [FGGRNId]                      VARCHAR (10)     NULL,
    [OpeningBalanceId]             VARCHAR (50)     NULL,
    [MaterialStorageId]            VARCHAR (10)     NULL,
    [MaterialMasterId]             VARCHAR (30)     NOT NULL,
    [ArticleId]                    VARCHAR (10)     NULL,
    [FirstCharacteristicsId]       VARCHAR (20)     NULL,
    [FirstCharacteristicsValueId]  VARCHAR (10)     NULL,
    [SecondCharacteristicsId]      VARCHAR (20)     NULL,
    [SecondCharacteristicsValueId] VARCHAR (10)     NULL,
    [ThirdCharacteristicsId]       VARCHAR (20)     NULL,
    [ThirdCharacteristicsValueId]  VARCHAR (10)     NULL,
    [Qty]                          DECIMAL (18, 10) NULL,
    [UoMId]                        VARCHAR (10)     NULL,
    [AddedBy]                      VARCHAR (30)     NOT NULL,
    [AddedDate]                    DATETIME         NOT NULL,
    [AddedFromIP]                  VARCHAR (15)     NOT NULL,
    [UpdatedBy]                    VARCHAR (30)     NULL,
    [UpdatedDate]                  DATETIME         NULL,
    [UpdatedFromIP]                VARCHAR (15)     NULL,
    CONSTRAINT [PK_FGInventoryReceive] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_FGInventoryReceive_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_FGInventoryReceive_Entity] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_FGInventoryReceive_FirstCharacteristics] FOREIGN KEY ([FirstCharacteristicsId]) REFERENCES [TRN].[FirstCharacteristics] ([Id]),
    CONSTRAINT [FK_FGInventoryReceive_FirstCharacteristicsValue] FOREIGN KEY ([FirstCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_FGInventoryReceive_MaterialMaster] FOREIGN KEY ([MaterialMasterId]) REFERENCES [MST].[MaterialMaster] ([Id]),
    CONSTRAINT [FK_FGInventoryReceive_MaterialMasterArticle] FOREIGN KEY ([ArticleId]) REFERENCES [MST].[MaterialMasterArticle] ([Id]),
    CONSTRAINT [FK_FGInventoryReceive_MaterialStorage] FOREIGN KEY ([MaterialStorageId]) REFERENCES [HKP].[MaterialStorage] ([Id]),
    CONSTRAINT [FK_FGInventoryReceive_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_FGInventoryReceive_ProductionOrderDetail] FOREIGN KEY ([ProductionOrderDetailId]) REFERENCES [TRN].[ProductionOrderDetail] ([Id]),
    CONSTRAINT [FK_FGInventoryReceive_ProductionSummaryDetail] FOREIGN KEY ([ProductionSummaryDetailId]) REFERENCES [TRN].[ProductionSummaryDetail] ([Id]),
    CONSTRAINT [FK_FGInventoryReceive_SecondCharacteristics] FOREIGN KEY ([SecondCharacteristicsId]) REFERENCES [TRN].[SecondCharacteristics] ([Id]),
    CONSTRAINT [FK_FGInventoryReceive_SecondCharacteristicsValue] FOREIGN KEY ([SecondCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_FGInventoryReceive_ThirdCharacteristics] FOREIGN KEY ([ThirdCharacteristicsId]) REFERENCES [TRN].[ThirdCharacteristics] ([Id]),
    CONSTRAINT [FK_FGInventoryReceive_ThirdCharacteristicsValue] FOREIGN KEY ([ThirdCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_FGInventoryReceive_UnitOfMeasurement] FOREIGN KEY ([UoMId]) REFERENCES [SCS].[UnitOfMeasurement] ([Id])
);

