CREATE TABLE [TRN].[FinancingWriteOff] (
    [Id]                 VARCHAR (10)     NOT NULL,
    [CompanyGroupId]     VARCHAR (10)     NOT NULL,
    [CompanyId]          VARCHAR (10)     NOT NULL,
    [PlantId]            VARCHAR (10)     NOT NULL,
    [EntityId]           VARCHAR (10)     NULL,
    [FiscalYearId]       VARCHAR (10)     NULL,
    [FiscalYearPeriodId] VARCHAR (10)     NULL,
    [TaxYearId]          VARCHAR (10)     NULL,
    [TaxYearPeriodId]    VARCHAR (10)     NULL,
    [CurrencyId]         VARCHAR (10)     NOT NULL,
    [VoucherId]          VARCHAR (50)     NULL,
    [VoucherTypeId]      VARCHAR (10)     NULL,
    [OpeningBalanceId]   VARCHAR (30)     NULL,
    [FinancingTypeId]    VARCHAR (10)     NOT NULL,
    [FinancingId]        VARCHAR (10)     NOT NULL,
    [EmployeeId]         VARCHAR (30)     NULL,
    [InterCompanyId]     VARCHAR (10)     NULL,
    [InterPlantId]       VARCHAR (10)     NULL,
    [BankMasterId]       VARCHAR (10)     NULL,
    [CashMasterId]       VARCHAR (10)     NULL,
    [PartyType]          VARCHAR (10)     NOT NULL,
    [PartyId]            VARCHAR (10)     NULL,
    [PartyPlantId]       VARCHAR (12)     NULL,
    [FinancingNo]        VARCHAR (30)     NULL,
    [TransactionType]    VARCHAR (30)     NULL,
    [SourceType]         VARCHAR (30)     NOT NULL,
    [PaymentSource]      VARCHAR (20)     NULL,
    [VoucherDate]        DATETIME         NULL,
    [PostingDate]        DATETIME         NOT NULL,
    [DocDate]            DATETIME         NOT NULL,
    [DocRefNo]           VARCHAR (50)     NOT NULL,
    [Narration]          VARCHAR (250)    NOT NULL,
    [Amount]             DECIMAL (20, 10) NOT NULL,
    [IsPosted]           BIT              NOT NULL,
    [RefId]              VARCHAR (10)     NULL,
    [ProfitAmount]       DECIMAL (18, 10) NOT NULL,
    [WrittenOffAmount]   DECIMAL (18, 10) NOT NULL,
    [IsWrittenOff]       BIT              NOT NULL,
    [IsPark]             BIT              NOT NULL,
    [Archive]            BIT              NOT NULL,
    [AddedBy]            VARCHAR (30)     NOT NULL,
    [AddedDate]          DATETIME         NOT NULL,
    [AddedFromIP]        VARCHAR (15)     NOT NULL,
    [UpdatedBy]          VARCHAR (30)     NULL,
    [UpdatedDate]        DATETIME         NULL,
    [UpdatedFromIP]      VARCHAR (15)     NULL,
    [IsSchedule]         BIT              DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_FinancingWriteOff] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_FinancingWriteOff_BankMaster] FOREIGN KEY ([BankMasterId]) REFERENCES [MST].[BankMaster] ([Id]),
    CONSTRAINT [FK_FinancingWriteOff_CashMaster] FOREIGN KEY ([CashMasterId]) REFERENCES [MST].[CashMaster] ([Id]),
    CONSTRAINT [FK_FinancingWriteOff_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_FinancingWriteOff_Company_InterCompanyId] FOREIGN KEY ([InterCompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_FinancingWriteOff_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_FinancingWriteOff_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_FinancingWriteOff_Employee] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_FinancingWriteOff_Entity] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_FinancingWriteOff_Financing] FOREIGN KEY ([FinancingId]) REFERENCES [TRN].[Financing] ([Id]),
    CONSTRAINT [FK_FinancingWriteOff_FinancingType] FOREIGN KEY ([FinancingTypeId]) REFERENCES [HKP].[FinancingType] ([Id]),
    CONSTRAINT [FK_FinancingWriteOff_FiscalYear] FOREIGN KEY ([FiscalYearId]) REFERENCES [SCS].[FiscalYear] ([Id]),
    CONSTRAINT [FK_FinancingWriteOff_FiscalYearPeriod] FOREIGN KEY ([FiscalYearPeriodId]) REFERENCES [SCS].[FiscalYearPeriod] ([Id]),
    CONSTRAINT [FK_FinancingWriteOff_OpeningBalance] FOREIGN KEY ([OpeningBalanceId]) REFERENCES [TRN].[OpeningBalance] ([Id]),
    CONSTRAINT [FK_FinancingWriteOff_Party] FOREIGN KEY ([PartyId]) REFERENCES [HKP].[Party] ([Id]),
    CONSTRAINT [FK_FinancingWriteOff_PartyPlant] FOREIGN KEY ([PartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_FinancingWriteOff_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_FinancingWriteOff_Plant_InterPlantId] FOREIGN KEY ([InterPlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_FinancingWriteOff_TaxYear] FOREIGN KEY ([TaxYearId]) REFERENCES [SCS].[TaxYear] ([Id]),
    CONSTRAINT [FK_FinancingWriteOff_TaxYearPeriod] FOREIGN KEY ([TaxYearPeriodId]) REFERENCES [SCS].[TaxYearPeriod] ([Id]),
    CONSTRAINT [FK_FinancingWriteOff_Voucher] FOREIGN KEY ([VoucherId]) REFERENCES [TRN].[Voucher] ([Id]),
    CONSTRAINT [FK_FinancingWriteOff_VoucherType] FOREIGN KEY ([VoucherTypeId]) REFERENCES [SCS].[VoucherType] ([Id])
);

