CREATE TABLE [TRN].[FinancingDetailWriteOff] (
    [Id]                  VARCHAR (12)     NOT NULL,
    [FinancingId]         VARCHAR (10)     NOT NULL,
    [FinancingDetailId]   VARCHAR (12)     NOT NULL,
    [FinancingWriteOffId] VARCHAR (10)     NOT NULL,
    [GLGeneralInfoId]     VARCHAR (10)     NOT NULL,
    [BudgetMasterId]      VARCHAR (20)     NULL,
    [ActivityId]          VARCHAR (10)     NULL,
    [BankMasterId]        VARCHAR (10)     NULL,
    [CashMasterId]        VARCHAR (10)     NULL,
    [Amount]              DECIMAL (20, 10) NOT NULL,
    [BankAmount]          DECIMAL (20, 10) CONSTRAINT [DF__FinancingDetailWriteOff__BankA__424F5426] DEFAULT ((0)) NOT NULL,
    [WrittenOffAmount]    DECIMAL (18, 10) NOT NULL,
    [IsWrittenOff]        BIT              NOT NULL,
    [SourceTo]            VARCHAR (10)     NULL,
    [Archive]             BIT              NOT NULL,
    [AddedBy]             VARCHAR (30)     NOT NULL,
    [AddedDate]           DATETIME         NOT NULL,
    [AddedFromIP]         VARCHAR (15)     NOT NULL,
    [UpdatedBy]           VARCHAR (30)     NULL,
    [UpdatedDate]         DATETIME         NULL,
    [UpdatedFromIP]       VARCHAR (15)     NULL,
    CONSTRAINT [PK_FinancingDetailWriteOff] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_FinancingDetailWriteOff_Activity] FOREIGN KEY ([ActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_FinancingDetailWriteOff_BankMaster] FOREIGN KEY ([BankMasterId]) REFERENCES [MST].[BankMaster] ([Id]),
    CONSTRAINT [FK_FinancingDetailWriteOff_BudgetMaster] FOREIGN KEY ([BudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_FinancingDetailWriteOff_CashMaster] FOREIGN KEY ([CashMasterId]) REFERENCES [MST].[CashMaster] ([Id]),
    CONSTRAINT [FK_FinancingDetailWriteOff_Financing] FOREIGN KEY ([FinancingId]) REFERENCES [TRN].[Financing] ([Id]),
    CONSTRAINT [FK_FinancingDetailWriteOff_FinancingDetail] FOREIGN KEY ([FinancingDetailId]) REFERENCES [TRN].[FinancingDetail] ([Id]),
    CONSTRAINT [FK_FinancingDetailWriteOff_FinancingWriteOff] FOREIGN KEY ([FinancingWriteOffId]) REFERENCES [TRN].[FinancingWriteOff] ([Id]),
    CONSTRAINT [FK_FinancingDetailWriteOff_GLGeneralInfo] FOREIGN KEY ([GLGeneralInfoId]) REFERENCES [HKP].[GLGeneralInfo] ([Id])
);

