CREATE TABLE [TRN].[Financing] (
    [Id]                     VARCHAR (10)     NOT NULL,
    [CompanyGroupId]         VARCHAR (10)     NOT NULL,
    [CompanyId]              VARCHAR (10)     NOT NULL,
    [PlantId]                VARCHAR (10)     NOT NULL,
    [EntityId]               VARCHAR (10)     NULL,
    [CurrencyId]             VARCHAR (10)     NOT NULL,
    [VoucherId]              VARCHAR (50)     NULL,
    [OpeningBalanceId]       VARCHAR (30)     NULL,
    [FinancingTypeId]        VARCHAR (10)     NOT NULL,
    [EmployeeId]             VARCHAR (30)     NULL,
    [InterCompanyId]         VARCHAR (10)     NULL,
    [InterPlantId]           VARCHAR (10)     NULL,
    [BankMasterId]           VARCHAR (10)     NULL,
    [PartyId]                VARCHAR (10)     NULL,
    [PartyType]              VARCHAR (10)     NOT NULL,
    [SourceType]             VARCHAR (30)     NOT NULL,
    [PaymentSource]          VARCHAR (20)     NULL,
    [PostingDate]            DATETIME         NOT NULL,
    [DocDate]                DATETIME         NOT NULL,
    [DocRefNo]               VARCHAR (50)     NOT NULL,
    [Narration]              VARCHAR (250)    NOT NULL,
    [Amount]                 DECIMAL (20, 10) NOT NULL,
    [IsPosted]               BIT              CONSTRAINT [DF__Financing__IsPos__19B68790] DEFAULT ((0)) NOT NULL,
    [RefId]                  VARCHAR (10)     NULL,
    [RepaymentStartDate]     DATETIME         NULL,
    [LifeOfYear]             TINYINT          CONSTRAINT [DF__Financing__LifeO__49659AB2] DEFAULT ((0)) NULL,
    [NoOfInstallmentPerYear] TINYINT          CONSTRAINT [DF__Financing__NoOfI__4A59BEEB] DEFAULT ((0)) NULL,
    [TotalNoOfInstallment]   TINYINT          CONSTRAINT [DF__Financing__Total__4B4DE324] DEFAULT ((0)) NULL,
    [ProfitRate]             DECIMAL (18, 10) CONSTRAINT [DF__Financing__Profi__4C42075D] DEFAULT ((0)) NOT NULL,
    [ProfitAmount]           DECIMAL (18, 10) CONSTRAINT [DF__Financing__Profi__4D362B96] DEFAULT ((0)) NOT NULL,
    [WrittenOffAmount]       DECIMAL (20, 10) NOT NULL,
    [IsWrittenOff]           BIT              NOT NULL,
    [IsPark]                 BIT              NOT NULL,
    [Archive]                BIT              NOT NULL,
    [AddedBy]                VARCHAR (30)     NOT NULL,
    [AddedDate]              DATETIME         NOT NULL,
    [AddedFromIP]            VARCHAR (15)     NOT NULL,
    [UpdatedBy]              VARCHAR (30)     NULL,
    [UpdatedDate]            DATETIME         NULL,
    [UpdatedFromIP]          VARCHAR (15)     NULL,
    [FinancingNo]            VARCHAR (30)     NULL,
    [FiscalYearId]           VARCHAR (10)     NULL,
    [FiscalYearPeriodId]     VARCHAR (10)     NULL,
    [TaxYearId]              VARCHAR (10)     NULL,
    [TaxYearPeriodId]        VARCHAR (10)     NULL,
    [VoucherTypeId]          VARCHAR (10)     NULL,
    [PartyPlantId]           VARCHAR (12)     NULL,
    [VoucherDate]            DATETIME         NULL,
    [IsSchedule]             BIT              DEFAULT ((0)) NOT NULL,
    [CashMasterId]           VARCHAR (10)     NULL,
    [TransactionType]        VARCHAR (30)     NULL,
    [OtherBankMasterId]      VARCHAR (10)     NULL,
    [AdditionalLoanAmount]   DECIMAL (20, 10) NULL,
    CONSTRAINT [PK_Financing] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Financing_BankMaster] FOREIGN KEY ([BankMasterId]) REFERENCES [MST].[BankMaster] ([Id]),
    CONSTRAINT [FK_Financing_CashMaster] FOREIGN KEY ([CashMasterId]) REFERENCES [MST].[CashMaster] ([Id]),
    CONSTRAINT [FK_Financing_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_Financing_Company_InterCompanyId] FOREIGN KEY ([InterCompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_Financing_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_Financing_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_Financing_Employee] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_Financing_Entity] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_Financing_FinancingType] FOREIGN KEY ([FinancingTypeId]) REFERENCES [HKP].[FinancingType] ([Id]),
    CONSTRAINT [FK_Financing_FiscalYear] FOREIGN KEY ([FiscalYearId]) REFERENCES [SCS].[FiscalYear] ([Id]),
    CONSTRAINT [FK_Financing_FiscalYearPeriod] FOREIGN KEY ([FiscalYearPeriodId]) REFERENCES [SCS].[FiscalYearPeriod] ([Id]),
    CONSTRAINT [FK_Financing_OpeningBalance] FOREIGN KEY ([OpeningBalanceId]) REFERENCES [TRN].[OpeningBalance] ([Id]),
    CONSTRAINT [FK_Financing_OtherBankMaster] FOREIGN KEY ([OtherBankMasterId]) REFERENCES [MST].[BankMaster] ([Id]),
    CONSTRAINT [FK_Financing_Party] FOREIGN KEY ([PartyId]) REFERENCES [HKP].[Party] ([Id]),
    CONSTRAINT [FK_Financing_PartyPlant] FOREIGN KEY ([PartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_Financing_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_Financing_Plant_InterPlantId] FOREIGN KEY ([InterPlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_Financing_TaxYear] FOREIGN KEY ([TaxYearId]) REFERENCES [SCS].[TaxYear] ([Id]),
    CONSTRAINT [FK_Financing_TaxYearPeriod] FOREIGN KEY ([TaxYearPeriodId]) REFERENCES [SCS].[TaxYearPeriod] ([Id]),
    CONSTRAINT [FK_Financing_Voucher] FOREIGN KEY ([VoucherId]) REFERENCES [TRN].[Voucher] ([Id]),
    CONSTRAINT [FK_Financing_VoucherType] FOREIGN KEY ([VoucherTypeId]) REFERENCES [SCS].[VoucherType] ([Id])
);

