CREATE TABLE [TRN].[FinancingSubsequentTransaction] (
    [Id]                VARCHAR (10)     NOT NULL,
    [CompanyGroupId]    VARCHAR (10)     NOT NULL,
    [CompanyId]         VARCHAR (10)     NOT NULL,
    [PlantId]           VARCHAR (10)     NOT NULL,
    [EntityId]          VARCHAR (10)     NULL,
    [CurrencyId]        VARCHAR (10)     NOT NULL,
    [VoucherId]         VARCHAR (50)     NULL,
    [FinancingId]       VARCHAR (10)     NOT NULL,
    [PartyType]         VARCHAR (10)     NOT NULL,
    [PartyId]           VARCHAR (10)     NULL,
    [PartyPlantId]      VARCHAR (12)     NULL,
    [TransactionType]   VARCHAR (30)     NULL,
    [VoucherTypeId]     VARCHAR (10)     NULL,
    [SourceType]        VARCHAR (30)     NOT NULL,
    [PaymentSource]     VARCHAR (20)     NULL,
    [VoucherDate]       DATETIME         NULL,
    [PostingDate]       DATETIME         NOT NULL,
    [DocDate]           DATETIME         NOT NULL,
    [DocRefNo]          VARCHAR (50)     NOT NULL,
    [Narration]         VARCHAR (250)    NOT NULL,
    [Amount]            DECIMAL (20, 10) NOT NULL,
    [IsPosted]          BIT              NOT NULL,
    [IsPark]            BIT              NOT NULL,
    [Archive]           BIT              NOT NULL,
    [AddedBy]           VARCHAR (30)     NOT NULL,
    [AddedDate]         DATETIME         NOT NULL,
    [AddedFromIP]       VARCHAR (15)     NOT NULL,
    [UpdatedBy]         VARCHAR (30)     NULL,
    [UpdatedDate]       DATETIME         NULL,
    [UpdatedFromIP]     VARCHAR (15)     NULL,
    [VoucherDetailId]   VARCHAR (80)     NULL,
    [SetOffFinancingId] VARCHAR (10)     NULL,
    CONSTRAINT [PK_FinancingSubsequentTransaction] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_FinancingSubsequentTransaction_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_FinancingSubsequentTransaction_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_FinancingSubsequentTransaction_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_FinancingSubsequentTransaction_Entity] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_FinancingSubsequentTransaction_Financing] FOREIGN KEY ([FinancingId]) REFERENCES [TRN].[Financing] ([Id]),
    CONSTRAINT [FK_FinancingSubsequentTransaction_Party] FOREIGN KEY ([PartyId]) REFERENCES [HKP].[Party] ([Id]),
    CONSTRAINT [FK_FinancingSubsequentTransaction_PartyPlant] FOREIGN KEY ([PartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_FinancingSubsequentTransaction_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_FinancingSubsequentTransaction_SetOffFinancing] FOREIGN KEY ([SetOffFinancingId]) REFERENCES [TRN].[Financing] ([Id]),
    CONSTRAINT [FK_FinancingSubsequentTransaction_Voucher] FOREIGN KEY ([VoucherId]) REFERENCES [TRN].[Voucher] ([Id]),
    CONSTRAINT [FK_FinancingSubsequentTransaction_VoucherDetail] FOREIGN KEY ([VoucherDetailId]) REFERENCES [TRN].[VoucherDetail] ([Id]),
    CONSTRAINT [FK_FinancingSubsequentTransaction_VoucherType] FOREIGN KEY ([VoucherTypeId]) REFERENCES [SCS].[VoucherType] ([Id])
);

