CREATE TABLE [TRN].[GateEntry] (
    [Id]                     VARCHAR (50)     NOT NULL,
    [CompanyGroupId]         VARCHAR (10)     NULL,
    [CompanyId]              VARCHAR (10)     NULL,
    [PlantId]                VARCHAR (10)     NULL,
    [EntryDate]              DATETIME         NULL,
    [InvoicingPartyPlantId]  VARCHAR (12)     NULL,
    [InvoicingByAddress]     VARCHAR (300)    NULL,
    [DeliveryPartyPlantId]   VARCHAR (12)     NULL,
    [DeliveryByAddress]      VARCHAR (300)    NULL,
    [Description]            VARCHAR (500)    NULL,
    [PackageQty]             DECIMAL (18, 10) NULL,
    [ModeofTransport]        VARCHAR (25)     NULL,
    [Bill]                   VARCHAR (25)     NULL,
    [PersonName]             VARCHAR (30)     NULL,
    [MobileNo]               VARCHAR (30)     NULL,
    [Remarks]                VARCHAR (500)    NULL,
    [AddedBy]                VARCHAR (10)     NOT NULL,
    [AddedDate]              DATETIME         NOT NULL,
    [AddedFromIP]            VARCHAR (15)     NOT NULL,
    [UpdatedBy]              VARCHAR (10)     NULL,
    [UpdatedDate]            DATETIME         NULL,
    [UpdatedFromIp]          VARCHAR (15)     NULL,
    [GateEntryTime]          DATETIME         NULL,
    [EmployeeId]             VARCHAR (30)     NULL,
    [FlagStatus]             VARCHAR (30)     NULL,
    [EmployeeIdForGateEntry] VARCHAR (30)     NULL,
    [GateEntryType]          VARCHAR (50)     NULL,
    [PlantWiseGateId]        VARCHAR (10)     NULL,
    [LocalImported]          VARCHAR (30)     NULL,
    [PartyId]                VARCHAR (10)     NULL,
    CONSTRAINT [PK_GateEntry] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_DeliveryPartyPlantId] FOREIGN KEY ([DeliveryPartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_EmployeeId] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_EmployeeIdForGateEntry] FOREIGN KEY ([EmployeeIdForGateEntry]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_GateEntry] FOREIGN KEY ([PlantWiseGateId]) REFERENCES [dbo].[PlantWiseGate] ([Id]),
    CONSTRAINT [FK_GateEntry_DeliveryPartyPlantId] FOREIGN KEY ([DeliveryPartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_GateEntry_InvoicingPartyPlantId] FOREIGN KEY ([InvoicingPartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_InvoicingPartyPlantId] FOREIGN KEY ([InvoicingPartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id])
);

