CREATE TABLE [TRN].[GatePassDetails] (
    [Id]                           VARCHAR (30)     NOT NULL,
    [GatePassMasterId]             VARCHAR (30)     NOT NULL,
    [MaterialMasterId]             VARCHAR (30)     NULL,
    [ArticleId]                    VARCHAR (10)     NULL,
    [FirstCharacteristicsId]       VARCHAR (10)     NULL,
    [FirstCharacteristicsValueId]  VARCHAR (10)     NULL,
    [SecondCharacteristicsId]      VARCHAR (10)     NULL,
    [SecondCharacteristicsValueId] VARCHAR (10)     NULL,
    [ThirdCharacteristicsId]       VARCHAR (10)     NULL,
    [ThirdCharacteristicsValueId]  VARCHAR (10)     NULL,
    [MaterialDetail]               VARCHAR (300)    NULL,
    [TransactionQty]               DECIMAL (18, 10) NOT NULL,
    [TransactionUoMId]             VARCHAR (10)     NULL,
    [Remarks]                      VARCHAR (100)    NULL,
    [IsReturnable]                 BIT              NULL,
    [ReturnableDate]               DATETIME         NULL,
    [IsMutilated]                  BIT              NULL,
    [AddedBy]                      VARCHAR (30)     NULL,
    [AddedDate]                    DATETIME         NOT NULL,
    [AddedFromIP]                  VARCHAR (15)     NULL,
    [UpdatedBy]                    VARCHAR (30)     NULL,
    [UpdatedDate]                  DATETIME         NULL,
    [UpdatedFromIP]                VARCHAR (15)     NULL,
    [Rate]                         DECIMAL (18, 4)  NULL,
    [ChallanNo]                    VARCHAR (30)     NULL,
    [ChallanNoDetailId]            VARCHAR (30)     NULL,
    CONSTRAINT [PK_GatePassDetails] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_GatePassDetails_FirstCharacteristicsGP] FOREIGN KEY ([FirstCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_GatePassDetails_FirstCharacteristicsValueGP] FOREIGN KEY ([FirstCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_GatePassDetails_MaterialMaster] FOREIGN KEY ([MaterialMasterId]) REFERENCES [MST].[MaterialMaster] ([Id]),
    CONSTRAINT [FK_GatePassDetails_MaterialMasterArticle] FOREIGN KEY ([ArticleId]) REFERENCES [MST].[MaterialMasterArticle] ([Id]),
    CONSTRAINT [FK_GatePassDetails_SecondCharacteristicsGP] FOREIGN KEY ([SecondCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_GatePassDetails_SecondCharacteristicsValueGP] FOREIGN KEY ([SecondCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_GatePassDetails_ThirdCharacteristicsGP] FOREIGN KEY ([ThirdCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_GatePassDetails_ThirdCharacteristicsValueGP] FOREIGN KEY ([ThirdCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_GatePassMasterDetail_GatePassMasterId] FOREIGN KEY ([GatePassMasterId]) REFERENCES [TRN].[GatePassMaster] ([Id])
);

