CREATE TABLE [TRN].[GatePassMaster] (
    [Id]                                    VARCHAR (30)    NOT NULL,
    [CompanyGroupId]                        VARCHAR (10)    NOT NULL,
    [PlantId]                               VARCHAR (10)    NULL,
    [GatePassType]                          VARCHAR (50)    NULL,
    [GatePassStatus]                        VARCHAR (50)    NULL,
    [ReturnableDate]                        DATETIME        NULL,
    [GatePassEntryDate]                     DATETIME        NULL,
    [FromEmployeeId]                        VARCHAR (30)    NULL,
    [Through]                               VARCHAR (100)   NULL,
    [CourierName]                           VARCHAR (150)   NULL,
    [RunnerEmployeeId]                      VARCHAR (30)    NULL,
    [ToType]                                VARCHAR (50)    NULL,
    [ToPartyCode]                           VARCHAR (10)    NULL,
    [ToBuyerId]                             VARCHAR (10)    NULL,
    [ToPlantId]                             VARCHAR (10)    NULL,
    [ToUnitId]                              VARCHAR (10)    NULL,
    [ToDivisionId]                          VARCHAR (10)    NULL,
    [ToDepartment]                          VARCHAR (10)    NULL,
    [DepartmentEmployeeId]                  VARCHAR (30)    NULL,
    [OtherCompanyName]                      VARCHAR (100)   NULL,
    [PersonName]                            VARCHAR (100)   NULL,
    [MobileNo]                              VARCHAR (100)   NULL,
    [Address]                               VARCHAR (250)   NULL,
    [Remarks]                               VARCHAR (500)   NULL,
    [CheckedBy]                             VARCHAR (30)    NULL,
    [CheckedByStatus]                       VARCHAR (30)    NULL,
    [CheckedHoldRejectReason]               VARCHAR (300)   NULL,
    [ApprovedBy]                            VARCHAR (30)    NULL,
    [ApprovedByStatus]                      VARCHAR (30)    NULL,
    [ApprovedHoldRejectReason]              VARCHAR (300)   NULL,
    [SenderSecurityEmployeeId]              VARCHAR (30)    NULL,
    [SenderSecurityApprovedStatus]          VARCHAR (30)    NULL,
    [ReceiverSecurityEmployeeId]            VARCHAR (30)    NULL,
    [ReceiverSecurityApprovedStatus]        VARCHAR (30)    NULL,
    [VendorBuyerOtherCompanyReceivedStatus] VARCHAR (200)   NULL,
    [AddedBy]                               VARCHAR (30)    NULL,
    [AddedDate]                             DATETIME        NOT NULL,
    [AddedFromIP]                           VARCHAR (15)    NULL,
    [UpdatedBy]                             VARCHAR (30)    NULL,
    [UpdatedDate]                           DATETIME        NULL,
    [UpdatedFromIP]                         VARCHAR (15)    NULL,
    [ChallanNo]                             VARCHAR (50)    NULL,
    [TransportAgentMobileNo]                VARCHAR (30)    NULL,
    [TransportAgentName]                    VARCHAR (200)   NULL,
    [VehicleNo]                             VARCHAR (20)    NULL,
    [GateOutStatus]                         BIT             NULL,
    [GateRegisterType]                      VARCHAR (10)    NULL,
    [ReceivedChallanNO]                     VARCHAR (100)   NULL,
    [InvoiceNo]                             VARCHAR (100)   NULL,
    [InvoiceValue]                          DECIMAL (18, 2) NULL,
    CONSTRAINT [PK_GatePassMasterPK] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_GatePassMaster_ApprovedBy] FOREIGN KEY ([ApprovedBy]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_GatePassMaster_CheckedBy] FOREIGN KEY ([CheckedBy]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_GatePassMaster_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_GatePassMaster_DepartmentEmployeeId] FOREIGN KEY ([DepartmentEmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_GatePassMaster_FromEmployeeId] FOREIGN KEY ([FromEmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_GatePassMaster_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_GatePassMaster_ReceiverSecurityEmployeeId] FOREIGN KEY ([ReceiverSecurityEmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_GatePassMaster_SenderSecurityEmployeeId] FOREIGN KEY ([SenderSecurityEmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_GatePassMaster_ToBuyerId] FOREIGN KEY ([ToBuyerId]) REFERENCES [HKP].[Buyer] ([Id]),
    CONSTRAINT [FK_GatePassMaster_ToDepartment] FOREIGN KEY ([ToDepartment]) REFERENCES [ORG].[Department] ([Id]),
    CONSTRAINT [FK_GatePassMaster_ToDivisionId] FOREIGN KEY ([ToDivisionId]) REFERENCES [ORG].[Division] ([Id]),
    CONSTRAINT [FK_GatePassMaster_ToPartyCode] FOREIGN KEY ([ToPartyCode]) REFERENCES [HKP].[Party] ([Id]),
    CONSTRAINT [FK_GatePassMaster_ToPlantId] FOREIGN KEY ([ToPlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_GatePassMaster_ToUnitId] FOREIGN KEY ([ToUnitId]) REFERENCES [ORG].[Unit] ([Id])
);

