CREATE TABLE [TRN].[IndependentMasterOrder] (
    [Id]                     VARCHAR (10)    NOT NULL,
    [MasterOrderNo]          VARCHAR (50)    NOT NULL,
    [CompanyId]              VARCHAR (10)    NOT NULL,
    [PlantId]                VARCHAR (10)    NULL,
    [EntityId]               VARCHAR (10)    NULL,
    [PartyId]                VARCHAR (10)    NOT NULL,
    [InvoicingPartyPlantId]  VARCHAR (12)    NULL,
    [DeliveryPartyPlantId]   VARCHAR (12)    NULL,
    [InvoicingByAddress]     VARCHAR (250)   NULL,
    [DeliveryByAddress]      VARCHAR (250)   NULL,
    [BuyerId]                VARCHAR (10)    NULL,
    [BuyerBrandId]           VARCHAR (10)    NULL,
    [BuyerDivisionId]        VARCHAR (10)    NULL,
    [BuyerDepartmentId]      VARCHAR (10)    NULL,
    [BuyerReferenceNo]       VARCHAR (20)    NULL,
    [OwnReferenceNo]         VARCHAR (20)    NULL,
    [OrderStatusId]          VARCHAR (10)    NULL,
    [OrderCategoryId]        VARCHAR (10)    NULL,
    [CurrencyId]             VARCHAR (10)    NOT NULL,
    [SeasonId]               VARCHAR (10)    NULL,
    [OrderYear]              VARCHAR (9)     NULL,
    [TestingStandardId]      VARCHAR (10)    NULL,
    [Type]                   VARCHAR (15)    NULL,
    [TotalQty]               DECIMAL (18, 2) NOT NULL,
    [Rate]                   DECIMAL (18, 2) NOT NULL,
    [OrderWastagePercentage] DECIMAL (18, 2) NULL,
    [ExtraOrderPercentage]   DECIMAL (18, 2) NULL,
    [IsExtraOrderPercentage] BIT             CONSTRAINT [DF_IndependentMasterOrder_IsExtraOrderPercentage] DEFAULT ((0)) NOT NULL,
    [TotalQtyUOMId]          VARCHAR (10)    NULL,
    [ResponsiblePersonId]    VARCHAR (30)    NULL,
    [Remarks]                VARCHAR (25)    NULL,
    [AddedBy]                VARCHAR (30)    NOT NULL,
    [AddedDate]              DATETIME        NOT NULL,
    [AddedFromIP]            VARCHAR (15)    NOT NULL,
    [UpdatedBy]              VARCHAR (30)    NULL,
    [UpdatedDate]            DATETIME        NULL,
    [UpdatedFromIP]          VARCHAR (15)    NULL,
    CONSTRAINT [PK_IndependentMasterOrder] PRIMARY KEY CLUSTERED ([Id] ASC),
    FOREIGN KEY ([TotalQtyUOMId]) REFERENCES [SCS].[UnitOfMeasurement] ([Id]),
    FOREIGN KEY ([TotalQtyUOMId]) REFERENCES [SCS].[UnitOfMeasurement] ([Id]),
    FOREIGN KEY ([TotalQtyUOMId]) REFERENCES [SCS].[UnitOfMeasurement] ([Id]),
    FOREIGN KEY ([TotalQtyUOMId]) REFERENCES [SCS].[UnitOfMeasurement] ([Id]),
    CONSTRAINT [FK_IndependentMasterOrder_Buyer] FOREIGN KEY ([BuyerId]) REFERENCES [HKP].[Buyer] ([Id]),
    CONSTRAINT [FK_IndependentMasterOrder_BuyerBrand] FOREIGN KEY ([BuyerBrandId]) REFERENCES [HKP].[BuyerBrand] ([Id]),
    CONSTRAINT [FK_IndependentMasterOrder_BuyerDepartment] FOREIGN KEY ([BuyerDepartmentId]) REFERENCES [HKP].[BuyerDepartment] ([Id]),
    CONSTRAINT [FK_IndependentMasterOrder_BuyerDivision] FOREIGN KEY ([BuyerDivisionId]) REFERENCES [HKP].[BuyerDivision] ([Id]),
    CONSTRAINT [FK_IndependentMasterOrder_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_IndependentMasterOrder_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_IndependentMasterOrder_DeliveryPartyPlant] FOREIGN KEY ([DeliveryPartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_IndependentMasterOrder_EmployeeInformation] FOREIGN KEY ([ResponsiblePersonId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_IndependentMasterOrder_EntityId] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_IndependentMasterOrder_InvoicingPartyPlant] FOREIGN KEY ([InvoicingPartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_IndependentMasterOrder_OrderCategory] FOREIGN KEY ([OrderCategoryId]) REFERENCES [HKP].[OrderCategory] ([Id]),
    CONSTRAINT [FK_IndependentMasterOrder_OrderStatus] FOREIGN KEY ([OrderStatusId]) REFERENCES [HKP].[OrderStatus] ([Id]),
    CONSTRAINT [FK_IndependentMasterOrder_Party] FOREIGN KEY ([PartyId]) REFERENCES [HKP].[Party] ([Id]),
    CONSTRAINT [FK_IndependentMasterOrder_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_IndependentMasterOrder_Season] FOREIGN KEY ([SeasonId]) REFERENCES [HKP].[Season] ([Id]),
    CONSTRAINT [FK_IndependentMasterOrder_TestingStandard] FOREIGN KEY ([TestingStandardId]) REFERENCES [SCS].[TestingStandard] ([Id])
);

