CREATE TABLE [TRN].[InquiryMaster] (
    [Id]                    VARCHAR (30)    NOT NULL,
    [CompanyId]             VARCHAR (10)    NOT NULL,
    [CommitmentId]          VARCHAR (10)    NULL,
    [PlantId]               VARCHAR (10)    NULL,
    [EntityId]              VARCHAR (10)    NULL,
    [OrderType]             VARCHAR (20)    NULL,
    [PartyId]               VARCHAR (10)    NOT NULL,
    [BuyerId]               VARCHAR (10)    NULL,
    [BuyerBrandId]          VARCHAR (10)    NULL,
    [BuyerDivisionId]       VARCHAR (10)    NULL,
    [InquiryTypeId]         VARCHAR (10)    NULL,
    [CriticalLevelId]       VARCHAR (10)    NULL,
    [SeasonId]              VARCHAR (10)    NULL,
    [OrderYear]             VARCHAR (9)     NULL,
    [InquiryClosingDate]    DATETIME        NULL,
    [ProjectedQty]          DECIMAL (18, 2) NULL,
    [NoOfLineItem]          INT             NULL,
    [ResponsiblePersonId]   VARCHAR (30)    NULL,
    [Remarks]               VARCHAR (25)    NULL,
    [AddedBy]               VARCHAR (30)    NULL,
    [AddedDate]             DATETIME        NULL,
    [AddedFromIP]           VARCHAR (15)    NULL,
    [UpdatedBy]             VARCHAR (30)    NULL,
    [UpdatedDate]           DATETIME        NULL,
    [UpdatedFromIP]         VARCHAR (15)    NULL,
    [InvoicingPartyPlantId] VARCHAR (12)    NULL,
    [DeliveryPartyPlantId]  VARCHAR (12)    NULL,
    [InvoicingByAddress]    VARCHAR (250)   NULL,
    [DeliveryByAddress]     VARCHAR (250)   NULL,
    [TestingStandardId]     VARCHAR (10)    NULL,
    [ProjectQtyUOMId]       VARCHAR (10)    NULL,
    [Type]                  VARCHAR (15)    NULL,
    [SpecialTaxId]          VARCHAR (10)    NULL,
    [BuyerDepartmentId]     VARCHAR (10)    NULL,
    [TaskTemplateMasterId]  VARCHAR (10)    NULL,
    [ContractId]            VARCHAR (10)    NULL,
    [BuyerReferenceNo]      VARCHAR (20)    NULL,
    [OwnReferenceNo]        VARCHAR (20)    NULL,
    [InquirySource]         VARCHAR (30)    NULL,
    [InquiryDate]           DATETIME        NULL,
    CONSTRAINT [PK_InquiryMaster] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK__InquiryMa__Total__40BC116F] FOREIGN KEY ([ProjectQtyUOMId]) REFERENCES [SCS].[UnitOfMeasurement] ([Id]),
    CONSTRAINT [FK__InquiryMa__Total__6128E101] FOREIGN KEY ([ProjectQtyUOMId]) REFERENCES [SCS].[UnitOfMeasurement] ([Id]),
    CONSTRAINT [FK_InquiryMaster_Buyer] FOREIGN KEY ([BuyerId]) REFERENCES [HKP].[Buyer] ([Id]),
    CONSTRAINT [FK_InquiryMaster_BuyerBrand] FOREIGN KEY ([BuyerBrandId]) REFERENCES [HKP].[BuyerBrand] ([Id]),
    CONSTRAINT [FK_InquiryMaster_BuyerDepartment] FOREIGN KEY ([BuyerDepartmentId]) REFERENCES [HKP].[BuyerDepartment] ([Id]),
    CONSTRAINT [FK_InquiryMaster_BuyerDivision] FOREIGN KEY ([BuyerDivisionId]) REFERENCES [HKP].[BuyerDivision] ([Id]),
    CONSTRAINT [FK_InquiryMaster_Commitment] FOREIGN KEY ([CommitmentId]) REFERENCES [TRN].[Commitment] ([Id]),
    CONSTRAINT [FK_InquiryMaster_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_InquiryMaster_Contract] FOREIGN KEY ([ContractId]) REFERENCES [dbo].[Contract] ([Id])
);

