CREATE TABLE [TRN].[InventoryIssueReturn] (
    [Id]                   VARCHAR (10)  NOT NULL,
    [CompanyGroupId]       VARCHAR (10)  NOT NULL,
    [CompanyId]            VARCHAR (10)  NULL,
    [PlantId]              VARCHAR (10)  NULL,
    [EntityId]             VARCHAR (10)  NULL,
    [IssueDate]            DATE          NOT NULL,
    [AddedBy]              VARCHAR (30)  NOT NULL,
    [AddedDate]            DATETIME      NOT NULL,
    [AddedFromIP]          VARCHAR (15)  NOT NULL,
    [UpdatedBy]            VARCHAR (30)  NULL,
    [UpdatedDate]          DATETIME      NULL,
    [UpdatedFromIP]        VARCHAR (15)  NULL,
    [MaterialStorageId]    VARCHAR (10)  NULL,
    [Status]               VARCHAR (15)  NULL,
    [VoucherId]            VARCHAR (50)  NULL,
    [Remarks]              VARCHAR (250) NULL,
    [EmployeeId]           VARCHAR (30)  NULL,
    [CurrencyId]           VARCHAR (10)  NULL,
    [IssueType]            VARCHAR (15)  NULL,
    [CapitalizeVoucherId]  VARCHAR (50)  NULL,
    [IssueRequestMasterId] VARCHAR (10)  NULL,
    [OrderRefNo]           VARCHAR (300) NULL,
    CONSTRAINT [PK_[InventoryIssueReturn] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [fk_InventoryIssueRequestedMasterId] FOREIGN KEY ([IssueRequestMasterId]) REFERENCES [TRN].[IssueRequestMaster] ([Id]),
    CONSTRAINT [FK_InventoryIssueReturn_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_InventoryIssueReturn_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_InventoryIssueReturn_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_InventoryIssueReturn_EmployeeInformation] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_InventoryIssueReturn_Entity] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_InventoryIssueReturn_MaterialStorage] FOREIGN KEY ([MaterialStorageId]) REFERENCES [HKP].[MaterialStorage] ([Id]),
    CONSTRAINT [FK_InventoryIssueReturn_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_InventoryIssueReturn_Voucher] FOREIGN KEY ([VoucherId]) REFERENCES [TRN].[Voucher] ([Id]),
    CONSTRAINT [FK_TRN.InventoryIssueR-CapitalizeVoucher] FOREIGN KEY ([CapitalizeVoucherId]) REFERENCES [TRN].[Voucher] ([Id]),
    CONSTRAINT [FK_TRN.InventoryIssueReturn_CapitalizeVoucher] FOREIGN KEY ([CapitalizeVoucherId]) REFERENCES [TRN].[Voucher] ([Id])
);

