CREATE TABLE [TRN].[InventoryMaterial] (
    [Id]                           VARCHAR (10)     NOT NULL,
    [CompanyGroupId]               VARCHAR (10)     NOT NULL,
    [CompanyId]                    VARCHAR (10)     NOT NULL,
    [PlantId]                      VARCHAR (10)     NOT NULL,
    [MaterialStorageId]            VARCHAR (10)     NULL,
    [MaterialMasterId]             VARCHAR (30)     NULL,
    [ArticleId]                    VARCHAR (10)     NULL,
    [FirstCharacteristicsId]       VARCHAR (10)     NULL,
    [FirstCharacteristicsValueId]  VARCHAR (10)     NULL,
    [SecondCharacteristicsId]      VARCHAR (10)     NULL,
    [SecondCharacteristicsValueId] VARCHAR (10)     NULL,
    [ThirdCharacteristicsId]       VARCHAR (10)     NULL,
    [ThirdCharacteristicsValueId]  VARCHAR (10)     NULL,
    [TotalQty]                     DECIMAL (18, 10) NOT NULL,
    [AvgRate]                      DECIMAL (18, 10) NOT NULL,
    [AddedBy]                      VARCHAR (30)     NOT NULL,
    [AddedDate]                    DATETIME         NOT NULL,
    [AddedFromIP]                  VARCHAR (15)     NOT NULL,
    [UpdatedBy]                    VARCHAR (30)     NULL,
    [UpdatedDate]                  DATETIME         NULL,
    [UpdatedFromIP]                VARCHAR (15)     NULL,
    [OpeningBalanceId]             VARCHAR (30)     NULL,
    [CountryId]                    VARCHAR (10)     NULL,
    [VendorArticulationId]         VARCHAR (10)     NULL,
    [ShortageQty]                  DECIMAL (18, 10) NULL,
    [RejectionQty]                 DECIMAL (18, 10) NULL,
    [ApprovedQty]                  DECIMAL (18, 10) NULL,
    [Type]                         VARCHAR (200)    NULL,
    [Diameter]                     VARCHAR (200)    NULL,
    [LotNumber]                    VARCHAR (200)    NULL,
    CONSTRAINT [PK_InventoryReveiveMaterial] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_InventoryMaterial_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_InventoryMaterial_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_InventoryMaterial_Country] FOREIGN KEY ([CountryId]) REFERENCES [SCS].[Country] ([Id]),
    CONSTRAINT [FK_InventoryMaterial_MaterialMaster] FOREIGN KEY ([MaterialMasterId]) REFERENCES [MST].[MaterialMaster] ([Id]),
    CONSTRAINT [FK_InventoryMaterial_MaterialMasterArticle] FOREIGN KEY ([ArticleId]) REFERENCES [MST].[MaterialMasterArticle] ([Id]),
    CONSTRAINT [FK_InventoryMaterial_MaterialStorage] FOREIGN KEY ([MaterialStorageId]) REFERENCES [HKP].[MaterialStorage] ([Id]),
    CONSTRAINT [FK_InventoryMaterial_PlantId] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_InventoryMaterial_VendorArticulation] FOREIGN KEY ([VendorArticulationId]) REFERENCES [MST].[VendorArticulation] ([Id]),
    CONSTRAINT [FK_InventoryReveiveMaterial_FirstCharacteristics] FOREIGN KEY ([FirstCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_InventoryReveiveMaterial_FirstCharacteristicsValue] FOREIGN KEY ([FirstCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_InventoryReveiveMaterial_SecondCharacteristics] FOREIGN KEY ([SecondCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_InventoryReveiveMaterial_SecondCharacteristicsValue] FOREIGN KEY ([SecondCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_InventoryReveiveMaterial_ThirdCharacteristics] FOREIGN KEY ([ThirdCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_InventoryReveiveMaterial_ThirdCharacteristicsValue] FOREIGN KEY ([ThirdCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_InventoryReveiveMaterial_ThirdCharacteristicsValue1] FOREIGN KEY ([ThirdCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id])
);

