CREATE TABLE [TRN].[InventorySalesHistory] (
    [Id]                        VARCHAR (50)     NOT NULL,
    [InventorySalesDetailId]    VARCHAR (50)     NOT NULL,
    [InventoryReceiveDetailId]  VARCHAR (50)     NOT NULL,
    [Qty]                       DECIMAL (18, 10) NOT NULL,
    [BaseRate]                  DECIMAL (18, 10) NOT NULL,
    [AddedBy]                   VARCHAR (30)     NOT NULL,
    [AddedDate]                 DATETIME         NOT NULL,
    [AddedFromIP]               VARCHAR (15)     NOT NULL,
    [UpdatedBy]                 VARCHAR (30)     NULL,
    [UpdatedDate]               DATETIME         NULL,
    [UpdatedFromIP]             VARCHAR (15)     NULL,
    [IsCapitalize]              BIT              NULL,
    [CapitalizeVoucherDetailId] VARCHAR (80)     NULL,
    [IsRegister]                BIT              NULL,
    [IssueRequestDetailId]      VARCHAR (10)     NULL,
    [IssueReturnQty]            DECIMAL (18, 2)  NULL,
    [TotalBaseAmount]           DECIMAL (18, 10) NULL,
    [BooksCurrencyBaseAmount]   DECIMAL (18, 2)  NULL,
    CONSTRAINT [PK_InventorySalesHistory] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_InventorySalesDetail_CapitalizeVoucherDetail] FOREIGN KEY ([CapitalizeVoucherDetailId]) REFERENCES [TRN].[VoucherDetail] ([Id]),
    CONSTRAINT [FK_InventorySalesHistory_InventoryReceiveDetail] FOREIGN KEY ([InventoryReceiveDetailId]) REFERENCES [TRN].[InventoryReceiveDetail] ([Id]),
    CONSTRAINT [FK_InventorySalesHistory_InventorySalesDetail] FOREIGN KEY ([InventorySalesDetailId]) REFERENCES [TRN].[InventorySalesDetail] ([Id]),
    CONSTRAINT [FK_InventorySalesHistory_InventorySalesDetailId] FOREIGN KEY ([InventorySalesDetailId]) REFERENCES [TRN].[InventorySalesDetail] ([Id]),
    CONSTRAINT [FK_InventorySalesHistory_IssueRequestDetailId] FOREIGN KEY ([IssueRequestDetailId]) REFERENCES [TRN].[IssueRequest] ([Id])
);

