CREATE TABLE [TRN].[InventoryScrap] (
    [Id]                       VARCHAR (50)     NOT NULL,
    [CompanyGroupId]           VARCHAR (10)     NOT NULL,
    [CompanyId]                VARCHAR (10)     NULL,
    [PlantId]                  VARCHAR (10)     NULL,
    [EntityId]                 VARCHAR (10)     NULL,
    [ScrapDate]                DATE             NOT NULL,
    [AddedBy]                  VARCHAR (30)     NOT NULL,
    [AddedDate]                DATETIME         NOT NULL,
    [AddedFromIP]              VARCHAR (15)     NOT NULL,
    [UpdatedBy]                VARCHAR (30)     NULL,
    [UpdatedDate]              DATETIME         NULL,
    [UpdatedFromIP]            VARCHAR (15)     NULL,
    [MaterialStorageId]        VARCHAR (10)     NULL,
    [Status]                   VARCHAR (15)     NULL,
    [VoucherId]                VARCHAR (50)     NULL,
    [Remarks]                  VARCHAR (250)    NULL,
    [CheckedBy]                VARCHAR (30)     NULL,
    [CheckedByStatus]          VARCHAR (30)     NULL,
    [ApprovedBy]               VARCHAR (30)     NULL,
    [ApprovedByStatus]         VARCHAR (30)     NULL,
    [CheckedHoldRejectReason]  VARCHAR (500)    NULL,
    [ApprovedHoldRejectReason] VARCHAR (500)    NULL,
    [CurrencyId]               VARCHAR (10)     NULL,
    [IssueType]                VARCHAR (15)     NULL,
    [CapitalizeVoucherId]      VARCHAR (50)     NULL,
    [IssueRequestMasterId]     VARCHAR (10)     NULL,
    [DocRefNo]                 VARCHAR (20)     NULL,
    [DocDate]                  DATETIME         NULL,
    [ToCurrencyRate]           DECIMAL (18, 10) NULL,
    [NoteForAccounts]          TEXT             NULL,
    CONSTRAINT [PK_InventoryScrap] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_InventoryScrap_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_InventoryScrap_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_InventoryScrap_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_InventoryScrap_Entity] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_InventoryScrap_MaterialStorage] FOREIGN KEY ([MaterialStorageId]) REFERENCES [HKP].[MaterialStorage] ([Id]),
    CONSTRAINT [FK_InventoryScrap_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_InventoryScrap_Voucher] FOREIGN KEY ([VoucherId]) REFERENCES [TRN].[Voucher] ([Id]),
    CONSTRAINT [FK_TRN.InventoryScrap_CapitalizeVoucher] FOREIGN KEY ([CapitalizeVoucherId]) REFERENCES [TRN].[Voucher] ([Id])
);

