CREATE TABLE [TRN].[InventoryIssueReturnHistory] (
    [Id]                        VARCHAR (50)     NOT NULL,
    [InventoryIssueReturnId]    VARCHAR (10)     NOT NULL,
    [InventoryMaterialId]       VARCHAR (10)     NOT NULL,
    [InventoryReceiveDetailId]  VARCHAR (50)     NOT NULL,
    [Qty]                       DECIMAL (18, 10) NOT NULL,
    [Rate]                      DECIMAL (18, 10) NOT NULL,
    [AddedBy]                   VARCHAR (30)     NOT NULL,
    [AddedDate]                 DATETIME         NOT NULL,
    [AddedFromIP]               VARCHAR (15)     NOT NULL,
    [UpdatedBy]                 VARCHAR (30)     NULL,
    [UpdatedDate]               DATETIME         NULL,
    [UpdatedFromIP]             VARCHAR (15)     NULL,
    [IsCapitalize]              BIT              NULL,
    [CapitalizeVoucherDetailId] VARCHAR (80)     NULL,
    [IsRegister]                BIT              NULL,
    [IssueRequestDetailId]      VARCHAR (10)     NULL,
    [CostCenterId]              VARCHAR (10)     NULL,
    [StorageLocationId]         VARCHAR (10)     NULL,
    [BaseUOMId]                 VARCHAR (10)     NULL,
    [TransactionUoMId]          VARCHAR (10)     NULL,
    [TotalAmount]               DECIMAL (18, 10) NULL,
    CONSTRAINT [PK_InventoryIssueReturnHistory] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_InventoryIssueReturnHistory_CapitalizeVoucherDetail] FOREIGN KEY ([CapitalizeVoucherDetailId]) REFERENCES [TRN].[VoucherDetail] ([Id]),
    CONSTRAINT [FK_InventoryIssueReturnHistory_CostCenterId] FOREIGN KEY ([CostCenterId]) REFERENCES [ORG].[CostCenter] ([Id]),
    CONSTRAINT [FK_InventoryIssueReturnHistory_InventoryIssueReturn] FOREIGN KEY ([InventoryIssueReturnId]) REFERENCES [TRN].[InventoryIssueReturn] ([Id]),
    CONSTRAINT [FK_InventoryIssueReturnHistory_InventoryMaterial] FOREIGN KEY ([InventoryMaterialId]) REFERENCES [TRN].[InventoryMaterial] ([Id]),
    CONSTRAINT [FK_InventoryIssueReturnHistory_InventoryReceiveDetail] FOREIGN KEY ([InventoryReceiveDetailId]) REFERENCES [TRN].[InventoryReceiveDetail] ([Id]),
    CONSTRAINT [FK_InventoryIssueReturnHistory_IssueRequestDetailId] FOREIGN KEY ([IssueRequestDetailId]) REFERENCES [TRN].[IssueRequest] ([Id]),
    CONSTRAINT [FK_InventoryIssueReturnHistory_StorageLocationId] FOREIGN KEY ([StorageLocationId]) REFERENCES [HKP].[MaterialStorage] ([Id]),
    CONSTRAINT [FK_InventoryIssueReturnHistory_TransactionUoM] FOREIGN KEY ([TransactionUoMId]) REFERENCES [SCS].[UnitOfMeasurement] ([Id])
);

