CREATE TABLE [TRN].[InventoryReceiveDetail] (
    [Id]                                   VARCHAR (50)     NOT NULL,
    [InventoryReceiveId]                   VARCHAR (10)     NOT NULL,
    [InventoryMaterialId]                  VARCHAR (10)     NULL,
    [MaterialStorageId]                    VARCHAR (10)     NULL,
    [TransactionQty]                       DECIMAL (18, 10) NOT NULL,
    [TransactionUoMId]                     VARCHAR (10)     NOT NULL,
    [BaseQty]                              DECIMAL (18, 10) NOT NULL,
    [BaseUOMId]                            VARCHAR (10)     NULL,
    [BaseUoMFactor]                        DECIMAL (18, 10) NOT NULL,
    [MaterialTranRate]                     DECIMAL (18, 10) NOT NULL,
    [MaterialTranAmount]                   DECIMAL (18, 10) NOT NULL,
    [IssueQty]                             DECIMAL (18, 10) NULL,
    [AddedBy]                              VARCHAR (30)     NOT NULL,
    [AddedDate]                            DATETIME         NOT NULL,
    [AddedFromIP]                          VARCHAR (15)     NOT NULL,
    [UpdatedBy]                            VARCHAR (30)     NULL,
    [UpdatedDate]                          DATETIME         NULL,
    [UpdatedFromIP]                        VARCHAR (15)     NULL,
    [TotalTaxAmount]                       DECIMAL (18, 10) NOT NULL,
    [TotalMaterialTranAmount]              DECIMAL (18, 10) NOT NULL,
    [TotalMaterialBooksCurrencyAmount]     DECIMAL (18, 10) NULL,
    [ChargesTranAmount]                    DECIMAL (18, 10) NOT NULL,
    [ChargesTaxTranAmount]                 DECIMAL (18, 10) NULL,
    [TrnCurrencyBaseRate]                  DECIMAL (18, 10) NOT NULL,
    [BooksCurrencyBaseRate]                DECIMAL (18, 10) NOT NULL,
    [CountryId]                            VARCHAR (10)     NULL,
    [POId]                                 VARCHAR (10)     NULL,
    [PODetailsId]                          VARCHAR (10)     NULL,
    [BaseIssueQty]                         DECIMAL (20, 10) CONSTRAINT [DF__Inventory__BaseI__21D92E4A] DEFAULT ((0)) NOT NULL,
    [ShortageQty]                          DECIMAL (18, 10) NULL,
    [RejectionQty]                         DECIMAL (18, 10) NULL,
    [ApprovedQty]                          DECIMAL (18, 10) NULL,
    [ShortageRatePercent]                  DECIMAL (18, 4)  NULL,
    [ShortageValue]                        DECIMAL (18, 4)  NULL,
    [RejectRatePercent]                    DECIMAL (18, 4)  NULL,
    [RejectValue]                          DECIMAL (18, 4)  NULL,
    [RejectClamPercent]                    DECIMAL (18, 4)  NULL,
    [RequisitionId]                        VARCHAR (10)     NULL,
    [RequisitionDetailId]                  VARCHAR (30)     NULL,
    [Description]                          VARCHAR (200)    NULL,
    [ShortRejFlag]                         BIT              NULL,
    [PostDrGLGeneralInfoId]                VARCHAR (10)     NULL,
    [PostDrBudgetMasterId]                 VARCHAR (20)     NULL,
    [PostDrActivityId]                     VARCHAR (10)     NULL,
    [PostCRGLGeneralInfoId]                VARCHAR (10)     NULL,
    [PostCRBudgetMasterId]                 VARCHAR (20)     NULL,
    [PostCRActivityId]                     VARCHAR (10)     NULL,
    [CapitalizeVoucherDetailId]            VARCHAR (80)     NULL,
    [IsAsset]                              BIT              NULL,
    [PurchaseDocumentAcceptanceId]         VARCHAR (10)     NULL,
    [PurchaseDocumentAcceptanceDetailId]   VARCHAR (10)     NULL,
    [PurchaseReturnQty]                    DECIMAL (18, 2)  NULL,
    [IssueReturnQty]                       DECIMAL (18, 2)  NULL,
    [MaterialMasterOpeningBalanceDetailId] VARCHAR (50)     NULL,
    [ReductionByAdjustmentQty]             DECIMAL (18, 2)  NULL,
    [InventorySalesQty]                    DECIMAL (18, 2)  NULL,
    [InventoryScrapQty]                    DECIMAL (18, 2)  NULL,
    [LotNumber]                            VARCHAR (200)    NULL,
    [Diameter]                             VARCHAR (200)    NULL,
    [Type]                                 VARCHAR (200)    NULL,
    [InventoryTransferQty]                 DECIMAL (18, 2)  NULL,
    [TransferedFromGrnId]                  VARCHAR (10)     NULL,
    [GRNQty]                               DECIMAL (18, 10) NULL,
    [GRNTotalAmount]                       DECIMAL (18, 10) NULL,
    [LotNo]                                VARCHAR (200)    NULL,
    [QualityStatus]                        VARCHAR (100)    NULL,
    [GrossAmount]                          DECIMAL (18, 10) NULL,
    [DiscountAmount]                       DECIMAL (18, 10) NULL,
    [MasterOrderItemId]                    VARCHAR (10)     NULL,
    CONSTRAINT [PK_InventoryReceiveDetail] PRIMARY KEY CLUSTERED ([Id] ASC),
    FOREIGN KEY ([RequisitionDetailId]) REFERENCES [TRN].[MaterialRequsitionDetails] ([Id]),
    CONSTRAINT [FK_InventoryReceive_PurchaseDocumentAcceptanceDetail] FOREIGN KEY ([PurchaseDocumentAcceptanceDetailId]) REFERENCES [TRN].[PurchaseDocAcceptanceDetail] ([Id]),
    CONSTRAINT [FK_InventoryReceiveDetail_[PostCRBudgetMasterId] FOREIGN KEY ([PostCRBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_InventoryReceiveDetail_BaseUoM] FOREIGN KEY ([BaseUOMId]) REFERENCES [SCS].[UnitOfMeasurement] ([Id]),
    CONSTRAINT [FK_InventoryReceiveDetail_CapitalizeVoucherDetail] FOREIGN KEY ([CapitalizeVoucherDetailId]) REFERENCES [TRN].[VoucherDetail] ([Id]),
    CONSTRAINT [FK_InventoryReceiveDetail_Country] FOREIGN KEY ([CountryId]) REFERENCES [SCS].[Country] ([Id]),
    CONSTRAINT [FK_InventoryReceiveDetail_InventoryMaterial] FOREIGN KEY ([InventoryMaterialId]) REFERENCES [TRN].[InventoryMaterial] ([Id]),
    CONSTRAINT [FK_InventoryReceiveDetail_InventoryReceive] FOREIGN KEY ([InventoryReceiveId]) REFERENCES [TRN].[InventoryReceive] ([Id]),
    CONSTRAINT [FK_InventoryReceiveDetail_MasterOrderItemId] FOREIGN KEY ([MasterOrderItemId]) REFERENCES [TRN].[MasterOrderItem] ([Id]),
    CONSTRAINT [FK_InventoryReceiveDetail_MaterialStorage] FOREIGN KEY ([MaterialStorageId]) REFERENCES [HKP].[MaterialStorage] ([Id]),
    CONSTRAINT [FK_InventoryReceiveDetail_PostCRActivity] FOREIGN KEY ([PostCRActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_InventoryReceiveDetail_PostCRGLGeneralInfoId] FOREIGN KEY ([PostCRGLGeneralInfoId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_InventoryReceiveDetail_PostDrActivity] FOREIGN KEY ([PostDrActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_InventoryReceiveDetail_PostDrBudgetMasterId] FOREIGN KEY ([PostDrBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_InventoryReceiveDetail_PostDrGLGeneralInfo] FOREIGN KEY ([PostDrGLGeneralInfoId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_InventoryReceiveDetail_PurchaseDocumentAcceptance] FOREIGN KEY ([PurchaseDocumentAcceptanceId]) REFERENCES [TRN].[PurchaseDocAcceptance] ([Id]),
    CONSTRAINT [FK_InventoryReceiveDetail_TransactionUoM] FOREIGN KEY ([TransactionUoMId]) REFERENCES [SCS].[UnitOfMeasurement] ([Id]),
    CONSTRAINT [fk_PODetailsId] FOREIGN KEY ([PODetailsId]) REFERENCES [TRN].[PurchaseOrderDetail] ([Id]),
    CONSTRAINT [fk_PODetailsId1] FOREIGN KEY ([PODetailsId]) REFERENCES [TRN].[PurchaseOrderDetail] ([Id]),
    CONSTRAINT [fk_POIdD1] FOREIGN KEY ([POId]) REFERENCES [TRN].[PurchaseOrder] ([Id]),
    CONSTRAINT [Fk_RequisitionId1] FOREIGN KEY ([RequisitionId]) REFERENCES [TRN].[MaterialRequsitionMaster] ([Id])
);

