CREATE TABLE [TRN].[InvoiceWriteOffDetail] (
    [Id]                      VARCHAR (80)     NOT NULL,
    [InvoiceId]               VARCHAR (50)     NULL,
    [InvoiceDetailId]         VARCHAR (80)     NULL,
    [InvoiceWriteOffId]       VARCHAR (50)     NOT NULL,
    [CurrencyId]              VARCHAR (10)     NOT NULL,
    [GLGeneralInfoId]         VARCHAR (10)     NOT NULL,
    [BudgetMasterId]          VARCHAR (20)     NULL,
    [ActivityId]              VARCHAR (10)     NULL,
    [DocDate]                 DATETIME         NOT NULL,
    [DocRefNo]                VARCHAR (50)     NOT NULL,
    [Narration]               VARCHAR (250)    NULL,
    [TakenAmount]             DECIMAL (18, 10) CONSTRAINT [DF__InvoiceWr__Taken__48124F1D] DEFAULT ((0)) NOT NULL,
    [DeductionAmount]         DECIMAL (18, 10) CONSTRAINT [DF__InvoiceWr__Deduc__49067356] DEFAULT ((0)) NOT NULL,
    [Amount]                  DECIMAL (18, 10) NOT NULL,
    [Archive]                 BIT              NOT NULL,
    [AddedBy]                 VARCHAR (30)     NOT NULL,
    [AddedDate]               DATETIME         NOT NULL,
    [AddedFromIP]             VARCHAR (15)     NOT NULL,
    [UpdatedBy]               VARCHAR (30)     NULL,
    [UpdatedDate]             DATETIME         NULL,
    [UpdatedFromIP]           VARCHAR (15)     NULL,
    [PartyType]               VARCHAR (10)     NULL,
    [CompanyId]               VARCHAR (10)     NULL,
    [PlantId]                 VARCHAR (10)     NULL,
    [PartyId]                 VARCHAR (10)     NULL,
    [PartyPlantId]            VARCHAR (12)     NULL,
    [AdjustmentNoteId]        VARCHAR (50)     NULL,
    [AdjustmentNoteDetailId]  VARCHAR (80)     NULL,
    [MultiplePaymentDetailId] VARCHAR (100)    NULL,
    CONSTRAINT [PK_InvoiceWriteOffDetail] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_InvoiceWriteOffDetail_Activity] FOREIGN KEY ([ActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_InvoiceWriteOffDetail_AdjustmentNote] FOREIGN KEY ([AdjustmentNoteId]) REFERENCES [TRN].[AdjustmentNote] ([Id]),
    CONSTRAINT [FK_InvoiceWriteOffDetail_AdjustmentNoteDetail] FOREIGN KEY ([AdjustmentNoteDetailId]) REFERENCES [TRN].[AdjustmentNoteDetail] ([Id]),
    CONSTRAINT [FK_InvoiceWriteOffDetail_BudgetMaster] FOREIGN KEY ([BudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_InvoiceWriteOffDetail_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_InvoiceWriteOffDetail_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_InvoiceWriteOffDetail_GLGeneralInfo] FOREIGN KEY ([GLGeneralInfoId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_InvoiceWriteOffDetail_Invoice] FOREIGN KEY ([InvoiceId]) REFERENCES [TRN].[Invoice] ([Id]),
    CONSTRAINT [FK_InvoiceWriteOffDetail_InvoiceDetail] FOREIGN KEY ([InvoiceDetailId]) REFERENCES [TRN].[InvoiceDetail] ([Id]),
    CONSTRAINT [FK_InvoiceWriteOffDetail_InvoiceWriteOff] FOREIGN KEY ([InvoiceWriteOffId]) REFERENCES [TRN].[InvoiceWriteOff] ([Id]),
    CONSTRAINT [FK_InvoiceWriteOffDetail_MultiplePaymentDetail] FOREIGN KEY ([MultiplePaymentDetailId]) REFERENCES [TRN].[MultiplePaymentDetail] ([Id]),
    CONSTRAINT [FK_InvoiceWriteOffDetail_Party] FOREIGN KEY ([PartyId]) REFERENCES [HKP].[Party] ([Id]),
    CONSTRAINT [FK_InvoiceWriteOffDetail_PartyPlant] FOREIGN KEY ([PartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_InvoiceWriteOffDetail_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id])
);

