CREATE TABLE [TRN].[InvoiceDetail] (
    [Id]                    VARCHAR (80)     NOT NULL,
    [InvoiceId]             VARCHAR (50)     NOT NULL,
    [GLGeneralInfoId]       VARCHAR (10)     NOT NULL,
    [BudgetMasterId]        VARCHAR (20)     NULL,
    [ActivityId]            VARCHAR (10)     NULL,
    [MaterialGroupMasterId] VARCHAR (10)     NULL,
    [Amount]                DECIMAL (18, 10) NOT NULL,
    [TaxAmount]             DECIMAL (18, 10) NOT NULL,
    [NetAmount]             DECIMAL (18, 10) NOT NULL,
    [WrittenOffAmount]      DECIMAL (18, 10) NOT NULL,
    [IsWrittenOff]          BIT              NOT NULL,
    [IsBlock]               BIT              NOT NULL,
    [BlockReason]           VARCHAR (250)    NULL,
    [BlockDate]             DATETIME         NULL,
    [Archive]               BIT              NOT NULL,
    [AddedBy]               VARCHAR (30)     NOT NULL,
    [AddedDate]             DATETIME         NOT NULL,
    [AddedFromIP]           VARCHAR (15)     NOT NULL,
    [UpdatedBy]             VARCHAR (30)     NULL,
    [UpdatedDate]           DATETIME         NULL,
    [UpdatedFromIP]         VARCHAR (15)     NULL,
    CONSTRAINT [PK_InvoiceDetail] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_InvoiceDetail_Activity] FOREIGN KEY ([ActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_InvoiceDetail_BudgetMaster] FOREIGN KEY ([BudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_InvoiceDetail_GLGeneralInfo] FOREIGN KEY ([GLGeneralInfoId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_InvoiceDetail_Invoice] FOREIGN KEY ([InvoiceId]) REFERENCES [TRN].[Invoice] ([Id]),
    CONSTRAINT [FK_InvoiceDetail_MaterialGroupMaster] FOREIGN KEY ([MaterialGroupMasterId]) REFERENCES [MST].[MaterialGroupMaster] ([Id])
);

