CREATE TABLE [TRN].[InvoiceServiceMasterCharges] (
    [Id]                   VARCHAR (80)     NOT NULL,
    [CompanyGroupId]       VARCHAR (10)     NOT NULL,
    [CompanyId]            VARCHAR (10)     NOT NULL,
    [PlantId]              VARCHAR (10)     NOT NULL,
    [CurrencyId]           VARCHAR (10)     NOT NULL,
    [PartyType]            VARCHAR (10)     NOT NULL,
    [PartyId]              VARCHAR (10)     NOT NULL,
    [PartyPlantId]         VARCHAR (12)     NULL,
    [DeliveryPartyPlantId] VARCHAR (12)     NULL,
    [PaymentTermId]        VARCHAR (10)     NULL,
    [IsNonCreditable]      BIT              NULL,
    [CompanyCurrencyRate]  DECIMAL (18, 10) NOT NULL,
    [Narration]            VARCHAR (250)    NULL,
    [BaseOnDueDate]        DATETIME         NULL,
    [BaseNoOfDays]         INT              NOT NULL,
    [ActualDueDate]        DATETIME         NULL,
    [RevisedDueDate]       DATETIME         NULL,
    [IsPark]               BIT              NULL,
    [AddedBy]              VARCHAR (30)     NOT NULL,
    [AddedDate]            DATETIME         NOT NULL,
    [AddedFromIP]          VARCHAR (15)     NOT NULL,
    [UpdatedBy]            VARCHAR (30)     NULL,
    [UpdatedDate]          DATETIME         NULL,
    [UpdatedFromIP]        VARCHAR (15)     NULL,
    [DocDate]              DATETIME         NULL,
    [DocRefNo]             VARCHAR (50)     NULL,
    CONSTRAINT [PK_InvoiceServiceMasterCharges] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_InvoiceServiceMasterCharge_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_InvoiceServiceMasterCharges_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_InvoiceServiceMasterCharges_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_InvoiceServiceMasterCharges_DeliveryPartyPlant] FOREIGN KEY ([DeliveryPartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_InvoiceServiceMasterCharges_Party] FOREIGN KEY ([PartyId]) REFERENCES [HKP].[Party] ([Id]),
    CONSTRAINT [FK_InvoiceServiceMasterCharges_PartyPlant] FOREIGN KEY ([PartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_InvoiceServiceMasterCharges_PaymentTerm] FOREIGN KEY ([PaymentTermId]) REFERENCES [MST].[PaymentTerm] ([Id]),
    CONSTRAINT [FK_InvoiceServiceMasterCharges_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id])
);

