CREATE TABLE [TRN].[Invoice] (
    [Id]                             VARCHAR (50)     NOT NULL,
    [CompanyGroupId]                 VARCHAR (10)     NOT NULL,
    [CompanyId]                      VARCHAR (10)     NOT NULL,
    [PlantId]                        VARCHAR (10)     NOT NULL,
    [EntityId]                       VARCHAR (10)     NULL,
    [VoucherId]                      VARCHAR (50)     NULL,
    [OpeningBalanceId]               VARCHAR (30)     NULL,
    [InventoryReceiveId]             VARCHAR (10)     NULL,
    [PaymentTermId]                  VARCHAR (10)     NULL,
    [CurrencyId]                     VARCHAR (10)     NOT NULL,
    [SalesTypeId]                    VARCHAR (10)     NULL,
    [EmployeeId]                     VARCHAR (30)     NULL,
    [PartyId]                        VARCHAR (10)     NOT NULL,
    [PartyPlantId]                   VARCHAR (12)     NULL,
    [DeliveryPartyPlantId]           VARCHAR (12)     NULL,
    [PartyType]                      VARCHAR (10)     NOT NULL,
    [SourceType]                     VARCHAR (30)     NOT NULL,
    [PostingDate]                    DATETIME         NOT NULL,
    [DocDate]                        DATETIME         NOT NULL,
    [DocRefNo]                       VARCHAR (50)     NOT NULL,
    [Narration]                      VARCHAR (500)    NULL,
    [BaseOnDueDate]                  DATETIME         NULL,
    [BaseNoOfDays]                   INT              NOT NULL,
    [ActualDueDate]                  DATETIME         NULL,
    [RevisedDueDate]                 DATETIME         NULL,
    [Amount]                         DECIMAL (18, 10) NOT NULL,
    [WrittenOffAmount]               DECIMAL (18, 10) NOT NULL,
    [IsExcludingTax]                 BIT              NOT NULL,
    [IsSplit]                        BIT              NOT NULL,
    [IsWrittenOff]                   BIT              NOT NULL,
    [IsPark]                         BIT              NOT NULL,
    [Archive]                        BIT              NOT NULL,
    [AddedBy]                        VARCHAR (30)     NOT NULL,
    [AddedDate]                      DATETIME         NOT NULL,
    [AddedFromIP]                    VARCHAR (15)     NOT NULL,
    [UpdatedBy]                      VARCHAR (30)     NULL,
    [UpdatedDate]                    DATETIME         NULL,
    [UpdatedFromIP]                  VARCHAR (15)     NULL,
    [InvoiceNo]                      VARCHAR (30)     NULL,
    [FiscalYearId]                   VARCHAR (10)     NULL,
    [FiscalYearPeriodId]             VARCHAR (10)     NULL,
    [TaxYearId]                      VARCHAR (10)     NULL,
    [TaxYearPeriodId]                VARCHAR (10)     NULL,
    [VoucherTypeId]                  VARCHAR (10)     NULL,
    [VoucherDate]                    DATETIME         NULL,
    [SalesOrderNo]                   VARCHAR (30)     NULL,
    [CompanyCurrencyRate]            DECIMAL (18, 10) NOT NULL,
    [PaymentSource]                  VARCHAR (20)     NULL,
    [CashMasterId]                   VARCHAR (10)     NULL,
    [ExpenseBookingId]               VARCHAR (100)    NULL,
    [InvoiceServiceMasterChargesId]  VARCHAR (80)     NULL,
    [PurchaseDocAcceptanceId]        VARCHAR (10)     NULL,
    [ServiceAcknowledgementMasterId] VARCHAR (30)     NULL,
    [InventorySalesId]               VARCHAR (50)     NULL,
    [InvoiceGroupNo]                 VARCHAR (20)     NULL,
    CONSTRAINT [PK_Invoice] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Invoice_CashMaster] FOREIGN KEY ([CashMasterId]) REFERENCES [MST].[CashMaster] ([Id]),
    CONSTRAINT [FK_Invoice_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_Invoice_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_Invoice_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_Invoice_DeliveryPartyPlant] FOREIGN KEY ([DeliveryPartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_Invoice_EmployeeInformation] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_Invoice_Entity] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_Invoice_ExpenseBooking] FOREIGN KEY ([ExpenseBookingId]) REFERENCES [TRN].[ExpenseBooking] ([Id]),
    CONSTRAINT [FK_Invoice_FiscalYear] FOREIGN KEY ([FiscalYearId]) REFERENCES [SCS].[FiscalYear] ([Id]),
    CONSTRAINT [FK_Invoice_FiscalYearPeriod] FOREIGN KEY ([FiscalYearPeriodId]) REFERENCES [SCS].[FiscalYearPeriod] ([Id]),
    CONSTRAINT [FK_Invoice_InventorySales] FOREIGN KEY ([InventorySalesId]) REFERENCES [TRN].[InventorySales] ([Id]),
    CONSTRAINT [FK_Invoice_InvoiceServiceMasterCharges] FOREIGN KEY ([InvoiceServiceMasterChargesId]) REFERENCES [TRN].[InvoiceServiceMasterCharges] ([Id]),
    CONSTRAINT [FK_Invoice_OpeningBalance] FOREIGN KEY ([OpeningBalanceId]) REFERENCES [TRN].[OpeningBalance] ([Id]),
    CONSTRAINT [FK_Invoice_Party] FOREIGN KEY ([PartyId]) REFERENCES [HKP].[Party] ([Id]),
    CONSTRAINT [FK_Invoice_PartyPlant] FOREIGN KEY ([PartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_Invoice_PaymentTerm] FOREIGN KEY ([PaymentTermId]) REFERENCES [MST].[PaymentTerm] ([Id]),
    CONSTRAINT [FK_Invoice_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_Invoice_PurchaseDocAcceptance] FOREIGN KEY ([PurchaseDocAcceptanceId]) REFERENCES [TRN].[PurchaseDocAcceptance] ([Id]),
    CONSTRAINT [FK_Invoice_SalesType] FOREIGN KEY ([SalesTypeId]) REFERENCES [HKP].[SalesType] ([Id]),
    CONSTRAINT [FK_Invoice_ServiceAcknowledgementMaster] FOREIGN KEY ([ServiceAcknowledgementMasterId]) REFERENCES [TRN].[ServiceAcknowledgementMaster] ([Id]),
    CONSTRAINT [FK_Invoice_TaxYear] FOREIGN KEY ([TaxYearId]) REFERENCES [SCS].[TaxYear] ([Id]),
    CONSTRAINT [FK_Invoice_TaxYearPeriod] FOREIGN KEY ([TaxYearPeriodId]) REFERENCES [SCS].[TaxYearPeriod] ([Id]),
    CONSTRAINT [FK_Invoice_Voucher] FOREIGN KEY ([VoucherId]) REFERENCES [TRN].[Voucher] ([Id]),
    CONSTRAINT [FK_Invoice_VoucherType] FOREIGN KEY ([VoucherTypeId]) REFERENCES [SCS].[VoucherType] ([Id])
);

