CREATE TABLE [TRN].[InvoiceWriteOff] (
    [Id]                     VARCHAR (50)     NOT NULL,
    [CompanyGroupId]         VARCHAR (10)     NOT NULL,
    [CompanyId]              VARCHAR (10)     NOT NULL,
    [PlantId]                VARCHAR (10)     NOT NULL,
    [CurrencyId]             VARCHAR (10)     NOT NULL,
    [VoucherId]              VARCHAR (50)     NULL,
    [EmployeeId]             VARCHAR (30)     NULL,
    [PartyId]                VARCHAR (10)     NULL,
    [PartyType]              VARCHAR (10)     NOT NULL,
    [SourceType]             VARCHAR (30)     NOT NULL,
    [PostingDate]            DATETIME         NOT NULL,
    [DocDate]                DATETIME         NOT NULL,
    [DocRefNo]               VARCHAR (50)     NULL,
    [Narration]              VARCHAR (250)    NULL,
    [Amount]                 DECIMAL (18, 10) NOT NULL,
    [Archive]                BIT              NOT NULL,
    [AddedBy]                VARCHAR (30)     NOT NULL,
    [AddedDate]              DATETIME         NOT NULL,
    [AddedFromIP]            VARCHAR (15)     NOT NULL,
    [UpdatedBy]              VARCHAR (30)     NULL,
    [UpdatedDate]            DATETIME         NULL,
    [UpdatedFromIP]          VARCHAR (15)     NULL,
    [InvoiceWriteOffNo]      VARCHAR (30)     NULL,
    [FiscalYearId]           VARCHAR (10)     NULL,
    [FiscalYearPeriodId]     VARCHAR (10)     NULL,
    [TaxYearId]              VARCHAR (10)     NULL,
    [TaxYearPeriodId]        VARCHAR (10)     NULL,
    [VoucherTypeId]          VARCHAR (10)     NULL,
    [PartyPlantId]           VARCHAR (12)     NULL,
    [VoucherDate]            DATETIME         NOT NULL,
    [PaymentSource]          VARCHAR (20)     NULL,
    [BankMasterId]           VARCHAR (10)     NULL,
    [CashMasterId]           VARCHAR (10)     NULL,
    [IsPark]                 BIT              NOT NULL,
    [RoundingType]           VARCHAR (20)     NULL,
    [RoundingAmount]         DECIMAL (18, 10) NULL,
    [BankJournalId]          VARCHAR (20)     NULL,
    [BankJournalDetailId]    VARCHAR (30)     NULL,
    [InvoiceWriteOffGroupNo] VARCHAR (20)     NULL,
    CONSTRAINT [PK_InvoiceWriteOff] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_InvoiceWriteOff_BankJournal] FOREIGN KEY ([BankJournalId]) REFERENCES [TRN].[BankJournal] ([Id]),
    CONSTRAINT [FK_InvoiceWriteOff_BankJournalDetail] FOREIGN KEY ([BankJournalDetailId]) REFERENCES [TRN].[BankJournalDetail] ([Id]),
    CONSTRAINT [FK_InvoiceWriteOff_BankMaster] FOREIGN KEY ([BankMasterId]) REFERENCES [MST].[BankMaster] ([Id]),
    CONSTRAINT [FK_InvoiceWriteOff_CashMaster] FOREIGN KEY ([CashMasterId]) REFERENCES [MST].[CashMaster] ([Id]),
    CONSTRAINT [FK_InvoiceWriteOff_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_InvoiceWriteOff_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_InvoiceWriteOff_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_InvoiceWriteOff_EmployeeInformation] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_InvoiceWriteOff_FiscalYear] FOREIGN KEY ([FiscalYearId]) REFERENCES [SCS].[FiscalYear] ([Id]),
    CONSTRAINT [FK_InvoiceWriteOff_FiscalYearPeriod] FOREIGN KEY ([FiscalYearPeriodId]) REFERENCES [SCS].[FiscalYearPeriod] ([Id]),
    CONSTRAINT [FK_InvoiceWriteOff_Party] FOREIGN KEY ([PartyId]) REFERENCES [HKP].[Party] ([Id]),
    CONSTRAINT [FK_InvoiceWriteOff_PartyPlant] FOREIGN KEY ([PartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_InvoiceWriteOff_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_InvoiceWriteOff_TaxYear] FOREIGN KEY ([TaxYearId]) REFERENCES [SCS].[TaxYear] ([Id]),
    CONSTRAINT [FK_InvoiceWriteOff_TaxYearPeriod] FOREIGN KEY ([TaxYearPeriodId]) REFERENCES [SCS].[TaxYearPeriod] ([Id]),
    CONSTRAINT [FK_InvoiceWriteOff_Voucher] FOREIGN KEY ([VoucherId]) REFERENCES [TRN].[Voucher] ([Id]),
    CONSTRAINT [FK_InvoiceWriteOff_VoucherType] FOREIGN KEY ([VoucherTypeId]) REFERENCES [SCS].[VoucherType] ([Id])
);

