CREATE TABLE [TRN].[IssueRequest] (
    [Id]                           VARCHAR (10)    NOT NULL,
    [CostCenterId]                 VARCHAR (10)    NOT NULL,
    [ExpenseActivityId]            VARCHAR (20)    NULL,
    [BudgetMasterId]               VARCHAR (20)    NULL,
    [GLGeneralInfoId]              VARCHAR (10)    NULL,
    [RequisitionId]                VARCHAR (10)    NULL,
    [RequisitionDetailId]          VARCHAR (10)    NULL,
    [RequestedQty]                 DECIMAL (18, 4) NOT NULL,
    [RejectedQty]                  DECIMAL (18, 4) NOT NULL,
    [AddedBy]                      VARCHAR (30)    NOT NULL,
    [AddedDate]                    DATETIME        NOT NULL,
    [AddedFromIP]                  VARCHAR (15)    NOT NULL,
    [UpdatedBy]                    VARCHAR (30)    NULL,
    [UpdatedDate]                  DATETIME        NULL,
    [UpdatedFromIP]                VARCHAR (15)    NULL,
    [Preparedby]                   VARCHAR (30)    NULL,
    [CheckedBy]                    VARCHAR (30)    NULL,
    [CheckedByStatus]              VARCHAR (30)    NULL,
    [AuthorizedBy]                 VARCHAR (30)    NULL,
    [AuthorizedByStatus]           VARCHAR (30)    NULL,
    [IssueRequestMasterId]         VARCHAR (10)    NULL,
    [MaterialMasterId]             VARCHAR (30)    NULL,
    [ArticleId]                    VARCHAR (10)    NULL,
    [FirstCharacteristicsId]       VARCHAR (20)    NULL,
    [FirstCharacteristicsValueId]  VARCHAR (10)    NULL,
    [SecondCharacteristicsId]      VARCHAR (20)    NULL,
    [SecondCharacteristicsValueId] VARCHAR (10)    NULL,
    [ThirdCharacteristicsId]       VARCHAR (20)    NULL,
    [ThirdCharacteristicsValueId]  VARCHAR (10)    NULL,
    [TransactionUoMId]             VARCHAR (10)    NULL,
    [IssueSlipType]                VARCHAR (30)    NULL,
    [CountryId]                    VARCHAR (10)    NULL,
    [InventoryMaterialId]          VARCHAR (10)    NULL,
    CONSTRAINT [PK_IssueRequest] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [Fk_BudgetMasterId] FOREIGN KEY ([BudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [fk_ChekdBy1] FOREIGN KEY ([CheckedBy]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [Fk_CostCenterId] FOREIGN KEY ([CostCenterId]) REFERENCES [ORG].[CostCenter] ([Id]),
    CONSTRAINT [Fk_GLGenrlInfoId] FOREIGN KEY ([GLGeneralInfoId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [fk_IssueRequestArticId] FOREIGN KEY ([ArticleId]) REFERENCES [MST].[MaterialMasterArticle] ([Id]),
    CONSTRAINT [fk_IssueRequestAuthordBy] FOREIGN KEY ([AuthorizedBy]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [Fk_IssueRequestCountryId] FOREIGN KEY ([CountryId]) REFERENCES [SCS].[Country] ([Id]),
    CONSTRAINT [fk_IssueRequestMasterId] FOREIGN KEY ([IssueRequestMasterId]) REFERENCES [TRN].[IssueRequestMaster] ([Id]),
    CONSTRAINT [fk_IssueRequestMaterialMasterId] FOREIGN KEY ([MaterialMasterId]) REFERENCES [MST].[MaterialMaster] ([Id]),
    CONSTRAINT [Fk_IssueRequestRequisitionId] FOREIGN KEY ([RequisitionId]) REFERENCES [TRN].[MaterialRequsitionMaster] ([Id]),
    CONSTRAINT [Fk_IssueRequestThirdCharacteristics2] FOREIGN KEY ([ThirdCharacteristicsId]) REFERENCES [TRN].[ThirdCharacteristics] ([Id]),
    CONSTRAINT [fk_MaterialMasterId] FOREIGN KEY ([MaterialMasterId]) REFERENCES [MST].[MaterialMaster] ([Id]),
    CONSTRAINT [Fk_RequisitionId] FOREIGN KEY ([RequisitionId]) REFERENCES [TRN].[MaterialRequsitionMaster] ([Id]),
    CONSTRAINT [Fk_ThirdCharacteristics2] FOREIGN KEY ([ThirdCharacteristicsId]) REFERENCES [TRN].[ThirdCharacteristics] ([Id])
);

