CREATE TABLE [TRN].[MainProcessPlanning] (
    [Id]                      VARCHAR (30)    NOT NULL,
    [PlantId]                 VARCHAR (10)    NOT NULL,
    [ProcessId]               VARCHAR (10)    NULL,
    [LineId]                  VARCHAR (30)    NULL,
    [ProductionBatchMasterId] VARCHAR (30)    NULL,
    [EntityId]                VARCHAR (10)    NULL,
    [OurStyleId]              VARCHAR (10)    NULL,
    [Sequence]                INT             NOT NULL,
    [Date]                    DATE            NOT NULL,
    [Lsd]                     DATE            NOT NULL,
    [CommitmentDate]          DATE            NOT NULL,
    [RunningDay]              INT             NOT NULL,
    [TotalQty]                INT             NOT NULL,
    [DailyOutPut]             INT             NOT NULL,
    [StandardDailyOutPut]     INT             NOT NULL,
    [LearningCurveOutPut]     INT             NULL,
    [HasLearningCurve]        BIT             NOT NULL,
    [OffDayType]              VARCHAR (50)    NULL,
    [OffDay]                  BIT             NOT NULL,
    [IsFreeze]                BIT             NOT NULL,
    [Color]                   VARCHAR (30)    NULL,
    [AddedBy]                 VARCHAR (30)    NOT NULL,
    [AddedDate]               DATETIME        NOT NULL,
    [AddedFromIP]             VARCHAR (15)    NOT NULL,
    [UpdatedBy]               VARCHAR (30)    NULL,
    [UpdatedDate]             DATETIME        NULL,
    [UpdatedFromIP]           VARCHAR (15)    NULL,
    [MinAllocatedLine]        INT             NULL,
    [IncrementType]           VARCHAR (30)    NULL,
    [IncrementValue]          DECIMAL (18, 2) NULL,
    [StandardTime]            INT             NULL,
    [MinRequiredTargetHourly] INT             NULL,
    [DaysToGetTheTarget]      INT             NULL,
    [FirstDayOutPut]          INT             NULL,
    [MinWorkingDays]          INT             NULL,
    CONSTRAINT [PK_MainProcessPlaningBlock] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_MainProcessPlaning_Entity] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_MainProcessPlaning_OurStyle] FOREIGN KEY ([OurStyleId]) REFERENCES [HKP].[OurStyle] ([Id]),
    CONSTRAINT [FK_MainProcessPlaning_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_MainProcessPlaning_ProductionBatchMaster] FOREIGN KEY ([ProductionBatchMasterId]) REFERENCES [TRN].[ProductionOrder] ([Id]),
    CONSTRAINT [FK_MainProcessPlaning_WorkCenterMaster] FOREIGN KEY ([LineId]) REFERENCES [SCS].[WorkCenterMaster] ([Id]),
    CONSTRAINT [FK_MainProcessPlanning_Process] FOREIGN KEY ([ProcessId]) REFERENCES [HKP].[Process] ([Id])
);

