CREATE TABLE [TRN].[MasterOrder] (
    [Id]                     VARCHAR (10)    NOT NULL,
    [CompanyId]              VARCHAR (10)    NOT NULL,
    [CommitmentId]           VARCHAR (10)    NULL,
    [PlantId]                VARCHAR (10)    NULL,
    [EntityId]               VARCHAR (10)    NULL,
    [OrderType]              VARCHAR (20)    NULL,
    [PartyId]                VARCHAR (10)    NOT NULL,
    [BuyerId]                VARCHAR (10)    NULL,
    [BuyerBrandId]           VARCHAR (10)    NULL,
    [BuyerDivisionId]        VARCHAR (10)    NULL,
    [MasterOrderNo]          VARCHAR (50)    NOT NULL,
    [OrderStatusId]          VARCHAR (10)    NULL,
    [OrderCategoryId]        VARCHAR (10)    NULL,
    [SeasonId]               VARCHAR (10)    NULL,
    [OrderYear]              VARCHAR (9)     NULL,
    [CurrencyId]             VARCHAR (10)    NOT NULL,
    [TotalQty]               DECIMAL (18, 2) NOT NULL,
    [NoOfLineItem]           INT             NOT NULL,
    [ResponsiblePersonId]    VARCHAR (30)    NULL,
    [Remarks]                VARCHAR (25)    NULL,
    [AddedBy]                VARCHAR (30)    NOT NULL,
    [AddedDate]              DATETIME        NOT NULL,
    [AddedFromIP]            VARCHAR (15)    NOT NULL,
    [UpdatedBy]              VARCHAR (30)    NULL,
    [UpdatedDate]            DATETIME        NULL,
    [UpdatedFromIP]          VARCHAR (15)    NULL,
    [OrderWastagePercentage] DECIMAL (18, 2) NULL,
    [ExtraOrderPercentage]   DECIMAL (18, 2) NULL,
    [TotalQtyUOMId]          VARCHAR (10)    NULL,
    [InvoicingPartyPlantId]  VARCHAR (12)    NULL,
    [DeliveryPartyPlantId]   VARCHAR (12)    NULL,
    [InvoicingByAddress]     VARCHAR (250)   NULL,
    [DeliveryByAddress]      VARCHAR (250)   NULL,
    [TestingStandardId]      VARCHAR (10)    NULL,
    [IsReplacement]          BIT             CONSTRAINT [DF__MasterOrd__IsRep__4382A42A] DEFAULT ((0)) NOT NULL,
    [Type]                   VARCHAR (15)    NULL,
    [SpecialTaxId]           VARCHAR (10)    NULL,
    [IsExtraOrderPercentage] BIT             CONSTRAINT [DF__MasterOrd__IsExt__32230DFE] DEFAULT ((0)) NOT NULL,
    [BuyerDepartmentId]      VARCHAR (10)    NULL,
    [TaskTemplateMasterId]   VARCHAR (10)    NULL,
    [BuyerReferenceNo]       VARCHAR (50)    NULL,
    [OwnReferenceNo]         VARCHAR (50)    NULL,
    [OrderStatus]            VARCHAR (10)    NULL,
    [PaymentTermId]          VARCHAR (10)    NULL,
    [PaymentTermDays]        INT             NULL,
    CONSTRAINT [PK_MasterOrder] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK__MasterOrd__Total__0531374D] FOREIGN KEY ([TotalQtyUOMId]) REFERENCES [SCS].[UnitOfMeasurement] ([Id]),
    CONSTRAINT [FK__MasterOrd__Total__234ADEC2] FOREIGN KEY ([TotalQtyUOMId]) REFERENCES [SCS].[UnitOfMeasurement] ([Id]),
    CONSTRAINT [FK_MasterOrder_Buyer] FOREIGN KEY ([BuyerId]) REFERENCES [HKP].[Buyer] ([Id]),
    CONSTRAINT [FK_MasterOrder_BuyerBrand] FOREIGN KEY ([BuyerBrandId]) REFERENCES [HKP].[BuyerBrand] ([Id]),
    CONSTRAINT [FK_MasterOrder_BuyerDepartment] FOREIGN KEY ([BuyerDepartmentId]) REFERENCES [HKP].[BuyerDepartment] ([Id]),
    CONSTRAINT [FK_MasterOrder_BuyerDivision] FOREIGN KEY ([BuyerDivisionId]) REFERENCES [HKP].[BuyerDivision] ([Id]),
    CONSTRAINT [FK_MasterOrder_Commitment] FOREIGN KEY ([CommitmentId]) REFERENCES [TRN].[Commitment] ([Id]),
    CONSTRAINT [FK_MasterOrder_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_MasterOrder_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_MasterOrder_DeliveryPartyPlant] FOREIGN KEY ([DeliveryPartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_MasterOrder_EmployeeInformation] FOREIGN KEY ([ResponsiblePersonId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_MasterOrder_EntityId] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_MasterOrder_InvoicingPartyPlant] FOREIGN KEY ([InvoicingPartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_MasterOrder_IrregularTax] FOREIGN KEY ([SpecialTaxId]) REFERENCES [HKP].[SpecialTax] ([Id]),
    CONSTRAINT [FK_MasterOrder_OrderCategory] FOREIGN KEY ([OrderCategoryId]) REFERENCES [HKP].[OrderCategory] ([Id]),
    CONSTRAINT [FK_MasterOrder_OrderStatus] FOREIGN KEY ([OrderStatusId]) REFERENCES [HKP].[OrderStatus] ([Id]),
    CONSTRAINT [FK_MasterOrder_Party] FOREIGN KEY ([PartyId]) REFERENCES [HKP].[Party] ([Id]),
    CONSTRAINT [FK_MasterOrder_PaymentTerm] FOREIGN KEY ([PaymentTermId]) REFERENCES [MST].[PaymentTerm] ([Id]),
    CONSTRAINT [FK_MasterOrder_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_MasterOrder_Season] FOREIGN KEY ([SeasonId]) REFERENCES [HKP].[Season] ([Id]),
    CONSTRAINT [FK_MasterOrder_TestingStandard] FOREIGN KEY ([TestingStandardId]) REFERENCES [SCS].[TestingStandard] ([Id])
);

