CREATE TABLE [TRN].[MaterialRequsitionMaster] (
    [Id]                                 VARCHAR (10)  NOT NULL,
    [CompanyGroupId]                     VARCHAR (10)  NOT NULL,
    [EntityId]                           VARCHAR (10)  NOT NULL,
    [RequisitionType]                    VARCHAR (50)  NOT NULL,
    [RequirmentType]                     VARCHAR (50)  NOT NULL,
    [QualityApprovalResponsiblePersonId] VARCHAR (30)  NULL,
    [NeedSpecialAppId]                   VARCHAR (30)  NULL,
    [ReasonWhyItIsNotPlanEarlier]        VARCHAR (250) NULL,
    [AddedBy]                            VARCHAR (30)  NULL,
    [AddedDate]                          DATETIME      NOT NULL,
    [AddedFromIP]                        VARCHAR (15)  NULL,
    [UpdatedBy]                          VARCHAR (30)  NULL,
    [UpdatedDate]                        DATETIME      NULL,
    [UpdatedFromIP]                      VARCHAR (15)  NULL,
    [RequisitionDate]                    DATETIME      NULL,
    [Remarks]                            VARCHAR (500) NULL,
    [CheckedBy]                          VARCHAR (30)  NULL,
    [CheckedByStatus]                    VARCHAR (30)  NULL,
    [AuthorizedBy]                       VARCHAR (30)  NULL,
    [AuthorizedByStatus]                 VARCHAR (30)  NULL,
    [IsApproved]                         VARCHAR (30)  NULL,
    [RequisitionStatus]                  VARCHAR (30)  NULL,
    [ReqEmpId]                           VARCHAR (30)  NULL,
    [CheckedHoldRejectReason]            VARCHAR (300) NULL,
    [ApprovedHoldRejectReason]           VARCHAR (300) NULL,
    [CompanyId]                          VARCHAR (10)  NULL,
    [PlantId]                            VARCHAR (10)  NULL,
    [ToBeCheckedRetrieve]                BIT           NULL,
    [ToBeApporvedRetrieve]               BIT           NULL,
    [InActive]                           BIT           NULL,
    [OrderRefNo]                         VARCHAR (300) NULL,
    CONSTRAINT [PK_MaterialRequsitionMaster] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [fk_CkdBy] FOREIGN KEY ([CheckedBy]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [Fk_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [fk_CompanyId] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [Fk_Entity] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_MaterialRequsitionMaster] FOREIGN KEY ([ReqEmpId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [fk_NeedSpecialAppId] FOREIGN KEY ([NeedSpecialAppId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [fk_PlantId] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [fk_QualityAppResponPerId] FOREIGN KEY ([QualityApprovalResponsiblePersonId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [fk_QualityApproval] FOREIGN KEY ([QualityApprovalResponsiblePersonId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId])
);

