CREATE TABLE [TRN].[MaterialMasterOpeningBalanceDetail] (
    [Id]                                    VARCHAR (50)     NOT NULL,
    [OpeningBalanceId]                      VARCHAR (30)     NOT NULL,
    [PlantId]                               VARCHAR (10)     NULL,
    [EntityId]                              VARCHAR (10)     NULL,
    [MaterialMasterId]                      VARCHAR (30)     NULL,
    [FixedAssetMasterId]                    VARCHAR (30)     NULL,
    [BaseUOMId]                             VARCHAR (10)     NULL,
    [CurrencyId]                            VARCHAR (10)     NOT NULL,
    [AccumulatedDepreciationGLId]           VARCHAR (10)     NULL,
    [AccumulatedDepreciationBudgetMasterId] VARCHAR (20)     NULL,
    [AccumulatedDepreciationActivityId]     VARCHAR (10)     NULL,
    [AssetGLId]                             VARCHAR (10)     NULL,
    [AssetBudgetMasterId]                   VARCHAR (20)     NULL,
    [AssetActivityId]                       VARCHAR (10)     NULL,
    [ArticleId]                             VARCHAR (10)     NULL,
    [FirstCharacteristicsId]                VARCHAR (10)     NULL,
    [FirstCharacteristicsValueId]           VARCHAR (10)     NULL,
    [SecondCharacteristicsId]               VARCHAR (10)     NULL,
    [SecondCharacteristicsValueId]          VARCHAR (10)     NULL,
    [ThirdCharacteristicsId]                VARCHAR (10)     NULL,
    [ThirdCharacteristicsValueId]           VARCHAR (10)     NULL,
    [MaterialStorageId]                     VARCHAR (10)     NULL,
    [Quantity]                              DECIMAL (18, 10) NOT NULL,
    [Amount]                                DECIMAL (18, 10) NOT NULL,
    [AddedBy]                               VARCHAR (30)     NOT NULL,
    [AddedDate]                             DATETIME         NOT NULL,
    [AddedFromIP]                           VARCHAR (15)     NOT NULL,
    [UpdatedBy]                             VARCHAR (30)     NULL,
    [UpdatedDate]                           DATETIME         NULL,
    [UpdatedFromIP]                         VARCHAR (15)     NULL,
    [CountryId]                             VARCHAR (10)     NULL,
    [VendorArticulationId]                  VARCHAR (10)     NULL,
    [LotNumber]                             VARCHAR (200)    NULL,
    [Diameter]                              VARCHAR (200)    NULL,
    [Type]                                  VARCHAR (200)    NULL,
    CONSTRAINT [PK_MaterialMasterOpeningBalanceDetail] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_MaterialMasterOpeningBalanceDetail_AccumulatedDepreciationBudgetMaster] FOREIGN KEY ([AccumulatedDepreciationBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_MaterialMasterOpeningBalanceDetail_AccumulatedDepreciationGL] FOREIGN KEY ([AccumulatedDepreciationGLId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_MaterialMasterOpeningBalanceDetail_Activity] FOREIGN KEY ([AssetActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_MaterialMasterOpeningBalanceDetail_Activity_AccumulatedDepreciationActivityId] FOREIGN KEY ([AccumulatedDepreciationActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_MaterialMasterOpeningBalanceDetail_BaseUOM] FOREIGN KEY ([BaseUOMId]) REFERENCES [SCS].[UnitOfMeasurement] ([Id]),
    CONSTRAINT [FK_MaterialMasterOpeningBalanceDetail_BudgetMaster] FOREIGN KEY ([AssetBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_MaterialMasterOpeningBalanceDetail_Country] FOREIGN KEY ([CountryId]) REFERENCES [SCS].[Country] ([Id]),
    CONSTRAINT [FK_MaterialMasterOpeningBalanceDetail_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_MaterialMasterOpeningBalanceDetail_Entity] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_MaterialMasterOpeningBalanceDetail_FirstCharacteristicsId_Characteristics] FOREIGN KEY ([FirstCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_MaterialMasterOpeningBalanceDetail_FirstCharacteristicsValueId_Characteristics] FOREIGN KEY ([FirstCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_MaterialMasterOpeningBalanceDetail_FixedAssetMaster] FOREIGN KEY ([FixedAssetMasterId]) REFERENCES [MST].[FixedAssetMaster] ([Id]),
    CONSTRAINT [FK_MaterialMasterOpeningBalanceDetail_GLGeneralInfo_AssetGL] FOREIGN KEY ([AssetGLId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_MaterialMasterOpeningBalanceDetail_MaterialMaster] FOREIGN KEY ([MaterialMasterId]) REFERENCES [MST].[MaterialMaster] ([Id]),
    CONSTRAINT [FK_MaterialMasterOpeningBalanceDetail_MaterialMasterArticle] FOREIGN KEY ([ArticleId]) REFERENCES [MST].[MaterialMasterArticle] ([Id]),
    CONSTRAINT [FK_MaterialMasterOpeningBalanceDetail_MaterialStorage] FOREIGN KEY ([MaterialStorageId]) REFERENCES [HKP].[MaterialStorage] ([Id]),
    CONSTRAINT [FK_MaterialMasterOpeningBalanceDetail_OpeningBalance] FOREIGN KEY ([OpeningBalanceId]) REFERENCES [TRN].[OpeningBalance] ([Id]),
    CONSTRAINT [FK_MaterialMasterOpeningBalanceDetail_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_MaterialMasterOpeningBalanceDetail_SecondCharacteristicsId_Characteristics] FOREIGN KEY ([SecondCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_MaterialMasterOpeningBalanceDetail_SecondCharacteristicsValueId_Characteristics] FOREIGN KEY ([SecondCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_MaterialMasterOpeningBalanceDetail_SecondCharaThirdCharacteristicsValueId_Characteristics] FOREIGN KEY ([ThirdCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_MaterialMasterOpeningBalanceDetail_ThirdCharacteristicsId_Characteristics] FOREIGN KEY ([ThirdCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_MaterialMasterOpeningBalanceDetail_VendorArticulation] FOREIGN KEY ([VendorArticulationId]) REFERENCES [MST].[VendorArticulation] ([Id])
);

