CREATE TABLE [TRN].[OpeningBalanceDetail] (
    [Id]                                   VARCHAR (50)     NOT NULL,
    [OpeningBalanceId]                     VARCHAR (30)     NOT NULL,
    [GLGeneralInfoId]                      VARCHAR (10)     NOT NULL,
    [BudgetMasterId]                       VARCHAR (20)     NULL,
    [ActivityId]                           VARCHAR (10)     NULL,
    [CurrencyId]                           VARCHAR (10)     NOT NULL,
    [BankMasterId]                         VARCHAR (10)     NULL,
    [CashMasterId]                         VARCHAR (10)     NULL,
    [EmployeeId]                           VARCHAR (30)     NULL,
    [PartyId]                              VARCHAR (10)     NULL,
    [PartyPlantId]                         VARCHAR (12)     NULL,
    [CompanyId]                            VARCHAR (10)     NULL,
    [PlantId]                              VARCHAR (10)     NULL,
    [EntityId]                             VARCHAR (10)     NULL,
    [PartyType]                            VARCHAR (30)     NULL,
    [RefId]                                VARCHAR (50)     NULL,
    [DocRefNo]                             VARCHAR (50)     NOT NULL,
    [DocDate]                              DATETIME         NOT NULL,
    [BaseOnDueDate]                        DATETIME         NULL,
    [BaseNoOfDays]                         INT              NOT NULL,
    [Narration]                            VARCHAR (250)    NOT NULL,
    [Amount]                               DECIMAL (20, 10) NOT NULL,
    [RepaymentStartDate]                   DATETIME         NULL,
    [LifeOfYear]                           TINYINT          NULL,
    [NoOfInstallmentPerYear]               TINYINT          NULL,
    [NoOfPaidInstallment]                  TINYINT          NULL,
    [TotalNoOfInstallment]                 TINYINT          NULL,
    [ProfitRate]                           DECIMAL (18, 10) NOT NULL,
    [SanctionAmount]                       DECIMAL (20, 10) NOT NULL,
    [AddedBy]                              VARCHAR (30)     NOT NULL,
    [AddedDate]                            DATETIME         NOT NULL,
    [AddedFromIP]                          VARCHAR (15)     NOT NULL,
    [UpdatedBy]                            VARCHAR (30)     NULL,
    [UpdatedDate]                          DATETIME         NULL,
    [UpdatedFromIP]                        VARCHAR (15)     NULL,
    [DrAmount]                             DECIMAL (20, 10) NULL,
    [CrAmount]                             DECIMAL (20, 10) NULL,
    [TransactionTypeId]                    VARCHAR (10)     NULL,
    [FixedAssetMasterId]                   VARCHAR (30)     NULL,
    [FAType]                               VARCHAR (30)     NULL,
    [MaterialMasterOpeningBalanceDetailId] VARCHAR (50)     NULL,
    [LoanOpeningBalanceDetailId]           VARCHAR (50)     NULL,
    [SecurityOpeningBalanceDetailId]       VARCHAR (50)     NULL,
    [InvestmentOpeningBalanceDetailId]     VARCHAR (50)     NULL,
    [EquityOpeningBalanceDetailId]         VARCHAR (50)     NULL,
    [BankCurrencyId]                       VARCHAR (10)     NULL,
    [CashCurrencyId]                       VARCHAR (10)     NULL,
    [BankAmount]                           DECIMAL (20, 10) NULL,
    [MaterialMasterId]                     VARCHAR (30)     NULL,
    CONSTRAINT [PK_OpeningBalanceDetail] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_OpeningBalanceDetail_Activity] FOREIGN KEY ([ActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_OpeningBalanceDetail_BankMaster] FOREIGN KEY ([BankMasterId]) REFERENCES [MST].[BankMaster] ([Id]),
    CONSTRAINT [FK_OpeningBalanceDetail_BudgetMaster] FOREIGN KEY ([BudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_OpeningBalanceDetail_CashMaster] FOREIGN KEY ([CashMasterId]) REFERENCES [MST].[CashMaster] ([Id]),
    CONSTRAINT [FK_OpeningBalanceDetail_Company_To] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_OpeningBalanceDetail_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_OpeningBalanceDetail_EmployeeInformation] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_OpeningBalanceDetail_Entity] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_OpeningBalanceDetail_FixedAssetMaster] FOREIGN KEY ([FixedAssetMasterId]) REFERENCES [MST].[FixedAssetMaster] ([Id]),
    CONSTRAINT [FK_OpeningBalanceDetail_GLGeneralInfo] FOREIGN KEY ([GLGeneralInfoId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_OpeningBalanceDetail_MaterialMaster] FOREIGN KEY ([MaterialMasterId]) REFERENCES [MST].[MaterialMaster] ([Id]),
    CONSTRAINT [FK_OpeningBalanceDetail_MaterialMasterOpeningBalanceDetail] FOREIGN KEY ([MaterialMasterOpeningBalanceDetailId]) REFERENCES [TRN].[MaterialMasterOpeningBalanceDetail] ([Id]),
    CONSTRAINT [FK_OpeningBalanceDetail_OpeningBalance] FOREIGN KEY ([OpeningBalanceId]) REFERENCES [TRN].[OpeningBalance] ([Id]),
    CONSTRAINT [FK_OpeningBalanceDetail_Party] FOREIGN KEY ([PartyId]) REFERENCES [HKP].[Party] ([Id]),
    CONSTRAINT [FK_OpeningBalanceDetail_PartyPlant] FOREIGN KEY ([PartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_OpeningBalanceDetail_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id])
);

