CREATE TABLE [TRN].[PhysicalStockAdjustmentDetail] (
    [Id]                              VARCHAR (10)     NOT NULL,
    [PhysicalStockAdjustmentMasterID] VARCHAR (10)     NOT NULL,
    [InventoryMaterialId]             VARCHAR (10)     NOT NULL,
    [TransactionQty]                  DECIMAL (18, 10) NOT NULL,
    [BaseUOMId]                       VARCHAR (10)     NULL,
    [AvgRate]                         DECIMAL (18, 10) NOT NULL,
    [AvgAmount]                       DECIMAL (18, 10) NOT NULL,
    [PolicyRate]                      DECIMAL (18, 10) NOT NULL,
    [PolicyAmount]                    DECIMAL (18, 10) NOT NULL,
    [Policy]                          VARCHAR (15)     NOT NULL,
    [AddedBy]                         VARCHAR (30)     NOT NULL,
    [AddedDate]                       DATETIME         NOT NULL,
    [AddedFromIP]                     VARCHAR (15)     NOT NULL,
    [UpdatedBy]                       VARCHAR (30)     NULL,
    [UpdatedDate]                     DATETIME         NULL,
    [UpdatedFromIP]                   VARCHAR (15)     NULL,
    [BaseQty]                         DECIMAL (20, 10) DEFAULT ((0)) NOT NULL,
    [InventoryReceiveId]              VARCHAR (10)     NULL,
    [InventoryReceiveDetailId]        VARCHAR (50)     NOT NULL,
    [TransactionUoMId]                VARCHAR (10)     NULL,
    [ActivityId]                      VARCHAR (10)     NULL,
    [BudgetMasterId]                  VARCHAR (20)     NULL,
    [Remarks]                         VARCHAR (250)    NULL,
    [PostDrGLGeneralInfoId]           VARCHAR (10)     NULL,
    [PostDrBudgetMasterId]            VARCHAR (20)     NULL,
    [PostDrActivityId]                VARCHAR (10)     NULL,
    [PostCRGLGeneralInfoId]           VARCHAR (10)     NULL,
    [PostCRBudgetMasterId]            VARCHAR (20)     NULL,
    [PostCRActivityId]                VARCHAR (10)     NULL,
    [CostCenterId]                    VARCHAR (10)     NULL,
    [IsAsset]                         BIT              NULL,
    CONSTRAINT [PK_PhysicalStockAdjustmentDetail] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_PhysicalStockAdjustmentDetail_[PostCRBudgetMasterId] FOREIGN KEY ([PostCRBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_PhysicalStockAdjustmentDetail_Activity] FOREIGN KEY ([ActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_PhysicalStockAdjustmentDetail_BudgetMaster] FOREIGN KEY ([BudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_PhysicalStockAdjustmentDetail_CostCenterId] FOREIGN KEY ([CostCenterId]) REFERENCES [ORG].[CostCenter] ([Id]),
    CONSTRAINT [FK_PhysicalStockAdjustmentDetail_InventoryMaterial] FOREIGN KEY ([InventoryMaterialId]) REFERENCES [TRN].[InventoryMaterial] ([Id]),
    CONSTRAINT [FK_PhysicalStockAdjustmentDetail_InventoryReceive] FOREIGN KEY ([InventoryReceiveId]) REFERENCES [TRN].[InventoryReceive] ([Id]),
    CONSTRAINT [FK_PhysicalStockAdjustmentDetail_InventoryReceiveDetail] FOREIGN KEY ([InventoryReceiveDetailId]) REFERENCES [TRN].[InventoryReceiveDetail] ([Id]),
    CONSTRAINT [FK_PhysicalStockAdjustmentDetail_PostCRActivity] FOREIGN KEY ([PostCRActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_PhysicalStockAdjustmentDetail_PostCRGLGeneralInfoId] FOREIGN KEY ([PostCRGLGeneralInfoId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_PhysicalStockAdjustmentDetail_PostDrActivity] FOREIGN KEY ([PostDrActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_PhysicalStockAdjustmentDetail_PostDrBudgetMasterId] FOREIGN KEY ([PostDrBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_PhysicalStockAdjustmentDetail_PostDrGLGeneralInfo] FOREIGN KEY ([PostDrGLGeneralInfoId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_PhysicalStockAdjustmentDetail_TransactionUoM] FOREIGN KEY ([TransactionUoMId]) REFERENCES [SCS].[UnitOfMeasurement] ([Id])
);

