CREATE TABLE [TRN].[ProductionBatchProcessSet] (
    [Id]                      VARCHAR (10) NOT NULL,
    [CompanyGroupId]          VARCHAR (10) NULL,
    [CompanyId]               VARCHAR (10) NULL,
    [EntityId]                VARCHAR (10) NULL,
    [ProductionBatchMasterId] VARCHAR (30) NULL,
    [ProcessId]               VARCHAR (10) NULL,
    [ProcessTypeId]           VARCHAR (10) NULL,
    [VendorId]                VARCHAR (10) NULL,
    [EntityIdWithinCompany]   VARCHAR (10) NULL,
    [EntityIdWithinGroup]     VARCHAR (10) NULL,
    [RequiredDays]            INT          NULL,
    [LeadDays]                INT          NOT NULL,
    [IsJobWorkApplicable]     BIT          NULL,
    [JobWorkType]             VARCHAR (50) NULL,
    [IsBaseProcess]           BIT          NULL,
    [Symbol]                  VARCHAR (2)  NULL,
    [AddedBy]                 VARCHAR (30) NOT NULL,
    [AddedDate]               DATETIME     NOT NULL,
    [AddedFromIP]             VARCHAR (15) NOT NULL,
    [UpdatedBy]               VARCHAR (30) NULL,
    [UpdatedDate]             DATETIME     NULL,
    [UpdatedFromIP]           VARCHAR (15) NULL,
    CONSTRAINT [PK_ProductionBatchProcessSet] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ProductionBatchProcessSet_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_ProductionBatchProcessSet_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_ProductionBatchProcessSet_Entity] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_ProductionBatchProcessSet_EntityIdWithinCompany] FOREIGN KEY ([EntityIdWithinCompany]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_ProductionBatchProcessSet_EntityIdWithinGroup] FOREIGN KEY ([EntityIdWithinGroup]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_ProductionBatchProcessSet_Party] FOREIGN KEY ([VendorId]) REFERENCES [HKP].[Party] ([Id]),
    CONSTRAINT [FK_ProductionBatchProcessSet_Process] FOREIGN KEY ([ProcessId]) REFERENCES [HKP].[Process] ([Id]),
    CONSTRAINT [FK_ProductionBatchProcessSet_ProcessType] FOREIGN KEY ([ProcessTypeId]) REFERENCES [HKP].[ProcessType] ([Id]),
    CONSTRAINT [FK_ProductionBatchProcessSet_ProductionBatchMaster] FOREIGN KEY ([ProductionBatchMasterId]) REFERENCES [TRN].[ProductionOrder] ([Id])
);

