CREATE TABLE [TRN].[ProductionSummaryDetail] (
    [Id]                      VARCHAR (30)    NOT NULL,
    [ProductionSummaryId]     VARCHAR (30)    NULL,
    [FCharId]                 VARCHAR (20)    NULL,
    [SCharId]                 VARCHAR (20)    NULL,
    [TCharId]                 VARCHAR (20)    NULL,
    [Characteristics1Id]      VARCHAR (10)    NULL,
    [Characteristics1ValueId] VARCHAR (10)    NULL,
    [Characteristics2Id]      VARCHAR (10)    NULL,
    [Characteristics2ValueId] VARCHAR (10)    NULL,
    [Characteristics3Id]      VARCHAR (10)    NULL,
    [Characteristics3ValueId] VARCHAR (10)    NULL,
    [Qty]                     DECIMAL (18, 2) CONSTRAINT [DF_ProductionSummaryDetail_Characteristics3Qty] DEFAULT ((0)) NOT NULL,
    [AddedBy]                 VARCHAR (100)   NULL,
    [AddedDate]               DATETIME        NULL,
    [AddedFromIP]             VARCHAR (15)    NULL,
    [UpdatedBy]               VARCHAR (100)   NULL,
    [UpdatedDate]             DATETIME        NULL,
    [UpdatedFromIP]           VARCHAR (15)    NULL,
    CONSTRAINT [PK_ProductionSummaryDetail] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ProductionSummaryDetail_Characteristics] FOREIGN KEY ([Characteristics1Id]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_ProductionSummaryDetail_Characteristics1] FOREIGN KEY ([Characteristics2Id]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_ProductionSummaryDetail_Characteristics2] FOREIGN KEY ([Characteristics3Id]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_ProductionSummaryDetail_CharacteristicsValue] FOREIGN KEY ([Characteristics1ValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_ProductionSummaryDetail_CharacteristicsValue1] FOREIGN KEY ([Characteristics2ValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_ProductionSummaryDetail_CharacteristicsValue2] FOREIGN KEY ([Characteristics3ValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_ProductionSummaryDetail_FirstCharacteristics] FOREIGN KEY ([FCharId]) REFERENCES [TRN].[FirstCharacteristics] ([Id]),
    CONSTRAINT [FK_ProductionSummaryDetail_ProductionSummary] FOREIGN KEY ([ProductionSummaryId]) REFERENCES [TRN].[ProductionSummary] ([Id]),
    CONSTRAINT [FK_ProductionSummaryDetail_SecondCharacteristics] FOREIGN KEY ([SCharId]) REFERENCES [TRN].[SecondCharacteristics] ([Id]),
    CONSTRAINT [FK_ProductionSummaryDetail_ThirdCharacteristics] FOREIGN KEY ([TCharId]) REFERENCES [TRN].[ThirdCharacteristics] ([Id])
);

