CREATE TABLE [TRN].[ProductDefinition] (
    [Id]                           VARCHAR (10)    NOT NULL,
    [MaterialMasterId]             VARCHAR (30)    NOT NULL,
    [ProductMasterId]              VARCHAR (10)    NOT NULL,
    [SeasonId]                     VARCHAR (10)    NULL,
    [OurStyleId]                   VARCHAR (10)    NULL,
    [CostAndManufactureCurrencyId] VARCHAR (10)    NULL,
    [CostAndManufacture]           DECIMAL (18, 2) CONSTRAINT [DF_ProductDefinition_CostAndManufacture] DEFAULT ((0)) NOT NULL,
    [ProductEfficiency]            DECIMAL (18, 2) CONSTRAINT [DF_ProductDefinition_ProductEfficiency] DEFAULT ((0)) NOT NULL,
    [FirstdayOutPut]               INT             CONSTRAINT [DF_ProductDefinition_FirstdayOutPut] DEFAULT ((0)) NOT NULL,
    [IsFixed]                      VARCHAR (20)    NOT NULL,
    [IncrementValue]               INT             CONSTRAINT [DF_ProductDefinition_IncrementValue] DEFAULT ((0)) NOT NULL,
    [DaysToReachTheTarget]         INT             CONSTRAINT [DF_ProductDefinition_DaysToReachTheTarget] DEFAULT ((0)) NOT NULL,
    [Active]                       BIT             NOT NULL,
    [AddedBy]                      VARCHAR (30)    NOT NULL,
    [AddedDate]                    DATETIME        NOT NULL,
    [AddedFromIP]                  VARCHAR (15)    NULL,
    [UpdatedBy]                    VARCHAR (30)    NULL,
    [UpdatedDate]                  DATETIME        NULL,
    [UpdatedFromIP]                VARCHAR (15)    NULL,
    [TotalQty]                     INT             NOT NULL,
    [ProcessId]                    VARCHAR (10)    NULL,
    CONSTRAINT [PK_ProductDefinition] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ProductDefinition_Currency] FOREIGN KEY ([CostAndManufactureCurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_ProductDefinition_MaterialMaster] FOREIGN KEY ([MaterialMasterId]) REFERENCES [MST].[MaterialMaster] ([Id]),
    CONSTRAINT [FK_ProductDefinition_OurStyle] FOREIGN KEY ([OurStyleId]) REFERENCES [HKP].[OurStyle] ([Id]),
    CONSTRAINT [FK_ProductDefinition_Process] FOREIGN KEY ([ProcessId]) REFERENCES [HKP].[Process] ([Id]),
    CONSTRAINT [FK_ProductDefinition_ProductMaster] FOREIGN KEY ([ProductMasterId]) REFERENCES [MST].[ProductMaster] ([Id]),
    CONSTRAINT [FK_ProductDefinition_Season] FOREIGN KEY ([SeasonId]) REFERENCES [HKP].[Season] ([Id])
);

