CREATE TABLE [TRN].[ProductionSummary] (
    [Id]                        VARCHAR (30)    NOT NULL,
    [PlantId]                   VARCHAR (10)    NULL,
    [EntityId]                  VARCHAR (10)    NULL,
    [ProcessId]                 VARCHAR (10)    NULL,
    [SalesOrderId]              VARCHAR (20)    NULL,
    [MaterialMasterId]          VARCHAR (30)    NULL,
    [ArticleId]                 VARCHAR (10)    NULL,
    [WorkCenterMasterId]        VARCHAR (30)    NULL,
    [ProductionDate]            DATETIME        NULL,
    [ProductionGrade]           VARCHAR (10)    NULL,
    [Quantity]                  DECIMAL (18, 2) NULL,
    [ProductionShiftId]         VARCHAR (10)    NULL,
    [AddedBy]                   VARCHAR (100)   NULL,
    [AddedDate]                 DATETIME        NULL,
    [AddedFromIP]               VARCHAR (15)    NULL,
    [UpdatedBy]                 VARCHAR (100)   NULL,
    [UpdatedDate]               DATETIME        NULL,
    [UpdatedFromIP]             VARCHAR (15)    NULL,
    [ProductionBookingPeriodId] VARCHAR (10)    NULL,
    [ProductionOrderId]         VARCHAR (30)    NULL,
    [MentorId]                  VARCHAR (30)    NULL,
    [ResponsiblePersonId]       VARCHAR (30)    NULL,
    [InTime]                    DATETIME        NULL,
    [OutTime]                   DATETIME        NULL,
    [ConsumeHour]               DECIMAL (18, 2) NULL,
    [ManPower]                  DECIMAL (18, 2) NULL,
    [CheckedBy]                 VARCHAR (30)    NULL,
    [Remarks]                   VARCHAR (300)   NULL,
    [ToProcessId]               VARCHAR (10)    NULL,
    [ToWorkCenterMasterId]      VARCHAR (30)    NULL,
    [FromSFGInventoryId]        VARCHAR (10)    NULL,
    [ToSFGInventoryId]          VARCHAR (10)    NULL,
    [LotNumber]                 VARCHAR (20)    NULL,
    [PackingConfirmationId]     VARCHAR (30)    NULL,
    CONSTRAINT [PK__Producti__3214EC278317E085] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK__Productio__Plant__70FE8AC0] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK__Productio__WorkC__2C696951] FOREIGN KEY ([WorkCenterMasterId]) REFERENCES [SCS].[WorkCenterMaster] ([Id]),
    CONSTRAINT [FK__Production_ToWorkCenterMaster] FOREIGN KEY ([ToWorkCenterMasterId]) REFERENCES [SCS].[WorkCenterMaster] ([Id]),
    CONSTRAINT [FK_ProductionSummary_CheckedBy_EmployeeInformation] FOREIGN KEY ([CheckedBy]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_ProductionSummary_CompliedShiftGrouping] FOREIGN KEY ([ProductionShiftId]) REFERENCES [MST].[CompliedShiftGrouping] ([Id]),
    CONSTRAINT [FK_ProductionSummary_Entity] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_ProductionSummary_FromSFGInventory] FOREIGN KEY ([FromSFGInventoryId]) REFERENCES [HKP].[SFGInventory] ([Id]),
    CONSTRAINT [FK_ProductionSummary_MaterialMaster] FOREIGN KEY ([MaterialMasterId]) REFERENCES [MST].[MaterialMaster] ([Id]),
    CONSTRAINT [FK_ProductionSummary_MaterialMasterArticle] FOREIGN KEY ([ArticleId]) REFERENCES [MST].[MaterialMasterArticle] ([Id]),
    CONSTRAINT [FK_ProductionSummary_Mentor_EmployeeInformation] FOREIGN KEY ([MentorId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_ProductionSummary_Process] FOREIGN KEY ([ProcessId]) REFERENCES [HKP].[Process] ([Id]),
    CONSTRAINT [FK_ProductionSummary_ProductionBookingPeriod] FOREIGN KEY ([ProductionBookingPeriodId]) REFERENCES [HKP].[ProductionBookingPeriod] ([Id]),
    CONSTRAINT [FK_ProductionSummary_ProductionOrder] FOREIGN KEY ([ProductionOrderId]) REFERENCES [TRN].[ProductionOrder] ([Id]),
    CONSTRAINT [FK_ProductionSummary_ResponsiblePerson_EmployeeInformation] FOREIGN KEY ([ResponsiblePersonId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_ProductionSummary_SalesOrder] FOREIGN KEY ([SalesOrderId]) REFERENCES [TRN].[SalesOrder] ([Id]),
    CONSTRAINT [FK_ProductionSummary_ToProcess] FOREIGN KEY ([ToProcessId]) REFERENCES [HKP].[Process] ([Id]),
    CONSTRAINT [FK_ProductionSummary_ToSFGInventory] FOREIGN KEY ([ToSFGInventoryId]) REFERENCES [HKP].[SFGInventory] ([Id])
);

