CREATE TABLE [TRN].[ProductionBulletinTemplateDetail] (
    [Id]                                 VARCHAR (10)    NOT NULL,
    [ProductionBulletinTemplateMasterId] VARCHAR (10)    NOT NULL,
    [Sequence]                           DECIMAL (18, 2) NOT NULL,
    [OperationVariationId]               VARCHAR (10)    NULL,
    [OperationGroup]                     VARCHAR (50)    NULL,
    [SkillId]                            VARCHAR (10)    NULL,
    [MachineVarientId]                   VARCHAR (10)    NULL,
    [FGZoneId]                           VARCHAR (10)    NULL,
    [FGComponentId]                      VARCHAR (10)    NULL,
    [AdditionalSPT]                      DECIMAL (18, 4) NOT NULL,
    [TotalSPT]                           DECIMAL (18, 4) NOT NULL,
    [AllotedWorkstation]                 DECIMAL (18, 4) NULL,
    [AllotedManpower]                    DECIMAL (18, 4) NULL,
    [AttachmentId]                       VARCHAR (10)    NULL,
    [GaugeFolderId]                      VARCHAR (10)    NULL,
    [OperationConsumptionId]             VARCHAR (10)    NULL,
    [OperationTypeId]                    VARCHAR (10)    NULL,
    [Frequency]                          DECIMAL (18, 4) NOT NULL,
    [Remark]                             VARCHAR (150)   NULL,
    [AddedBy]                            VARCHAR (30)    NOT NULL,
    [AddedDate]                          DATETIME        NOT NULL,
    [AddedFromIP]                        VARCHAR (15)    NOT NULL,
    [UpdatedBy]                          VARCHAR (30)    NULL,
    [UpdatedDate]                        DATETIME        NULL,
    [UpdatedFromIP]                      VARCHAR (15)    NULL,
    [OperationCategoryId]                VARCHAR (10)    NULL,
    [QualityLevel]                       VARCHAR (10)    NULL,
    [AvgAllotedTime]                     DECIMAL (18, 4) CONSTRAINT [DF_ProductionBulletinTemplateDetail_AvgAllotedTime] DEFAULT ((0)) NOT NULL,
    [OperationTargetPerHr]               DECIMAL (18, 4) CONSTRAINT [DF__Productio__Opera__72144138] DEFAULT ((0)) NOT NULL,
    [RequiredManPower]                   DECIMAL (18, 4) CONSTRAINT [DF__Productio__Requi__73086571] DEFAULT ((0)) NOT NULL,
    [OperationMasterId]                  VARCHAR (10)    NULL,
    [SPI]                                INT             DEFAULT ((0)) NULL,
    [NoOfStitch]                         INT             DEFAULT ((0)) NULL,
    [OperationLength]                    DECIMAL (18, 2) DEFAULT ((0)) NULL,
    [StitchCodeId]                       VARCHAR (10)    NULL,
    [FabricWidth]                        DECIMAL (18, 4) DEFAULT ((0)) NULL,
    [NeedleDescription]                  VARCHAR (100)   NULL,
    [NeedleMaterialMasterId]             VARCHAR (30)    NULL,
    [NeedleArticleId]                    VARCHAR (10)    NULL,
    [BobbinDescription]                  VARCHAR (100)   NULL,
    [BobbinMaterialMasterId]             VARCHAR (30)    NULL,
    [BobbinArticleId]                    VARCHAR (10)    NULL,
    [LooperDescription]                  VARCHAR (100)   NULL,
    [LooperMaterialMasterId]             VARCHAR (30)    NULL,
    [LooperArticleId]                    VARCHAR (10)    NULL,
    [SPIConsumption]                     DECIMAL (18, 4) NULL,
    [Consumption]                        DECIMAL (18, 4) NULL,
    [NeedleConsumption]                  DECIMAL (18, 4) DEFAULT ((0)) NULL,
    [BobbinConsumption]                  DECIMAL (18, 4) DEFAULT ((0)) NULL,
    [LooperConsumption]                  DECIMAL (18, 4) DEFAULT ((0)) NULL,
    CONSTRAINT [PK_ProductionBulletinTemplateDetail] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ProductionBulletinTemplateDetail_Attachment] FOREIGN KEY ([AttachmentId]) REFERENCES [HKP].[Attachment] ([Id]),
    CONSTRAINT [FK_ProductionBulletinTemplateDetail_BobbinArticle] FOREIGN KEY ([BobbinArticleId]) REFERENCES [MST].[MaterialMasterArticle] ([Id]),
    CONSTRAINT [FK_ProductionBulletinTemplateDetail_BobbinMaterialMaster] FOREIGN KEY ([BobbinMaterialMasterId]) REFERENCES [MST].[MaterialMaster] ([Id]),
    CONSTRAINT [FK_ProductionBulletinTemplateDetail_FGComponent] FOREIGN KEY ([FGComponentId]) REFERENCES [HKP].[FGComponent] ([Id]),
    CONSTRAINT [FK_ProductionBulletinTemplateDetail_FGZone] FOREIGN KEY ([FGZoneId]) REFERENCES [HKP].[FGZone] ([Id]),
    CONSTRAINT [FK_ProductionBulletinTemplateDetail_GaugeFolder] FOREIGN KEY ([GaugeFolderId]) REFERENCES [HKP].[GaugeFolder] ([Id]),
    CONSTRAINT [FK_ProductionBulletinTemplateDetail_LooperArticle] FOREIGN KEY ([LooperArticleId]) REFERENCES [MST].[MaterialMasterArticle] ([Id]),
    CONSTRAINT [FK_ProductionBulletinTemplateDetail_LooperMaterialMaster] FOREIGN KEY ([LooperMaterialMasterId]) REFERENCES [MST].[MaterialMaster] ([Id]),
    CONSTRAINT [FK_ProductionBulletinTemplateDetail_MachineVariant] FOREIGN KEY ([MachineVarientId]) REFERENCES [MST].[MaterialMasterArticle] ([Id]),
    CONSTRAINT [FK_ProductionBulletinTemplateDetail_NeedleArticle] FOREIGN KEY ([NeedleArticleId]) REFERENCES [MST].[MaterialMasterArticle] ([Id]),
    CONSTRAINT [FK_ProductionBulletinTemplateDetail_NeedleMaterialMaster] FOREIGN KEY ([NeedleMaterialMasterId]) REFERENCES [MST].[MaterialMaster] ([Id]),
    CONSTRAINT [FK_ProductionBulletinTemplateDetail_OperationCategory] FOREIGN KEY ([OperationCategoryId]) REFERENCES [HKP].[OperationCategory] ([Id]),
    CONSTRAINT [FK_ProductionBulletinTemplateDetail_OperationConsumption] FOREIGN KEY ([OperationConsumptionId]) REFERENCES [HKP].[OperationConsumption] ([Id]),
    CONSTRAINT [FK_ProductionBulletinTemplateDetail_OperationMaster] FOREIGN KEY ([OperationMasterId]) REFERENCES [MST].[OperationMaster] ([Id]),
    CONSTRAINT [FK_ProductionBulletinTemplateDetail_OperationType] FOREIGN KEY ([OperationTypeId]) REFERENCES [HKP].[OperationType] ([Id]),
    CONSTRAINT [FK_ProductionBulletinTemplateDetail_OperationVariation] FOREIGN KEY ([OperationVariationId]) REFERENCES [MST].[OperationVariation] ([Id]),
    CONSTRAINT [FK_ProductionBulletinTemplateDetail_ProductionBulletinTemplateMaster] FOREIGN KEY ([ProductionBulletinTemplateMasterId]) REFERENCES [TRN].[ProductionBulletinTemplateMaster] ([Id]),
    CONSTRAINT [FK_ProductionBulletinTemplateDetail_Skill] FOREIGN KEY ([SkillId]) REFERENCES [HKP].[Skill] ([Id])
);


GO
CREATE NONCLUSTERED INDEX [Ind_ProductionBulletin]
    ON [TRN].[ProductionBulletinTemplateDetail]([Id] ASC, [ProductionBulletinTemplateMasterId] ASC, [OperationVariationId] ASC);

