CREATE TABLE [TRN].[PurchaseBookingSoda] (
    [Id]               VARCHAR (20) NOT NULL,
    [LocationId]       VARCHAR (20) NOT NULL,
    [Date]             DATETIME     NOT NULL,
    [Time]             DATETIME     NOT NULL,
    [CropPlanningId]   VARCHAR (20) NOT NULL,
    [ValidationDate]   DATETIME     NOT NULL,
    [CustomerId]       VARCHAR (10) NOT NULL,
    [AddedBy]          VARCHAR (30) NOT NULL,
    [AddedDate]        DATETIME     NOT NULL,
    [AddedFromIP]      VARCHAR (15) NOT NULL,
    [UpdatedBy]        VARCHAR (30) NULL,
    [UpdatedDate]      DATETIME     NULL,
    [UpdatedFromIP]    VARCHAR (15) NULL,
    [IsConfirmed]      BIT          NULL,
    [ConfirmationBy]   VARCHAR (30) NULL,
    [ConfirmationDate] DATETIME     NULL,
    [ConfirmationIP]   VARCHAR (15) NULL,
    [IsApproved]       BIT          NULL,
    [ApprovalBy]       VARCHAR (30) NULL,
    [ApprovalDate]     DATETIME     NULL,
    [ApprovalIP]       VARCHAR (15) NULL,
    [IsPayment]        BIT          NULL,
    [PaymentBy]        VARCHAR (30) NULL,
    [PaymentDate]      DATETIME     NULL,
    [PaymentIP]        VARCHAR (15) NULL,
    [VoucherId]        VARCHAR (20) NULL,
    [VoucherDate]      DATETIME     NULL,
    [IsVoucher]        BIT          NULL,
    CONSTRAINT [PK_PurchaseBookingSoda] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_PurchaseBookingSoda_CropPlanning] FOREIGN KEY ([CropPlanningId]) REFERENCES [TRN].[CropPlanning] ([Id]),
    CONSTRAINT [FK_PurchaseBookingSoda_Customer] FOREIGN KEY ([CustomerId]) REFERENCES [HKP].[Party] ([Id]),
    CONSTRAINT [FK_PurchaseBookingSoda_Location] FOREIGN KEY ([LocationId]) REFERENCES [HKP].[CropRateLocation] ([Id])
);

