CREATE TABLE [TRN].[PurchaseOrderDetail] (
    [Id]                           VARCHAR (10)     NOT NULL,
    [InventoryReceiveId]           VARCHAR (10)     NOT NULL,
    [InventoryMaterialId]          VARCHAR (10)     NULL,
    [MaterialStorageId]            VARCHAR (10)     NULL,
    [TransactionQty]               DECIMAL (18, 10) NOT NULL,
    [TransactionUoMId]             VARCHAR (10)     NOT NULL,
    [BaseQty]                      DECIMAL (18, 10) NOT NULL,
    [BaseUOMId]                    VARCHAR (10)     NULL,
    [BaseUoMFactor]                DECIMAL (18, 10) NOT NULL,
    [TransactionRate]              DECIMAL (18, 10) NOT NULL,
    [TransactionAmount]            DECIMAL (18, 10) NOT NULL,
    [IssueQty]                     DECIMAL (18, 10) NULL,
    [AddedBy]                      VARCHAR (30)     NOT NULL,
    [AddedDate]                    DATETIME         NOT NULL,
    [AddedFromIP]                  VARCHAR (15)     NOT NULL,
    [UpdatedBy]                    VARCHAR (30)     NULL,
    [UpdatedDate]                  DATETIME         NULL,
    [UpdatedFromIP]                VARCHAR (15)     NULL,
    [TotalTaxAmount]               DECIMAL (18, 10) NOT NULL,
    [BaseAmount]                   DECIMAL (18, 10) NOT NULL,
    [ChargesAmount]                DECIMAL (18, 10) NOT NULL,
    [WithInvoiceRate]              DECIMAL (18, 10) NOT NULL,
    [AfterInvoiceRate]             DECIMAL (18, 10) NOT NULL,
    [CountryId]                    VARCHAR (10)     NULL,
    [GRNRcvQty]                    DECIMAL (18, 10) NULL,
    [QtyStatus]                    BIT              NULL,
    [MasterOrderId]                VARCHAR (10)     NULL,
    [MasterOrderDetailId]          VARCHAR (10)     NULL,
    [Description]                  VARCHAR (300)    NULL,
    [DeliveryDate]                 DATETIME         NULL,
    [RequisitionId]                VARCHAR (10)     NULL,
    [RequisitionDetailId]          VARCHAR (10)     NULL,
    [ArticleId]                    VARCHAR (10)     NULL,
    [FirstCharacteristicsId]       VARCHAR (10)     NULL,
    [FirstCharacteristicsValueId]  VARCHAR (10)     NULL,
    [SecondCharacteristicsId]      VARCHAR (10)     NULL,
    [SecondCharacteristicsValueId] VARCHAR (10)     NULL,
    [ThirdCharacteristicsId]       VARCHAR (10)     NULL,
    [ThirdCharacteristicsValueId]  VARCHAR (10)     NULL,
    [AcceptanceRcvQty]             DECIMAL (18, 2)  NULL,
    [AcceptanceRcvStatusQty]       BIT              NULL,
    [RefferenceNo]                 VARCHAR (1000)   NULL,
    [Tolerance]                    DECIMAL (18, 4)  NULL,
    CONSTRAINT [PK_PurchaseOrderDetail] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [fk_ArticleId] FOREIGN KEY ([ArticleId]) REFERENCES [MST].[MaterialMasterArticle] ([Id]),
    CONSTRAINT [fk_ArticleId1] FOREIGN KEY ([ArticleId]) REFERENCES [MST].[MaterialMasterArticle] ([Id]),
    CONSTRAINT [fk_BaseUOMId] FOREIGN KEY ([BaseUOMId]) REFERENCES [SCS].[UnitOfMeasurement] ([Id]),
    CONSTRAINT [fk_BaseUOMId1] FOREIGN KEY ([BaseUOMId]) REFERENCES [SCS].[UnitOfMeasurement] ([Id]),
    CONSTRAINT [fk_CountryId] FOREIGN KEY ([CountryId]) REFERENCES [SCS].[Country] ([Id]),
    CONSTRAINT [fk_CountryId1] FOREIGN KEY ([CountryId]) REFERENCES [SCS].[Country] ([Id]),
    CONSTRAINT [fk_FirstCharacteristicsValueId] FOREIGN KEY ([FirstCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [fk_MastOrderId] FOREIGN KEY ([MasterOrderId]) REFERENCES [TRN].[MasterOrder] ([Id]),
    CONSTRAINT [fk_MaterialStorageId] FOREIGN KEY ([MaterialStorageId]) REFERENCES [HKP].[MaterialStorage] ([Id]),
    CONSTRAINT [fk_RequtionId] FOREIGN KEY ([RequisitionId]) REFERENCES [TRN].[MaterialRequsitionMaster] ([Id]),
    CONSTRAINT [fk_SecondCharacteristicsValueId] FOREIGN KEY ([SecondCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [fk_ThirdCharacteristicsValueId] FOREIGN KEY ([ThirdCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [fk_ThirdCharacteristicsValueId1] FOREIGN KEY ([ThirdCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [Po_fk] FOREIGN KEY ([InventoryReceiveId]) REFERENCES [TRN].[PurchaseOrder] ([Id]),
    CONSTRAINT [Po_fk1] FOREIGN KEY ([InventoryReceiveId]) REFERENCES [TRN].[PurchaseOrder] ([Id])
);

