CREATE TABLE [TRN].[PurchaseOrderGroupDetails] (
    [Id]                           VARCHAR (10) NOT NULL,
    [CompanyGroupId]               VARCHAR (10) NOT NULL,
    [PurchaseOrderGroupId]         VARCHAR (10) NOT NULL,
    [MaterialMasterId]             VARCHAR (30) NULL,
    [ArticleId]                    VARCHAR (10) NULL,
    [FirstCharacteristicsId]       VARCHAR (20) NULL,
    [FirstCharacteristicsValueId]  VARCHAR (10) NULL,
    [SecondCharacteristicsId]      VARCHAR (20) NULL,
    [SecondCharacteristicsValueId] VARCHAR (10) NULL,
    [ThirdCharacteristicsId]       VARCHAR (20) NULL,
    [ThirdCharacteristicsValueId]  VARCHAR (10) NULL,
    [ResponsiblePerson]            VARCHAR (30) NULL,
    [EmployeeCode]                 VARCHAR (30) NULL,
    [AddedBy]                      VARCHAR (30) NOT NULL,
    [AddedDate]                    DATETIME     NOT NULL,
    [AddedFromIP]                  VARCHAR (15) NOT NULL,
    [UpdatedBy]                    VARCHAR (30) NULL,
    [UpdatedDate]                  DATETIME     NULL,
    [UpdatedFromIP]                VARCHAR (15) NULL,
    [CompanyId]                    VARCHAR (10) NULL,
    [PlantId]                      VARCHAR (10) NULL,
    CONSTRAINT [PK__Purchase__3214EC0743675E09] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK__PurchaseO__Purch__4B2627F7] FOREIGN KEY ([PurchaseOrderGroupId]) REFERENCES [TRN].[PurchaseOrderGroup] ([Id]),
    CONSTRAINT [FK_PurchaseOrderGroupDetails_PurchaseOrderGroupDetails] FOREIGN KEY ([Id]) REFERENCES [TRN].[PurchaseOrderGroupDetails] ([Id]),
    CONSTRAINT [FK_PurchaseOrderGroupDetails_PurchaseOrderGroupDetails1] FOREIGN KEY ([Id]) REFERENCES [TRN].[PurchaseOrderGroupDetails] ([Id]),
    CONSTRAINT [FK_PurchaseOrderGroupDetails_PurchaseOrderGroupDetails2] FOREIGN KEY ([Id]) REFERENCES [TRN].[PurchaseOrderGroupDetails] ([Id]),
    CONSTRAINT [FK_PurchaseOrderGroupDetails_PurchaseOrderGroupDetails3] FOREIGN KEY ([Id]) REFERENCES [TRN].[PurchaseOrderGroupDetails] ([Id])
);

