CREATE TABLE [TRN].[PurchaseDocAcceptance] (
    [Id]                      VARCHAR (10)    NOT NULL,
    [CompanyGroupId]          VARCHAR (10)    NOT NULL,
    [CompanyId]               VARCHAR (10)    NOT NULL,
    [PlantId]                 VARCHAR (10)    NOT NULL,
    [AcceptanceNo]            VARCHAR (30)    NOT NULL,
    [EntryDate]               DATE            NOT NULL,
    [AddedBy]                 VARCHAR (30)    NOT NULL,
    [AddedDate]               DATETIME        NOT NULL,
    [AddedFromIP]             VARCHAR (15)    NOT NULL,
    [UpdatedBy]               VARCHAR (30)    NULL,
    [UpdatedDate]             DATETIME        NULL,
    [UpdatedFromIP]           VARCHAR (15)    NULL,
    [AcceptanceDate]          DATE            NOT NULL,
    [POId]                    VARCHAR (10)    NULL,
    [CheckedBy]               VARCHAR (30)    NULL,
    [CheckedByStatus]         VARCHAR (30)    NULL,
    [AuthorizedBy]            VARCHAR (30)    NULL,
    [AuthorizedByStatus]      VARCHAR (30)    NULL,
    [Remarks]                 VARCHAR (300)   NULL,
    [PurchaseLCId]            VARCHAR (10)    NULL,
    [VoucherId]               VARCHAR (50)    NULL,
    [PartyId]                 VARCHAR (10)    NULL,
    [PartyPlantId]            VARCHAR (12)    NULL,
    [DueDate]                 DATETIME        NULL,
    [InvoiceDate]             DATETIME        NULL,
    [AcceptancePaymentSource] VARCHAR (10)    NULL,
    [AcceptanceRate]          DECIMAL (18, 2) NULL,
    [IsNonCreditable]         BIT             DEFAULT ((0)) NOT NULL,
    [PrePurchaseInvoiceId]    VARCHAR (10)    NULL,
    [InvoiceNo]               VARCHAR (25)    NULL,
    CONSTRAINT [PK_PurchaseDocAcceptance] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_PurchaseDocAcceptance_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_PurchaseDocAcceptance_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_PurchaseDocAcceptance_Party] FOREIGN KEY ([PartyId]) REFERENCES [HKP].[Party] ([Id]),
    CONSTRAINT [FK_PurchaseDocAcceptance_PartyPlant] FOREIGN KEY ([PartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_PurchaseDocAcceptance_PlantId] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_PurchaseDocAcceptance_PO] FOREIGN KEY ([POId]) REFERENCES [TRN].[PurchaseOrder] ([Id]),
    CONSTRAINT [FK_PurchaseDocAcceptance_PrePurchaseInvoice] FOREIGN KEY ([PrePurchaseInvoiceId]) REFERENCES [dbo].[PrePurchaseInvoice] ([Id]),
    CONSTRAINT [FK_PurchaseDocAcceptance_PurchaseLCId] FOREIGN KEY ([PurchaseLCId]) REFERENCES [dbo].[PurchaseLC] ([Id]),
    CONSTRAINT [FK_PurchaseDocAcceptance_Voucher] FOREIGN KEY ([VoucherId]) REFERENCES [TRN].[Voucher] ([Id])
);

