CREATE TABLE [TRN].[PurchaseDocAcceptanceDetail] (
    [Id]                           VARCHAR (10)     NOT NULL,
    [PurchaseDocAcceptanceId]      VARCHAR (10)     NOT NULL,
    [MaterialMasterId]             VARCHAR (30)     NULL,
    [ArticleId]                    VARCHAR (10)     NULL,
    [FirstCharacteristicsId]       VARCHAR (10)     NULL,
    [FirstCharacteristicsValueId]  VARCHAR (10)     NULL,
    [SecondCharacteristicsId]      VARCHAR (10)     NULL,
    [SecondCharacteristicsValueId] VARCHAR (10)     NULL,
    [ThirdCharacteristicsId]       VARCHAR (10)     NULL,
    [ThirdCharacteristicsValueId]  VARCHAR (10)     NULL,
    [TransactionQty]               DECIMAL (18, 10) NOT NULL,
    [TransactionUoMId]             VARCHAR (10)     NOT NULL,
    [MaterialTranRate]             DECIMAL (18, 10) NOT NULL,
    [MaterialTranAmount]           DECIMAL (18, 10) NOT NULL,
    [AddedBy]                      VARCHAR (30)     NOT NULL,
    [AddedDate]                    DATETIME         NOT NULL,
    [AddedFromIP]                  VARCHAR (15)     NOT NULL,
    [UpdatedBy]                    VARCHAR (30)     NULL,
    [UpdatedDate]                  DATETIME         NULL,
    [UpdatedFromIP]                VARCHAR (15)     NULL,
    [POId]                         VARCHAR (10)     NULL,
    [PODetailId]                   VARCHAR (10)     NULL,
    [GLGeneralInfoId]              VARCHAR (10)     NULL,
    [BudgetMasterId]               VARCHAR (20)     NULL,
    [ActivityId]                   VARCHAR (10)     NULL,
    [TotalMaterialTranAmount]      DECIMAL (18, 10) NULL,
    [ChargesTranAmount]            DECIMAL (18, 10) NULL,
    [ChargesTaxTranAmount]         DECIMAL (18, 10) NULL,
    [TaxAmount]                    DECIMAL (18, 10) NULL,
    [AcceptanceRate]               DECIMAL (18, 2)  DEFAULT ((0)) NULL,
    CONSTRAINT [PK_PurchaseDocAcceptanceDetail] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_PurchaseDocAcceptanceDetail_Activity] FOREIGN KEY ([ActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_PurchaseDocAcceptanceDetail_BudgetMaster] FOREIGN KEY ([BudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_PurchaseDocAcceptanceDetail_GLGeneralInfo] FOREIGN KEY ([GLGeneralInfoId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_PurchaseDocAcceptanceDetail_MaterialMasters] FOREIGN KEY ([MaterialMasterId]) REFERENCES [MST].[MaterialMaster] ([Id]),
    CONSTRAINT [FK_PurchaseDocAcceptanceDetails_FirstCharacteristics] FOREIGN KEY ([FirstCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_PurchaseDocAcceptanceDetails_FirstCharacteristicsValue] FOREIGN KEY ([FirstCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_PurchaseDocAcceptanceDetails_MaterialMasterArticles] FOREIGN KEY ([ArticleId]) REFERENCES [MST].[MaterialMasterArticle] ([Id]),
    CONSTRAINT [FK_PurchaseDocAcceptanceDetails_PO] FOREIGN KEY ([POId]) REFERENCES [TRN].[PurchaseOrder] ([Id]),
    CONSTRAINT [FK_PurchaseDocAcceptanceDetails_PODetail] FOREIGN KEY ([PODetailId]) REFERENCES [TRN].[PurchaseOrderDetail] ([Id]),
    CONSTRAINT [FK_PurchaseDocAcceptanceDetails_PurchaseDocAcceptance] FOREIGN KEY ([PurchaseDocAcceptanceId]) REFERENCES [TRN].[PurchaseDocAcceptance] ([Id]),
    CONSTRAINT [FK_PurchaseDocAcceptanceDetails_SecondCharacteristics] FOREIGN KEY ([SecondCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_PurchaseDocAcceptanceDetails_SecondCharacteristicsValue] FOREIGN KEY ([SecondCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_PurchaseDocAcceptanceDetails_ThirdCharacteristics] FOREIGN KEY ([ThirdCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_PurchaseDocAcceptanceDetails_ThirdCharacteristicsValue1] FOREIGN KEY ([ThirdCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id])
);

