CREATE TABLE [TRN].[QMSInspection] (
    [Id]                    VARCHAR (20)    NOT NULL,
    [InspectionMasterId]    VARCHAR (10)    NOT NULL,
    [InspectionTypeId]      VARCHAR (20)    NOT NULL,
    [InspectionLevelId]     VARCHAR (10)    NOT NULL,
    [EmployeeId]            VARCHAR (30)    NOT NULL,
    [ProcessId]             VARCHAR (10)    NOT NULL,
    [LocationId]            VARCHAR (20)    NOT NULL,
    [ResponsiblePersonId]   VARCHAR (30)    NOT NULL,
    [ProductionReferenceId] VARCHAR (30)    NOT NULL,
    [BatchReferenceNo]      VARCHAR (50)    NULL,
    [BatchSize]             DECIMAL (18, 2) NOT NULL,
    [SampleSize]            DECIMAL (18, 2) NOT NULL,
    [NoOfDefectiveUnit]     DECIMAL (18, 2) NOT NULL,
    [StatusId]              VARCHAR (20)    NOT NULL,
    [Remarks]               VARCHAR (250)   NULL,
    [AddedBy]               VARCHAR (30)    NOT NULL,
    [AddedDate]             DATETIME        NOT NULL,
    [AddedFromIP]           VARCHAR (15)    NOT NULL,
    [UpdatedBy]             VARCHAR (30)    NULL,
    [UpdatedDate]           DATETIME        NULL,
    [UpdatedFromIP]         VARCHAR (15)    NULL,
    [Date]                  VARCHAR (15)    NOT NULL,
    [ShiftMasterId]         VARCHAR (10)    NOT NULL,
    CONSTRAINT [PK_QMSInspection] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_QMSInspection_Employee] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_QMSInspection_InspectionMaster] FOREIGN KEY ([InspectionMasterId]) REFERENCES [HKP].[InspectionMaster] ([Id]),
    CONSTRAINT [FK_QMSInspection_InspectionType] FOREIGN KEY ([InspectionTypeId]) REFERENCES [HKP].[InspectionType] ([Id]),
    CONSTRAINT [FK_QMSInspection_Location] FOREIGN KEY ([LocationId]) REFERENCES [MST].[QMSMaster] ([Id]),
    CONSTRAINT [FK_QMSInspection_Process] FOREIGN KEY ([ProcessId]) REFERENCES [HKP].[Process] ([Id]),
    CONSTRAINT [FK_QMSInspection_ProductionReference] FOREIGN KEY ([ProductionReferenceId]) REFERENCES [TRN].[ProductionOrder] ([Id]),
    CONSTRAINT [FK_QMSInspection_ResponsiblePerson] FOREIGN KEY ([ResponsiblePersonId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_QMSInspection_ShiftMaster] FOREIGN KEY ([ShiftMasterId]) REFERENCES [MST].[CompliedShiftGrouping] ([Id]),
    CONSTRAINT [FK_QMSInspection_Status] FOREIGN KEY ([StatusId]) REFERENCES [HKP].[QualityStatus] ([Id])
);

