CREATE TABLE [TRN].[RecipeWashMaster] (
    [Id]                      VARCHAR (30)    NOT NULL,
    [CompanyGroupId]          VARCHAR (10)    NULL,
    [CompanyId]               VARCHAR (10)    NULL,
    [EntityId]                VARCHAR (10)    NULL,
    [MaterialMasterId]        VARCHAR (30)    NULL,
    [ProcessId]               VARCHAR (10)    NULL,
    [ProcessCriteriaId]       VARCHAR (10)    NULL,
    [MaterialAvgWeight]       DECIMAL (18, 3) NULL,
    [AvgUom]                  VARCHAR (10)    NULL,
    [Characteristics1Id]      VARCHAR (10)    NULL,
    [Characteristics2Id]      VARCHAR (10)    NULL,
    [Characteristics3Id]      VARCHAR (10)    NULL,
    [Characteristics1ValueId] VARCHAR (10)    NULL,
    [Characteristics2ValueId] VARCHAR (10)    NULL,
    [Characteristics3ValueId] VARCHAR (10)    NULL,
    [BatchSize]               DECIMAL (18, 3) NULL,
    [UOM]                     VARCHAR (10)    NULL,
    [Description]             VARCHAR (100)   NULL,
    [Code]                    VARCHAR (10)    NULL,
    [UserName]                VARCHAR (20)    NULL,
    [StartTemperature]        DECIMAL (18)    NULL,
    [StartPressure]           DECIMAL (18)    NULL,
    [EndPressure]             DECIMAL (18)    NULL,
    [GradientTemperature]     DECIMAL (18)    NULL,
    [GradientPressure]        DECIMAL (18)    NULL,
    [EndTemperature]          DECIMAL (18)    NULL,
    [AddedBy]                 VARCHAR (30)    NOT NULL,
    [AddedDate]               DATETIME        NOT NULL,
    [AddedFromIP]             VARCHAR (15)    NOT NULL,
    [UpdatedBy]               VARCHAR (30)    NULL,
    [UpdatedDate]             DATETIME        NULL,
    [UpdatedFromIP]           VARCHAR (15)    NULL,
    CONSTRAINT [PK_RecipeWashMaster] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_RecipeWashMaster_Characteristics1] FOREIGN KEY ([Characteristics1Id]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_RecipeWashMaster_Characteristics2] FOREIGN KEY ([Characteristics2Id]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_RecipeWashMaster_Characteristics3] FOREIGN KEY ([Characteristics3Id]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_RecipeWashMaster_CharacteristicsValue1] FOREIGN KEY ([Characteristics1ValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_RecipeWashMaster_CharacteristicsValue2] FOREIGN KEY ([Characteristics2ValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_RecipeWashMaster_CharacteristicsValue3] FOREIGN KEY ([Characteristics3ValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_RecipeWashMaster_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_RecipeWashMaster_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_RecipeWashMaster_Entity] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_RecipeWashMaster_Process] FOREIGN KEY ([ProcessId]) REFERENCES [HKP].[Process] ([Id]),
    CONSTRAINT [FK_RecipeWashMaster_UOM] FOREIGN KEY ([UOM]) REFERENCES [SCS].[UnitOfMeasurement] ([Id])
);

