CREATE TABLE [TRN].[RecipeGlobalMaster] (
    [Id]                      VARCHAR (30)    NOT NULL,
    [CompanyGroupId]          VARCHAR (10)    NULL,
    [CompanyId]               VARCHAR (10)    NULL,
    [EntityId]                VARCHAR (10)    NULL,
    [MaterialMasterId]        VARCHAR (30)    NULL,
    [ProcessId]               VARCHAR (10)    NULL,
    [ProcessCriteriaId]       VARCHAR (10)    NULL,
    [MaterialAvgWeight]       DECIMAL (18, 3) NULL,
    [AvgUom]                  VARCHAR (10)    NULL,
    [Characteristics1Id]      VARCHAR (10)    NULL,
    [Characteristics2Id]      VARCHAR (10)    NULL,
    [Characteristics3Id]      VARCHAR (10)    NULL,
    [Characteristics1ValueId] VARCHAR (10)    NULL,
    [Characteristics2ValueId] VARCHAR (10)    NULL,
    [Characteristics3ValueId] VARCHAR (10)    NULL,
    [BatchSize]               DECIMAL (18, 3) NULL,
    [UOM]                     VARCHAR (10)    NULL,
    [Description]             VARCHAR (100)   NULL,
    [Code]                    VARCHAR (20)    NULL,
    [UserName]                VARCHAR (50)    NULL,
    [StartTemperature]        DECIMAL (18)    NULL,
    [StartPressure]           DECIMAL (18)    NULL,
    [EndPressure]             DECIMAL (18)    NULL,
    [GradientTemperature]     DECIMAL (18)    NULL,
    [GradientPressure]        DECIMAL (18)    NULL,
    [EndTemperature]          DECIMAL (18)    NULL,
    [AddedBy]                 VARCHAR (30)    NOT NULL,
    [AddedDate]               DATETIME        NOT NULL,
    [AddedFromIP]             VARCHAR (15)    NOT NULL,
    [UpdatedBy]               VARCHAR (30)    NULL,
    [UpdatedDate]             DATETIME        NULL,
    [UpdatedFromIP]           VARCHAR (15)    NULL,
    [MaterialAttributeId]     VARCHAR (10)    NULL,
    [AttributeValueId]        VARCHAR (10)    NULL,
    [Thickness]               VARCHAR (10)    NULL,
    [Weight]                  VARCHAR (10)    NULL,
    [Specification1Id]        VARCHAR (10)    NULL,
    [Specification2Id]        VARCHAR (10)    NULL,
    [Specification1ValueId]   VARCHAR (10)    NULL,
    [Specification2ValueId]   VARCHAR (10)    NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    FOREIGN KEY ([Characteristics1Id]) REFERENCES [HKP].[Characteristics] ([Id]),
    FOREIGN KEY ([Characteristics1ValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    FOREIGN KEY ([Characteristics2Id]) REFERENCES [HKP].[Characteristics] ([Id]),
    FOREIGN KEY ([Characteristics2ValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    FOREIGN KEY ([Characteristics3Id]) REFERENCES [HKP].[Characteristics] ([Id]),
    FOREIGN KEY ([Characteristics3ValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    FOREIGN KEY ([ProcessId]) REFERENCES [HKP].[Process] ([Id]),
    FOREIGN KEY ([UOM]) REFERENCES [SCS].[UnitOfMeasurement] ([Id]),
    CONSTRAINT [FK_RecipeGlobalMaster_AttributeValue] FOREIGN KEY ([AttributeValueId]) REFERENCES [HKP].[MaterialAttributeValue] ([Id]),
    CONSTRAINT [FK_RecipeGlobalMaster_MaterialAttribute] FOREIGN KEY ([MaterialAttributeId]) REFERENCES [HKP].[MaterialAttribute] ([Id]),
    CONSTRAINT [FK_RecipeGlobalMaster_MaterialMaster] FOREIGN KEY ([MaterialMasterId]) REFERENCES [MST].[MaterialMaster] ([Id]),
    CONSTRAINT [FK_RecipeGlobalMaster_ProcessCriteria] FOREIGN KEY ([ProcessCriteriaId]) REFERENCES [HKP].[ProcessCriteria] ([Id]),
    CONSTRAINT [FK_RecipeGlobalMaster_Specification1] FOREIGN KEY ([Specification1Id]) REFERENCES [HKP].[MaterialAttribute] ([Id]),
    CONSTRAINT [FK_RecipeGlobalMaster_Specification1Value] FOREIGN KEY ([Specification1ValueId]) REFERENCES [HKP].[MaterialAttributeValue] ([Id]),
    CONSTRAINT [FK_RecipeGlobalMaster_Specification2] FOREIGN KEY ([Specification2Id]) REFERENCES [HKP].[MaterialAttribute] ([Id]),
    CONSTRAINT [FK_RecipeGlobalMaster_Specification2Value] FOREIGN KEY ([Specification2ValueId]) REFERENCES [HKP].[MaterialAttributeValue] ([Id])
);

