CREATE TABLE [TRN].[Resignation] (
    [Id]                          VARCHAR (10)  NOT NULL,
    [CompanyGroupId]              VARCHAR (10)  NOT NULL,
    [CompanyId]                   VARCHAR (10)  NOT NULL,
    [PlantId]                     VARCHAR (10)  NULL,
    [EmployeeId]                  VARCHAR (30)  NOT NULL,
    [ResignationDate]             DATETIME      NOT NULL,
    [Reason]                      VARCHAR (250) NOT NULL,
    [AttachLetter]                VARCHAR (50)  NOT NULL,
    [ApprovedBy]                  VARCHAR (50)  NULL,
    [ApprovedDate]                DATETIME      NULL,
    [ApprovedFromIP]              VARCHAR (50)  NULL,
    [EffectiveDate]               DATETIME      NULL,
    [ApprovedEffectiveDate]       DATETIME      NULL,
    [Remarks]                     VARCHAR (250) NULL,
    [ApprovalUpdatedBy]           VARCHAR (50)  NULL,
    [ApprovalUpdatedDate]         DATETIME      NULL,
    [ApprovalUpdatedFromIP]       VARCHAR (10)  NULL,
    [ApprovalStatus]              VARCHAR (10)  NOT NULL,
    [AddedBy]                     VARCHAR (30)  NOT NULL,
    [AddedDate]                   DATETIME      NOT NULL,
    [AddedFromIP]                 VARCHAR (15)  NOT NULL,
    [UpdatedBy]                   VARCHAR (30)  NULL,
    [UpdatedDate]                 DATETIME      NULL,
    [UpdatedFromIP]               VARCHAR (15)  NULL,
    [SpecialFollowUP]             BIT           DEFAULT ((0)) NOT NULL,
    [IsProcessed]                 BIT           DEFAULT ((0)) NOT NULL,
    [SeparationTypeId]            VARCHAR (10)  NULL,
    [DisciplinaryActionDetailsId] VARCHAR (30)  NULL,
    CONSTRAINT [PK_Resignation] PRIMARY KEY CLUSTERED ([Id] ASC),
    FOREIGN KEY ([DisciplinaryActionDetailsId]) REFERENCES [dbo].[EmployeeDisciplinaryActionDetails] ([Id]),
    CONSTRAINT [FK_Resignation_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_Resignation_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_Resignation_EmployeeInformation] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_Resignation_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_Resignation_SeparationType] FOREIGN KEY ([SeparationTypeId]) REFERENCES [HKP].[SeparationType] ([Id])
);

