CREATE TABLE [TRN].[SalesOrderMaster] (
    [Id]                      VARCHAR (20)    NOT NULL,
    [CompanyGroupId]          VARCHAR (10)    NOT NULL,
    [CompanyId]               VARCHAR (10)    NOT NULL,
    [PlantId]                 VARCHAR (10)    NULL,
    [EntityId]                VARCHAR (10)    NULL,
    [ProductionOrderMasterId] VARCHAR (20)    NULL,
    [Active]                  BIT             NOT NULL,
    [Archive]                 BIT             NOT NULL,
    [AddedBy]                 VARCHAR (30)    NOT NULL,
    [AddedDate]               DATETIME        NOT NULL,
    [AddedFromIP]             VARCHAR (15)    NOT NULL,
    [UpdatedBy]               VARCHAR (30)    NULL,
    [UpdatedDate]             DATETIME        NULL,
    [UpdatedFromIP]           VARCHAR (15)    NULL,
    [PaymentTermId]           VARCHAR (10)    NULL,
    [MasterOrderId]           VARCHAR (10)    NULL,
    [CustomerPOId]            VARCHAR (20)    NULL,
    [PortId]                  VARCHAR (10)    NULL,
    [DestinationId]           VARCHAR (10)    NULL,
    [ShipmentModeId]          VARCHAR (10)    NULL,
    [DeliveryDate]            DATE            NULL,
    [OwnShipmentDate]         DATE            NULL,
    [ExcessPercentage]        DECIMAL (18, 3) NULL,
    [Rate]                    DECIMAL (18, 3) NULL,
    [InvoicingPartyPlantId]   VARCHAR (12)    NULL,
    [DeliveryPartyPlantId]    VARCHAR (12)    NULL,
    [InvoicingByAddress]      VARCHAR (200)   NULL,
    [DeliveryByAddress]       VARCHAR (200)   NULL,
    CONSTRAINT [PK_SalesOrderMaster] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_SalesOrderMaster_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_SalesOrderMaster_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_SalesOrderMaster_CustomerPO] FOREIGN KEY ([CustomerPOId]) REFERENCES [TRN].[CustomerPO] ([Id]),
    CONSTRAINT [FK_SalesOrderMaster_DeliveryPartyPlantId_PartyPlant] FOREIGN KEY ([DeliveryPartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_SalesOrderMaster_Entity] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_SalesOrderMaster_InvoicingPartyPlantId_PartyPlant] FOREIGN KEY ([InvoicingPartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_SalesOrderMaster_PaymentTerm] FOREIGN KEY ([PaymentTermId]) REFERENCES [MST].[PaymentTerm] ([Id]),
    CONSTRAINT [FK_SalesOrderMaster_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_SalesOrderMaterialMaster_Destination] FOREIGN KEY ([DestinationId]) REFERENCES [MST].[Destination] ([Id]),
    CONSTRAINT [FK_SalesOrderMaterialMaster_Port] FOREIGN KEY ([PortId]) REFERENCES [MST].[Port] ([Id]),
    CONSTRAINT [FK_SalesOrderMaterialMaster_ShipMode] FOREIGN KEY ([ShipmentModeId]) REFERENCES [MST].[ShipMode] ([Id])
);

