CREATE TABLE [TRN].[SalesOrderPackingListMaterial] (
    [Id]                                  VARCHAR (30) NOT NULL,
    [CompanyGroupId]                      VARCHAR (10) NOT NULL,
    [CompanyId]                           VARCHAR (10) NOT NULL,
    [PlantId]                             VARCHAR (10) NULL,
    [EntityId]                            VARCHAR (10) NULL,
    [SalesOrderPackingListMasterId]       VARCHAR (30) NULL,
    [SalesOrderMasterId]                  VARCHAR (20) NULL,
    [SalesOrderMaterialMasterId]          VARCHAR (20) NULL,
    [SalesOrderCharacteristicsValue1stId] VARCHAR (20) NULL,
    [SalesOrderCharacteristicsValue2ndId] VARCHAR (20) NULL,
    [SalesOrderPackingListFormId]         VARCHAR (30) NULL,
    [MaterialGroupMasterId]               VARCHAR (10) NULL,
    [MaterialMasterId]                    VARCHAR (30) NULL,
    [ArticleId]                           VARCHAR (10) NULL,
    [UomId]                               VARCHAR (10) NULL,
    [Characteristics1Id]                  VARCHAR (10) NULL,
    [CharacteristicsValue1Id]             VARCHAR (10) NULL,
    [Characteristics2Id]                  VARCHAR (10) NULL,
    [CharacteristicsValue2Id]             VARCHAR (10) NULL,
    [Characteristics3Id]                  VARCHAR (10) NULL,
    [CharacteristicsValue3Id]             VARCHAR (10) NULL,
    [SalesOrderPackingListFirstPFId]      VARCHAR (30) NULL,
    [Qty]                                 DECIMAL (18) NULL,
    [AddedBy]                             VARCHAR (30) NOT NULL,
    [AddedDate]                           DATETIME     NOT NULL,
    [AddedFromIP]                         VARCHAR (15) NOT NULL,
    [UpdatedBy]                           VARCHAR (30) NULL,
    [UpdatedDate]                         DATETIME     NULL,
    [UpdatedFromIP]                       VARCHAR (15) NULL,
    CONSTRAINT [PK_SalesOrderPackingListMaterial] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_SalesOrderPackingListDetail_Characteristics] FOREIGN KEY ([Characteristics1Id]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_SalesOrderPackingListDetail_Characteristics1] FOREIGN KEY ([Characteristics2Id]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_SalesOrderPackingListDetail_Characteristics2] FOREIGN KEY ([Characteristics3Id]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_SalesOrderPackingListDetail_CharacteristicsValue] FOREIGN KEY ([CharacteristicsValue1Id]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_SalesOrderPackingListDetail_CharacteristicsValue1] FOREIGN KEY ([CharacteristicsValue2Id]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_SalesOrderPackingListDetail_CharacteristicsValue2] FOREIGN KEY ([CharacteristicsValue3Id]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_SalesOrderPackingListDetail_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_SalesOrderPackingListDetail_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_SalesOrderPackingListDetail_Entity] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_SalesOrderPackingListDetail_MaterialGroupMaster] FOREIGN KEY ([MaterialGroupMasterId]) REFERENCES [MST].[MaterialGroupMaster] ([Id]),
    CONSTRAINT [FK_SalesOrderPackingListDetail_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_SalesOrderPackingListDetail_SalesOrderPackingListMaster] FOREIGN KEY ([SalesOrderPackingListMasterId]) REFERENCES [TRN].[SalesOrderPackingListMaster] ([Id]),
    CONSTRAINT [FK_SalesOrderPackingListDetail_Submaterial] FOREIGN KEY ([ArticleId]) REFERENCES [MST].[MaterialMasterArticle] ([Id]),
    CONSTRAINT [FK_SalesOrderPackingListDetail_UnitOfMeasurement] FOREIGN KEY ([UomId]) REFERENCES [SCS].[UnitOfMeasurement] ([Id]),
    CONSTRAINT [FK_SalesOrderPackingListMaterial_MaterialMaster] FOREIGN KEY ([MaterialMasterId]) REFERENCES [MST].[MaterialMaster] ([Id]),
    CONSTRAINT [FK_SalesOrderPackingListMaterial_SalesOrderPackingListFirstPF] FOREIGN KEY ([SalesOrderPackingListFormId]) REFERENCES [TRN].[SalesOrderPackingListForm] ([Id])
);

