CREATE TABLE [TRN].[SalesOrderPackingListMaster] (
    [Id]                    VARCHAR (30)  NOT NULL,
    [CompanyGroupId]        VARCHAR (10)  NOT NULL,
    [CompanyId]             VARCHAR (10)  NOT NULL,
    [PlantId]               VARCHAR (10)  NULL,
    [EntityId]              VARCHAR (10)  NULL,
    [PartyId]               VARCHAR (10)  NULL,
    [PackingListNo]         VARCHAR (50)  NULL,
    [PackingDate]           DATE          NULL,
    [IsEntryCompleted]      BIT           CONSTRAINT [DF_SalesOrderPackingListMaster_IsEntryCompleted] DEFAULT ((0)) NULL,
    [AddedBy]               VARCHAR (30)  NOT NULL,
    [AddedDate]             DATETIME      NOT NULL,
    [AddedFromIP]           VARCHAR (15)  NOT NULL,
    [UpdatedBy]             VARCHAR (30)  NULL,
    [UpdatedDate]           DATETIME      NULL,
    [UpdatedFromIP]         VARCHAR (15)  NULL,
    [InvoicingByAddress]    VARCHAR (250) NULL,
    [DeliveryByAddress]     VARCHAR (250) NULL,
    [InvoicingPartyPlantId] VARCHAR (12)  NOT NULL,
    [DeliveryPartyPlantId]  VARCHAR (12)  NOT NULL,
    CONSTRAINT [PK_SalesOrderPackingListMaster] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_SalesOrderPackingListMaster_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_SalesOrderPackingListMaster_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_SalesOrderPackingListMaster_DeliveryPartyPlantId_PartyPlant] FOREIGN KEY ([DeliveryPartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_SalesOrderPackingListMaster_Entity] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_SalesOrderPackingListMaster_InvoicingPartyPlantId_PartyPlant] FOREIGN KEY ([InvoicingPartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_SalesOrderPackingListMaster_Party] FOREIGN KEY ([PartyId]) REFERENCES [HKP].[Party] ([Id]),
    CONSTRAINT [FK_SalesOrderPackingListMaster_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id])
);

