CREATE TABLE [TRN].[Sales] (
    [Id]                    VARCHAR (10)     NOT NULL,
    [CompanyGroupId]        VARCHAR (10)     NOT NULL,
    [CompanyId]             VARCHAR (10)     NOT NULL,
    [PlantId]               VARCHAR (10)     NOT NULL,
    [EntityId]              VARCHAR (10)     NULL,
    [CurrencyId]            VARCHAR (10)     NOT NULL,
    [PartyType]             VARCHAR (10)     NOT NULL,
    [PartyId]               VARCHAR (10)     NOT NULL,
    [InvoicingPartyPlantId] VARCHAR (12)     NOT NULL,
    [DeliveryPartyPlantId]  VARCHAR (12)     NULL,
    [DocRefNo]              VARCHAR (20)     NULL,
    [EntryDate]             DATE             NOT NULL,
    [InvoiceNo]             VARCHAR (20)     NULL,
    [InvoiceDate]           DATE             NULL,
    [PaymentTermId]         VARCHAR (10)     NULL,
    [BaseOnDueDate]         DATETIME         NULL,
    [BaseNoOfDays]          INT              NOT NULL,
    [MatureDate]            DATETIME         NULL,
    [RowState]              VARCHAR (20)     NOT NULL,
    [AddedBy]               VARCHAR (30)     NOT NULL,
    [AddedDate]             DATETIME         NOT NULL,
    [AddedFromIP]           VARCHAR (15)     NOT NULL,
    [UpdatedBy]             VARCHAR (30)     NULL,
    [UpdatedDate]           DATETIME         NULL,
    [UpdatedFromIP]         VARCHAR (15)     NULL,
    [ToCurrencyRate]        DECIMAL (18, 10) NULL,
    [Narration]             VARCHAR (250)    NULL,
    [VoucherId]             VARCHAR (50)     NULL,
    [InvoicingByAddress]    VARCHAR (200)    NULL,
    [DeliveryByAddress]     VARCHAR (200)    NULL,
    [BLNumber]              VARCHAR (25)     NULL,
    [ComercialInvoiceNo]    VARCHAR (25)     NULL,
    [EXPFromNo]             VARCHAR (25)     NULL,
    [ItemDescription]       VARCHAR (250)    NULL,
    [BLDate]                DATETIME         NULL,
    [EXPDate]               DATETIME         NULL,
    [SourceType]            VARCHAR (20)     NULL,
    CONSTRAINT [PK_Sales] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Sales_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_Sales_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_Sales_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_Sales_DeliveryPartyPlant] FOREIGN KEY ([DeliveryPartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_Sales_Entity] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_Sales_InvoicingPartyPlant] FOREIGN KEY ([InvoicingPartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_Sales_Party] FOREIGN KEY ([PartyId]) REFERENCES [HKP].[Party] ([Id]),
    CONSTRAINT [FK_Sales_PaymentTerm] FOREIGN KEY ([PaymentTermId]) REFERENCES [MST].[PaymentTerm] ([Id]),
    CONSTRAINT [FK_Sales_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_Sales_Voucher] FOREIGN KEY ([VoucherId]) REFERENCES [TRN].[Voucher] ([Id])
);

