CREATE TABLE [TRN].[SalesMaterial] (
    [Id]                             VARCHAR (30)     NOT NULL,
    [SalesId]                        VARCHAR (10)     NOT NULL,
    [MaterialMasterId]               VARCHAR (30)     NOT NULL,
    [ArticleId]                      VARCHAR (10)     NULL,
    [TaxAmount]                      DECIMAL (18, 10) NOT NULL,
    [NetAmount]                      DECIMAL (18, 10) NOT NULL,
    [AddedBy]                        VARCHAR (30)     NOT NULL,
    [AddedDate]                      DATETIME         NOT NULL,
    [AddedFromIP]                    VARCHAR (15)     NOT NULL,
    [UpdatedBy]                      VARCHAR (30)     NULL,
    [UpdatedDate]                    DATETIME         NULL,
    [UpdatedFromIP]                  VARCHAR (15)     NULL,
    [BaseUOMId]                      VARCHAR (10)     NOT NULL,
    [BaseRate]                       DECIMAL (18, 10) NOT NULL,
    [BaseQty]                        DECIMAL (18, 2)  NOT NULL,
    [BaseAmount]                     DECIMAL (18, 10) NOT NULL,
    [BaseUoMFactor]                  DECIMAL (18, 10) NOT NULL,
    [TransactionUoMId]               VARCHAR (10)     NOT NULL,
    [TransactionRate]                DECIMAL (18, 10) NOT NULL,
    [TransactionQty]                 DECIMAL (18, 2)  NOT NULL,
    [TransactionAmount]              DECIMAL (18, 10) NOT NULL,
    [VoucherDetailId]                VARCHAR (80)     NULL,
    [FirstCharacteristicsId]         VARCHAR (20)     NULL,
    [FirstCharacteristicsValueId]    VARCHAR (10)     NULL,
    [SecondCharacteristicsId]        VARCHAR (20)     NULL,
    [SecondCharacteristicsValueId]   VARCHAR (10)     NULL,
    [ThirdCharacteristicsId]         VARCHAR (10)     NULL,
    [ThirdCharacteristicsValueId]    VARCHAR (10)     NULL,
    [SalesOrderId]                   VARCHAR (10)     NULL,
    [BooksCurrencyTransactionAmount] DECIMAL (18, 10) NULL,
    [BooksCurrencyTaxAmount]         DECIMAL (18, 10) NULL,
    [BooksCurrencyBaseRate]          DECIMAL (18, 10) NULL,
    [PostDrGLGeneralInfoId]          VARCHAR (10)     NULL,
    [PostDrBudgetMasterId]           VARCHAR (20)     NULL,
    [PostDrActivityId]               VARCHAR (10)     NULL,
    [PostCrGLGeneralInfoId]          VARCHAR (10)     NULL,
    [PostCrBudgetMasterId]           VARCHAR (20)     NULL,
    [PostCrActivityId]               VARCHAR (10)     NULL,
    CONSTRAINT [PK_SalesMaterial] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_SalesMaterial_BaseUoM] FOREIGN KEY ([BaseUOMId]) REFERENCES [SCS].[UnitOfMeasurement] ([Id]),
    CONSTRAINT [FK_SalesMaterial_FirstCharacteristicsValue] FOREIGN KEY ([FirstCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_SalesMaterial_MaterialMaster] FOREIGN KEY ([MaterialMasterId]) REFERENCES [MST].[MaterialMaster] ([Id]),
    CONSTRAINT [FK_SalesMaterial_MaterialMasterArticle] FOREIGN KEY ([ArticleId]) REFERENCES [MST].[MaterialMasterArticle] ([Id]),
    CONSTRAINT [FK_SalesMaterial_PostCrActivity] FOREIGN KEY ([PostCrActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_SalesMaterial_PostCrBudgetMasterId] FOREIGN KEY ([PostCrBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_SalesMaterial_PostCrGLGeneralInfoId] FOREIGN KEY ([PostCrGLGeneralInfoId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_SalesMaterial_PostDrActivity] FOREIGN KEY ([PostDrActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_SalesMaterial_PostDrBudgetMasterId] FOREIGN KEY ([PostDrBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_SalesMaterial_PostDrGLGeneralInfo] FOREIGN KEY ([PostDrGLGeneralInfoId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_SalesMaterial_Sales] FOREIGN KEY ([SalesId]) REFERENCES [TRN].[Sales] ([Id]),
    CONSTRAINT [FK_SalesMaterial_SecondCharacteristicsValue] FOREIGN KEY ([SecondCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_SalesMaterial_ThirdCharacteristics] FOREIGN KEY ([ThirdCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_SalesMaterial_ThirdCharacteristicsValue] FOREIGN KEY ([ThirdCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_SalesMaterial_TransactionUoM] FOREIGN KEY ([TransactionUoMId]) REFERENCES [SCS].[UnitOfMeasurement] ([Id]),
    CONSTRAINT [FK_SalesMaterial_VoucherDetail] FOREIGN KEY ([VoucherDetailId]) REFERENCES [TRN].[VoucherDetail] ([Id])
);

