CREATE TABLE [TRN].[SamplePackingListMaterialDetails] (
    [Id]                           VARCHAR (10)    NOT NULL,
    [SamplePackingListId]          VARCHAR (10)    NOT NULL,
    [SampleOrderId]                VARCHAR (10)    NULL,
    [SampleOrderSubMaterialId]     VARCHAR (10)    NULL,
    [SamplePackingListMaterialId]  VARCHAR (10)    NULL,
    [MaterialGroupMasterId]        VARCHAR (10)    NOT NULL,
    [MaterialMasterId]             VARCHAR (30)    NOT NULL,
    [ArticleId]                    VARCHAR (10)    NULL,
    [FirstCharacteristicsId]       VARCHAR (10)    NULL,
    [FirstCharacteristicsValueId]  VARCHAR (10)    NULL,
    [SecondCharacteristicsId]      VARCHAR (10)    NULL,
    [SecondCharacteristicsValueId] VARCHAR (10)    NULL,
    [ThirdCharacteristicsId]       VARCHAR (10)    NULL,
    [ThirdCharacteristicsValueId]  VARCHAR (10)    NULL,
    [UoMId]                        VARCHAR (10)    NOT NULL,
    [BaseUOMId]                    VARCHAR (10)    NULL,
    [Qty]                          INT             NOT NULL,
    [BaseQty]                      DECIMAL (18, 2) CONSTRAINT [DF__SamplePac__Conve__12B48446] DEFAULT ((0)) NULL,
    [Description]                  VARCHAR (250)   NULL,
    [AddedBy]                      VARCHAR (30)    NOT NULL,
    [AddedDate]                    DATETIME        NOT NULL,
    [AddedFromIP]                  VARCHAR (15)    NOT NULL,
    [UpdatedBy]                    VARCHAR (30)    NULL,
    [UpdatedDate]                  DATETIME        NULL,
    [UpdatedFromIP]                VARCHAR (15)    NULL,
    CONSTRAINT [PK_SamplePackingListMaterialDetails] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_SamplePackingListMaterialDetails_BaseUOM] FOREIGN KEY ([BaseUOMId]) REFERENCES [SCS].[UnitOfMeasurement] ([Id]),
    CONSTRAINT [FK_SamplePackingListMaterialDetails_Characteristics1] FOREIGN KEY ([FirstCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_SamplePackingListMaterialDetails_Characteristics2] FOREIGN KEY ([SecondCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_SamplePackingListMaterialDetails_Characteristics3] FOREIGN KEY ([ThirdCharacteristicsId]) REFERENCES [HKP].[Characteristics] ([Id]),
    CONSTRAINT [FK_SamplePackingListMaterialDetails_CharacteristicsValue1] FOREIGN KEY ([FirstCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_SamplePackingListMaterialDetails_CharacteristicsValue2] FOREIGN KEY ([SecondCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_SamplePackingListMaterialDetails_CharacteristicsValue3] FOREIGN KEY ([ThirdCharacteristicsValueId]) REFERENCES [HKP].[CharacteristicsValue] ([Id]),
    CONSTRAINT [FK_SamplePackingListMaterialDetails_MaterialGroupMaster] FOREIGN KEY ([MaterialGroupMasterId]) REFERENCES [MST].[MaterialGroupMaster] ([Id]),
    CONSTRAINT [FK_SamplePackingListMaterialDetails_MaterialMaster] FOREIGN KEY ([MaterialMasterId]) REFERENCES [MST].[MaterialMaster] ([Id]),
    CONSTRAINT [FK_SamplePackingListMaterialDetails_SampleOrder] FOREIGN KEY ([SampleOrderId]) REFERENCES [TRN].[SampleOrder] ([Id]),
    CONSTRAINT [FK_SamplePackingListMaterialDetails_SampleOrderSubMaterial] FOREIGN KEY ([SampleOrderSubMaterialId]) REFERENCES [TRN].[SampleOrderSubMaterial] ([Id]),
    CONSTRAINT [FK_SamplePackingListMaterialDetails_SamplePackingList] FOREIGN KEY ([SamplePackingListId]) REFERENCES [TRN].[SamplePackingList] ([Id]),
    CONSTRAINT [FK_SamplePackingListMaterialDetails_SamplePackingListMaterial] FOREIGN KEY ([SamplePackingListMaterialId]) REFERENCES [TRN].[SamplePackingListMaterial] ([Id]),
    CONSTRAINT [FK_SamplePackingListMaterialDetails_SubMaterial] FOREIGN KEY ([ArticleId]) REFERENCES [MST].[MaterialMasterArticle] ([Id]),
    CONSTRAINT [FK_SamplePackingListMaterialDetails_UnitOfMeasurement] FOREIGN KEY ([UoMId]) REFERENCES [SCS].[UnitOfMeasurement] ([Id])
);

