CREATE TABLE [TRN].[SampleOrder] (
    [Id]                    VARCHAR (10)  NOT NULL,
    [PlantId]               VARCHAR (10)  NOT NULL,
    [EntityId]              VARCHAR (10)  NOT NULL,
    [SalesOrganisationId]   VARCHAR (10)  NOT NULL,
    [SalesGroupId]          VARCHAR (10)  NOT NULL,
    [BuyerId]               VARCHAR (10)  NULL,
    [PartyId]               VARCHAR (10)  NOT NULL,
    [PaymentTermId]         VARCHAR (10)  NOT NULL,
    [CurrencyId]            VARCHAR (10)  NOT NULL,
    [RequestReferenceDate]  DATE          NULL,
    [ReferenceDocNo]        VARCHAR (50)  NULL,
    [DeliveryDate]          DATE          NULL,
    [AddedBy]               VARCHAR (30)  NOT NULL,
    [AddedDate]             DATETIME      NOT NULL,
    [AddedFromIP]           VARCHAR (15)  NOT NULL,
    [UpdatedBy]             VARCHAR (30)  NULL,
    [UpdatedDate]           DATETIME      NULL,
    [UpdatedFromIP]         VARCHAR (15)  NULL,
    [InvoicingPartyPlantId] VARCHAR (12)  NULL,
    [DeliveryPartyPlantId]  VARCHAR (12)  NULL,
    [InvoicingByAddress]    VARCHAR (200) NULL,
    [DeliveryByAddress]     VARCHAR (200) NULL,
    CONSTRAINT [PK_SampleSalesOrder] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_SampleOrder_DeliveryPartyPlantId_PartyPlant] FOREIGN KEY ([DeliveryPartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_SampleOrder_InvoicingPartyPlantId_PartyPlant] FOREIGN KEY ([InvoicingPartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_SampleSalesOrder_Buyer] FOREIGN KEY ([BuyerId]) REFERENCES [HKP].[Buyer] ([Id]),
    CONSTRAINT [FK_SampleSalesOrder_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_SampleSalesOrder_Entity] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_SampleSalesOrder_Party] FOREIGN KEY ([PartyId]) REFERENCES [HKP].[Party] ([Id]),
    CONSTRAINT [FK_SampleSalesOrder_PaymentTerm] FOREIGN KEY ([PaymentTermId]) REFERENCES [MST].[PaymentTerm] ([Id]),
    CONSTRAINT [FK_SampleSalesOrder_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_SampleSalesOrder_SalesGroup] FOREIGN KEY ([SalesGroupId]) REFERENCES [ORG].[SalesGroup] ([Id]),
    CONSTRAINT [FK_SampleSalesOrder_SalesOrganisation] FOREIGN KEY ([SalesOrganisationId]) REFERENCES [ORG].[SalesOrganisation] ([Id])
);

