CREATE TABLE [TRN].[SecurityDepositWriteOffDetail] (
    [Id]                        VARCHAR (100)    NOT NULL,
    [SecurityDepositId]         VARCHAR (80)     NOT NULL,
    [SecurityDepositDetailId]   VARCHAR (100)    NOT NULL,
    [SecurityDepositWriteOffId] VARCHAR (80)     NOT NULL,
    [CurrencyId]                VARCHAR (10)     NOT NULL,
    [GLGeneralInfoId]           VARCHAR (10)     NOT NULL,
    [BudgetMasterId]            VARCHAR (20)     NULL,
    [ActivityId]                VARCHAR (10)     NULL,
    [DocDate]                   DATETIME         NOT NULL,
    [DocRefNo]                  VARCHAR (50)     NOT NULL,
    [Narration]                 VARCHAR (250)    NOT NULL,
    [SourceTo]                  VARCHAR (10)     NULL,
    [Amount]                    DECIMAL (18, 10) NOT NULL,
    [Archive]                   BIT              NOT NULL,
    [AddedBy]                   VARCHAR (30)     NOT NULL,
    [AddedDate]                 DATETIME         NOT NULL,
    [AddedFromIP]               VARCHAR (15)     NOT NULL,
    [UpdatedBy]                 VARCHAR (30)     NULL,
    [UpdatedDate]               DATETIME         NULL,
    [UpdatedFromIP]             VARCHAR (15)     NULL,
    CONSTRAINT [PK_SecurityDepositWriteOffDetail] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_SecurityDepositWriteOffDetail_Activity] FOREIGN KEY ([ActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_SecurityDepositWriteOffDetail_BudgetMaster] FOREIGN KEY ([BudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_SecurityDepositWriteOffDetail_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_SecurityDepositWriteOffDetail_GLGeneralInfo] FOREIGN KEY ([GLGeneralInfoId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_SecurityDepositWriteOffDetail_SecurityDepositDetail] FOREIGN KEY ([SecurityDepositDetailId]) REFERENCES [TRN].[SecurityDepositDetail] ([Id]),
    CONSTRAINT [FK_SecurityDepositWriteOffDetail_SecurityDepositWriteOff] FOREIGN KEY ([SecurityDepositWriteOffId]) REFERENCES [TRN].[SecurityDepositWriteOff] ([Id]),
    CONSTRAINT [FK_SecurityDepositWriteOffDetail_Voucher] FOREIGN KEY ([SecurityDepositId]) REFERENCES [TRN].[SecurityDeposit] ([Id])
);

