CREATE TABLE [TRN].[SecurityDepositWriteOff] (
    [Id]                        VARCHAR (80)     NOT NULL,
    [CompanyGroupId]            VARCHAR (10)     NOT NULL,
    [CompanyId]                 VARCHAR (10)     NOT NULL,
    [PlantId]                   VARCHAR (10)     NOT NULL,
    [EntityId]                  VARCHAR (10)     NULL,
    [CurrencyId]                VARCHAR (10)     NOT NULL,
    [VoucherId]                 VARCHAR (50)     NOT NULL,
    [EmployeeId]                VARCHAR (30)     NULL,
    [PartyId]                   VARCHAR (10)     NULL,
    [PartyType]                 VARCHAR (10)     NOT NULL,
    [SourceType]                VARCHAR (30)     NULL,
    [SourceFrom]                VARCHAR (20)     NULL,
    [PostingDate]               DATETIME         NOT NULL,
    [DocDate]                   DATETIME         NOT NULL,
    [DocRefNo]                  VARCHAR (50)     NOT NULL,
    [Narration]                 VARCHAR (250)    NOT NULL,
    [Amount]                    DECIMAL (18, 10) NOT NULL,
    [Archive]                   BIT              NOT NULL,
    [AddedBy]                   VARCHAR (30)     NOT NULL,
    [AddedDate]                 DATETIME         NOT NULL,
    [AddedFromIP]               VARCHAR (15)     NOT NULL,
    [UpdatedBy]                 VARCHAR (30)     NULL,
    [UpdatedDate]               DATETIME         NULL,
    [UpdatedFromIP]             VARCHAR (15)     NULL,
    [SecurityDepositWriteOffNo] VARCHAR (30)     NULL,
    [FiscalYearId]              VARCHAR (10)     NULL,
    [FiscalYearPeriodId]        VARCHAR (10)     NULL,
    [TaxYearId]                 VARCHAR (10)     NULL,
    [TaxYearPeriodId]           VARCHAR (10)     NULL,
    [VoucherTypeId]             VARCHAR (10)     NULL,
    [InvoicingPartyPlantId]     VARCHAR (12)     NULL,
    [DeliveryPartyPlantId]      VARCHAR (12)     NULL,
    CONSTRAINT [PK_SecurityDepositWriteOff] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_SecurityDepositWriteOff_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_SecurityDepositWriteOff_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_SecurityDepositWriteOff_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_SecurityDepositWriteOff_EmployeeInformation] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_SecurityDepositWriteOff_Entity] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_SecurityDepositWriteOff_FiscalYear] FOREIGN KEY ([FiscalYearId]) REFERENCES [SCS].[FiscalYear] ([Id]),
    CONSTRAINT [FK_SecurityDepositWriteOff_FiscalYearPeriod] FOREIGN KEY ([FiscalYearPeriodId]) REFERENCES [SCS].[FiscalYearPeriod] ([Id]),
    CONSTRAINT [FK_SecurityDepositWriteOff_Party] FOREIGN KEY ([PartyId]) REFERENCES [HKP].[Party] ([Id]),
    CONSTRAINT [FK_SecurityDepositWriteOff_PartyPlant_DeliveryPartyPlantId] FOREIGN KEY ([DeliveryPartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_SecurityDepositWriteOff_PartyPlant_InvoicingPartyPlantId] FOREIGN KEY ([InvoicingPartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_SecurityDepositWriteOff_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_SecurityDepositWriteOff_TaxYear] FOREIGN KEY ([TaxYearId]) REFERENCES [SCS].[TaxYear] ([Id]),
    CONSTRAINT [FK_SecurityDepositWriteOff_TaxYearPeriod] FOREIGN KEY ([TaxYearPeriodId]) REFERENCES [SCS].[TaxYearPeriod] ([Id]),
    CONSTRAINT [FK_SecurityDepositWriteOff_Voucher] FOREIGN KEY ([VoucherId]) REFERENCES [TRN].[Voucher] ([Id]),
    CONSTRAINT [FK_SecurityDepositWriteOff_VoucherType] FOREIGN KEY ([VoucherTypeId]) REFERENCES [SCS].[VoucherType] ([Id])
);

