CREATE TABLE [TRN].[ServiceAcknowledgementMaster] (
    [Id]                       VARCHAR (30)     NOT NULL,
    [CompanyGroupId]           VARCHAR (10)     NOT NULL,
    [CompanyId]                VARCHAR (10)     NOT NULL,
    [PlantId]                  VARCHAR (10)     NOT NULL,
    [CurrencyId]               VARCHAR (10)     NOT NULL,
    [PartyId]                  VARCHAR (10)     NULL,
    [DocRefNo]                 VARCHAR (20)     NOT NULL,
    [DocDate]                  DATE             NOT NULL,
    [PODepended]               BIT              NOT NULL,
    [PaymentTermId]            VARCHAR (10)     NULL,
    [BaseOnDueDate]            DATETIME         NULL,
    [BaseNoOfDays]             INT              NOT NULL,
    [MatureDate]               DATETIME         NULL,
    [Status]                   VARCHAR (15)     NULL,
    [BaseCurrencyId]           VARCHAR (10)     NOT NULL,
    [InvoicingPartyPlantId]    VARCHAR (12)     NULL,
    [DeliveryPartyPlantId]     VARCHAR (12)     NULL,
    [AcknowledgementDate]      DATE             NOT NULL,
    [IsNonCreditable]          BIT              NOT NULL,
    [InvoicingByAddress]       VARCHAR (300)    NULL,
    [DeliveryByAddress]        VARCHAR (300)    NULL,
    [ToCurrencyRate]           DECIMAL (18, 10) NOT NULL,
    [IsTaxApplicable]          BIT              NOT NULL,
    [PartyType]                VARCHAR (10)     NULL,
    [PreparedBy]               VARCHAR (30)     NULL,
    [IsApproved]               BIT              NOT NULL,
    [IsPaymentHold]            BIT              NOT NULL,
    [ServicePOId]              VARCHAR (10)     NULL,
    [CheckedBy]                VARCHAR (30)     NULL,
    [CheckedByStatus]          VARCHAR (30)     NULL,
    [ApprovedBy]               VARCHAR (30)     NULL,
    [ApprovedByStatus]         VARCHAR (30)     NULL,
    [ApprovedHoldRejectReason] VARCHAR (300)    NULL,
    [CheckedHoldRejectReason]  VARCHAR (300)    NULL,
    [NoteForAccounts]          TEXT             NULL,
    [AddedBy]                  VARCHAR (30)     NOT NULL,
    [AddedDate]                DATETIME         NOT NULL,
    [AddedFromIP]              VARCHAR (15)     NOT NULL,
    [UpdatedBy]                VARCHAR (30)     NULL,
    [UpdatedDate]              DATETIME         NULL,
    [UpdatedFromIP]            VARCHAR (15)     NULL,
    [VoucherId]                VARCHAR (50)     NULL,
    CONSTRAINT [PK_ServiceAcknowledgementMaster] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [fk_CheckedBy] FOREIGN KEY ([CheckedBy]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [fk_SACKM_PlntId] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [fk_SACKMBaseCurrencyId] FOREIGN KEY ([BaseCurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [fk_SACKMChekdBy] FOREIGN KEY ([CheckedBy]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [fk_SACKMCmpanyId] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [fk_SACKMCompanyGroupId] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [fk_SACKMCurrencyId] FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [fk_SACKMPartyId] FOREIGN KEY ([PartyId]) REFERENCES [HKP].[Party] ([Id]),
    CONSTRAINT [FK_ServiceAcknowledgement_BaseCurrency] FOREIGN KEY ([BaseCurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_ServiceAcknowledgement_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_ServiceAcknowledgement_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_ServiceAcknowledgement_DeliveryPartyPlant] FOREIGN KEY ([DeliveryPartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_ServiceAcknowledgement_Employee] FOREIGN KEY ([PreparedBy]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_ServiceAcknowledgement_InvoicingPartyPlant] FOREIGN KEY ([InvoicingPartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_ServiceAcknowledgement_Party] FOREIGN KEY ([PartyId]) REFERENCES [HKP].[Party] ([Id]),
    CONSTRAINT [FK_ServiceAcknowledgement_PaymentTerm] FOREIGN KEY ([PaymentTermId]) REFERENCES [MST].[PaymentTerm] ([Id]),
    CONSTRAINT [FK_ServiceAcknowledgement_PlantId] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_ServiceAcknowledgementMaster_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_ServiceAcknowledgementMaster_Voucher] FOREIGN KEY ([VoucherId]) REFERENCES [TRN].[Voucher] ([Id]),
    CONSTRAINT [fk_ServicePOId] FOREIGN KEY ([ServicePOId]) REFERENCES [TRN].[ServicePOMaster] ([Id])
);

