CREATE TABLE [TRN].[SubsectionStructureMaster] (
    [Id]                      VARCHAR (30)  NOT NULL,
    [Code]                    VARCHAR (10)  NULL,
    [Description]             VARCHAR (50)  NULL,
    [Sequence]                DECIMAL (18)  NULL,
    [UnitId]                  VARCHAR (10)  NULL,
    [PlantId]                 VARCHAR (10)  NULL,
    [CompanyId]               VARCHAR (10)  NULL,
    [CompanyGroupId]          VARCHAR (10)  NULL,
    [ProcessId]               VARCHAR (10)  NULL,
    [StartTime]               DATETIME2 (7) NULL,
    [LunchStartTime]          DATETIME2 (7) NULL,
    [LunchEndTime]            DATETIME2 (7) NULL,
    [ApplicableForProduction] BIT           NULL,
    [ApplicableForWIP]        BIT           NULL,
    [ApplicableForIncentive]  BIT           NULL,
    [ApplicableForBulletin]   BIT           NULL,
    [Archive]                 BIT           NULL,
    [AddedBy]                 VARCHAR (30)  NOT NULL,
    [AddedDate]               DATETIME      NOT NULL,
    [AddedFromIP]             VARCHAR (15)  NOT NULL,
    [UpdatedBy]               VARCHAR (30)  NULL,
    [UpdatedDate]             DATETIME      NULL,
    [UpdatedFromIP]           VARCHAR (15)  NULL,
    CONSTRAINT [PK_SubsectionStructure] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_SubsectionStructure_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_SubsectionStructure_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_SubsectionStructure_Unit] FOREIGN KEY ([UnitId]) REFERENCES [ORG].[Unit] ([Id]),
    CONSTRAINT [FK_SubsectionStructureMaster_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_SubsectionStructureMaster_Process] FOREIGN KEY ([ProcessId]) REFERENCES [HKP].[Process] ([Id])
);

