CREATE TABLE [TRN].[VoucherDetail] (
    [Id]                              VARCHAR (80)     NOT NULL,
    [PlantId]                         VARCHAR (10)     NULL,
    [EntityId]                        VARCHAR (10)     NULL,
    [FiscalYearId]                    VARCHAR (10)     NULL,
    [FiscalYearPeriodId]              VARCHAR (10)     NULL,
    [VoucherId]                       VARCHAR (50)     NOT NULL,
    [GLGeneralInfoId]                 VARCHAR (10)     NOT NULL,
    [BudgetMasterId]                  VARCHAR (20)     NULL,
    [ActivityId]                      VARCHAR (10)     NULL,
    [CheckLotDetailId]                INT              NULL,
    [CurrencyId]                      VARCHAR (10)     NULL,
    [BankMasterId]                    VARCHAR (10)     NULL,
    [BankChargeId]                    VARCHAR (30)     NULL,
    [CashMasterId]                    VARCHAR (10)     NULL,
    [CostCenterId]                    VARCHAR (10)     NULL,
    [FinancingDetailId]               VARCHAR (12)     NULL,
    [InvoiceTaxWriteOffDetailId]      VARCHAR (150)    NULL,
    [EmployeeId]                      VARCHAR (30)     NULL,
    [PartyId]                         VARCHAR (10)     NULL,
    [PartyPlantId]                    VARCHAR (12)     NULL,
    [InvoiceDetailId]                 VARCHAR (80)     NULL,
    [AdvanceDetailId]                 VARCHAR (100)    NULL,
    [AdvanceWriteOffDetailId]         VARCHAR (100)    NULL,
    [InvoiceWriteOffDetailId]         VARCHAR (80)     NULL,
    [SecurityDepositDetailId]         VARCHAR (100)    NULL,
    [SecurityDepositWriteOffDetailId] VARCHAR (100)    NULL,
    [EmployeePayableDetailId]         VARCHAR (150)    NULL,
    [EmployeePayableWriteOffDetailId] VARCHAR (150)    NULL,
    [ExpenseBookingDetailId]          VARCHAR (150)    NULL,
    [PartyType]                       VARCHAR (30)     NULL,
    [DocRefNo]                        VARCHAR (50)     NULL,
    [DocDate]                         DATETIME         NULL,
    [RefCode]                         VARCHAR (20)     NULL,
    [Narration]                       VARCHAR (250)    NULL,
    [DrAmount]                        DECIMAL (18, 10) NOT NULL,
    [CrAmount]                        DECIMAL (18, 10) NOT NULL,
    [TotalTaxAmount]                  DECIMAL (18, 10) NOT NULL,
    [PostingWithoutTaxAllow]          BIT              NOT NULL,
    [IsExcludingTax]                  BIT              NULL,
    [IsPark]                          BIT              NOT NULL,
    [Archive]                         BIT              NOT NULL,
    [AddedBy]                         VARCHAR (30)     NOT NULL,
    [AddedDate]                       DATETIME         NOT NULL,
    [AddedFromIP]                     VARCHAR (15)     NOT NULL,
    [UpdatedBy]                       VARCHAR (30)     NULL,
    [UpdatedDate]                     DATETIME         NULL,
    [UpdatedFromIP]                   VARCHAR (15)     NULL,
    [CompanyId]                       VARCHAR (10)     NULL,
    [PaymentSource]                   VARCHAR (20)     NULL,
    [JournalId]                       VARCHAR (40)     NULL,
    [InterTransactionDetailId]        VARCHAR (12)     NULL,
    [BankJournalDetailId]             VARCHAR (30)     NULL,
    [InvoiceTaxDetailId]              VARCHAR (80)     NULL,
    [TrnNature]                       VARCHAR (25)     NULL,
    [AdjustmentNoteDetailId]          VARCHAR (80)     NULL,
    [InventoryIssueDetailId]          VARCHAR (10)     NULL,
    [OpeningBalanceDetailId]          VARCHAR (50)     NULL,
    [FinancingDetailWriteOffId]       VARCHAR (12)     NULL,
    [FixedAssetMasterId]              VARCHAR (30)     NULL,
    [FAType]                          VARCHAR (30)     NULL,
    [IsCapitalizeExpenseRegister]     BIT              NULL,
    CONSTRAINT [PK_VoucherDetail] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_AdvanceDetail_AdvanceDetail] FOREIGN KEY ([AdvanceDetailId]) REFERENCES [TRN].[AdvanceDetail] ([Id]),
    CONSTRAINT [FK_VoucherDetail_Activity] FOREIGN KEY ([ActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_VoucherDetail_AdjustmentNoteDetail] FOREIGN KEY ([AdjustmentNoteDetailId]) REFERENCES [TRN].[AdjustmentNoteDetail] ([Id]),
    CONSTRAINT [FK_VoucherDetail_AdvanceWriteOffDetail] FOREIGN KEY ([AdvanceWriteOffDetailId]) REFERENCES [TRN].[AdvanceWriteOffDetail] ([Id]),
    CONSTRAINT [FK_VoucherDetail_BankCharge] FOREIGN KEY ([BankChargeId]) REFERENCES [TRN].[BankCharge] ([Id]),
    CONSTRAINT [FK_VoucherDetail_BankJournalDetail] FOREIGN KEY ([BankJournalDetailId]) REFERENCES [TRN].[BankJournalDetail] ([Id]),
    CONSTRAINT [FK_VoucherDetail_BankMaster] FOREIGN KEY ([BankMasterId]) REFERENCES [MST].[BankMaster] ([Id]),
    CONSTRAINT [FK_VoucherDetail_BudgetMaster] FOREIGN KEY ([BudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_VoucherDetail_CashMaster] FOREIGN KEY ([CashMasterId]) REFERENCES [MST].[CashMaster] ([Id]),
    CONSTRAINT [FK_VoucherDetail_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_VoucherDetail_CostCenter] FOREIGN KEY ([CostCenterId]) REFERENCES [ORG].[CostCenter] ([Id]),
    CONSTRAINT [FK_VoucherDetail_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_VoucherDetail_EmployeeInformation] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_VoucherDetail_EmployeePayableDetail] FOREIGN KEY ([EmployeePayableDetailId]) REFERENCES [TRN].[EmployeePayableDetail] ([Id]),
    CONSTRAINT [FK_VoucherDetail_EmployeePayableWriteOffDetail] FOREIGN KEY ([EmployeePayableWriteOffDetailId]) REFERENCES [TRN].[EmployeePayableWriteOffDetail] ([Id]),
    CONSTRAINT [FK_VoucherDetail_Entity] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_VoucherDetail_ExpenseBookingDetail] FOREIGN KEY ([ExpenseBookingDetailId]) REFERENCES [TRN].[ExpenseBookingDetail] ([Id]),
    CONSTRAINT [FK_VoucherDetail_FinancingDetail] FOREIGN KEY ([FinancingDetailId]) REFERENCES [TRN].[FinancingDetail] ([Id]),
    CONSTRAINT [FK_VoucherDetail_FinancingDetailWriteOff] FOREIGN KEY ([FinancingDetailWriteOffId]) REFERENCES [TRN].[FinancingDetailWriteOff] ([Id]),
    CONSTRAINT [FK_VoucherDetail_FiscalYear] FOREIGN KEY ([FiscalYearId]) REFERENCES [SCS].[FiscalYear] ([Id]),
    CONSTRAINT [FK_VoucherDetail_FiscalYearPeriod] FOREIGN KEY ([FiscalYearPeriodId]) REFERENCES [SCS].[FiscalYearPeriod] ([Id]),
    CONSTRAINT [FK_VoucherDetail_FixedAssetMaster] FOREIGN KEY ([FixedAssetMasterId]) REFERENCES [MST].[FixedAssetMaster] ([Id]),
    CONSTRAINT [FK_VoucherDetail_GLGeneralInfo] FOREIGN KEY ([GLGeneralInfoId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_VoucherDetail_InvoiceDetail] FOREIGN KEY ([InvoiceDetailId]) REFERENCES [TRN].[InvoiceDetail] ([Id]),
    CONSTRAINT [FK_VoucherDetail_InvoiceTaxDetail] FOREIGN KEY ([InvoiceTaxDetailId]) REFERENCES [TRN].[InvoiceTaxDetail] ([Id]),
    CONSTRAINT [FK_VoucherDetail_InvoiceWriteOffDetail] FOREIGN KEY ([InvoiceWriteOffDetailId]) REFERENCES [TRN].[InvoiceWriteOffDetail] ([Id]),
    CONSTRAINT [FK_VoucherDetail_OpeningBalanceDetail] FOREIGN KEY ([OpeningBalanceDetailId]) REFERENCES [TRN].[OpeningBalanceDetail] ([Id]),
    CONSTRAINT [FK_VoucherDetail_Party] FOREIGN KEY ([PartyId]) REFERENCES [HKP].[Party] ([Id]),
    CONSTRAINT [FK_VoucherDetail_PartyPlant] FOREIGN KEY ([PartyPlantId]) REFERENCES [HKP].[PartyPlant] ([Id]),
    CONSTRAINT [FK_VoucherDetail_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_VoucherDetail_SecurityDepositDetail] FOREIGN KEY ([SecurityDepositDetailId]) REFERENCES [TRN].[SecurityDepositDetail] ([Id]),
    CONSTRAINT [FK_VoucherDetail_SecurityDepositWriteOffDetail] FOREIGN KEY ([SecurityDepositWriteOffDetailId]) REFERENCES [TRN].[SecurityDepositWriteOffDetail] ([Id]),
    CONSTRAINT [FK_VoucherDetail_Voucher] FOREIGN KEY ([VoucherId]) REFERENCES [TRN].[Voucher] ([Id])
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'ACCIF14', @level0type = N'SCHEMA', @level0name = N'TRN', @level1type = N'TABLE', @level1name = N'VoucherDetail';

