CREATE TABLE [SEC].[User] (
    [Id]                    VARCHAR (10)  NOT NULL,
    [CompanyGroupId]        VARCHAR (10)  NOT NULL,
    [EmployeeId]            VARCHAR (30)  NULL,
    [UserId]                VARCHAR (30)  NOT NULL,
    [FullName]              VARCHAR (100) NULL,
    [Password]              VARCHAR (100) NOT NULL,
    [LastPwdChangedDay]     DATETIME      NULL,
    [DateOfBirth]           DATE          NULL,
    [Image]                 VARCHAR (50)  NULL,
    [Phone]                 VARCHAR (20)  NULL,
    [Email]                 VARCHAR (80)  NULL,
    [EmailVerified]         BIT           NOT NULL,
    [EmailVerifiedDate]     DATETIME      NULL,
    [EmailVerificationCode] VARCHAR (36)  NULL,
    [PasswordFailCount]     INT           CONSTRAINT [DF_User_PasswordFailCount] DEFAULT ((0)) NOT NULL,
    [UserLocked]            BIT           NOT NULL,
    [UserLockedDate]        DATETIME      NULL,
    [UserUnlockDate]        DATETIME      NULL,
    [AuthToken]             VARCHAR (36)  NOT NULL,
    [AuthTokenFailCount]    INT           CONSTRAINT [DF_User_AuthKeyFailCount] DEFAULT ((0)) NOT NULL,
    [AuthTokenLocked]       BIT           NOT NULL,
    [AuthTokenLockedDate]   DATETIME      NULL,
    [AuthTokenUnlockDate]   DATETIME      NULL,
    [SysAdmin]              BIT           NOT NULL,
    [PowerUser]             BIT           NOT NULL,
    [PwdChangeOnFirstLogin] BIT           NOT NULL,
    [PasswordNeverExpired]  BIT           NOT NULL,
    [Remarks]               VARCHAR (250) NULL,
    [DOSBy]                 VARCHAR (100) NULL,
    [DOSDate]               DATETIME      NULL,
    [Active]                BIT           NOT NULL,
    [Archive]               BIT           CONSTRAINT [DF_User_ARCHIVE] DEFAULT ((0)) NOT NULL,
    [AddedBy]               VARCHAR (30)  NOT NULL,
    [AddedDate]             DATETIME      NOT NULL,
    [AddedFromIP]           VARCHAR (15)  NOT NULL,
    [UpdatedBy]             VARCHAR (30)  NULL,
    [UpdatedDate]           DATETIME      NULL,
    [UpdatedFromIP]         VARCHAR (15)  NULL,
    CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_User_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_User_EmployeeProfile] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [IX_User_AuthKey] UNIQUE NONCLUSTERED ([AuthToken] ASC),
    CONSTRAINT [IX_User_UserIdCompanyGroupId] UNIQUE NONCLUSTERED ([UserId] ASC, [CompanyGroupId] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Need for 2 factor authentication', @level0type = N'SCHEMA', @level0name = N'SEC', @level1type = N'TABLE', @level1name = N'User', @level2type = N'COLUMN', @level2name = N'Phone';

