CREATE TABLE [MST].[AccessControllerList] (
    [Id]                        VARCHAR (10)  NOT NULL,
    [CompanyGroupId]            VARCHAR (10)  NOT NULL,
    [PlantId]                   VARCHAR (10)  NOT NULL,
    [MachineID]                 INT           NOT NULL,
    [MachineIP]                 VARCHAR (50)  NOT NULL,
    [IsActive]                  BIT           CONSTRAINT [DF_BiometricDeviceAsAccessController_IsActive] DEFAULT ((1)) NOT NULL,
    [IsDataAutoDownloadBySched] BIT           CONSTRAINT [DF_BiometricDeviceAsAccessController_IsDataAutoDownloadBySched] DEFAULT ((1)) NOT NULL,
    [IsAdmin]                   BIT           CONSTRAINT [DF_BiometricDeviceAsAccessController_IsAdmin] DEFAULT ((0)) NOT NULL,
    [AdminEnrollID]             VARCHAR (50)  NULL,
    [AdminPassword]             VARCHAR (50)  NULL,
    [AdminProxiCard]            VARCHAR (50)  NULL,
    [Description]               VARCHAR (200) NULL,
    [Remarks]                   VARCHAR (200) NULL,
    [OneFlag]                   VARCHAR (5)   NULL,
    [ZeroFlag]                  VARCHAR (5)   NULL,
    [RegisTypeDec]              BIT           CONSTRAINT [DF_BiometricDeviceAsAccessController_RegisTypeDec] DEFAULT ((0)) NOT NULL,
    [RegisTypeHex]              BIT           CONSTRAINT [DF_BiometricDeviceAsAccessController_RegisTypeHex] DEFAULT ((0)) NOT NULL,
    [RegisCharacter]            INT           CONSTRAINT [DF_BiometricDeviceAsAccessController_RegisCharacter] DEFAULT ((0)) NOT NULL,
    [DownLdEnrollID]            BIT           CONSTRAINT [DF_BiometricDeviceAsAccessController_DownLdEnrollID] DEFAULT ((0)) NOT NULL,
    [DownLdTypeDec]             BIT           CONSTRAINT [DF_BiometricDeviceAsAccessController_DownLdTypeDec] DEFAULT ((0)) NOT NULL,
    [DownLdTypeHex]             BIT           CONSTRAINT [DF_BiometricDeviceAsAccessController_DownLdTypeHex] DEFAULT ((0)) NOT NULL,
    [DownLdTypeScan]            BIT           CONSTRAINT [DF_BiometricDeviceAsAccessController_DownLdTypeScan] DEFAULT ((0)) NOT NULL,
    [DownLdCharacter]           INT           CONSTRAINT [DF_BiometricDeviceAsAccessController_DownLdCharacter] DEFAULT ((0)) NOT NULL,
    [IsDataClearAftDW]          BIT           CONSTRAINT [DF_BiometricDeviceAsAccessController_IsDataClearAftDW] DEFAULT ((1)) NOT NULL,
    [AddedBy]                   VARCHAR (30)  NULL,
    [AddedDate]                 DATETIME      NULL,
    [AddedFromIP]               VARCHAR (15)  NULL,
    [UpdatedBy]                 VARCHAR (30)  NULL,
    [UpdatedDate]               DATETIME      NULL,
    [UpdatedFromIP]             VARCHAR (15)  NULL,
    [IsDeviceBasedInOut]        BIT           DEFAULT ((1)) NOT NULL,
    [DeviceInOutFlag]           VARCHAR (5)   NULL,
    [AttendanceDeviceZoneid]    VARCHAR (10)  NULL,
    CONSTRAINT [PK_BiometricDeviceAsAccessList] PRIMARY KEY CLUSTERED ([Id] ASC),
    FOREIGN KEY ([AttendanceDeviceZoneid]) REFERENCES [HKP].[AttendanceDeviceZone] ([Id])
);

