CREATE TABLE [MST].[AnnualBudgetDetail] (
    [Id]                 VARCHAR (20)    NOT NULL,
    [CompanyGroupId]     VARCHAR (10)    NOT NULL,
    [CompanyId]          VARCHAR (10)    NOT NULL,
    [PlantId]            VARCHAR (10)    NOT NULL,
    [EntityId]           VARCHAR (10)    NOT NULL,
    [AnnualBudgetId]     VARCHAR (20)    NOT NULL,
    [FiscalYearId]       VARCHAR (10)    NOT NULL,
    [FiscalYearPeriodId] VARCHAR (10)    NOT NULL,
    [BudgetMasterId]     VARCHAR (20)    NOT NULL,
    [StandardAmount]     DECIMAL (18, 2) NOT NULL,
    [ActualAmount]       DECIMAL (18, 2) NOT NULL,
    [Remarks]            VARCHAR (250)   NULL,
    [AddedBy]            VARCHAR (30)    NOT NULL,
    [AddedDate]          DATETIME        NOT NULL,
    [AddedFromIP]        VARCHAR (15)    NOT NULL,
    [UpdatedBy]          VARCHAR (30)    NULL,
    [UpdatedDate]        DATETIME        NULL,
    [UpdatedFromIP]      VARCHAR (15)    NULL,
    CONSTRAINT [PK_AnnualBudgetDetail] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_AnnualBudgetDetail_AnnualBudget] FOREIGN KEY ([AnnualBudgetId]) REFERENCES [MST].[AnnualBudget] ([Id]),
    CONSTRAINT [FK_AnnualBudgetDetail_BudgetMaster] FOREIGN KEY ([BudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_AnnualBudgetDetail_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_AnnualBudgetDetail_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_AnnualBudgetDetail_Entity] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_AnnualBudgetDetail_FiscalYear] FOREIGN KEY ([FiscalYearId]) REFERENCES [SCS].[FiscalYear] ([Id]),
    CONSTRAINT [FK_AnnualBudgetDetail_FiscalYearPeriod] FOREIGN KEY ([FiscalYearPeriodId]) REFERENCES [SCS].[FiscalYearPeriod] ([Id]),
    CONSTRAINT [FK_AnnualBudgetDetail_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id])
);

