CREATE TABLE [MST].[AnnualBudget] (
    [Id]                  VARCHAR (20)    NOT NULL,
    [CompanyGroupId]      VARCHAR (10)    NOT NULL,
    [CompanyId]           VARCHAR (10)    NOT NULL,
    [FiscalYearId]        VARCHAR (10)    NOT NULL,
    [EntityId]            VARCHAR (10)    NOT NULL,
    [BudgetMasterId]      VARCHAR (20)    NOT NULL,
    [CurrencyId]          VARCHAR (10)    NOT NULL,
    [PositionId]          VARCHAR (10)    NULL,
    [ManpowerBudgetId]    VARCHAR (10)    NULL,
    [EmployeeId]          VARCHAR (30)    NULL,
    [ResponsiblePersonBy] VARCHAR (10)    NULL,
    [ApprovalCategory]    VARCHAR (10)    NULL,
    [BudgetLimit]         VARCHAR (20)    NULL,
    [Amount]              DECIMAL (18, 2) NOT NULL,
    [VariationPercent]    DECIMAL (18, 2) NOT NULL,
    [Remarks]             VARCHAR (250)   NULL,
    [Active]              BIT             NOT NULL,
    [Archive]             BIT             NOT NULL,
    [AddedBy]             VARCHAR (30)    NOT NULL,
    [AddedDate]           DATETIME        NOT NULL,
    [AddedFromIP]         VARCHAR (15)    NOT NULL,
    [UpdatedBy]           VARCHAR (30)    NULL,
    [UpdatedDate]         DATETIME        NULL,
    [UpdatedFromIP]       VARCHAR (15)    NULL,
    [PlantId]             VARCHAR (10)    NOT NULL,
    CONSTRAINT [PK_AnnualBudget] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_AnnualBudget_BudgetMaster] FOREIGN KEY ([BudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_AnnualBudget_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_AnnualBudget_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_AnnualBudget_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_AnnualBudget_EmployeeInformation] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_AnnualBudget_Entity] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_AnnualBudget_FiscalYear] FOREIGN KEY ([FiscalYearId]) REFERENCES [SCS].[FiscalYear] ([Id]),
    CONSTRAINT [FK_AnnualBudget_ManpowerBudget] FOREIGN KEY ([ManpowerBudgetId]) REFERENCES [MST].[ManpowerBudget] ([Id]),
    CONSTRAINT [FK_AnnualBudget_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_AnnualBudget_Position] FOREIGN KEY ([PositionId]) REFERENCES [ORG].[Position] ([Id])
);

