CREATE TABLE [MST].[BankMaster] (
    [Id]                              VARCHAR (10)    NOT NULL,
    [CompanyGroupId]                  VARCHAR (10)    NOT NULL,
    [CompanyId]                       VARCHAR (10)    NOT NULL,
    [PlantId]                         VARCHAR (10)    NULL,
    [EntityId]                        VARCHAR (10)    NULL,
    [GLGeneralInfoId]                 VARCHAR (10)    NULL,
    [BudgetMasterId]                  VARCHAR (20)    NULL,
    [ActivityId]                      VARCHAR (10)    NULL,
    [BankCategoryId]                  VARCHAR (10)    NOT NULL,
    [BankSubCategoryId]               VARCHAR (10)    NULL,
    [BankAccountTypeId]               VARCHAR (10)    NULL,
    [BankId]                          VARCHAR (10)    NULL,
    [BankBranchId]                    VARCHAR (10)    NULL,
    [CurrencyId]                      VARCHAR (10)    NULL,
    [ResponsiblePersonId]             VARCHAR (30)    NULL,
    [AccountType]                     VARCHAR (30)    NULL,
    [Code]                            VARCHAR (10)    NOT NULL,
    [AccountTitle]                    VARCHAR (50)    NOT NULL,
    [OpeningDate]                     DATETIME        NULL,
    [ShortAccountNumber]              VARCHAR (30)    NOT NULL,
    [AccountNumber]                   VARCHAR (30)    NOT NULL,
    [IsLimitApplicable]               BIT             NULL,
    [LimitAmount]                     DECIMAL (18, 4) NOT NULL,
    [IsBeyondLimitTransactionAllowed] BIT             NULL,
    [EffectiveDate]                   DATETIME        NULL,
    [ReviewDate]                      DATETIME        NULL,
    [Description]                     VARCHAR (250)   NULL,
    [Remarks]                         VARCHAR (250)   NULL,
    [Active]                          BIT             NOT NULL,
    [Archive]                         BIT             NOT NULL,
    [AddedBy]                         VARCHAR (30)    NOT NULL,
    [AddedDate]                       DATETIME        NOT NULL,
    [AddedFromIP]                     VARCHAR (15)    NOT NULL,
    [UpdatedBy]                       VARCHAR (30)    NULL,
    [UpdatedDate]                     DATETIME        NULL,
    [UpdatedFromIP]                   VARCHAR (15)    NULL,
    CONSTRAINT [PK_BankMaster] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_BankMaster_Activity] FOREIGN KEY ([ActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_BankMaster_Bank] FOREIGN KEY ([BankId]) REFERENCES [HKP].[Bank] ([Id]),
    CONSTRAINT [FK_BankMaster_BankAccountType] FOREIGN KEY ([BankAccountTypeId]) REFERENCES [HKP].[BankAccountType] ([Id]),
    CONSTRAINT [FK_BankMaster_BankBranch] FOREIGN KEY ([BankBranchId]) REFERENCES [HKP].[BankBranch] ([Id]),
    CONSTRAINT [FK_BankMaster_BankCategory] FOREIGN KEY ([BankCategoryId]) REFERENCES [HKP].[BankCategory] ([Id]),
    CONSTRAINT [FK_BankMaster_BankSubCategory] FOREIGN KEY ([BankSubCategoryId]) REFERENCES [HKP].[BankSubCategory] ([Id]),
    CONSTRAINT [FK_BankMaster_BudgetMaster] FOREIGN KEY ([BudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_BankMaster_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_BankMaster_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_BankMaster_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_BankMaster_EmployeeInformation] FOREIGN KEY ([ResponsiblePersonId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_BankMaster_Entity] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_BankMaster_GLGeneralInfo] FOREIGN KEY ([GLGeneralInfoId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_BankMaster_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id])
);

