CREATE TABLE [MST].[BudgetMaster] (
    [Id]                       VARCHAR (20)  NOT NULL,
    [COAId]                    VARCHAR (10)  NULL,
    [GLGeneralInfoId]          VARCHAR (10)  NULL,
    [BudgetGroupId]            VARCHAR (10)  NULL,
    [BudgetCategoryId]         VARCHAR (10)  NULL,
    [BudgetSubCategoryId]      VARCHAR (10)  NULL,
    [BudgetClassId]            VARCHAR (10)  NULL,
    [BudgetId]                 VARCHAR (10)  NOT NULL,
    [RegisterId]               VARCHAR (10)  NULL,
    [BudgetType]               VARCHAR (10)  NULL,
    [Remarks]                  VARCHAR (250) NULL,
    [IsProject]                BIT           NOT NULL,
    [Active]                   BIT           NOT NULL,
    [Archive]                  BIT           NOT NULL,
    [AddedBy]                  VARCHAR (30)  NOT NULL,
    [AddedDate]                DATETIME      NOT NULL,
    [AddedFromIP]              VARCHAR (15)  NOT NULL,
    [UpdatedBy]                VARCHAR (30)  NULL,
    [UpdatedDate]              DATETIME      NULL,
    [UpdatedFromIP]            VARCHAR (15)  NULL,
    [DefaultTransactionStatus] BIT           DEFAULT ((0)) NOT NULL,
    [TransactionParameter]     VARCHAR (50)  NULL,
    [PaymentVoucherType]       VARCHAR (50)  NULL,
    [Narration]                VARCHAR (250) NULL,
    [IsNarrationEditable]      BIT           DEFAULT ((0)) NOT NULL,
    [IsCarryforward]           BIT           DEFAULT ((0)) NOT NULL,
    [IsPartyListing]           BIT           DEFAULT ((0)) NULL,
    [PaymentRuleDeduction]     VARCHAR (50)  NULL,
    [IsDirectPaymentVoucher]   BIT           DEFAULT ((0)) NOT NULL,
    [PaymentMode]              VARCHAR (10)  NULL,
    [RefNo]                    VARCHAR (20)  NULL,
    [ReportType]               VARCHAR (10)  NULL,
    [IsOrderSpecific]          BIT           DEFAULT ((0)) NULL,
    CONSTRAINT [PK_BudgetMaster] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_BudgetMaster_Budget] FOREIGN KEY ([BudgetId]) REFERENCES [HKP].[Budget] ([Id]),
    CONSTRAINT [FK_BudgetMaster_BudgetCategory] FOREIGN KEY ([BudgetCategoryId]) REFERENCES [HKP].[BudgetCategory] ([Id]),
    CONSTRAINT [FK_BudgetMaster_BudgetClass] FOREIGN KEY ([BudgetClassId]) REFERENCES [HKP].[BudgetClass] ([Id]),
    CONSTRAINT [FK_BudgetMaster_BudgetGroup] FOREIGN KEY ([BudgetGroupId]) REFERENCES [HKP].[BudgetGroup] ([Id]),
    CONSTRAINT [FK_BudgetMaster_BudgetSubCategory] FOREIGN KEY ([BudgetSubCategoryId]) REFERENCES [HKP].[BudgetSubCategory] ([Id]),
    CONSTRAINT [FK_BudgetMaster_COA] FOREIGN KEY ([COAId]) REFERENCES [HKP].[COA] ([Id]),
    CONSTRAINT [FK_BudgetMaster_GLGeneralInfo] FOREIGN KEY ([GLGeneralInfoId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_BudgetMaster_Register] FOREIGN KEY ([RegisterId]) REFERENCES [HKP].[Register] ([Id])
);

