CREATE TABLE [MST].[BudgetApprovalPerson] (
    [Id]               VARCHAR (50) NOT NULL,
    [AnnualBudgetId]   VARCHAR (20) NULL,
    [PositionId]       VARCHAR (10) NULL,
    [ManpowerBudgetId] VARCHAR (10) NULL,
    [EmployeeId]       VARCHAR (30) NULL,
    [ApprovalLevel]    INT          NOT NULL,
    [SourceType]       VARCHAR (30) NULL,
    [Active]           BIT          NOT NULL,
    [Archive]          BIT          NOT NULL,
    [AddedBy]          VARCHAR (30) NOT NULL,
    [AddedDate]        DATETIME     NOT NULL,
    [AddedFromIP]      VARCHAR (15) NOT NULL,
    [UpdatedBy]        VARCHAR (30) NULL,
    [UpdatedDate]      DATETIME     NULL,
    [UpdatedFromIP]    VARCHAR (15) NULL,
    [BudgetMasterId]   VARCHAR (20) NULL,
    [DepartmentId]     VARCHAR (10) NULL,
    [EntityId]         VARCHAR (10) NULL,
    [CompanyId]        VARCHAR (10) NULL,
    CONSTRAINT [PK_BudgetApprovalPerson] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_BudgetApprovalPerson_AnnualBudget] FOREIGN KEY ([AnnualBudgetId]) REFERENCES [MST].[AnnualBudget] ([Id]),
    CONSTRAINT [FK_BudgetApprovalPerson_BudgetMaster] FOREIGN KEY ([BudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_BudgetApprovalPerson_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_BudgetApprovalPerson_Department] FOREIGN KEY ([DepartmentId]) REFERENCES [ORG].[Department] ([Id]),
    CONSTRAINT [FK_BudgetApprovalPerson_Employee] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_BudgetApprovalPerson_Entity] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_BudgetApprovalPerson_ManpowerBudget] FOREIGN KEY ([ManpowerBudgetId]) REFERENCES [MST].[ManpowerBudget] ([Id]),
    CONSTRAINT [FK_BudgetApprovalPerson_Position] FOREIGN KEY ([PositionId]) REFERENCES [ORG].[Position] ([Id])
);

