CREATE TABLE [MST].[BulletinTemplateDetail] (
    [Id]                       VARCHAR (50)    NOT NULL,
    [BulletinTemplateMasterId] VARCHAR (10)    NOT NULL,
    [Sequence]                 DECIMAL (18, 2) NOT NULL,
    [OperationVariationId]     VARCHAR (10)    NULL,
    [OperationGroup]           VARCHAR (50)    NULL,
    [SkillId]                  VARCHAR (10)    NULL,
    [MachineVarientId]         VARCHAR (10)    NULL,
    [FGZoneId]                 VARCHAR (10)    NULL,
    [FGComponentId]            VARCHAR (10)    NULL,
    [AdditionalSPT]            DECIMAL (18, 4) NOT NULL,
    [TotalSPT]                 DECIMAL (18, 4) NOT NULL,
    [AllotedWorkstation]       DECIMAL (18, 4) NULL,
    [AllotedManpower]          DECIMAL (18, 4) NULL,
    [AttachmentId]             VARCHAR (10)    NULL,
    [GaugeFolderId]            VARCHAR (10)    NULL,
    [OperationConsumptionId]   VARCHAR (10)    NULL,
    [OperationTypeId]          VARCHAR (10)    NULL,
    [Frequency]                DECIMAL (18, 4) NULL,
    [Remark]                   VARCHAR (150)   NULL,
    [AddedBy]                  VARCHAR (30)    NOT NULL,
    [AddedDate]                DATETIME        NOT NULL,
    [AddedFromIP]              VARCHAR (15)    NOT NULL,
    [UpdatedBy]                VARCHAR (30)    NULL,
    [UpdatedDate]              DATETIME        NULL,
    [UpdatedFromIP]            VARCHAR (15)    NULL,
    [OperationCategoryId]      VARCHAR (10)    NULL,
    [QualityLevel]             VARCHAR (10)    NULL,
    [AvgAllotedTime]           DECIMAL (18, 4) CONSTRAINT [DF__BulletinT__AvgAl__739E2DA5] DEFAULT ((0)) NOT NULL,
    [OperationTargetPerHr]     DECIMAL (18, 4) CONSTRAINT [DF__BulletinT__Opera__6F37D48D] DEFAULT ((0)) NOT NULL,
    [RequiredManPower]         DECIMAL (18, 4) CONSTRAINT [DF__BulletinT__Requi__702BF8C6] DEFAULT ((0)) NOT NULL,
    [SPI]                      INT             CONSTRAINT [DF__BulletinTem__SPI__54D8E40C] DEFAULT ((0)) NULL,
    [NoOfStitch]               INT             CONSTRAINT [DF__BulletinT__NoOfS__55CD0845] DEFAULT ((0)) NULL,
    [OperationLength]          DECIMAL (18, 2) NULL,
    [StitchCodeId]             VARCHAR (10)    NULL,
    [FabricWidth]              DECIMAL (18, 4) CONSTRAINT [DF__BulletinT__Fabri__57B550B7] DEFAULT ((0)) NULL,
    [NeedleDescription]        VARCHAR (100)   NULL,
    [NeedleMaterialMasterId]   VARCHAR (30)    NULL,
    [NeedleArticleId]          VARCHAR (10)    NULL,
    [BobbinDescription]        VARCHAR (100)   NULL,
    [BobbinMaterialMasterId]   VARCHAR (30)    NULL,
    [BobbinArticleId]          VARCHAR (10)    NULL,
    [LooperDescription]        VARCHAR (100)   NULL,
    [LooperMaterialMasterId]   VARCHAR (30)    NULL,
    [LooperArticleId]          VARCHAR (10)    NULL,
    [SPIConsumption]           DECIMAL (18, 4) DEFAULT ((0)) NULL,
    [NeedleConsumption]        DECIMAL (18, 4) DEFAULT ((0)) NULL,
    [BobbinConsumption]        DECIMAL (18, 4) DEFAULT ((0)) NULL,
    [LooperConsumption]        DECIMAL (18, 4) DEFAULT ((0)) NULL,
    [Consumption]              DECIMAL (18, 4) DEFAULT ((0)) NULL,
    [WastagePercentage]        DECIMAL (18, 4) DEFAULT ((0)) NULL,
    [ExtraOrderPercentage]     DECIMAL (18, 4) DEFAULT ((0)) NULL,
    CONSTRAINT [PK_BulletinTemplateDetail] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_BulletinTemplateDetail_Attachment] FOREIGN KEY ([AttachmentId]) REFERENCES [HKP].[Attachment] ([Id]),
    CONSTRAINT [FK_BulletinTemplateDetail_BobbinArticle] FOREIGN KEY ([BobbinArticleId]) REFERENCES [MST].[MaterialMasterArticle] ([Id]),
    CONSTRAINT [FK_BulletinTemplateDetail_BobbinMaterialMaster] FOREIGN KEY ([BobbinMaterialMasterId]) REFERENCES [MST].[MaterialMaster] ([Id]),
    CONSTRAINT [FK_BulletinTemplateDetail_BulletinTemplateMaster] FOREIGN KEY ([BulletinTemplateMasterId]) REFERENCES [MST].[BulletinTemplateMaster] ([Id]),
    CONSTRAINT [FK_BulletinTemplateDetail_FGComponent] FOREIGN KEY ([FGComponentId]) REFERENCES [HKP].[FGComponent] ([Id]),
    CONSTRAINT [FK_BulletinTemplateDetail_FGZone] FOREIGN KEY ([FGZoneId]) REFERENCES [HKP].[FGZone] ([Id]),
    CONSTRAINT [FK_BulletinTemplateDetail_GaugeFolder] FOREIGN KEY ([GaugeFolderId]) REFERENCES [HKP].[GaugeFolder] ([Id]),
    CONSTRAINT [FK_BulletinTemplateDetail_LooperArticle] FOREIGN KEY ([LooperArticleId]) REFERENCES [MST].[MaterialMasterArticle] ([Id]),
    CONSTRAINT [FK_BulletinTemplateDetail_LooperMaterialMaster] FOREIGN KEY ([LooperMaterialMasterId]) REFERENCES [MST].[MaterialMaster] ([Id]),
    CONSTRAINT [FK_BulletinTemplateDetail_MachineVariant] FOREIGN KEY ([MachineVarientId]) REFERENCES [MST].[MaterialMasterArticle] ([Id]),
    CONSTRAINT [FK_BulletinTemplateDetail_NeedleArticle] FOREIGN KEY ([NeedleArticleId]) REFERENCES [MST].[MaterialMasterArticle] ([Id]),
    CONSTRAINT [FK_BulletinTemplateDetail_NeedleMaterialMaster] FOREIGN KEY ([NeedleMaterialMasterId]) REFERENCES [MST].[MaterialMaster] ([Id]),
    CONSTRAINT [FK_BulletinTemplateDetail_OperationCategory] FOREIGN KEY ([OperationCategoryId]) REFERENCES [HKP].[OperationCategory] ([Id]),
    CONSTRAINT [FK_BulletinTemplateDetail_OperationConsumption] FOREIGN KEY ([OperationConsumptionId]) REFERENCES [HKP].[OperationConsumption] ([Id]),
    CONSTRAINT [FK_BulletinTemplateDetail_OperationType] FOREIGN KEY ([OperationTypeId]) REFERENCES [HKP].[OperationType] ([Id]),
    CONSTRAINT [FK_BulletinTemplateDetail_OperationVariation] FOREIGN KEY ([OperationVariationId]) REFERENCES [MST].[OperationVariation] ([Id]),
    CONSTRAINT [FK_BulletinTemplateDetail_Skill] FOREIGN KEY ([SkillId]) REFERENCES [HKP].[Skill] ([Id])
);

