CREATE TABLE [MST].[CropMaster] (
    [Id]                  VARCHAR (20)    NOT NULL,
    [Sequence]            DECIMAL (18, 2) NOT NULL,
    [Code]                VARCHAR (10)    NOT NULL,
    [ShortName]           VARCHAR (15)    NOT NULL,
    [StandardName]        VARCHAR (50)    NOT NULL,
    [UserName]            VARCHAR (50)    NOT NULL,
    [CropCategoryId]      VARCHAR (20)    NOT NULL,
    [CropSubCategoryId]   VARCHAR (20)    NOT NULL,
    [AreaUOMId]           VARCHAR (10)    NOT NULL,
    [OutputUOMId]         VARCHAR (10)    NOT NULL,
    [MinimumOutput]       DECIMAL (18, 2) NOT NULL,
    [MaximumOutput]       DECIMAL (18, 2) NOT NULL,
    [AverageOutput]       DECIMAL (18, 2) NOT NULL,
    [MinimumRate]         VARCHAR (20)    NULL,
    [MaximumRate]         VARCHAR (20)    NULL,
    [AverageRate]         VARCHAR (20)    NULL,
    [ResponsiblePersonId] VARCHAR (30)    NULL,
    [Remarks]             VARCHAR (250)   NULL,
    [AddedBy]             VARCHAR (30)    NOT NULL,
    [AddedDate]           DATETIME        NOT NULL,
    [AddedFromIP]         VARCHAR (15)    NOT NULL,
    [UpdatedBy]           VARCHAR (30)    NULL,
    [UpdatedDate]         DATETIME        NULL,
    [UpdatedFromIP]       VARCHAR (15)    NULL,
    [TransactionTypeId]   VARCHAR (20)    NULL,
    CONSTRAINT [PK_CropMaster] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_CropMaster_AreaUOM] FOREIGN KEY ([AreaUOMId]) REFERENCES [SCS].[UnitOfMeasurement] ([Id]),
    CONSTRAINT [FK_CropMaster_CropCategory] FOREIGN KEY ([CropCategoryId]) REFERENCES [HKP].[CropCategory] ([Id]),
    CONSTRAINT [FK_CropMaster_CropSubCategory] FOREIGN KEY ([CropSubCategoryId]) REFERENCES [HKP].[CropSubCategory] ([Id]),
    CONSTRAINT [FK_CropMaster_OutputUOM] FOREIGN KEY ([OutputUOMId]) REFERENCES [SCS].[UnitOfMeasurement] ([Id]),
    CONSTRAINT [FK_CropMaster_ResponsiblePerson] FOREIGN KEY ([ResponsiblePersonId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_CropMaster_TransactionType] FOREIGN KEY ([TransactionTypeId]) REFERENCES [dbo].[TransactionType] ([Id])
);

