CREATE TABLE [MST].[FarmerMasterPlot] (
    [Id]                     VARCHAR (20)    NOT NULL,
    [FarmerMasterId]         VARCHAR (20)    NOT NULL,
    [PlotNameNo]             VARCHAR (50)    NOT NULL,
    [PlotArea]               DECIMAL (18, 2) NOT NULL,
    [Survey]                 VARCHAR (50)    NOT NULL,
    [Latitude]               VARCHAR (35)    NULL,
    [Longitude]              VARCHAR (35)    NULL,
    [PlotStatus]             VARCHAR (20)    NOT NULL,
    [ICSMasterId]            VARCHAR (20)    NOT NULL,
    [FarmerRegistrationID]   VARCHAR (30)    NOT NULL,
    [FarmerRegistrationDate] DATETIME        NOT NULL,
    [InspectionDate]         DATETIME        NOT NULL,
    [ApprovalDate]           DATETIME        NULL,
    [RenewalPeriod]          DECIMAL (18, 2) NOT NULL,
    [FileName]               VARCHAR (100)   NULL,
    [Remarks]                VARCHAR (250)   NULL,
    [Active]                 BIT             NOT NULL,
    [AddedBy]                VARCHAR (30)    NOT NULL,
    [AddedDate]              DATETIME        NOT NULL,
    [AddedFromIP]            VARCHAR (15)    NOT NULL,
    [UpdatedBy]              VARCHAR (30)    NULL,
    [UpdatedDate]            DATETIME        NULL,
    [UpdatedFromIP]          VARCHAR (15)    NULL,
    CONSTRAINT [PK_FarmerMasterPlot] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_FarmerMasterPlot_FarmerMaster] FOREIGN KEY ([FarmerMasterId]) REFERENCES [MST].[FarmerMaster] ([Id]),
    CONSTRAINT [FK_FarmerMasterPlot_ICSMasterId] FOREIGN KEY ([ICSMasterId]) REFERENCES [MST].[ICSMaster] ([Id]),
    CONSTRAINT [FK_FarmerMasterPlot_PlotStatus] FOREIGN KEY ([PlotStatus]) REFERENCES [HKP].[LandCategory] ([Id])
);

