CREATE TABLE [MST].[ItemMaster] (
    [ID]                  NVARCHAR (128) NOT NULL,
    [StandardName]        NVARCHAR (50)  NULL,
    [Description]         NVARCHAR (50)  NULL,
    [ShortName]           NVARCHAR (50)  NULL,
    [UserName]            NVARCHAR (50)  NULL,
    [Code]                NVARCHAR (50)  NULL,
    [Sequence]            NVARCHAR (50)  NULL,
    [Remarks]             NVARCHAR (50)  NULL,
    [AT73C18]             NVARCHAR (1)   NULL,
    [AT73C19]             NVARCHAR (1)   NULL,
    [ItemTypeID]          NVARCHAR (128) NULL,
    [ExpensesCategoryID]  NVARCHAR (128) NULL,
    [ProcurementCatID]    NVARCHAR (128) NULL,
    [ProcurementBasID]    NVARCHAR (128) NULL,
    [ProcurementFreqID]   NVARCHAR (3)   NULL,
    [PaymentPolicyID]     NVARCHAR (128) NULL,
    [PaymentTermID]       NVARCHAR (128) NULL,
    [DependentDateID]     NVARCHAR (128) NULL,
    [DeliveryDate_Id]     NVARCHAR (128) NULL,
    [GRNDate_Id]          NVARCHAR (128) NULL,
    [PODate_Id]           NVARCHAR (128) NULL,
    [Remark_Id]           NVARCHAR (128) NULL,
    [SpecialCondition_Id] NVARCHAR (128) NULL,
    [ItemCategoryID]      NVARCHAR (128) NULL,
    [ItemSubCategoryID]   NVARCHAR (128) NULL,
    [ItemID]              NVARCHAR (128) NULL,
    [Active]              BIT            NOT NULL,
    [Archive]             BIT            NOT NULL,
    [AddedBy]             VARCHAR (30)   NOT NULL,
    [AddedDate]           DATETIME       NOT NULL,
    [AddedFromIP]         VARCHAR (15)   NOT NULL,
    [UpdatedBy]           VARCHAR (30)   NULL,
    [UpdatedDate]         DATETIME       NULL,
    [UpdatedFromIP]       VARCHAR (15)   NULL,
    CONSTRAINT [PK_aplos.ItemMaster] PRIMARY KEY CLUSTERED ([ID] ASC)
);

