CREATE TABLE [MST].[MachineMaster_old] (
    [Id]                   NVARCHAR (128)  NOT NULL,
    [Sequence]             DECIMAL (18, 2) NOT NULL,
    [CompanyId]            NVARCHAR (2)    NOT NULL,
    [DivisionId]           NVARCHAR (2)    NULL,
    [SubDivisionId]        NVARCHAR (2)    NULL,
    [UnitId]               NVARCHAR (2)    NULL,
    [DepartmentId]         NVARCHAR (2)    NULL,
    [SectionId]            NVARCHAR (2)    NULL,
    [SubSectionId]         NVARCHAR (2)    NULL,
    [LineId]               NVARCHAR (128)  NULL,
    [MachineCategoryId]    NVARCHAR (3)    NULL,
    [MachineSubCategoryId] NVARCHAR (128)  NULL,
    [MachineClassId]       VARCHAR (10)    NULL,
    [MachineSubClassId]    NVARCHAR (128)  NULL,
    [MachineId]            NVARCHAR (128)  NULL,
    [UnitOMId]             NVARCHAR (128)  NULL,
    [ProcessMasterId]      NVARCHAR (128)  NULL,
    [ResponsiblePerson]    NVARCHAR (50)   NULL,
    [MachineCapacity]      NVARCHAR (100)  NULL,
    [Specification]        NVARCHAR (100)  NULL,
    [Purpose]              NVARCHAR (100)  NULL,
    [EffectiveDate]        DATETIME        NULL,
    [ReviewDate]           DATETIME        NULL,
    [Remarks]              NVARCHAR (500)  NULL,
    [Active]               BIT             NOT NULL,
    [Archive]              BIT             NOT NULL,
    [AddedBy]              VARCHAR (30)    NOT NULL,
    [AddedDate]            DATETIME        NOT NULL,
    [AddedFromIP]          VARCHAR (15)    NOT NULL,
    [UpdatedBy]            VARCHAR (30)    NULL,
    [UpdatedDate]          DATETIME        NULL,
    [UpdatedFromIP]        VARCHAR (15)    NULL,
    [SkillId]              VARCHAR (10)    NOT NULL,
    [UserName]             VARCHAR (100)   NOT NULL,
    CONSTRAINT [PK_MachineMasters] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_MachineMaster_Skill] FOREIGN KEY ([SkillId]) REFERENCES [HKP].[Skill] ([Id])
);

