CREATE TABLE [MST].[ManpowerBudget] (
    [Id]                   VARCHAR (10)  NOT NULL,
    [CompanyGroupId]       VARCHAR (10)  NOT NULL,
    [CompanyId]            VARCHAR (10)  NOT NULL,
    [EntityId]             VARCHAR (10)  NOT NULL,
    [PositionId]           VARCHAR (10)  NOT NULL,
    [LineId]               VARCHAR (10)  NULL,
    [ShiftDefinationId]    VARCHAR (30)  NULL,
    [PayrollGroupId]       VARCHAR (10)  NULL,
    [Code]                 VARCHAR (50)  NULL,
    [ROBudgetCode]         VARCHAR (10)  NULL,
    [PRBudgetCode]         VARCHAR (10)  NULL,
    [PreOperatingUpToDate] DATETIME      NULL,
    [Remarks]              VARCHAR (250) NULL,
    [EmploymentType]       VARCHAR (15)  NULL,
    [IsOTEntitled]         BIT           NOT NULL,
    [Active]               BIT           NOT NULL,
    [Archive]              BIT           NOT NULL,
    [AddedBy]              VARCHAR (30)  NOT NULL,
    [AddedDate]            DATETIME      NOT NULL,
    [AddedFromIP]          VARCHAR (15)  NOT NULL,
    [UpdatedBy]            VARCHAR (30)  NULL,
    [UpdatedDate]          DATETIME      NULL,
    [UpdatedFromIP]        VARCHAR (15)  NULL,
    [BudgetedMale]         INT           DEFAULT ((0)) NOT NULL,
    [BudgetedFemale]       INT           DEFAULT ((0)) NOT NULL,
    [OnRollMale]           INT           DEFAULT ((0)) NOT NULL,
    [OnRollFemale]         INT           DEFAULT ((0)) NOT NULL,
    [WorkGroupId]          VARCHAR (10)  NULL,
    [EmployeeLocationId]   VARCHAR (10)  NULL,
    [Deployment]           VARCHAR (50)  NULL,
    [Email]                VARCHAR (50)  NULL,
    [ResponsiblePerson]    VARCHAR (30)  NULL,
    [AttendanceGroupId]    VARCHAR (30)  NULL,
    [RosterPatternId]      VARCHAR (30)  NULL,
    CONSTRAINT [PK_ManpowerBudget] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_manpowerbudget_atdnid] FOREIGN KEY ([AttendanceGroupId]) REFERENCES [dbo].[AttendanceGroup] ([Id]),
    CONSTRAINT [FK_ManpowerBudget_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_ManpowerBudget_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_manpowerbudget_empid] FOREIGN KEY ([ResponsiblePerson]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_ManpowerBudget_EmployeeLocation] FOREIGN KEY ([EmployeeLocationId]) REFERENCES [HKP].[EmployeeLocation] ([Id]),
    CONSTRAINT [FK_ManpowerBudget_Entity] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_ManpowerBudget_Line] FOREIGN KEY ([LineId]) REFERENCES [ORG].[Line] ([Id]),
    CONSTRAINT [FK_ManpowerBudget_PayrollGroup] FOREIGN KEY ([PayrollGroupId]) REFERENCES [HKP].[PayrollGroup] ([Id]),
    CONSTRAINT [FK_ManpowerBudget_Position] FOREIGN KEY ([PositionId]) REFERENCES [ORG].[Position] ([Id]),
    CONSTRAINT [FK_ManpowerBudget_Roster] FOREIGN KEY ([RosterPatternId]) REFERENCES [dbo].[RosterPatternHeader] ([Id]),
    CONSTRAINT [FK_ManpowerBudget_ShiftDefination] FOREIGN KEY ([ShiftDefinationId]) REFERENCES [dbo].[ShiftDefination] ([SystemID]),
    CONSTRAINT [FK_ManpowerBudget_WorkGroup] FOREIGN KEY ([WorkGroupId]) REFERENCES [HKP].[WorkGroup] ([Id])
);

