CREATE TABLE [MST].[MaternityLeavePolicy] (
    [Id]                          VARCHAR (10)    NOT NULL,
    [CompanyId]                   VARCHAR (10)    NOT NULL,
    [PlantId]                     VARCHAR (10)    NOT NULL,
    [ChildNo]                     INT             CONSTRAINT [DF_MaternityLeavePolicy_ChildNo] DEFAULT ((0)) NOT NULL,
    [AddedBy]                     VARCHAR (30)    NOT NULL,
    [AddedDate]                   DATETIME        NOT NULL,
    [AddedFromIP]                 VARCHAR (15)    NOT NULL,
    [UpdatedBy]                   VARCHAR (30)    NULL,
    [UpdatedDate]                 DATETIME        NULL,
    [UpdatedFromIP]               VARCHAR (15)    NULL,
    [IsBefore]                    BIT             DEFAULT ((0)) NOT NULL,
    [IsAfter]                     BIT             DEFAULT ((0)) NOT NULL,
    [IsMonthly]                   BIT             DEFAULT ((0)) NOT NULL,
    [BeforePercentage]            DECIMAL (18, 2) NULL,
    [AfterPercentage]             DECIMAL (18, 2) NULL,
    [MaternityStartDay]           INT             DEFAULT ((0)) NOT NULL,
    [MaternityEndDay]             INT             DEFAULT ((0)) NOT NULL,
    [MaternityLeaveStartDay]      INT             DEFAULT ((0)) NOT NULL,
    [MaternityLeaveEndDay]        INT             DEFAULT ((0)) NOT NULL,
    [CanAvailAfterDOJ]            INT             DEFAULT ((0)) NOT NULL,
    [EffectiveDate]               DATETIME        DEFAULT ((0)) NOT NULL,
    [GapeBetweenConsecutiveIssue] INT             DEFAULT ((0)) NOT NULL,
    [IsNoBenefit]                 BIT             NULL,
    CONSTRAINT [PK_MaternityLeavePolicy] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_MaternityLeavePolicy_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_MaternityLeavePolicy_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id])
);

