CREATE TABLE [MST].[MaterialGroupMaster] (
    [Id]                   VARCHAR (10) NOT NULL,
    [MaterialGroup1Id]     VARCHAR (10) NOT NULL,
    [MaterialGroup2Id]     VARCHAR (10) NULL,
    [MaterialGroup3Id]     VARCHAR (10) NULL,
    [MaterialGroup4Id]     VARCHAR (10) NULL,
    [MaterialTypeId]       VARCHAR (10) NOT NULL,
    [BaseUoMId]            VARCHAR (10) NULL,
    [HSNCodeId]            VARCHAR (10) NULL,
    [Code]                 VARCHAR (10) NULL,
    [UserName]             VARCHAR (50) NOT NULL,
    [Active]               BIT          NOT NULL,
    [Archive]              BIT          NOT NULL,
    [AddedBy]              VARCHAR (30) NOT NULL,
    [AddedDate]            DATETIME     NOT NULL,
    [AddedFromIP]          VARCHAR (15) NOT NULL,
    [UpdatedBy]            VARCHAR (30) NULL,
    [UpdatedDate]          DATETIME     NULL,
    [UpdatedFromIP]        VARCHAR (15) NULL,
    [InventoryIssuePolicy] VARCHAR (15) NOT NULL,
    CONSTRAINT [PK_MaterialGroupMaster] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_MaterialGroupMaster_HSNCode] FOREIGN KEY ([HSNCodeId]) REFERENCES [HKP].[HSNCode] ([Id]),
    CONSTRAINT [FK_MaterialGroupMaster_MaterialGroup1] FOREIGN KEY ([MaterialGroup1Id]) REFERENCES [HKP].[MaterialGroup1] ([Id]),
    CONSTRAINT [FK_MaterialGroupMaster_MaterialGroup2] FOREIGN KEY ([MaterialGroup2Id]) REFERENCES [HKP].[MaterialGroup2] ([Id]),
    CONSTRAINT [FK_MaterialGroupMaster_MaterialGroup3] FOREIGN KEY ([MaterialGroup3Id]) REFERENCES [HKP].[MaterialGroup3] ([Id]),
    CONSTRAINT [FK_MaterialGroupMaster_MaterialGroup4] FOREIGN KEY ([MaterialGroup4Id]) REFERENCES [HKP].[MaterialGroup4] ([Id]),
    CONSTRAINT [FK_MaterialGroupMaster_MaterialType] FOREIGN KEY ([MaterialTypeId]) REFERENCES [HKP].[MaterialType] ([Id]),
    CONSTRAINT [FK_MaterialGroupMaster_UnitOfMeasurement] FOREIGN KEY ([BaseUoMId]) REFERENCES [SCS].[UnitOfMeasurement] ([Id])
);

