CREATE TABLE [MST].[MenuMaster] (
    [Id]                      VARCHAR (20)    NOT NULL,
    [ModuleId]                VARCHAR (20)    NOT NULL,
    [SubModuleId]             VARCHAR (20)    NULL,
    [MenuFrameId]             VARCHAR (20)    NOT NULL,
    [MenuGroupId]             VARCHAR (20)    NULL,
    [MenuSubGroupId]          VARCHAR (20)    NULL,
    [PanelName]               VARCHAR (20)    NULL,
    [IsExternalMenu]          BIT             NOT NULL,
    [Description]             VARCHAR (250)   NULL,
    [Remarks]                 VARCHAR (250)   NULL,
    [AddedBy]                 VARCHAR (30)    NOT NULL,
    [AddedDate]               DATETIME        NOT NULL,
    [AddedFromIP]             VARCHAR (15)    NOT NULL,
    [UpdatedBy]               VARCHAR (30)    NULL,
    [UpdatedDate]             DATETIME        NULL,
    [UpdatedFromIP]           VARCHAR (15)    NULL,
    [MarkForDeletion]         BIT             NULL,
    [Controller]              VARCHAR (80)    NULL,
    [Href]                    VARCHAR (150)   NULL,
    [Sequence]                DECIMAL (18, 2) NULL,
    [UserDefineCode]          VARCHAR (30)    NULL,
    [MenuHelpDoc]             VARBINARY (MAX) NULL,
    [MenuHelpDocName]         VARCHAR (50)    NULL,
    [MenuHelpDocInternalName] VARCHAR (50)    NULL,
    [Image]                   VARCHAR (MAX)   NULL,
    [Code]                    VARCHAR (20)    NULL,
    [TobeChecked]             BIT             NULL,
    [Specialdecision]         VARCHAR (1000)  NULL,
    CONSTRAINT [PK_MenuMaster] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_MenuMaster_MenuFrame] FOREIGN KEY ([MenuFrameId]) REFERENCES [MMS].[MenuFrame] ([Id]),
    CONSTRAINT [FK_MenuMaster_MenuGroup] FOREIGN KEY ([MenuGroupId]) REFERENCES [MMS].[MenuGroup] ([Id]),
    CONSTRAINT [FK_MenuMaster_MenuSubGroup] FOREIGN KEY ([MenuSubGroupId]) REFERENCES [MMS].[MenuSubGroup] ([Id]),
    CONSTRAINT [FK_MenuMaster_Module] FOREIGN KEY ([ModuleId]) REFERENCES [MMS].[Module] ([Id]),
    CONSTRAINT [FK_MenuMaster_SubModule] FOREIGN KEY ([SubModuleId]) REFERENCES [MMS].[SubModule] ([Id])
);

