CREATE TYPE [MST].[MenuMaster_BulkType] AS TABLE (
    [Id]                         VARCHAR (15)  NOT NULL,
    [ModuleId]                   VARCHAR (2)   NULL,
    [SubModuleId]                VARCHAR (2)   NULL,
    [MenuId]                     VARCHAR (10)  NULL,
    [MenuFrameId]                VARCHAR (4)   NULL,
    [MenuGroupId]                VARCHAR (6)   NULL,
    [MenuSubGroupId]             VARCHAR (5)   NULL,
    [MenuItemId]                 VARCHAR (10)  NULL,
    [PanelName]                  VARCHAR (20)  NULL,
    [IsExternalMenu]             BIT           NULL,
    [Description]                VARCHAR (250) NULL,
    [Remarks]                    VARCHAR (250) NULL,
    [Active]                     BIT           NULL,
    [Archive]                    BIT           NULL,
    [AddedBy]                    VARCHAR (30)  NULL,
    [AddedDate]                  DATETIME      NULL,
    [AddedFromIP]                VARCHAR (15)  NULL,
    [UpdatedBy]                  VARCHAR (30)  NULL,
    [UpdatedDate]                DATETIME      NULL,
    [UpdatedFromIP]              VARCHAR (15)  NULL,
    [sync_update_peer_timestamp] BIGINT        NULL,
    [sync_update_peer_key]       INT           NULL,
    [sync_create_peer_timestamp] BIGINT        NULL,
    [sync_create_peer_key]       INT           NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC));

