CREATE TABLE [MST].[Operation] (
    [Id]                   VARCHAR (20)    NOT NULL,
    [OperationTypeId]      VARCHAR (10)    NULL,
    [OperationCategoryId]  VARCHAR (10)    NULL,
    [OperationActivityId]  VARCHAR (10)    NULL,
    [Sequence]             DECIMAL (18, 2) NOT NULL,
    [Code]                 VARCHAR (10)    NOT NULL,
    [ShortName]            VARCHAR (15)    NOT NULL,
    [StandardName]         VARCHAR (100)   NOT NULL,
    [UserName]             VARCHAR (100)   NOT NULL,
    [Remarks]              VARCHAR (250)   NULL,
    [IsMachineRequired]    VARCHAR (10)    NOT NULL,
    [Active]               BIT             NOT NULL,
    [Archive]              BIT             NOT NULL,
    [AddedBy]              VARCHAR (30)    NOT NULL,
    [AddedDate]            DATETIME        NOT NULL,
    [AddedFromIP]          VARCHAR (15)    NOT NULL,
    [UpdatedBy]            VARCHAR (30)    NULL,
    [UpdatedDate]          DATETIME        NULL,
    [UpdatedFromIP]        VARCHAR (15)    NULL,
    [CompanyGroupId]       VARCHAR (10)    NOT NULL,
    [ArticleId]            VARCHAR (10)    NULL,
    [SkillId]              VARCHAR (10)    NULL,
    [ProductionSystemId]   VARCHAR (10)    NULL,
    [BasicProcessTime]     DECIMAL (10, 2) NOT NULL,
    [AssociateProcessTime] DECIMAL (10, 2) NOT NULL,
    [PersonalAllowance]    DECIMAL (10, 2) NOT NULL,
    [MachineAllowance]     DECIMAL (10, 2) NOT NULL,
    [OperationLength]      DECIMAL (10, 2) NOT NULL,
    [Frequency]            DECIMAL (10, 2) NOT NULL,
    [SPI]                  INT             NOT NULL,
    [AdditionalAllowance]  DECIMAL (10, 2) DEFAULT ((0)) NULL,
    CONSTRAINT [PK_Operation_1] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Operation_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_Operation_MaterialMasterArticle] FOREIGN KEY ([ArticleId]) REFERENCES [MST].[MaterialMasterArticle] ([Id]),
    CONSTRAINT [FK_Operation_OperationAction] FOREIGN KEY ([OperationActivityId]) REFERENCES [HKP].[OperationActivity] ([Id]),
    CONSTRAINT [FK_Operation_OperationCategory] FOREIGN KEY ([OperationCategoryId]) REFERENCES [HKP].[OperationCategory] ([Id]),
    CONSTRAINT [FK_Operation_OperationType] FOREIGN KEY ([OperationTypeId]) REFERENCES [HKP].[OperationType] ([Id]),
    CONSTRAINT [FK_Operation_ProductionSystem] FOREIGN KEY ([ProductionSystemId]) REFERENCES [HKP].[ProductionSystem] ([Id]),
    CONSTRAINT [FK_Operation_Skill] FOREIGN KEY ([SkillId]) REFERENCES [HKP].[Skill] ([Id])
);

