CREATE TABLE [MST].[OperationMaster] (
    [Id]                  VARCHAR (10)    NOT NULL,
    [CompanyGroupId]      VARCHAR (10)    NOT NULL,
    [Sequence]            DECIMAL (18, 2) NOT NULL,
    [Code]                VARCHAR (10)    NOT NULL,
    [ShortName]           VARCHAR (15)    NOT NULL,
    [StandardName]        VARCHAR (100)   NOT NULL,
    [UserName]            VARCHAR (100)   NOT NULL,
    [OperationActivityId] VARCHAR (10)    NOT NULL,
    [OperationTypeId]     VARCHAR (10)    NOT NULL,
    [OperationCategoryId] VARCHAR (10)    NOT NULL,
    [SkillId]             VARCHAR (10)    NULL,
    [Type]                VARCHAR (10)    NOT NULL,
    [MachineMasterId]     VARCHAR (10)    NULL,
    [SkillGroupId]        VARCHAR (10)    NOT NULL,
    [LegalDesignationId]  VARCHAR (10)    NULL,
    [ProcessId]           VARCHAR (10)    NULL,
    [ProposedSalary]      DECIMAL (18, 2) NULL,
    [Remarks]             VARCHAR (250)   NULL,
    [Active]              BIT             NOT NULL,
    [AddedBy]             VARCHAR (30)    NOT NULL,
    [AddedDate]           DATETIME        NOT NULL,
    [AddedFromIP]         VARCHAR (15)    NOT NULL,
    [UpdatedBy]           VARCHAR (30)    NULL,
    [UpdatedDate]         DATETIME        NULL,
    [UpdatedFromIP]       VARCHAR (15)    NULL,
    CONSTRAINT [PK_OperationMaster] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_OperationMaster_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_OperationMaster_LegalDesignation] FOREIGN KEY ([LegalDesignationId]) REFERENCES [HKP].[LegalDesignation] ([Id])
);

