CREATE TABLE [MST].[OperationAttribute] (
    [Id]                   VARCHAR (10)    NOT NULL,
    [OperationId]          VARCHAR (20)    NOT NULL,
    [Sequence]             DECIMAL (18, 2) NOT NULL,
    [Code]                 VARCHAR (10)    NOT NULL,
    [ShortName]            VARCHAR (15)    NOT NULL,
    [StandardName]         VARCHAR (50)    NOT NULL,
    [UserName]             VARCHAR (50)    NOT NULL,
    [AttributeProperty]    VARCHAR (15)    NOT NULL,
    [IsFixedNoOfCharacter] BIT             NOT NULL,
    [NoOfCharacter]        INT             NOT NULL,
    [IsFreeField]          BIT             NOT NULL,
    [IsPreDefinedField]    BIT             NOT NULL,
    [IsMandatory]          BIT             NOT NULL,
    [ValueAssignmentLevel] VARCHAR (10)    NOT NULL,
    [AddedBy]              VARCHAR (30)    NOT NULL,
    [AddedDate]            DATETIME        NOT NULL,
    [AddedFromIP]          VARCHAR (15)    NOT NULL,
    [UpdatedBy]            VARCHAR (30)    NULL,
    [UpdatedDate]          DATETIME        NULL,
    [UpdatedFromIP]        VARCHAR (15)    NULL,
    CONSTRAINT [PK_OperationAttribute] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_OperationAttribute_Operation] FOREIGN KEY ([OperationId]) REFERENCES [MST].[Operation] ([Id])
);

