CREATE TABLE [MST].[OperationVariation] (
    [Id]                  VARCHAR (10)    NOT NULL,
    [CompanyGroupId]      VARCHAR (10)    NOT NULL,
    [OperationId]         VARCHAR (20)    NOT NULL,
    [ArticleId]           VARCHAR (10)    NULL,
    [SkillId]             VARCHAR (10)    NULL,
    [SubOperationSAM]     DECIMAL (18, 2) NOT NULL,
    [AdditionalSAMSymbol] VARCHAR (1)     NOT NULL,
    [AdditionalSAM]       DECIMAL (18, 4) NULL,
    [Frequency]           DECIMAL (10, 2) NOT NULL,
    [MachineAllowance]    DECIMAL (10, 2) NOT NULL,
    [SPI]                 INT             NOT NULL,
    [Sequence]            DECIMAL (18, 2) NOT NULL,
    [Code]                VARCHAR (10)    NOT NULL,
    [ShortName]           VARCHAR (15)    NOT NULL,
    [StandardName]        VARCHAR (50)    NOT NULL,
    [UserName]            VARCHAR (50)    NULL,
    [Description]         VARCHAR (250)   NULL,
    [Remarks]             VARCHAR (250)   NULL,
    [Active]              BIT             NOT NULL,
    [Archive]             BIT             NOT NULL,
    [AddedBy]             VARCHAR (30)    NOT NULL,
    [AddedDate]           DATETIME        NOT NULL,
    [AddedFromIP]         VARCHAR (15)    NOT NULL,
    [UpdatedBy]           VARCHAR (30)    NULL,
    [UpdatedDate]         DATETIME        NULL,
    [UpdatedFromIP]       VARCHAR (15)    NULL,
    [TotalSAM]            DECIMAL (18, 2) DEFAULT ((0)) NOT NULL,
    [OperationMasterId]   VARCHAR (10)    NULL,
    [AdditionalAllowance] DECIMAL (10, 2) DEFAULT ((0)) NULL,
    [VASSAMSOURCE]        VARCHAR (20)    NULL,
    [VASSAMApprovedBy]    VARCHAR (50)    NULL,
    [VASSAMApprovedDate]  DATETIME        NULL,
    [VASFINALSAM]         DECIMAL (10, 4) NULL,
    CONSTRAINT [PK_OperationVariation] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_OperationVariation_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_OperationVariation_MaterialMasterArticle] FOREIGN KEY ([ArticleId]) REFERENCES [MST].[MaterialMasterArticle] ([Id]),
    CONSTRAINT [FK_OperationVariation_Operation] FOREIGN KEY ([OperationId]) REFERENCES [MST].[Operation] ([Id]),
    CONSTRAINT [FK_OperationVariation_OperationMaster] FOREIGN KEY ([OperationMasterId]) REFERENCES [MST].[OperationMaster] ([Id]),
    CONSTRAINT [FK_OperationVariation_Skill] FOREIGN KEY ([SkillId]) REFERENCES [HKP].[Skill] ([Id])
);

