CREATE TABLE [MST].[ProductMaster] (
    [Id]                           VARCHAR (10)    NOT NULL,
    [CompanyGroupId]               VARCHAR (10)    NOT NULL,
    [ProductCategoryId]            VARCHAR (10)    NOT NULL,
    [ProductSubCategoryId]         VARCHAR (10)    NOT NULL,
    [ProductId]                    VARCHAR (10)    NULL,
    [Sequence]                     DECIMAL (18, 2) NOT NULL,
    [Code]                         VARCHAR (10)    NOT NULL,
    [ShortName]                    VARCHAR (15)    NOT NULL,
    [StandardName]                 VARCHAR (50)    NOT NULL,
    [UserName]                     VARCHAR (50)    NOT NULL,
    [Description]                  VARCHAR (250)   NULL,
    [Active]                       BIT             NOT NULL,
    [Archive]                      BIT             NOT NULL,
    [AddedBy]                      VARCHAR (30)    NOT NULL,
    [AddedDate]                    DATETIME        NOT NULL,
    [AddedFromIP]                  VARCHAR (15)    NOT NULL,
    [UpdatedBy]                    VARCHAR (30)    NULL,
    [UpdatedDate]                  DATETIME        NULL,
    [UpdatedFromIP]                VARCHAR (15)    NULL,
    [CostAndManufacture]           DECIMAL (18, 2) NULL,
    [CostAndManufactureCurrencyId] VARCHAR (10)    NULL,
    [FirstdayOutPut]               INT             DEFAULT ((0)) NOT NULL,
    [DaysToReachTheTarget]         INT             DEFAULT ((0)) NOT NULL,
    [IsFixed]                      VARCHAR (10)    NULL,
    [IncrementValue]               INT             DEFAULT ((0)) NOT NULL,
    [TargetQty]                    INT             DEFAULT ((0)) NOT NULL,
    [BaseProcessId]                VARCHAR (10)    NULL,
    [CostingType]                  VARCHAR (15)    NULL,
    [PlanningType]                 VARCHAR (20)    NULL,
    CONSTRAINT [PK_ProductMaster] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ProductMaster_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_ProductMaster_Currency] FOREIGN KEY ([CostAndManufactureCurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_ProductMaster_Process] FOREIGN KEY ([BaseProcessId]) REFERENCES [HKP].[Process] ([Id]),
    CONSTRAINT [FK_ProductMaster_Product] FOREIGN KEY ([ProductId]) REFERENCES [HKP].[Product] ([Id]),
    CONSTRAINT [FK_ProductMaster_ProductCategory] FOREIGN KEY ([ProductCategoryId]) REFERENCES [HKP].[ProductCategory] ([Id]),
    CONSTRAINT [FK_ProductMaster_ProductSubCategory] FOREIGN KEY ([ProductSubCategoryId]) REFERENCES [HKP].[ProductSubCategory] ([Id])
);

