CREATE TABLE [MST].[ProjectPlanning] (
    [Id]               VARCHAR (10)    NOT NULL,
    [CompanyId]        VARCHAR (10)    NOT NULL,
    [PlantId]          VARCHAR (10)    NOT NULL,
    [EntityId]         VARCHAR (10)    NULL,
    [Code]             VARCHAR (30)    NOT NULL,
    [Description]      VARCHAR (250)   NULL,
    [Title]            VARCHAR (130)   NULL,
    [PositionId]       VARCHAR (10)    NULL,
    [ManpowerBudgetId] VARCHAR (10)    NULL,
    [EmployeeId]       VARCHAR (30)    NULL,
    [CurrencyId]       VARCHAR (10)    NOT NULL,
    [ExchangeRate]     DECIMAL (18, 4) NOT NULL,
    [FromDate]         DATETIME        NOT NULL,
    [ToDate]           DATETIME        NOT NULL,
    [Status]           VARCHAR (30)    NOT NULL,
    [AddedBy]          VARCHAR (30)    NOT NULL,
    [AddedDate]        DATETIME        NOT NULL,
    [AddedFromIP]      VARCHAR (15)    NOT NULL,
    [UpdatedBy]        VARCHAR (30)    NULL,
    [UpdatedDate]      DATETIME        NULL,
    [UpdatedFromIP]    VARCHAR (15)    NULL,
    CONSTRAINT [PK_ProjectPlanning] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ProjectPlanning_Company] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_ProjectPlanning_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [SCS].[Currency] ([Id]),
    CONSTRAINT [FK_ProjectPlanning_EmployeeInformation] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_ProjectPlanning_Entity] FOREIGN KEY ([EntityId]) REFERENCES [ORG].[Entity] ([Id]),
    CONSTRAINT [FK_ProjectPlanning_ManpowerBudget] FOREIGN KEY ([ManpowerBudgetId]) REFERENCES [MST].[ManpowerBudget] ([Id]),
    CONSTRAINT [FK_ProjectPlanning_Plant] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id]),
    CONSTRAINT [FK_ProjectPlanning_Position] FOREIGN KEY ([PositionId]) REFERENCES [ORG].[Position] ([Id])
);

