CREATE TABLE [MST].[ProjectPlanningPORequisitionMaterialMaster] (
    [Id]                                        VARCHAR (10)    NOT NULL,
    [ProjectPlanningId]                         VARCHAR (10)    NOT NULL,
    [ProjectPlanningRequisitionId]              VARCHAR (10)    NOT NULL,
    [ProjectPlanningMaterialMasterId]           VARCHAR (10)    NOT NULL,
    [ProjectPlanningRequsitionMaterialMasterId] VARCHAR (10)    NULL,
    [ProjectPlanningPurchaseOrderId]            VARCHAR (10)    NOT NULL,
    [MaterialMasterId]                          VARCHAR (30)    NULL,
    [ReverseQuantity]                           DECIMAL (18, 4) NULL,
    [Quantity]                                  DECIMAL (18, 4) NOT NULL,
    [Rate]                                      DECIMAL (18, 4) NOT NULL,
    [AlternativeUomId]                          VARCHAR (10)    NULL,
    [BaseUOMId]                                 VARCHAR (10)    NULL,
    [AddedBy]                                   VARCHAR (30)    NOT NULL,
    [AddedDate]                                 DATETIME        NOT NULL,
    [AddedFromIP]                               VARCHAR (15)    NOT NULL,
    [UpdatedBy]                                 VARCHAR (30)    NULL,
    [UpdatedDate]                               DATETIME        NULL,
    [UpdatedFromIP]                             VARCHAR (15)    NULL,
    [RequisitionUoMQuantity]                    DECIMAL (18, 4) NULL,
    [BaseUoMQuantity]                           DECIMAL (18, 4) NULL,
    [RequisitionUoMId]                          VARCHAR (10)    NULL,
    CONSTRAINT [PK_ProjectPlanningPORequisitionMaterialMaster] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ProjectPlanningPORequisitionMaterialMaster_ProjectPlanningMaterialMaster] FOREIGN KEY ([ProjectPlanningMaterialMasterId]) REFERENCES [MST].[ProjectPlanningMaterialMaster] ([Id]),
    CONSTRAINT [FK_ProjectPlanningPORequisitionMaterialMaster_ProjectPlanningPORequisitionMaterialMaster] FOREIGN KEY ([Id]) REFERENCES [MST].[ProjectPlanningPORequisitionMaterialMaster] ([Id]),
    CONSTRAINT [FK_ProjectPlanningPORequisitionMaterialMaster_ProjectPlanningPurchaseOrder] FOREIGN KEY ([ProjectPlanningPurchaseOrderId]) REFERENCES [MST].[ProjectPlanningPurchaseOrder] ([Id]),
    CONSTRAINT [FK_ProjectPlanningPORequisitionMaterialMaster_ProjectPlanningRequisition] FOREIGN KEY ([ProjectPlanningRequisitionId]) REFERENCES [MST].[ProjectPlanningRequisition] ([Id]),
    CONSTRAINT [FK_ProjectPlanningPORequisitionMaterialMaster_ProjectPlanningRequisitionMaterialMaster] FOREIGN KEY ([ProjectPlanningRequsitionMaterialMasterId]) REFERENCES [MST].[ProjectPlanningRequisitionMaterialMaster] ([Id]),
    CONSTRAINT [FK_ProjectPlanningPORequisitionMaterialMaster_UnitOfMeasurement] FOREIGN KEY ([RequisitionUoMId]) REFERENCES [SCS].[UnitOfMeasurement] ([Id])
);

