CREATE TABLE [MST].[QMSDefectMaster] (
    [Id]                         VARCHAR (10)    NOT NULL,
    [StandardName]               VARCHAR (50)    NOT NULL,
    [StandardCode]               VARCHAR (10)    NOT NULL,
    [UserName]                   VARCHAR (50)    NOT NULL,
    [UserCode]                   VARCHAR (10)    NOT NULL,
    [ShortName]                  VARCHAR (15)    NOT NULL,
    [CriticalityLevelId]         VARCHAR (10)    NOT NULL,
    [RepairTypeId]               VARCHAR (10)    NULL,
    [DefectCause]                VARCHAR (250)   NULL,
    [AddedBy]                    VARCHAR (30)    NOT NULL,
    [AddedDate]                  DATETIME        NOT NULL,
    [AddedFromIP]                VARCHAR (15)    NOT NULL,
    [UpdatedBy]                  VARCHAR (30)    NULL,
    [UpdatedDate]                DATETIME        NULL,
    [UpdatedFromIP]              VARCHAR (15)    NULL,
    [ProductApplicable]          BIT             NULL,
    [MaterialApplicable]         BIT             NULL,
    [ProcessApplicable]          BIT             NULL,
    [TestApplicable]             BIT             NULL,
    [SkillApplicable]            BIT             NULL,
    [MachineApplicable]          BIT             NULL,
    [ProcessParameterApplicable] BIT             NULL,
    [Sequence]                   DECIMAL (18, 2) NOT NULL,
    CONSTRAINT [PK_QMSDefectMaster] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_QMSDefectMaster_Critical] FOREIGN KEY ([CriticalityLevelId]) REFERENCES [HKP].[Critical] ([Id]),
    CONSTRAINT [FK_QMSDefectMaster_RepairType] FOREIGN KEY ([RepairTypeId]) REFERENCES [HKP].[RepairType] ([Id])
);

