CREATE TABLE [MST].[Route] (
    [Id]            VARCHAR (10)  NOT NULL,
    [PlantId]       VARCHAR (10)  NOT NULL,
    [DriverId]      VARCHAR (30)  NULL,
    [Code]          VARCHAR (10)  NOT NULL,
    [UserName]      VARCHAR (50)  NOT NULL,
    [StandardName]  VARCHAR (50)  NOT NULL,
    [ShortName]     VARCHAR (15)  NOT NULL,
    [Description]   VARCHAR (250) NULL,
    [Remarks]       VARCHAR (250) NULL,
    [AddedBy]       VARCHAR (30)  NOT NULL,
    [AddedDate]     DATETIME      NOT NULL,
    [AddedFromIP]   VARCHAR (15)  NOT NULL,
    [UpdatedBy]     VARCHAR (30)  NULL,
    [UpdatedDate]   DATETIME      NULL,
    [UpdatedFromIP] VARCHAR (15)  NULL,
    [Active]        BIT           NOT NULL,
    [AssetId]       VARCHAR (30)  NULL,
    [UpOrDown]      VARCHAR (30)  NOT NULL,
    [CompanyId]     VARCHAR (10)  NOT NULL,
    CONSTRAINT [PK__Route] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Route_CompanyId] FOREIGN KEY ([CompanyId]) REFERENCES [ORG].[Company] ([Id]),
    CONSTRAINT [FK_Route_EmployeeInformation] FOREIGN KEY ([DriverId]) REFERENCES [dbo].[EmployeeInformation] ([SystemId]),
    CONSTRAINT [FK_Route_PlantId] FOREIGN KEY ([PlantId]) REFERENCES [ORG].[Plant] ([Id])
);

