CREATE TABLE [MST].[SFGMovement] (
    [Id]                 VARCHAR (10)    NOT NULL,
    [Sequence]           DECIMAL (18, 2) NOT NULL,
    [Code]               VARCHAR (10)    NOT NULL,
    [ShortName]          VARCHAR (15)    NOT NULL,
    [StandardName]       VARCHAR (50)    NOT NULL,
    [UserName]           VARCHAR (50)    NOT NULL,
    [FromProcessId]      VARCHAR (10)    NULL,
    [FromSFGInventoryId] VARCHAR (10)    NULL,
    [ToProcessId]        VARCHAR (10)    NULL,
    [ToSFGInventoryId]   VARCHAR (10)    NULL,
    [Description]        VARCHAR (250)   NULL,
    [Remarks]            VARCHAR (250)   NULL,
    [Active]             BIT             NOT NULL,
    [AddedBy]            VARCHAR (30)    NOT NULL,
    [AddedDate]          DATETIME        NOT NULL,
    [AddedFromIP]        VARCHAR (15)    NOT NULL,
    [UpdatedBy]          VARCHAR (30)    NULL,
    [UpdatedDate]        DATETIME        NULL,
    [UpdatedFromIP]      VARCHAR (15)    NULL,
    CONSTRAINT [PK_SFGMovement] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [PK_SFGMovement_FromProcess] FOREIGN KEY ([FromProcessId]) REFERENCES [HKP].[Process] ([Id]),
    CONSTRAINT [PK_SFGMovement_FromSFGInventory] FOREIGN KEY ([FromSFGInventoryId]) REFERENCES [HKP].[SFGInventory] ([Id]),
    CONSTRAINT [PK_SFGMovement_ToProcess] FOREIGN KEY ([ToProcessId]) REFERENCES [HKP].[Process] ([Id]),
    CONSTRAINT [PK_SFGMovement_ToSFGInventory] FOREIGN KEY ([ToSFGInventoryId]) REFERENCES [HKP].[SFGInventory] ([Id])
);

