CREATE TABLE [MST].[TaxCategoryGL] (
    [Id]                      VARCHAR (20) NOT NULL,
    [COAId]                   VARCHAR (10) NOT NULL,
    [CountryId]               VARCHAR (10) NOT NULL,
    [TaxCategoryId]           VARCHAR (10) NOT NULL,
    [GLGeneralInfoId]         VARCHAR (10) NOT NULL,
    [BudgetMasterId]          VARCHAR (20) NULL,
    [ActivityId]              VARCHAR (10) NULL,
    [InputTaxOutPutTax]       VARCHAR (10) NOT NULL,
    [AddedBy]                 VARCHAR (30) NOT NULL,
    [AddedDate]               DATETIME     NOT NULL,
    [AddedFromIP]             VARCHAR (15) NOT NULL,
    [UpdatedBy]               VARCHAR (30) NULL,
    [UpdatedDate]             DATETIME     NULL,
    [UpdatedFromIP]           VARCHAR (15) NULL,
    [LiabilityGLId]           VARCHAR (10) NULL,
    [LiabilityBudgetMasterId] VARCHAR (20) NULL,
    [LiabilityActivityId]     VARCHAR (10) NULL,
    [TaxType]                 VARCHAR (20) NULL,
    [WithholdGLId]            VARCHAR (10) NULL,
    [WithholdBudgetMasterId]  VARCHAR (20) NULL,
    [WithholdActivityId]      VARCHAR (10) NULL,
    [ExpensesGLId]            VARCHAR (10) NULL,
    [ExpensesBudgetMasterId]  VARCHAR (20) NULL,
    [ExpensesActivityId]      VARCHAR (10) NULL,
    CONSTRAINT [PK_TaxCategoryGL] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_TaxCategoryGL_Activity] FOREIGN KEY ([ActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_TaxCategoryGL_Activity_ActivityId] FOREIGN KEY ([ActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_TaxCategoryGL_Activity_ExpensesActivityId] FOREIGN KEY ([ExpensesActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_TaxCategoryGL_Activity_LiabilityActivityId] FOREIGN KEY ([LiabilityActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_TaxCategoryGL_Activity_WithholdActivityId] FOREIGN KEY ([WithholdActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_TaxCategoryGL_BudgetMaster] FOREIGN KEY ([BudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_TaxCategoryGL_BudgetMaster_BudgetMasterId] FOREIGN KEY ([BudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_TaxCategoryGL_BudgetMaster_ExpensesBudgetMasterId] FOREIGN KEY ([ExpensesBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_TaxCategoryGL_BudgetMaster_LiabilityBudgetMasterId] FOREIGN KEY ([LiabilityBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_TaxCategoryGL_BudgetMaster_WithholdBudgetMasterId] FOREIGN KEY ([WithholdBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_TaxCategoryGL_COA] FOREIGN KEY ([COAId]) REFERENCES [HKP].[COA] ([Id]),
    CONSTRAINT [FK_TaxCategoryGL_COA_COAId] FOREIGN KEY ([COAId]) REFERENCES [HKP].[COA] ([Id]),
    CONSTRAINT [FK_TaxCategoryGL_Country] FOREIGN KEY ([CountryId]) REFERENCES [SCS].[Country] ([Id]),
    CONSTRAINT [FK_TaxCategoryGL_Country_CountryId] FOREIGN KEY ([CountryId]) REFERENCES [SCS].[Country] ([Id]),
    CONSTRAINT [FK_TaxCategoryGL_GLGeneralInfo] FOREIGN KEY ([GLGeneralInfoId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_TaxCategoryGL_GLGeneralInfo_ExpensesGLId] FOREIGN KEY ([ExpensesGLId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_TaxCategoryGL_GLGeneralInfo_GLGeneralInfoId] FOREIGN KEY ([GLGeneralInfoId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_TaxCategoryGL_GLGeneralInfo_LiabilityGLId] FOREIGN KEY ([LiabilityGLId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_TaxCategoryGL_GLGeneralInfo_WithholdGLId] FOREIGN KEY ([WithholdGLId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_TaxCategoryGL_TaxCategory] FOREIGN KEY ([TaxCategoryId]) REFERENCES [MST].[TaxCategory] ([Id]),
    CONSTRAINT [FK_TaxCategoryGL_TaxCategory_TaxCategoryId] FOREIGN KEY ([TaxCategoryId]) REFERENCES [MST].[TaxCategory] ([Id])
);

