CREATE TABLE [MST].[TaxCodeGL] (
    [Id]                               VARCHAR (10) NOT NULL,
    [COAId]                            VARCHAR (10) NULL,
    [TaxCodeId]                        VARCHAR (10) NOT NULL,
    [WithholdCreditableGLId]           VARCHAR (10) NULL,
    [WithholdCreditableBudgetMasterId] VARCHAR (20) NULL,
    [WithholdCreditableActivityId]     VARCHAR (10) NULL,
    [CreditableGLId]                   VARCHAR (10) NULL,
    [CreditableGLBudgetMasterId]       VARCHAR (20) NULL,
    [CreditableGLActivityId]           VARCHAR (10) NULL,
    [ExpensesGLId]                     VARCHAR (10) NULL,
    [ExpensesGLBudgetMasterId]         VARCHAR (20) NULL,
    [ExpensesGLActivityId]             VARCHAR (10) NULL,
    [Active]                           BIT          NOT NULL,
    [AddedBy]                          VARCHAR (30) NOT NULL,
    [AddedDate]                        DATETIME     NOT NULL,
    [AddedFromIP]                      VARCHAR (15) NOT NULL,
    [UpdatedBy]                        VARCHAR (30) NULL,
    [UpdatedDate]                      DATETIME     NULL,
    [UpdatedFromIP]                    VARCHAR (15) NULL,
    CONSTRAINT [PK_TaxCodeGL] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_TaxCodeGL_Activity_CreditableGLActivityId] FOREIGN KEY ([CreditableGLActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_TaxCodeGL_Activity_ExpensesGLActivityId] FOREIGN KEY ([ExpensesGLActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_TaxCodeGL_Activity_WithholdCreditableActivityId] FOREIGN KEY ([WithholdCreditableActivityId]) REFERENCES [HKP].[Activity] ([Id]),
    CONSTRAINT [FK_TaxCodeGL_COA] FOREIGN KEY ([COAId]) REFERENCES [HKP].[COA] ([Id]),
    CONSTRAINT [FK_TaxCodeGL_CreditableGLBudgetMaster] FOREIGN KEY ([CreditableGLBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_TaxCodeGL_ExpensesGLBudgetMaster] FOREIGN KEY ([ExpensesGLBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id]),
    CONSTRAINT [FK_TaxCodeGL_GLGeneralInfo_CreditableGLId] FOREIGN KEY ([CreditableGLId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_TaxCodeGL_GLGeneralInfo_ExpensesGLId] FOREIGN KEY ([ExpensesGLId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_TaxCodeGL_GLGeneralInfo_WithholdCreditableGLId] FOREIGN KEY ([WithholdCreditableGLId]) REFERENCES [HKP].[GLGeneralInfo] ([Id]),
    CONSTRAINT [FK_TaxCodeGL_TaxCode] FOREIGN KEY ([TaxCodeId]) REFERENCES [MST].[TaxCode] ([Id]),
    CONSTRAINT [FK_TaxCodeGL_WithholdCreditableBudgetMaster] FOREIGN KEY ([WithholdCreditableBudgetMasterId]) REFERENCES [MST].[BudgetMaster] ([Id])
);

