CREATE TABLE [MST].[TaxVariant] (
    [Id]             VARCHAR (10)    NOT NULL,
    [CompanyGroupId] VARCHAR (10)    NOT NULL,
    [CountryId]      VARCHAR (10)    NULL,
    [Sequence]       DECIMAL (18, 2) NOT NULL,
    [Code]           VARCHAR (10)    NOT NULL,
    [ShortName]      VARCHAR (15)    NOT NULL,
    [StandardName]   VARCHAR (50)    NOT NULL,
    [UserName]       VARCHAR (50)    NOT NULL,
    [Description]    VARCHAR (250)   NULL,
    [Remarks]        VARCHAR (250)   NULL,
    [Active]         BIT             NOT NULL,
    [Archive]        BIT             NOT NULL,
    [AddedBy]        VARCHAR (30)    NOT NULL,
    [AddedDate]      DATETIME        NOT NULL,
    [AddedFromIP]    VARCHAR (15)    NOT NULL,
    [UpdatedBy]      VARCHAR (30)    NULL,
    [UpdatedDate]    DATETIME        NULL,
    [UpdatedFromIP]  VARCHAR (15)    NULL,
    [TaxFor]         VARCHAR (30)    NULL,
    [DifferentIn]    VARCHAR (30)    NULL,
    [Different]      VARCHAR (30)    NULL,
    CONSTRAINT [PK_TaxVariant] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_TaxVariant_CompanyGroup] FOREIGN KEY ([CompanyGroupId]) REFERENCES [ORG].[CompanyGroup] ([Id]),
    CONSTRAINT [FK_TaxVariant_Country] FOREIGN KEY ([CountryId]) REFERENCES [SCS].[Country] ([Id])
);

