CREATE TABLE [MST].[VASChild] (
    [Id]                         VARCHAR (30)    NOT NULL,
    [VASMasterID]                VARCHAR (30)    NOT NULL,
    [ElementID]                  INT             NULL,
    [ElementTypeId]              INT             NULL,
    [TMU]                        DECIMAL (18, 3) NULL,
    [CT1]                        DECIMAL (18, 3) NULL,
    [CT2]                        DECIMAL (18, 3) NULL,
    [CT3]                        DECIMAL (18, 3) NULL,
    [CT4]                        DECIMAL (18, 3) NULL,
    [CT5]                        DECIMAL (18, 3) NULL,
    [TimeAvg]                    DECIMAL (18, 3) NULL,
    [Ratings]                    INT             NULL,
    [BasicTime]                  DECIMAL (18, 3) NULL,
    [Version]                    INT             NOT NULL,
    [AddedBy]                    VARCHAR (30)    NOT NULL,
    [AddedDate]                  DATETIME        NOT NULL,
    [AddedFromIP]                VARCHAR (15)    NOT NULL,
    [UpdatedBy]                  VARCHAR (30)    NULL,
    [UpdatedDate]                DATETIME        NULL,
    [UpdatedFromIP]              VARCHAR (15)    NULL,
    [OperationVariationSystemId] VARCHAR (10)    NULL,
    [Sequence]                   INT             NULL,
    CONSTRAINT [PK_VASChild] PRIMARY KEY CLUSTERED ([Id] ASC),
    FOREIGN KEY ([OperationVariationSystemId]) REFERENCES [MST].[OperationVariation] ([Id]),
    CONSTRAINT [fk_Element_id] FOREIGN KEY ([ElementID]) REFERENCES [HKP].[ElementCode] ([Id]),
    CONSTRAINT [FK_VASChildElementTypeId_ElementType_Id] FOREIGN KEY ([ElementTypeId]) REFERENCES [HKP].[ElementType] ([Id]),
    CONSTRAINT [FK_VASMaster_Id] FOREIGN KEY ([VASMasterID]) REFERENCES [MST].[VASMaster] ([Id])
);

